### ISSUE TITLE
[1.5.2] [TT 186] [MCPC] [SEVERE] [TickThreading] Exception ticking TileEntity c TileMultipart_cmp$$5 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1005]
[SEVERE] [TickThreading] Exception ticking TileEntity c TileMultipart_cmp$$5 @595020789 in Nether/-1 at x, y, z: -1025, 35, -27
java.lang.IndexOutOfBoundsException: 1
    at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
    at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:47)
    at codechicken.multipart.TileMultipart$OperationSynchroniser.finishOperation(TileMultipart.scala:457)
    at codechicken.multipart.TileMultipart$.finishOperation(TileMultipart.scala:513)
    at codechicken.multipart.TileMultipart.func_70316_g(TileMultipart.scala:84)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

Wireless Redstone issue I believe

**Comment by alicheek** [comment]
Resultant of the same issue I think : 

[SEVERE] [TickThreading] Exception while updating block neighbours in Overworld/0 at -620, 70, -9
java.lang.IndexOutOfBoundsException: 1
    at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
    at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:47)
    at codechicken.multipart.TileMultipart$OperationSynchroniser.startOperation(TileMultipart.scala:438)
    at codechicken.multipart.TileMultipart$.startOperation(TileMultipart.scala:511)
    at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:124)
    at codechicken.multipart.BlockMultipart$class.onNeighborBlockChange(BlockMultipart.scala:79)
    at codechicken.multipart.BlockMultipartImpl.func_71863_a(BlockMultipart.scala:272)
    at net.minecraft.world.World.func_72821_m(World.java:306)
    at net.minecraft.world.World.func_72898_h(World.java:1052)
    at net.minecraft.block.BlockBasePressurePlate.func_94354_b_(BlockBasePressurePlate.java:214)
    at net.minecraft.block.BlockBasePressurePlate.func_72193_l(BlockBasePressurePlate.java:173)
    at net.minecraft.block.BlockBasePressurePlate.func_71847_b(BlockBasePressurePlate.java:127)
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:352)
    at net.minecraft.world.WorldServer.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:411)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:531)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:684)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
