### ISSUE TITLE
[1.5.2] [TT 186] [MCPC] [SEVERE] [TickThreading] Failed to handle packet from fletchmanjr

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1010]
[SEVERE] [TickThreading] Failed to handle packet from fletchmanjr
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:457)
    at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:501)
    at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:82)
    at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:323)
    at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
    at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at net.minecraft.entity.EntityTracker.func_72787_a(EntityTracker.java:333)
    at net.minecraft.server.management.ServerConfigurationManager.moveToWorld(ServerConfigurationManager.java:602)
    at net.minecraft.server.management.ServerConfigurationManager.changeDimension(ServerConfigurationManager.java:855)
    at net.minecraft.entity.player.EntityPlayerMP.func_71027_c(EntityPlayerMP.java:638)
    at net.minecraft.entity.Entity.func_70030_z(Entity.java:527)
    at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:576)
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:479)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:835)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:336)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406)
    ... 5 more

**Comment by alicheek** [comment]
[SEVERE] [TickThreading] Failed to handle packet from kyle_rann
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:457)
    at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:501)
    at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:82)
    at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:323)
    at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
    at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at net.minecraft.entity.EntityTracker.func_72787_a(EntityTracker.java:333)
    at net.minecraft.server.management.ServerConfigurationManager.moveToWorld(ServerConfigurationManager.java:602)
    at net.minecraft.server.management.ServerConfigurationManager.changeDimension(ServerConfigurationManager.java:855)
    at net.minecraft.entity.player.EntityPlayerMP.func_71027_c(EntityPlayerMP.java:638)
    at net.minecraft.entity.Entity.func_70030_z(Entity.java:527)
    at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:576)
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:479)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:835)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:336)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406)
    ... 5 more
