### ISSUE TITLE
Applied Energetics error spam

### ISSUE THREAD

**Issue by shady2k** [MinimallyCorrect/TickThreading#1020]
MCPC+ 1.5.2-R.1.1-forge738-B636
Applied Energetics rv13.b

AE machines does not open, client crash. 
Spam in console:

2013-11-14 20:10:49 [INFO] [TickThreading] Activating mod TickThreading
2013-11-14 20:10:51 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-11-14 20:11:16 [SEVERE] [TickThreading] TickThreading v1.5.2.186 for MC1.5.2 on 1.5.2 tickthreading,mcpc,spigot,craftbukkit,forge,fml - 1.7.0_25-mockbuild_2013_07_01_09_31-b00 is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at https://github.com/nallar/TickThreading/issues/new

Also, you really should be making regular backups. (You should be doing that even when not using TT.)
2013-11-14 20:11:23 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @367495283 in Overworld/0 at x, y, z: 340, 64, -1898
java.lang.RuntimeException: java.lang.RuntimeException: Invalid Network Recussion Detected
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:557)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.RuntimeException: Invalid Network Recussion Detected
        at appeng.me.MEInventoryNetwork.endRecurssion(MEInventoryNetwork.java:60)
        at appeng.me.MEInventoryNetwork.extractItems(MEInventoryNetwork.java:137)
        at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:427)
        at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:554)
        at appeng.me.tile.TileController.updateTileEntity(TileController.java)
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:550)
        ... 5 more
2013-11-14 20:11:23 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @108942890 in Overworld/0 at x, y, z: 1021, 65, -3651
java.lang.RuntimeException: java.lang.RuntimeException: Invalid Network Recussion Detected
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:557)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.RuntimeException: Invalid Network Recussion Detected
        at appeng.me.MEInventoryNetwork.endRecurssion(MEInventoryNetwork.java:60)
        at appeng.me.MEInventoryNetwork.extractItems(MEInventoryNetwork.java:137)
        at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:427)
        at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:554)
        at appeng.me.tile.TileController.updateTileEntity(TileController.java)
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:550)
        ... 5 more
2013-11-14 20:11:26 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @108942890 in Overworld/0 at x, y, z: 1021, 65, -3651
java.lang.RuntimeException: java.util.NoSuchElementException
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:557)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.util.NoSuchElementException
        at java.util.LinkedList.removeFirst(LinkedList.java:268)
        at java.util.LinkedList.pop(LinkedList.java:799)
        at appeng.me.MEInventoryNetwork.endRecurssion(MEInventoryNetwork.java:58)
        at appeng.me.MEInventoryNetwork.extractItems(MEInventoryNetwork.java:137)
        at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:427)
        at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:554)
        at appeng.me.tile.TileController.updateTileEntity(TileController.java)
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:550)
        ... 5 more

**Comment by dariusc93** [comment]
Common issue in 1.5.2. Likely due to the partial patches

**Comment by LunNova** [comment]
Not going to be fixing this, no support for 1.5.2 builds any more except fixing the barrel issue as it should be simple and has a high impact.
