### ISSUE TITLE
MCPC+ Legacy build 649 MC 1.5.2

### ISSUE THREAD

**Issue by bloodwi11** [MinimallyCorrect/TickThreading#1026]
MCPC+ Ver 649 Patching Issues

Full Log.
http://pastebin.com/ZWcXLCZP

2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: forceChunk() was not found in aab
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: unforceChunk() was not found in aab
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: G()Z was not found in qr
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: removeAllTrackingPlayers() was not found in it
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: func_85156_a() was not found in on
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: func_75775_b() was not found in on
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: loadChunkOnProvideBegin() was not found in aab
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: loadChunkOnProvideEnd() was not found in aab
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:18 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: a(ILnet/minecraft/item/ItemStack;)V was not found in factorization.common.TileEntityBarrel
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:20 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: signalInput(Lnet/minecraft/item/ItemStack;)V was not found in appeng.me.tile.TileController
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:20 [WARNING] [TickThreading] Failed to find exact match for (Lappeng/api/me/util/IMEInventory;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/ItemStack;, trying to find similar methods.
2013-12-02 20:09:20 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: signalInput(Lappeng/api/me/util/IMEInventory;Lnet/minecraft/item/ItemStack;)Lnet/minecraft/item/ItemStack; was not found in appeng.me.tile.TileController
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:20 [FINE] [TickThreading] Patching appeng.me.tile.TileStorageBus with synchronize() {getCellArray,getSharedTagCompound,signalInput}
2013-12-02 20:09:20 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: getSharedTagCompound() was not found in appeng.me.tile.TileStorageBus
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
2013-12-02 20:09:20 [WARNING] [TickThreading]
java.lang.RuntimeException: Method not found: signalInput() was not found in appeng.me.tile.TileStorageBus
        at nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
        at nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:380)
        at nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:257)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:66)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)

**Comment by LunNova** [comment]
These are bugs, but given that they're all only WARNINGS or less severe and for 1.5.2 (which is no longer supported), won't be fixing them.
