### ISSUE TITLE
Crash log from latest version. I know its not ready. I hope I'm helpful.

### ISSUE THREAD

**Issue by Twiggholmes** [MinimallyCorrect/TickThreading#1028]
Last login: Tue Dec  3 18:08:09 on ttys000
Twiggs-Mac-Pro:~ admin$ /Users/admin/Desktop/Minecraft/start_server.command ; exit;
Considering library net.minecraftforge:minecraftforge:9.11.1.953
Considering library net.minecraft:launchwrapper:1.8
Considering library org.ow2.asm:asm-all:4.1
Considering library org.scala-lang:scala-library:2.10.2
Considering library org.scala-lang:scala-compiler:2.10.2
Considering library lzma:lzma:0.0.1
Considering library net.sf.jopt-simple:jopt-simple:4.5
Considering library com.paulscode:codecjorbis:20101023
Considering library com.paulscode:codecwav:20101023
Considering library com.paulscode:libraryjavasound:20101123
Considering library com.paulscode:librarylwjglopenal:20100824
Considering library com.paulscode:soundsystem:20120107
Considering library org.lwjgl.lwjgl:lwjgl:2.9.0
Considering library org.lwjgl.lwjgl:lwjgl_util:2.9.0
Considering library argo:argo:2.25_fixed
Considering library org.bouncycastle:bcprov-jdk15on:1.47
Considering library com.google.guava:guava:14.0
Considering library org.apache.commons:commons-lang3:3.1
Considering library commons-io:commons-io:2.4
Considering library net.java.jinput:jinput:2.0.5
Considering library net.java.jutils:jutils:1.0.0
Considering library com.google.code.gson:gson:2.2.2
Considering library org.lwjgl.lwjgl:lwjgl:2.9.0
Considering library org.lwjgl.lwjgl:lwjgl_util:2.9.0
Considering library org.lwjgl.lwjgl:lwjgl-platform:2.9.0
Considering library org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3
Considering library org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3
Considering library org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20130708-debug3
Considering library net.java.jinput:jinput-platform:2.0.5
Dec 03, 2013 6:08:25 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
Dec 03, 2013 6:08:25 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
Dec 03, 2013 6:08:25 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
2013-12-03 18:08:25 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.45.953 for Minecraft 1.6.4 loading
2013-12-03 18:08:25 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_45, running on Mac OS X:x86_64:10.9, installed at /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
2013-12-03 18:08:25 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:25 [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:25 [WARNING] [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:26 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:26 [SEVERE] [ForgeModLoader] The coremod sharose.mods.guiapi.GuiAPIDummyCoreMod is requesting minecraft version 1.5.2 and minecraft is 1.6.4. It will be ignored.
2013-12-03 18:08:26 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:26 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:26 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:26 [WARNING] [ForgeModLoader] The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-12-03 18:08:26 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2013-12-03 18:08:26 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2013-12-03 18:08:26 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2013-12-03 18:08:26 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2013-12-03 18:08:26 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
Loaded 110 rules from AccessTransformer config file forge_at.cfg
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
Adding AccessTransformer: nei_at.cfg
Adding Accesstransformer map: temp.dat
Loaded 11 rules from AccessTransformer config file temp.dat
Adding AccessTransformer: wrcbe_at.cfg
Adding Accesstransformer map: temp.dat
Loaded 13 rules from AccessTransformer config file temp.dat
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2013-12-03 18:08:27 [INFO] [IC2-core] Loaded library ejml-0.23.jar.
2013-12-03 18:08:27 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
2013-12-03 18:08:28 [INFO] [ForgeModLoader] Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
2013-12-03 18:08:31 [SEVERE] [ForgeModLoader] Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:86)
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:54)
Caused by: java.lang.NoClassDefFoundError: nallar/collections/ListSet
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:195)
    at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:67)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1759)
    ... 12 more
Caused by: java.lang.ClassNotFoundException: nallar.collections.ListSet
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 15 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
    ... 17 more
logout

[Process completed]

**Comment by dariusc93** [comment]
Current version of Tickthreading for 1.6.2 is broken. Related to #1027

**Comment by LunNova** [comment]
Still not helpful :p, it's broken for you in exactly the same way as it is for me.
