### ISSUE TITLE
Tick threading start up error?

### ISSUE THREAD

**Issue by Luke9978** [MinimallyCorrect/TickThreading#1031]
Tried running tick threading 1.6.4.41 and get a funny error even on a brand new server. Not sure if a spelling error or something.

LOG:
 [SEVERE] Encountered an unexpected exception NoSuchMethodError java.lang.NoSuchMethodError: net.minecraft.world.World.getDimension()I
    at nallar.tickthreading.minecraft.TickThreading.onWorldLoad(TickThreading.java:225)
    at net.minecraftforge.event.ASMEventHandler_6_TickThreading_onWorldLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:259)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

**Comment by Katelyn-SN** [comment]
I second this and verify this is a tickthreading error as the server starts correctly without the tickthreading jar

**Comment by LunNova** [comment]
Update for 1.6.4 isn't done yet, see #1030.

Added a warning when starting current builds that they won't work.
