### ISSUE TITLE
Error with TT1.6.4.51 / FTB Monster 1.03

### ISSUE THREAD

**Issue by Bachuey** [MinimallyCorrect/TickThreading#1043]
Clean install, new world etc. Doesn't create crash report, TT and server logs don't contain anything. Copied from cmd window used to start server.

Several mods disabled in pack from default, Biomes o Plenty enabled.

TT patch hook for org.bukkit.craftbukkit.libs.joptsimple.internal.Objects after
cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer@62f242cc
TT patch hook for org.bukkit.craftbukkit.libs.joptsimple.internal.MethodInvoking
ValueConverter after cpw.mods.fml.common.asm.transformers.DeobfuscationTransform
er@62f242cc
TT patch hook for org.bukkit.craftbukkit.libs.joptsimple.ArgumentList after cpw.
mods.fml.common.asm.transformers.DeobfuscationTransformer@62f242cc
2014-01-12 13:34:04 [SEVERE] [ForgeModLoader] Unable to launch
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at nallar.tickthreading.patcher.PatchLauncher.run(PatchLauncher.java:37)

```
    at nallar.tickthreading.patcher.PatchLauncher.main(PatchLauncher.java:14
```

)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.libs.joptsimple.ArgumentList.<init>(ArgumentLi
st.java:40)
        at org.bukkit.craftbukkit.libs.joptsimple.OptionParser.parse(OptionParse
r.java:428)
        at net.minecraft.server.MinecraftServer.loadOptions(MinecraftServer.java
:1888)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1749)
        ... 12 more

**Comment by dariusc93** [comment]
Please read the commits. TickThreading for 1.6.4 does not work.
