### ISSUE TITLE
Bukkit plugin remap fails due to java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1063]
This is the error im getting when it loads the plugins.

```
22:16:54 [SEVERE] Could not load 'plugins/WorldEdit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class com.sk89q.worldedit.bukkit.WorldEditP
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:194)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
        at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugins(CraftServer.java:231)
        at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:29)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
        at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:817)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:222)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:153)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.sk89q.worldedit.bukkit.WorldEditPlugin
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:539)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:456)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:234)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:183)
        ... 15 more
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.commons.Remapper.mapFieldName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/
        at net.md_5.specialsource.RemappingClassAdapter.visitField(RemappingClassAdapter.java:125)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:241)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:227)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:504)
        ... 22 more
22:16:54 [SEVERE] Could not load 'plugins/PermissionsEx.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class ru.tehkode.permissions.bukkit.Permiss
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:194)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
        at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugins(CraftServer.java:231)
        at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:29)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
        at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:817)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:222)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:153)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: Failed to remap class ru.tehkode.permissions.bukkit.PermissionsEx
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:539)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:456)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:234)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:183)
        ... 15 more
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.commons.Remapper.mapFieldName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/
        at net.md_5.specialsource.RemappingClassAdapter.visitField(RemappingClassAdapter.java:125)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:241)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:227)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:504)
        ... 22 more
22:16:54 [SEVERE] Could not load 'plugins/Essentials.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class com.earth2me.essentials.Essentials
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:194)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
        at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugins(CraftServer.java:231)
        at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:29)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
        at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:817)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:222)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:153)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.earth2me.essentials.Essentials
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:539)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:456)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:234)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:183)
        ... 15 more
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.commons.Remapper.mapFieldName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/
        at net.md_5.specialsource.RemappingClassAdapter.visitField(RemappingClassAdapter.java:125)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:241)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:227)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:504)
        ... 22 more
```

**Comment by ghost** [comment]
Doesn't take a genius level IQ to read a little and notice that everywhere you look TickThreading is not ready yet. Don't use your all caps title saying something shouldn't be used just because you couldn't be bothered to read.

**Comment by Katelyn-SN** [comment]
This was not of the intent to use it as he made a semi usable build a while ago and I tested it and this bug was found. I completely understand its not completely usable yet but I guess you don't understand is a bug tracker.

**Comment by LunNova** [comment]
Just don't put messages in all caps that aren't relevant to the actual issue. I've edited the issue title.

**Comment by ruifung** [comment]
As a temporary but imperfect workaround, set custom-class-loader: false in mcpc.yml

I've tested with worldedit, it appears to be functional with a few warnings and a severe in console.

On a side note: Disabling that appears to break a large amount of other plugins, like essentials.
