### ISSUE TITLE
AE crash with networks with certain tiles in them -  java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1070]
```
2014-05-05 22:26:12 [SEVERE] java.lang.AbstractMethodError
2014-05-05 22:26:12 [SEVERE]    at appeng.me.tile.TileController.updateTileEntity(TileController.java)
2014-05-05 22:26:12 [SEVERE]    at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:713)
2014-05-05 22:26:12 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
2014-05-05 22:26:12 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
2014-05-05 22:26:12 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:98)
2014-05-05 22:26:12 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
2014-05-05 22:26:12 [SEVERE]    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

**Comment by WeslieDE** [comment]
http://pastebin.com/jnwMH9jn

**Comment by WeslieDE** [comment]
With B122 http://pastebin.com/tRKdbs1p
