### ISSUE TITLE
NPE saving entity NBT cause by Morph

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1085]
Morph causes issues when TT installed 

Tested and occuring with both mcpc and vanilla forge

```
05-08 01:53:30 [SEVERE] [TickThreading] Exception ticking world Overworld/0
net.minecraft.util.ReportedException: Saving entity NBT
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1827)
    at net.minecraft.entity.Entity.func_70039_c(Entity.java:1748)
    at morph.common.morph.MorphState.getTag(MorphState.java:79)
    at morph.common.core.EventHandler.onWorldSave(EventHandler.java:852)
    at net.minecraftforge.event.ASMEventHandler_150_EventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:168)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:668)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1791)
    ... 11 more
```

**Comment by devryb** [comment]
Also getting this, it actually breaks world saving too sometimes

http://pastebin.com/7zYiUsQY
