### ISSUE TITLE
Applied Energistics console spam.

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1089]
Error occuring with and without mcpc+ 

Testbed:
MCPC+ latest
Direwolf20 1.6 .20

```
05-08 15:16:03 [SEVERE] Exception When Ticking appeng.me.tile.TileController at -226, 62, -282
05-08 15:16:03 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
05-08 15:16:03 [SEVERE]         at java.util.LinkedList.checkPositionIndex(LinkedList.java:558)
05-08 15:16:03 [SEVERE]         at java.util.LinkedList.listIterator(LinkedList.java:865)
05-08 15:16:03 [SEVERE]         at java.util.AbstractList.listIterator(AbstractList.java:299)
05-08 15:16:03 [SEVERE]         at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
05-08 15:16:03 [SEVERE]         at appeng.me.MEInventoryNetwork.checkRecurrsion(MEInventoryNetwork.java:48)
05-08 15:16:03 [SEVERE]         at appeng.me.MEInventoryNetwork.extractItems(MEInventoryNetwork.java:125)
05-08 15:16:03 [SEVERE]         at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:422)
05-08 15:16:03 [SEVERE]         at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:550)
05-08 15:16:03 [SEVERE]         at appeng.me.tile.TileController.updateTileEntity(TileController.java)
05-08 15:16:03 [SEVERE]         at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:713)
05-08 15:16:03 [SEVERE]         at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
05-08 15:16:03 [SEVERE]         at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
05-08 15:16:03 [SEVERE]         at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:98)
05-08 15:16:03 [SEVERE]         at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
05-08 15:16:03 [SEVERE]         at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
05-08 15:16:03 [SEVERE] MC might crash now...
05-08 15:16:03 [SEVERE] Exception ticking TileEntity c appeng.me.tile.TileController @1203520456 in Overworld/0 at x, y, z: -226, 62, -282
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:720)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:98)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
        at java.util.LinkedList.checkPositionIndex(LinkedList.java:558)
        at java.util.LinkedList.listIterator(LinkedList.java:865)
        at java.util.AbstractList.listIterator(AbstractList.java:299)
        at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
        at appeng.me.MEInventoryNetwork.checkRecurrsion(MEInventoryNetwork.java:48)
        at appeng.me.MEInventoryNetwork.extractItems(MEInventoryNetwork.java:125)
        at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:422)
        at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:550)
        at appeng.me.tile.TileController.updateTileEntity(TileController.java)
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:713)
        ... 5 more
```

**Comment by Vycraftujto** [comment]
and im cann add that opening this AE inventory cause client crash

**Comment by Zeroxius** [comment]
I'm running mine on the latest version of FTB Monster, with the vanilla server jar it includes

In addition, it appears that Applied Energistics systems don't work any longer when the console spits out this error. It no longer imports or exports items that are connected to it, and as said above, accessing the ME system's inventory in any way causes the server to kick the player, or a client crash. (This includes through the wireless terminal, regular terminals or even a logistics pipe)
