### ISSUE TITLE
[TT#171] Thermal Expansion & LP? NPE ticking TileEntity

### ISSUE THREAD

**Issue by nylser** [MinimallyCorrect/TickThreading#1094]
This seems to only happen with machines next to any kind of logistics pipes.
http://pastebin.com/5FGTr7Pe

```
05-10 07:27:53 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.block.machine.TileFurnace @372034430 in Overworld/0 at x, y, z: 860, 108, -464
java.lang.NullPointerException
        at thermalexpansion.block.machine.TileFurnace.processFinish(TileFurnace.java:88)
        at thermalexpansion.block.machine.TileMachineEnergized.func_70316_g(TileMachineEnergized.java:117)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
        at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

**Comment by nylser** [comment]
This NPE happens while accessing the machines inventory (or getRecipe(item)?) it seems:

``` java
this.inventory[0]
```

eg:

``` java
ItemStack output = FurnaceManager.getRecipe(this.inventory[0]).getOutput();
```

or

``` java
this.processMax = PulverizerManager.getRecipe(this.inventory[0]).getEnergy();
```
