### ISSUE TITLE
Exception in main tick loop - Conduits still not fixed - BuildCraft also not fixed

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1095]
Conduits started bugging out and disconnecting this morning and even to go as far as crashing every player on the server no matter where in the world they were.

TT 1.6.4 - Build: 171
MCPC+ 1.6.4 - Build: 262

Thermal Expansion:

```
05-10 12:56:52 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
    at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:75)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
```

BuildCraft:

```
05-10 04:01:40 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileQuarry @2000589439 in Underdark/-100 at x, y, z: -226, 248, -287
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
    at java.util.HashMap$KeyIterator.next(HashMap.java:960)
    at java.util.AbstractCollection.toArray(AbstractCollection.java:195)
    at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:41)
    at org.bukkit.craftbukkit.v1_6_R3.SpigotTimings.getEntityTimings(SpigotTimings.java:70)
    at net.minecraft.entity.Entity.<init>(Entity.java:281)
    at buildcraft.core.EntityRobot.<init>(EntityRobot.java:67)
    at buildcraft.factory.TileQuarry.buildFrame(TileQuarry.java:206)
    at buildcraft.factory.TileQuarry.func_70316_g(TileQuarry.java:175)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

LINK TO FULL LOG:

https://drive.google.com/file/d/0B_ezGwB4rZiNdzBEZmhsN1ljUUE/edit?usp=sharing

**Comment by LunNova** [comment]
Don't put two things in one issue, split this up.
