### ISSUE TITLE
Fluid Conduit NPE

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1096]
```

05-10 22:39:52 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at net.minecraft.world.World.func_82737_E(World.java:4805)
        at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
        at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:75)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
```

**Comment by Katelyn-SN** [comment]
![2014-05-11_18 07 20](https://cloud.githubusercontent.com/assets/2229748/2940145/226658b6-d972-11e3-92f1-4990cb3e2012.png)

Some image of the issue

**Comment by LunNova** [comment]
Looks like this would be caused by a GridFluid from an unloaded world that should no longer exist being left in the list of active grids. I'll add some debugging to log more details when this occurs.

**Comment by Katelyn-SN** [comment]
Alright i will be ready to test it
