### ISSUE TITLE
Minions NPE, causes crash

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1097]
```
05-10 16:58:53 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at atomicstryker.minions.common.jobmanager.Minion_Job_DigMineStairwell.onJobUpdateTick(Minion_Job_DigMineStairwell.java:56)
    at atomicstryker.minions.common.MinionsCore.onTick(MinionsCore.java:195)
    at atomicstryker.minions.common.MinionsCore$ServerTickHandler.tickEnd(MinionsCore.java:705)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:523)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

**Comment by LunNova** [comment]
If that doesn't work, I need a patcher log.

**Comment by Katelyn-SN** [comment]
http://pastebin.com/raw.php?i=pbmBVGyR There you go

**Comment by Katelyn-SN** [comment]
Im going to test that build

**Comment by LunNova** [comment]
You need to give the patcher log taken from after the issue has occurred, if it does happen. That log was from before the relevant minions classes were loaded, so they had not yet been patched and there's nothing related to them in the patcher log yet.

**Comment by Katelyn-SN** [comment]
Our b-team server is starting with the new version ill send you the log after we go through and test minions to cause the logs to generate errors if any

**Comment by Katelyn-SN** [comment]
Still occuring

http://pastebin.com/raw.php?i=MisAc8CL

**Comment by LunNova** [comment]
Patcher log.

**Comment by Katelyn-SN** [comment]
Sorry about that well now you have both :P http://pastebin.com/raw.php?i=6h5Cw1Bm

**Comment by Katelyn-SN** [comment]
Oh 4 lines from the top of the patcher log that did not get copyed

```
05-17 19:09:08 [FINE] [TTPatcher] PatchHook running under classloader sun.misc.Launcher$AppClassLoader
05-17 19:09:11 [FINE] [TTPatcher] Patching net.minecraftforge.event.Event with final(field:listeners)
05-17 19:09:11 [FINE] [TTPatcher] Patching net.minecraftforge.event.Event with removeFieldAndInitializers(field:annotationMap,silent:true)
05-17 19:09:11 [FINE] [TTPatcher] java.util.Map at Event.java:34 replaced with {{ $_ = null; }}
```

**Comment by Katelyn-SN** [comment]
Alright going to test

**Comment by Katelyn-SN** [comment]
Errors seem to be gone and creating minions does not cause errors either TT log is all FINEST and FINE errors now patcher log shows no patcher errors

**Comment by LunNova** [comment]
Excellent. I'll close this tomorrow if you still haven't had any minion-related issues by then.

**Comment by Katelyn-SN** [comment]
Alright we will be doing some extensive testing through the mod to make sure nothing else turns up :)

**Comment by Katelyn-SN** [comment]
Confirmed to be fixed you may close now
