### ISSUE TITLE
Greymerk NPE generating world on first start

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1098]
```
2014-05-10 23:27:53 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNullPointerException
java.lang.NullPointerException
    at greymerk.roguelike.catacomb.dungeon.room.DungeonOssuary.skull(DungeonOssuary.java:382)
    at greymerk.roguelike.catacomb.dungeon.room.DungeonOssuary.generate(DungeonOssuary.java:242)
    at greymerk.roguelike.catacomb.CatacombLevel.generate(CatacombLevel.java:99)
    at greymerk.roguelike.catacomb.Catacomb.generate(Catacomb.java:65)
    at greymerk.roguelike.catacomb.Catacomb.generateNear(Catacomb.java:38)
    at greymerk.roguelike.catacomb.Catacomb.spawnInChunk(Catacomb.java:202)
    at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:13)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:133)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ThreadedChunkProvider.java:659)
    at net.minecraft.world.gen.ChunkProviderServer.tryPopulateChunks(ThreadedChunkProvider.java:677)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAtInternal(ThreadedChunkProvider.java:642)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ThreadedChunkProvider.java:514)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ThreadedChunkProvider.java:455)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:480)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:428)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:159)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
```

**Comment by LunNova** [comment]
Nevermind, this issue can happen without TT: http://hopper.minecraft.net/crashes/minecraft/MCX-1374130/
