### ISSUE TITLE
ComputerCraft Deadlock

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1110]
```
Waiting ThreadManagers: Entities in Overworld/0, World Tick

Definitely deadlocked: 
"Thread-598645" Id=599733 BLOCKED on [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@bdb352d owned by "Entities in Overworld/0 - 4" Id=129
    at dan200.computer.core.apis.PeripheralAPI$2.execute(PeripheralAPI.java:306)
    -  blocked on [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@bdb352d
    at dan200.computer.core.ComputerThread$1$1.run(ComputerThread.java:117)
    at java.lang.Thread.run(Unknown Source)


"Entities in Overworld/0 - 4" Id=129 BLOCKED on dan200.computer.core.Computer@2f185af4 owned by "Entities in Overworld/0 - 3" Id=128
    at dan200.computer.core.Computer.queueLuaEvent(Computer.java:956)
    -  blocked on dan200.computer.core.Computer@2f185af4
    at dan200.computer.core.Computer$APIEnvironment.queueEvent(Computer.java:94)
    at dan200.computer.core.apis.PeripheralAPI.onPeripheralChanged(PeripheralAPI.java:282)
    -  locked [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@bdb352d
    at dan200.computer.core.Computer$APIEnvironment.onPeripheralChanged(Computer.java:169)
    -  locked [Ldan200.computer.api.IPeripheral;@6480236f
    at dan200.computer.core.Computer.setPeripheral(Computer.java:683)
    -  locked [Ldan200.computer.api.IPeripheral;@6480236f
    at dan200.computer.shared.NetworkedComputerHelper.setPeripheral(NetworkedComputerHelper.java:440)
    at dan200.turtle.shared.TileEntityTurtle.setPeripheral(TileEntityTurtle.java:1005)
    at dan200.computer.shared.BlockComputerBase.refreshInput(BlockComputerBase.java:192)
    at dan200.computer.shared.BlockComputerBase.func_71863_a(BlockComputerBase.java:146)
    at net.minecraft.world.World.func_72821_m(World.java:302)
    at net.minecraft.world.World.func_72898_h(World.java:1127)
    at net.minecraft.world.World.func_72851_f(World.java:1082)
    at dan200.turtle.shared.TileEntityTurtle.move(TileEntityTurtle.java:1598)
    at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2607)
    at dan200.turtle.shared.TileEntityTurtle.func_70316_g(TileEntityTurtle.java:2469)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@18967ff5
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@18967ff5
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)


"Entities in Overworld/0 - 3" Id=128 BLOCKED on [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@bdb352d owned by "Entities in Overworld/0 - 4" Id=129
    at dan200.computer.core.apis.PeripheralAPI.advance(PeripheralAPI.java:351)
    -  blocked on [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@bdb352d
    at dan200.computer.core.Computer.advance(Computer.java:511)
    -  locked java.util.ArrayList@40aaba6f
    -  locked dan200.computer.core.Computer@2f185af4
    at dan200.computer.shared.NetworkedComputerHelper.update(NetworkedComputerHelper.java:128)
    at dan200.turtle.shared.TileEntityTurtle.func_70316_g(TileEntityTurtle.java:2464)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@8b5ee94
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@8b5ee94
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

```

**Comment by dariusc93** [comment]
Is this using the latest CC from their website and not from a modpack? Sorry for replying to this, but CC did fix most of their deadlock issues unless this is related to TT itself

**Comment by LunNova** [comment]
It's not latest, but this one looks like it will only happen with multiple CC tileentities being ticked in different threads, so it's a TT issue.
