### ISSUE TITLE
NPE in ThermalExpansion

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1112]
2014-05-15 20:52:15 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.block.machine.TilePulverizer @1079223390 in skyworld/6 at x, y, z: -3000, 79, -4199
java.lang.NullPointerException
        at thermalexpansion.block.machine.TilePulverizer.processStart(TilePulverizer.java:97)
        at thermalexpansion.block.machine.TileMachineEnergized.func_70316_g(TileMachineEnergized.java:126)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
        at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by ProsperCraft** [comment]
We are having this as well on FTB Agrarian Skies 2.1.6, MCPC+

05-28 01:21:41 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.block.machine.TilePulverizer @1103677668 in AgrarianSkies2/0 at x, y, z: 3297, 78, 3419
java.lang.NullPointerException
        at thermalexpansion.block.machine.TilePulverizer.processFinish(TilePulverizer.java:105)
        at thermalexpansion.block.machine.TileMachineEnergized.func_70316_g(TileMachineEnergized.java:117)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
        at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by ProsperCraft** [comment]
One thing I can add to this, when we went to the machine, it was set up on a loop, on Agrarian Skies you put cobble in which turns to gravel, then gravel in to get sand, and sand in to get dust, then dust won't go in.

This pulverizer was accepting dust, and turning it into gravel.

dupe here: https://github.com/nallar/TickThreading/issues/1139

**Comment by Phreag** [comment]
@nallar are you working on this issue? or will you not support thermalexpansion with tickThreading?
