### ISSUE TITLE
Exception ticking TileEntity c net.minecraft.tileentity.TileEntityBeacon

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1115]
2014-05-15 20:45:08 [SEVERE] [TickThreading] Exception ticking TileEntity c net.minecraft.tileentity.TileEntityBeacon @143955883 in skyworld/6 at x, y, z: 3154, 33, -4211
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
        at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(ModifiableAttributeInstance.java:85)
        at net.minecraft.potion.Potion.func_111185_a(Potion.java:384)
        at net.minecraft.entity.EntityLivingBase.func_70695_b(EntityLivingBase.java:850)
        at net.minecraft.entity.player.EntityPlayerMP.func_70695_b(EntityPlayerMP.java:1273)
        at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:779)
        at net.minecraft.tileentity.TileEntityBeacon.func_82124_t(TileEntityBeacon.java:112)
        at net.minecraft.tileentity.TileEntityBeacon.func_70316_g(TileEntityBeacon.java:87)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
        at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by Katelyn-SN** [comment]
I would recommend adding -XX:-OmitStackTraceInFastThrow to your java arguments so nallar can get the caused by stacks as well.

**Comment by WeslieDE** [comment]
This was on out Agrarian server who dont run with TT.
We have switch back to pure mcpc+. 
Then you need more infos to fix this i cant install TT again.

**Comment by Katelyn-SN** [comment]
We need stack traces so we can locate the line numbers on where the error is occuring

**Comment by LunNova** [comment]
Nah, that parameter is only needed if it tells you to add it, it didn't.

**Comment by LunNova** [comment]
@PePaPu, in that area are there multiple nearby beacons?

**Comment by WeslieDE** [comment]
![2014-05-17_11 56 55](https://cloud.githubusercontent.com/assets/7493154/3004588/b1c3b9d2-dda9-11e3-8189-369cd7e2fc7c.png)

every bacon is in one chunk.
