### ISSUE TITLE
NPE in thermalexpansion

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1122]
Still not fixet in B200. See #1096 

05-17 21:15:01 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
        at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:75)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:331)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Which version of Thermal Expansion are you using? I might be looking at a different version of TE's GridFluid, as far as I can see this should be impossible now.

**Comment by WeslieDE** [comment]
This is from the FTB monster modpack. It include Thermal Expansion v3.0.0.2
