### ISSUE TITLE
NPE - Exception ticking entity EntitySkeleton

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1136]
05-19 07:50:44 [SEVERE] [TickThreading] Exception ticking entity EntitySkeleton['Skeleton'/61520, l='DIM_MYST55', x=77,50, y=60,00, z=416,50] in rX: 2, rZ: 13, hashCode: 851970/DIM_MYST55/0:
java.lang.NullPointerException
    at net.minecraft.entity.EntityLiving.func_70623_bb(EntityLiving.java:622)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:644)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:196)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:41)
    at net.minecraft.entity.monster.EntitySkeleton.func_70636_d(EntitySkeleton.java:189)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1973)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:264)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:49)
    at net.minecraft.world.World.func_72866_a(World.java:387)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:1006)
    at net.minecraft.world.World.func_72870_g(World.java:2891)
    at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by Jasnatdic** [comment]
This plus #1134 and also #1119 are all the same issue with identical stack trace other than the entity name and location.
