### ISSUE TITLE
Exception ticking entity EntityGrenade - Causing all of flans mod to break

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1140]
It causes flans mod to break not allowing you to use or craft anything.

```
05-19 11:18:43 [SEVERE] [TickThreading] Exception ticking entity EntityGrenade['entity.Grenade.name'/210844, l='world', x=-1144.44, y=31.00, z=-703.37] in rX: -36, rZ: -22, hashCode: -1441828/Overworld/0:
java.lang.NullPointerException
    at co.uk.flansmods.common.guns.EntityGrenade.func_70071_h_(EntityGrenade.java:80)
    at net.minecraft.world.World.func_72866_a(World.java:387)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:1006)
    at net.minecraft.world.World.func_72870_g(World.java:2891)
    at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

**Comment by LunNova** [comment]
That's odd, I don't see how that can be null without other flans mod errors occurring earlier in the log. Are there any different errors before that happens?

**Comment by LunNova** [comment]
Also, this is with flan's mod 4.1.1?

**Comment by Katelyn-SN** [comment]
flansmod-4.1.1 Yep
