### ISSUE TITLE
[SEVERE] [TickThreading-1.6.4.206] [MCPC] [1.6.4] Exception ticking TileEntity c codechicken.translocator.TileItemTranslocator 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1145]
[SEVERE] [TickThreading] Exception ticking TileEntity c codechicken.translocator.TileItemTranslocator @875599067 in Overworld/0 at x, y, z: -10793, 51, 1033
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.<init>(ItemStack.java:91)
    at codechicken.translocator.TileTranslocator$Attachment.getDrops(TileTranslocator.java:167)
    at codechicken.translocator.TileItemTranslocator$ItemAttachment.getDrops(TileItemTranslocator.java:103)
    at codechicken.translocator.TileTranslocator.harvestPart(TileTranslocator.java:302)
    at codechicken.translocator.TileItemTranslocator.func_70316_g(TileItemTranslocator.java:273)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
Ps welcome back! and sorry if im spamming you with these :P
