### ISSUE TITLE
[SEVERE] [TickThreading-1.6.4.206] [MCPC] [1.6.4] The server appears to have deadlocked.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1146]
[SEVERE] [TickThreading] The server appears to have deadlocked.
Last tick 35s ago.
Waiting ThreadManagers: Entities in Overworld/0

Definitely deadlocked: 
"Connection #35 write thread" Id=493 BLOCKED on java.lang.Object@74afaaff owned by "Connection #10 write thread" Id=331
    at net.minecraft.network.TcpConnection.func_74429_a(TcpConnection.java:93)
    -  blocked on java.lang.Object@74afaaff
    at net.minecraft.network.NetServerHandler.func_72567_b(NetServerHandler.java:1050)
    at net.minecraft.server.management.ServerConfigurationManager.func_72384_a(ServerConfigurationManager.java:1135)
    at cpw.mods.fml.common.network.PacketDispatcher.sendPacketToAllPlayers(PacketDispatcher.java:80)
    at mcp.mobius.opis.data.managers.StringCache.getIndex(StringCache.java:54)
    at mcp.mobius.opis.data.holders.newtypes.CachedString.<init>(CachedString.java:33)
    at mcp.mobius.opis.data.holders.newtypes.DataPacket250.<init>(DataPacket250.java:20)
    at mcp.mobius.opis.data.profilers.ProfilerPacket.start(ProfilerPacket.java:55)
    at mcp.mobius.mobiuscore.profiler.ProfilerSection.start(ProfilerSection.java:111)
    at net.minecraft.network.TcpConnection.func_74460_a(TcpConnection.java:269)
    -  locked java.lang.Object@51238bce
    at net.minecraft.network.TcpConnection.func_74459_h(TcpConnection.java:198)
    at net.minecraft.network.TcpConnection.func_74451_d(TcpConnection.java:564)
    at net.minecraft.network.TcpWriterThread.run(TcpWriterThread.java:25)

"Connection #10 write thread" Id=331 BLOCKED on java.lang.Object@51238bce owned by "Connection #35 write thread" Id=493
    at net.minecraft.network.TcpConnection.func_74429_a(TcpConnection.java:93)
    -  blocked on java.lang.Object@51238bce
    at net.minecraft.network.NetServerHandler.func_72567_b(NetServerHandler.java:1050)
    at net.minecraft.server.management.ServerConfigurationManager.func_72384_a(ServerConfigurationManager.java:1135)
    at cpw.mods.fml.common.network.PacketDispatcher.sendPacketToAllPlayers(PacketDispatcher.java:80)
    at mcp.mobius.opis.data.managers.StringCache.getIndex(StringCache.java:54)
    at mcp.mobius.opis.data.holders.newtypes.CachedString.<init>(CachedString.java:33)
    at mcp.mobius.opis.data.holders.newtypes.DataPacket250.<init>(DataPacket250.java:20)
    at mcp.mobius.opis.data.profilers.ProfilerPacket.start(ProfilerPacket.java:55)
    at mcp.mobius.mobiuscore.profiler.ProfilerSection.start(ProfilerSection.java:111)
    at net.minecraft.network.TcpConnection.func_74460_a(TcpConnection.java:269)
    -  locked java.lang.Object@74afaaff
    at net.minecraft.network.TcpConnection.func_74459_h(TcpConnection.java:198)
    at net.minecraft.network.TcpConnection.func_74451_d(TcpConnection.java:564)
    at net.minecraft.network.TcpWriterThread.run(TcpWriterThread.java:25)

Attempting to recover without restarting.

**Comment by LunNova** [comment]
This issue can occur without TT. Report to the Opis dev that it can cause deadlocks.

**Comment by LunNova** [comment]
Fixed in latest, although it shouldn't be my job to fix! :P
