### ISSUE TITLE
Plugin & IC2 & Grass issues...

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1152]
05-23 04:17:30 [WARNING] [TickThreading] Bukkit getChunks call for unloaded world
java.lang.Throwable
    at net.minecraft.world.WorldServer.getChunks(WorldServer.java:113)
    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getLoadedChunks(CraftWorld.java)
    at me.ryanhamshire.TekkitCustomizer.ContrabandScannerTask.run(ContrabandScannerTask.java:49)
    at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:58)
    at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.runQueuedTasks_net_minecraft_server_MinecraftServer_runQueuedTasks_p0(MinecraftServer.java:428)
    at net.minecraft.server.MinecraftServer.runQueuedTasks(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:358)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:294)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

This just keeps spamming the console, im going to guess this has something to do with TC's world bans.

And this crashes the entire server when a MFSU from IC2 is hooked up to a tesseract from Thermal Expansion

05-23 02:17:59 [SEVERE] [TickThreading] Exception ticking world Resource/0
java.lang.AbstractMethodError
    at ic2.core.energy.Grid.prepareCalculation(Grid.java:201)
    at ic2.core.energy.EnergyNetLocal.onTickEnd_sync0(EnergyNetLocal.java:264)
    at ic2.core.energy.EnergyNetLocal.onTickEnd_sync1(EnergyNetLocal.java)
    at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java)
    at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:51)
    at ic2.core.IC2.tickEnd(IC2.java:1793)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:523)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

And yeah... Apparently grass is bad?

05-23 03:35:21 [SEVERE] [TickThreading] Exception ticking block net.minecraft.block.BlockGrass@54b24650 at x40y464z150 in Spawn/2
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getBlockAt(CraftWorld.java:82)
    at net.minecraft.block.BlockGrass.func_71847_b(BlockGrass.java:56)
    at net.minecraft.world.WorldServer.run(WorldServer.java:605)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

Also I am very new to your TT mod but why does it take literally 20x longer to load up plugins then it does mods? And why is MCPC without TT faster at loading up then TT + MCPC?

**Comment by LunNova** [comment]
The patching is done at every startup just now, so that's slow. It'll be changed to cache patched classes eventually.

About TekkitCustomizer, see the plugin compatibility page, https://github.com/nallar/TickThreading/wiki/Bukkit-Plugin-Compatibility-(MCPC-) - Tekkit Customizer does naughty things with unloaded worlds and is no longer maintained so I updated it.

Your IC2 issue is odd - please check that's not TT only, and if it is TT only give a list of your mods directory - in that case it means you have multiple copies of that class in different mods.

The grass issue does appear to be a real problem.

In future please don't post a single issue with multiple problems, make an issue per different error.

**Comment by Zilacon** [comment]
Alright thanks for the quick reply, ill try the TC version you linked.

Also question: Is there ANY config to the TT settings? Or is there any settings at all?
And would you ever add detailed reports to /profile like what Opis Control Panel has? It shows every entity, tile entity, handler, etc in a GUI but could this be possible to do and throw it in a txt file like how Bukkit does plugin profiling with /timings?

**Comment by alicheek** [comment]
Yea there is a tickthreading config in the config folder where all the mods configs are held

**Comment by Zilacon** [comment]
I know that but thats simply to ask if you want the logs colored or not and where the server jar is.

I mean settings controlling how TT functions.

**Comment by alicheek** [comment]
that's the ttstartup config I'm meaning in the config folder there is a tickthreading config file

**Comment by Zilacon** [comment]
Thanks! I dont know why i didnt see that earlier... Ive been in and out of that folder for 14 hours now...

One last question: How do i disable the console logs from showing the directory names of the plugins or mods?
Like make this: [com.sk89q.worldguard.bukkit.WorldGuardPlugin] [WorldGuard] INFO
To this: [WorldGuard] INFO

**Comment by alicheek** [comment]
No idea tbh I've never even noticed that in my logs lol

**Comment by Zilacon** [comment]
Well TT shows it in the console, but it never shows it in the actual log files.
Its just really spammy and id like it back to normal if possible.

**Comment by Zilacon** [comment]
Also im watching my server start up from 1GB and slowly rise to 1.6GB when everything is loaded up.

I put the chunk cache as low as i could go (100) but its still going up there, any ideas what could be causing this?

**Comment by alicheek** [comment]
You maybe got forced chunks loaded?

**Comment by Zilacon** [comment]
All of my configs on my server prohibit forced chunk loading.
MCPC.yml & Forge.cfg & ForgeChunkLoading.cfg are all set to "off" for allowing forced chunks.

So its not that...
And this is a brand new world, making a modpack so the worlds not even touched.

**Comment by LunNova** [comment]
Logging should be more normal in latest.

I wouldn't worry about memory usage unless there's actually a problem. What does `/ticks` say?

**Comment by Zilacon** [comment]
05-23 05:36:31 [INFO] [TickThreading] 
World: Resource/0
---- Slowest tick regions ----
 | X | Z | N | Time

---- World stats ----
Loaded 0 Loading 0 Unload 0 UnloadSave 0 Locks 0 PartialSave 0 Forced 0 Cached 100
Average tick time: NaNms
Max tick time: 0.0ms
Effective tick time: 0.034869ms
Average effective tick time: 0.053744886ms
Global TPS: 20.00

Server freshly started 1.78GB RAM used. The server fully loads plugins & mods at around 1GB and then you sit there and watch as the RAM goes up and up and up... When someone logs in the RAM spikes to around 2-2.4GB.

**Comment by LunNova** [comment]
Also, missed your question earlier. A cool GUI for profiling is planned just it's not a priority just now. #1083

If you're not getting out of memory errors there's not a problem. Set your startup options to only allow 2GB of RAM and see if it actually dies.

**Comment by Zilacon** [comment]
Thanks for the quick fix on the log problem.

And i set it to 2G and it stops at 1.4GB now. I never said it crashed or anything i was just wondering why it just loaded up 400-800MB of ram on what seems to be nothing.
