### ISSUE TITLE
Pixelmon Issue

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1159]
```
05-24 14:06:21 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
    at java.util.HashMap$KeyIterator.next(HashMap.java:960)
    at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
    at java.util.ArrayList.<init>(ArrayList.java:164)
    at pixelmon.spawning.PixelmonSpawner.doSpawning(PixelmonSpawner.java:103)
    at pixelmon.spawning.PixelmonSpawner.tickEnd(PixelmonSpawner.java:307)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:523)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

With this error the server goes into world Nether unstable restarting in under 10 seconds after inital player login

**Comment by Katelyn-SN** [comment]
This fix is useless until #1125 is fixed
