### ISSUE TITLE
exception in EntityPotionColorPacketAdapter#onPacketSending OMG SPAM!

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1160]
2014-05-24 14:13:19 [INFO] Caught java.lang.NullPointerException exception in EntityPotionColorPacketAdapter#onPacketSending
2014-05-24 14:13:19 [INFO] Message: null
2014-05-24 14:13:19 [INFO] Stack Trace:
2014-05-24 14:13:19 [SEVERE] java.lang.NullPointerException
2014-05-24 14:13:19 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getUID(CraftWorld.java:481)
2014-05-24 14:13:19 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.equals(CraftWorld.java:1156)
2014-05-24 14:13:19 [SEVERE]    at guava10.com.google.common.base.Objects.equal(Objects.java:51)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.wrappers.BukkitConverters$WorldSpecificConverter.equals(BukkitConverters.java:189)
2014-05-24 14:13:19 [SEVERE]    at guava10.com.google.common.base.Objects.equal(Objects.java:51)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:423)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.events.PacketContainer.getEntityModifier(PacketContainer.java:416)
2014-05-24 14:13:19 [SEVERE]    at com.massivecraft.mcore.integration.protocollib.EntityPotionColorPacketAdapter.onPacketSending(EntityPotionColorPacketAdapter.java:54)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:612)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:588)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.injector.player.PlayerInjector.handlePacketSending(PlayerInjector.java:628)
2014-05-24 14:13:19 [SEVERE]    at com.comphenix.protocol.injector.player.NetworkServerInjector$1.intercept(NetworkServerInjector.java:159)
2014-05-24 14:13:19 [SEVERE]    at net.minecraft.network.NetServerHandler$$EnhancerByCGLIB$$ec68c0d0.func_72567_b(<generated>)
2014-05-24 14:13:19 [SEVERE]    at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:463)
2014-05-24 14:13:19 [SEVERE]    at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:291)
2014-05-24 14:13:19 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:526)
2014-05-24 14:13:19 [SEVERE]    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
2014-05-24 14:13:19 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
2014-05-24 14:13:19 [SEVERE]    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

This was literally spammed on the console over 500 times in a 3 second span, made a 1.5MB server log file instantly... I have no clue what caused this or how to re-produce this.

Apparently this is caused by ProtocolLib, this versions being used on 4 of my 1.6.4 servers and never have i seen this lol...

I am using ProtocolLib 3.3.1

**Comment by LunNova** [comment]
ProtocolLib is storing unloaded worlds in a collection, which would normally cause a memory leak. Disable world unloading in TT's config or stop using ProtocolLib.
