### ISSUE TITLE
NPE for ThermalExpansion/LogisticPipes/BuildCraft in 1 error.

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1164]
2014-05-25 20:29:16 [SEVERE] java.lang.NoClassDefFoundError: thermalexpansion/block/ender/TileTesseract
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.proxy.te.ThermalExpansionProxy.isTesseract(ThermalExpansionProxy.java:65)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.asm.wrapper.ThermalExpansionProxyWrapper.isTesseract(ThermalExpansionProxyWrapper.java:182)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.proxy.specialconnection.TesseractConnection.isType(TesseractConnection.java:26)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.proxy.specialconnection.SpecialTileConnection.getConnectedPipes(SpecialTileConnection.java:24)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.routing.pathfinder.PathFinder.getConnectedRoutingPipes(PathFinder.java:223)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.routing.pathfinder.PathFinder.<init>(PathFinder.java:79)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.routing.pathfinder.PathFinder.<init>(PathFinder.java:83)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.routing.ServerRouter.recheckAdjacent(ServerRouter.java:327)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.routing.ServerRouter.checkAdjacentUpdate(ServerRouter.java:824)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:873)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:378)
2014-05-25 20:29:16 [SEVERE]    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
2014-05-25 20:29:16 [SEVERE]    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70316_g(LogisticsTileGenericPipe.java:87)
2014-05-25 20:29:16 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
2014-05-25 20:29:16 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
2014-05-25 20:29:16 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
2014-05-25 20:29:16 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
2014-05-25 20:29:16 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
2014-05-25 20:29:16 [SEVERE]    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2014-05-25 20:29:16 [SEVERE] Caused by: java.lang.ClassNotFoundException: thermalexpansion.block.ender.TileTesseract
2014-05-25 20:29:16 [SEVERE]    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:280)
2014-05-25 20:29:16 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2014-05-25 20:29:16 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2014-05-25 20:29:16 [SEVERE]    ... 19 more
2014-05-25 20:29:16 [SEVERE] Caused by: java.lang.NullPointerException

**Comment by Katelyn-SN** [comment]
This error states that there is a missing class file here:

```
NoClassDefFoundError: thermalexpansion/block/ender/TileTesseract
```

In the thermal expansion mod this could not be caused by tick threading and is likely caused by a corrupt or incomplete mod zip

**Comment by Zilacon** [comment]
Ill try re-downloading it then...

Re-downloaded and even updated, error still persists...
