### ISSUE TITLE
java.lang.NoSuchFieldError: captureBlockStates

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1168]
2014-05-26 01:04:31 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoSuchFieldError
java.lang.NoSuchFieldError: captureBlockStates
    at net.minecraft.world.World.func_72832_d(World.java:867)
    at net.minecraft.world.gen.feature.WorldGenLakes.func_76484_a(WorldGenLakes.java:106)
    at biomesoplenty.world.ChunkProviderBOP.func_73153_a(ChunkProviderBOP.java:596)
    at org.bukkit.craftbukkit.v1_6_R3.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:59)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ThreadedChunkProvider.java:663)
    at net.minecraft.world.gen.ChunkProviderServer.tryPopulateChunks(ThreadedChunkProvider.java:687)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAtInternal(ThreadedChunkProvider.java:644)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ThreadedChunkProvider.java:518)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ThreadedChunkProvider.java:459)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:480)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:428)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:156)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

This error crashes my server everytime now (didnt before but now it does).
I tried downgrading BOP, still did this, then i got a similar error from COFH:
So i tried taking off TT and just using MCPC, server started up fine no problems.

Any idea how to fix this? BOP is a big part of my server.

**Comment by Zilacon** [comment]
I thought maybe it was linked to the Packet54 option in forge.cfg so i set that back down to 64 (minimum) and it gave a new error, still crashes for a similar problem though.

java.lang.NoSuchFieldError: captureBlockStates
    at net.minecraft.world.World.func_72832_d(World.java:867)
    at net.minecraft.world.gen.feature.WorldGenMinable.func_76484_a(WorldGenMinable.java:82)
    at biomesoplenty.biomes.BiomeDecoratorBOP.func_76795_a(BiomeDecoratorBOP.java:1900)
    at biomesoplenty.biomes.BiomeDecoratorBOP.func_76797_b(BiomeDecoratorBOP.java:1928)
    at biomesoplenty.biomes.BiomeDecoratorBOP.func_76794_a(BiomeDecoratorBOP.java:729)
    at biomesoplenty.biomes.BiomeDecoratorBOP.func_76796_a(BiomeDecoratorBOP.java:709)
    at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:371)
    at biomesoplenty.biomes.vanilla.BiomeGenForestNew.func_76728_a(BiomeGenForestNew.java:52)
    at biomesoplenty.world.ChunkProviderBOP.func_73153_a(ChunkProviderBOP.java:625)
    at org.bukkit.craftbukkit.v1_6_R3.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:59)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ThreadedChunkProvider.java:663)
    at net.minecraft.world.gen.ChunkProviderServer.tryPopulateChunks(ThreadedChunkProvider.java:687)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAtInternal(ThreadedChunkProvider.java:644)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ThreadedChunkProvider.java:518)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ThreadedChunkProvider.java:459)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:480)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:428)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:156)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by Zilacon** [comment]
Downgrading TT to build 219 fixes this problem.
The latest version causes this error.
