### ISSUE TITLE
NoSuchFieldError at Chunk Updates

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1173]
05-26 15:44:55 [SEVERE] [TickThreading] Unhandled exception in worker thread Chunk Updates for DIM_MYST63/63 - 9
java.lang.NoSuchFieldError: capturedBlockStates
        at net.minecraft.block.BlockSapling.func_71847_b(BlockSapling.java:58)
        at net.minecraft.world.WorldServer.run(WorldServer.java:605)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by Jasnatdic** [comment]
Which version of TT is this with? I imagine this should have been fixed by the changes in build last couple builds to address block states

**Comment by Katelyn-SN** [comment]
Yes this was fixed in the latest builds I can confirm that

**Comment by WeslieDE** [comment]
Oh sorry, you fix faster then i can update ^^
