### ISSUE TITLE
[TT-1.6.4.225] [MCPC] [1.6.4] [SEVERE] [TickThreading] Exception ticking TileEntity c Reika.RotaryCraft.TileEntities.Production.TileEntityBorer 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1178]
[SEVERE] [TickThreading] Exception ticking TileEntity c Reika.RotaryCraft.TileEntities.Production.TileEntityBorer Tile Entity Boring Machine @ -372, 43, 1883 x, y, z: -372, 43, 1883
java.lang.UnsupportedOperationException: Unused, inefficient parameter choice.
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ThreadedChunkProvider.java:792)
    at Reika.RotaryCraft.TileEntities.Production.TileEntityBorer.forceGenAndPopulate(TileEntityBorer.java:166)
    at Reika.RotaryCraft.TileEntities.Production.TileEntityBorer.updateEntity(TileEntityBorer.java:146)
    at Reika.DragonAPI.Base.TileEntityBase.func_70316_g(TileEntityBase.java:198)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:193)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Spamming the console

**Comment by LunNova** [comment]
Reika.RotaryCraft.TileEntities.Production.TileEntityBorer.forceGenAndPopulate(TileEntityBorer.java:166)

FFS. This shouldn't exist :)

Can we just ban Reika's mods or something? They keep doing odd things.

**Comment by ghost** [comment]
:\ I guess you could but but they are pretty popular. Don't know why he didn't just have the Borer simulate world generation and drop its items from the simulated version.

**Comment by LunNova** [comment]
I'm fine with it causing world gen, that's not the problem. The issue is that it's doing chunk gen wrongly and forcing chunks to be populated before surrounding chunks are loaded, which will cause some populators not to work correctly.

**Comment by Sgat8516** [comment]
Any short term solution to this? Other than chunk loading the line ahead of the bores? These machines are quite effective resource gathering devices when grouped together and powered sufficiently.
