### ISSUE TITLE
[TT-1.6.4.225] [MCPC] [1.6.4] [SEVERE] [TickThreading] Failed to handle packet from unknown

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1180]
[SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (10496 > 16)
    at net.minecraft.network.packet.Packet.func_73282_a(Packet.java:251)
    at net.minecraft.network.packet.Packet2ClientProtocol.func_73267_a(Packet2ClientProtocol.java:34)
    at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:186)
    at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:327)
    at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:69)

**Comment by LunNova** [comment]
Not a TT issue. Caused by a client of the wrong version trying to connect, or possibly some server list services iirc.
