### ISSUE TITLE
TT-230 1.6.4 ThermalExpansion Conduits and Fluiducts randomly stop working until restart

### ISSUE THREAD

**Issue by devryb** [MinimallyCorrect/TickThreading#1194]
This is a pretty big issue as it makes the thermal expansion fluiducts and energy conduits useless in all worlds.

2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:51 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805
2014-05-27 20:17:52 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@a5bc805

**Comment by devryb** [comment]
Possible duplicate of https://github.com/nallar/TickThreading/issues/1122 but was apparently fixed?

This is however with Thermal Expansion 3.0.0.7

**Comment by alicheek** [comment]
Yea can confirm I'm getting spammed with that

**Comment by devryb** [comment]
Here is the full error from in the console:

27.05 19:03:28 [Server] SEVERE Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@2334b9df
27.05 19:03:28 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
27.05 19:03:28 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
27.05 19:03:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
27.05 19:03:28 [Server] INFO at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
27.05 19:03:28 [Server] INFO at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:76)
27.05 19:03:28 [Server] INFO at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
27.05 19:03:28 [Server] INFO java.lang.NullPointerException
27.05 19:03:28 [Server] SEVERE Exception in main tick loop
27.05 19:03:28 [Server] SEVERE Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@2334b9df
27.05 19:03:28 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
27.05 19:03:28 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
27.05 19:03:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
27.05 19:03:28 [Server] INFO at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
27.05 19:03:28 [Server] INFO at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:76)
27.05 19:03:28 [Server] INFO at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
27.05 19:03:28 [Server] INFO java.lang.NullPointerException
27.05 19:03:28 [Server] SEVERE Exception in main tick loop
27.05 19:03:28 [Server] SEVERE Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@2334b9df
27.05 19:03:28 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
27.05 19:03:28 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
27.05 19:03:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
27.05 19:03:28 [Server] INFO at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
27.05 19:03:28 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
27.05 19:03:28 [Server] INFO at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:76)
27.05 19:03:28 [Server] INFO at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
27.05 19:03:28 [Server] INFO java.lang.NullPointerException

**Comment by Katelyn-SN** [comment]
A simple fix for this when running mcpc plus is to edit the mcpc.yml at the bottom to make sure all worlds stay loaded its a work around for now

**Comment by devryb** [comment]
Thanks, trying that out now

**Comment by devryb** [comment]
Still happens with those values all set to true

**Comment by Katelyn-SN** [comment]
Well don't expect  a fix soon nallar is gone and nobody knows if he will be back
