### ISSUE TITLE
Unhandled exception in worker thread Entities

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1195]
05-27 22:40:51 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Sanctuary/3 - 1
java.lang.IllegalStateException: Not iterating yet.
    at nallar.collections.LinkedHashSetTempSetNoClear.done(LinkedHashSetTempSetNoClear.java:50)
    at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:103)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
#1195, #1196 and #1197 are all symptoms of the same issue - a world is being ticked twice at the same time for some odd reason.

Can you paste your TT config? Specifically I'm wondering if it's set not to wait for entity tick completion.

I'mll close the others as duplicate since they're caused by a single root problem.

**Comment by alicheek** [comment]
I can confirm that if you have wait for tick completion that ic2 items don't work, it's like that old bug where the solar panels aren't facing up and also the ic2 cables don't connect to each other, so I turned it back to true

**Comment by Zilacon** [comment]
Heres my config http://pastie.org/9231533

**Comment by LunNova** [comment]
Change B:waitForEntityTickCompletion=false back to true, it should resolve the issue.
