### ISSUE TITLE
TT 1.4.7 Does not work at all with Tekkit Lite

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1201]
Tried using Tekkit Lite since that server has so many crashing problems and TT shutsdown when a crash happens and my start script restarts it so i don't have to worry about it crashing when im asleep.

However this is what i get everytime i start the server:

2014-05-28 10:15:19 [SEVERE] [TickThreading] Nether/-1 has become unstable, stopping.
2014-05-28 10:15:19 [SEVERE] [TickThreading] Exception ticking world The End/1
java.lang.NoSuchFieldError: a
    at yc.h_net_minecraft_world_World_updateEntities_p0(World.java:854)
    at yc.h(World.java)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:532)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:411)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:306)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
    at fy.run(ThreadMinecraftServer.java:16)
2014-05-28 10:15:19 [SEVERE] [TickThreading] The End/1 has become unstable, stopping.
2014-05-28 10:15:19 [INFO] [TickThreading] Saving all player data.
2014-05-28 10:15:19 [INFO] [TickThreading] Done saving player data, now saving 6 worlds.
2014-05-28 10:15:19 [INFO] [TickThreading] World save completed, flushing world data to disk.
2014-05-28 10:15:20 [INFO] [TickThreading] Flushed world data to disk.
2014-05-28 10:15:20 [INFO] [TickThreading] Stopping the server. serverRunning: false, serverIsRunning: true, is crash: false

I tried turning everything on and off in the config, there isn't a single thing i didn't try to change in it. Any idea how to fix this?

Oh and it does this for EVERY world not just the nether, just didn't see the point of pasting the same thing over and over.

**Comment by LunNova** [comment]
Make sure you're using the correct latest 1.4.7 build, http://nallar.me/buildservice/job/TickThreading-1.4.7/lastSuccessfulBuild/ and that you remembered to run the patchme script.

Other than that, TT 1.4.7 is no longer supported and I will not be making any bugfixes.

**Comment by Zilacon** [comment]
Thats the build im using... :(
