### ISSUE TITLE
Initing extra LaunchClassLoader - why?!

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1204]
2014-05-29 14:37:22 [SEVERE] [ForgeModLoader] Initing extra LaunchClassLoader - why?!
java.lang.Throwable
    at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:46)
    at micdoodle8.mods.miccore.MicdoodleTransformer.<init>(MicdoodleTransformer.java:43)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:107)
    at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:100)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at nallar.tickthreading.patcher.PatchLauncher.run(PatchLauncher.java:80)
    at nallar.tickthreading.patcher.PatchLauncher.main(PatchLauncher.java:12)

This only happens with Galacticraft, not sure if its TT or a fault in GC coding but none the less my technic servers that all use GC do not have this error.

**Comment by radfast** [comment]
This is an issue in Galacticraft coding (actually, MicdoodleCore) which will affect some more complex setups.  Here's the erroring code:
https://github.com/micdoodle8/MicdoodleCore/blob/1.6/common/micdoodle8/mods/miccore/MicdoodleTransformer.java

We have fixed the issue in Galacticraft 3 for Minecraft 1.7.10.  If you need a fix for Minecraft 1.6.4 we can make a new Galacticraft build easily enough, but that obviously won't be picked up by any of the modpack makers for quite a while - we have no control at all over which versions go into modpacks, and they tend to be a couple of months out of date.

Galacticraft needs the version number (for example, 2.0.14) to match on the server and the client.  It doesn't matter about the build number within that version, so it's ok to use patched builds on a server and not on a client, so long as the main version number 2.0.14 stays the same.

A new build we make now will be version 2.0.14.1092.  So a new build is probably only going to be useful to you if you have players with a modpack which already includes a Galacticraft 2.0.14 version.

Another approach would be to patch the MicdoodleCore code yourself server-side and recompile.  All the MicdoodleCore source code is available on the Github at the link I posted.  You would just need to delete lines 43 to 62 and replace with these two lines instead:

> deobfuscated = Launch.classLoader.getClassBytes("net.minecraft.world.World") != null;
> optifinePresent = Launch.classLoader.getClassBytes("CustomColorizer") != null;
