### ISSUE TITLE
Twilight Forest with TPPI 1.0.4 MCPC+

### ISSUE THREAD

**Issue by Landrash** [MinimallyCorrect/TickThreading#1220]
Whenever anyone enters The Twilight Forest with TPPI 1.0.4 MCPC+/Cauldron.
TickThreading-1.6.4.230
mcpc-plus-1.6.4-R2.1-forge965-B271
Server doesn't crash and continues running without any problems.

```
06-07 22:20:39 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at chylex.hee.system.savedata.WorldData.equals(WorldData.java:77)
    at chylex.hee.system.savedata.Savefile.isWorldEqual(Savefile.java:26)
    at chylex.hee.mechanics.infestation.InfestationTicker.getCache(InfestationTicker.java:50)
    at chylex.hee.mechanics.infestation.InfestationTicker.tickStart(InfestationTicker.java:57)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:55)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:295)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:516)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
06-07 22:20:42 [INFO] [Minecraft] <Landrash> ./tpx Molntussen 7 0 80 0
06-07 22:20:44 [INFO] [Minecraft] <Molntussen> provade du den till Nether?
06-07 22:20:48 [INFO] [Minecraft] <Landrash> för att hoppa hitt
06-07 22:20:53 [INFO] [Minecraft] <Landrash> nej kollar de nu
06-07 22:20:55 [INFO] [Minecraft] Landrash issued server command: /spawn
06-07 22:20:56 [INFO] [Minecraft] Landrash has enabled Thaumic Reliquary.
06-07 22:20:58 [INFO] [Project Red] Created Retrogen database for dimension 7
06-07 22:21:09 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at chylex.hee.system.savedata.WorldData.equals(WorldData.java:77)
    at chylex.hee.system.savedata.Savefile.isWorldEqual(Savefile.java:26)
    at chylex.hee.mechanics.infestation.InfestationTicker.getCache(InfestationTicker.java:50)
    at chylex.hee.mechanics.infestation.InfestationTicker.tickStart(InfestationTicker.java:57)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:55)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:295)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:516)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
06-07 22:21:11 [INFO] [Minecraft] Landrash has enabled Thaumic Reliquary.
06-07 22:21:19 [INFO] [Minecraft] <Landrash> perfekt =)
06-07 22:21:38 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at chylex.hee.system.savedata.WorldData.equals(WorldData.java:77)
    at chylex.hee.system.savedata.Savefile.isWorldEqual(Savefile.java:26)
    at chylex.hee.mechanics.infestation.InfestationTicker.getCache(InfestationTicker.java:50)
    at chylex.hee.mechanics.infestation.InfestationTicker.tickStart(InfestationTicker.java:57)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:55)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:295)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:516)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
06-07 22:21:39 [INFO] [Minecraft] <Landrash> byggt nether huset i en chunk med flit eller random? :p
06-07 22:21:43 [INFO] [Minecraft] Landrash has enabled Thaumic Reliquary.
06-07 22:22:08 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at chylex.hee.system.savedata.WorldData.equals(WorldData.java:77)
    at chylex.hee.system.savedata.Savefile.isWorldEqual(Savefile.java:26)
    at chylex.hee.mechanics.infestation.InfestationTicker.getCache(InfestationTicker.java:50)
    at chylex.hee.mechanics.infestation.InfestationTicker.tickStart(InfestationTicker.java:57)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:55)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:295)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:516)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
06-07 22:22:16 [INFO] [Minecraft] <Molntussen> awade är i tppi chatten
06-07 22:22:38 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at chylex.hee.system.savedata.WorldData.equals(WorldData.java:77)
    at chylex.hee.system.savedata.Savefile.isWorldEqual(Savefile.java:26)
    at chylex.hee.mechanics.infestation.InfestationTicker.getCache(InfestationTicker.java:50)
    at chylex.hee.mechanics.infestation.InfestationTicker.tickStart(InfestationTicker.java:57)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:55)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:295)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:516)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
>
```

**Comment by witchway915** [comment]
We got the error with all dimensions.

The errors are now gone after disabling hard core ender expansion.
