### ISSUE TITLE
Error: Grid in unloaded or null world nullthermalex pansion.part.conduit.fluid.GridFluid@3295ded0

### ISSUE THREAD

**Issue by Phreag** [MinimallyCorrect/TickThreading#1223]
I run an Attack of The B-Team-Server which i want to work with TickThreading.
It works well, but the console is spamming out this:

06-11 20:50:09 [SEVERE] [Minecraft] Grid in unloaded or null world nullthermalex
pansion.part.conduit.fluid.GridFluid@3295ded0
06-11 20:50:09 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.
java:63)
        at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler
.java:75)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandl
er.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(Wrapped
ScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80
)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_co
mmon_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandle
r.java)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:330)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.
java:16)
06-11 20:50:09 [SEVERE] [Minecraft] Grid in unloaded or null world nullthermalex
pansion.part.conduit.fluid.GridFluid@3295ded0
06-11 20:50:09 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.
java:63)
        at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler
.java:75)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandl
er.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(Wrapped
ScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80
)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_co
mmon_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandle
r.java)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:330)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.

**Comment by Katelyn-SN** [comment]
Already a known issue please close this duplicate
