### ISSUE TITLE
Exception ticking world galacticraft.api.transmission.compatibility.UniversalNetwork

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#1233]
[TickThreading] Exception ticking world Promised Land/21
java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(LinkedList.java:891)
        at micdoodle8.mods.galacticraft.api.transmission.compatibility.UniversalNetwork.doTickStartCalc(UniversalNetwork.java:223)
        at micdoodle8.mods.galacticraft.api.transmission.compatibility.UniversalNetwork.tickEnd(UniversalNetwork.java:184)
        at micdoodle8.mods.galacticraft.core.tick.GCCoreTickHandlerServer.tickEnd(GCCoreTickHandlerServer.java:205)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:282)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:480)
        at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:606)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by Bucky420** [comment]
fixed 

```
<galacticraft>
    <class id="micdoodle8.mods.galacticraft.api.transmission.compatibility.UniversalNetwork">
        <synchronize>refreshAcceptors</synchronize>
    </class>
    <class id="micdoodle8.mods.galacticraft.core.tick.GCCoreTickHandlerServer">
        <synchronize>tickEnd</synchronize>
        <replaceInitializer field="networkTicks" class="nallar.collections.ConcurrentLinkedQueueList"/>
    </class>
</galacticraft>
```

**Comment by radfast** [comment]
Hey, I'm co-dev of Galacticraft with micdoodle8.  Seems like you've fixed the issue with your `<synchronize>` function, but if there's anything we need to do in Galacticraft's code to help things along, please let me know.

Also a heads up, in 1.7.2 / 1.7.10 we plan to refactor Galacticraft's code to move `micdoodle8.mods.galacticraft.api.transmission.compatibility.UniversalNetwork` to become `micdoodle8.mods.galacticraft.core.energy.EnergyNetwork`.  Apart from refactoring changes the code won't actually be changing.  Needs moving because there are too many imports of non-API classes, it doesn't belong in the API any longer (that was a legacy from the Universal Electricity days).  This change will probably be happening today.  Galacticraft 1.7 (compatible with both 1.7.2 and 1.7.10) is here: http://ci.micdoodle8.com/job/Galacticraft-1.7/

**Comment by Bucky420** [comment]
still haven't tried to fix slimelings
