### ISSUE TITLE
Exception in main tick loop - thermalexpansion.part.conduit.GridTickHandler.tickEnd

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#1235]
[TickThreading] Exception in main tick loop
java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
        at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
        at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:101)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:311)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:164)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by Bucky420** [comment]
posable fix :) 

```
<thermalExpansionTransport>
    <class id="thermalexpansion.part.conduit.GridTickHandler">
        <synchronize>tickEnd</synchronize>
    </class>
    <class id="thermalexpansion.part.conduit.ConduitBase">
        <synchronize>load</synchronize>
    </class>
    <class id="thermalexpansion.part.conduit.fluid.GridFluid">
        <insertBefore code="{
            if (worldObj == null || worldObj.unloaded) {
                thermalexpansion.part.conduit.GridTickHandler.tickingGridsToRemove.add(this);
                System.err.println(&quot;Grid in unloaded or null world &quot; + String.valueOf(worldObj) + String.valueOf(this));
                return;
            }
        }">doGridUpdate</insertBefore>
    </class>
    <class id="thermalexpansion.part.conduit.energy.GridEnergy">
        <synchronize/>
    </class>
</thermalExpansionTransport>
```

**Comment by Katelyn-SN** [comment]
Seems to be working so far the console is not full of errors yet but we will have to see what happens.

**Comment by Katelyn-SN** [comment]
Conduits - Functional
Liquiducts - Functional - But break on chunk borders
Itemducts - Functional - But Break on chunk borders

So the main issue with completely not functioning is fixed but breaking on borders is still a issue.

**Comment by Katelyn-SN** [comment]
Sadly seems that there is still issues:

```
07-15 15:47:20 [SEVERE] Grid in unloaded or null world nullthermalexpansion.part.conduit.fluid.GridFluid@792fffc9
07-15 15:47:20 [SEVERE] Exception in main tick loop
java.lang.NullPointerException
        at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
        at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:76)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
        at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:311)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:164)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)


```

This seems to be spamming the console now .....

**Comment by dariusc93** [comment]
This is likely due to the world being uploaded. Please change allowWorldUnloading to false in your TT config and retry again. If possible try without cauldron

**Comment by gigafunk** [comment]
tf-101 wizard, I am having a heck of a time building this from source, and I see on your branch you have applied this change already.  Any possibility of getting your last artifact from you? Even a mediafire link would be helpful.  In Nallar's source build instructs he says its built with ant, yet I can find any ant.xmls, there is a gradle wrapper that I ran successfully per the command given. I even did gradle -build and it was successful, I just cant find the artifact. I have hacked in a few other code echanges in plugins and stuff, this one is just got one to many layer of complication for me to cut through. I know this is beyond the scope of this thread, But I want you to know I tried! I treid for hours!  I got  a vps for a year cheap cheap and this is my only hope of getting some performance out of it.!!!

Thanks! for any tips, link, or _crossing fingers_ artifact download links!!!

**Comment by LunNova** [comment]
See https://github.com/nallar/TickThreading#compiling

Check build/libs for jars.

On 26 July 2014 21:04, gigafunk notifications@github.com wrote:

> tf-101 wizard, I am having a heck of a time building this from source, and
> I see on your branch you have applied this change already. Any possibility
> of getting your last artifact from you? Even a mediafire link would be
> helpful. In Nallar's source build instructs he says its built with ant, yet
> I can find any ant.xmls, there is a gradle wrapper that I ran successfully
> per the command given. I even did gradle -build and it was successful, I
> just cant find the artifact. I have hacked in a few other code echanges in
> plugins and stuff, this one is just got one to many layer of complication
> for me to cut through. I know this is beyond the scope of this thread, But
> I want you to know I tried! I treid for hours! I got a vps for a year cheap
> cheap and this is my only hope of getting some performance out of it.!!!
> 
> Thanks! for any tips, link, or _crossing fingers_ artifact download
> links!!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nallar/TickThreading/issues/1235#issuecomment-50246965
> .

## 

Ross Allan

**Comment by gigafunk** [comment]
Wooo hoo! I found it in build/libs! thank you!! and thank you for all your work on this amazing piece of code man. 

I compiled with gradle, I didn't seem to need ant, but I have it setup, so maybe it works in the background? or maybe I screwed it up!   Thanks for the quick reply!

**Comment by Katelyn-SN** [comment]
Nvm i should read also if your using my source make sure to disable the ability for world's to unload in TT config
