### ISSUE TITLE
Saving entity NBT morph mod?

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#1236]
java.lang.NullPointerException
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1791)
    at net.minecraft.entity.Entity.func_70039_c(Entity.java:1748)
    at morph.common.morph.MorphState.getTag(MorphState.java:81)
    at morph.common.core.EventHandler.onWorldSave(EventHandler.java:862)
    at net.minecraftforge.event.ASMEventHandler_48_EventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:171)
    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.save(CraftWorld.java:717)
    at com.cody.consolerestart.LogHandler.Restart(LogHandler.java:88)
    at com.cody.consolerestart.LogHandler.publish(LogHandler.java:70)
    at java.util.logging.Logger.log(Logger.java:610)
    at java.util.logging.Logger.doLog(Logger.java:631)
    at java.util.logging.Logger.log(Logger.java:720)
    at nallar.tickthreading.Log.severe(Log.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:166)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Entity being saved --
Details:
    Entity Type: witchery.covenwitch (com.emoniph.witchery.entity.EntityCovenWitch)
    Entity ID: 363115
    Entity Name: Coven Witch
    Entity's Exact location: -243.30, 47.00, 336.70
    Entity's Block location: World: (-244,47,336), Chunk: (at 12,2,0 in -16,21; contains blocks -256,0,336 to -241,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: 0.34, 0.36, 0.21
Stacktrace:
    at net.minecraft.entity.Entity.func_70109_d(Entity.java:1791)
    at net.minecraft.entity.Entity.func_70039_c(Entity.java:1748)
    at morph.common.morph.MorphState.getTag(MorphState.java:81)
    at morph.common.core.EventHandler.onWorldSave(EventHandler.java:862)
    at net.minecraftforge.event.ASMEventHandler_48_EventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:171)
    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.save(CraftWorld.java:717)
    at com.cody.consolerestart.LogHandler.Restart(LogHandler.java:88)
    at com.cody.consolerestart.LogHandler.publish(LogHandler.java:70)
    at java.util.logging.Logger.log(Logger.java:610)
    at java.util.logging.Logger.doLog(Logger.java:631)
    at java.util.logging.Logger.log(Logger.java:720)
    at nallar.tickthreading.Log.severe(Log.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:166)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by dariusc93** [comment]
Does this happen without TT? This looks more like the fault of the mod itself (possible corruption in the morph data file?)

**Comment by Bucky420** [comment]
no this happens with any entity and spams the console

**Comment by Katelyn-SN** [comment]
But the stack does not contain anything to do with tickthreading directly.. only things with logging which wont be a factor in the error.
