### ISSUE TITLE
Exception ticking TileEntity c logisticspipes.pipes.basic.LogisticsTileGenericPipe

### ISSUE THREAD

**Issue by Logos01** [MinimallyCorrect/TickThreading#1237]
```
07-25 15:02:49 [SEVERE] [TickThreading] Exception ticking TileEntity c logisticspipes.pipes.basic.LogisticsTileGenericPipe @662309145 in Overworld/0 at x, y, z: 338, 17, 1212  
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)  
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)  
    at logisticspipes.routing.order.LogisticsOrderManager.totalItemsCountInOrders(LogisticsOrderManager.java:128)  
    at logisticspipes.modules.ModuleProvider.getAvailableItemCount(ModuleProvider.java:204)  
    at logisticspipes.modules.ModuleProvider.canProvide(ModuleProvider.java:188)  
    at logisticspipes.pipes.PipeLogisticsChassi.canProvide(PipeLogisticsChassi.java:513)  
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:296)  
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:60)  
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:43)  
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:41)  
    at logisticspipes.request.RequestTree.request(RequestTree.java:199)  
    at logisticspipes.request.RequestTree.requestPartial(RequestTree.java:225)  
    at logisticspipes.pipes.PipeItemsSatelliteLogistics.throttledUpdateEntity(PipeItemsSatelliteLogistics.java:287)  
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:384)  
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)  
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70316_g(LogisticsTileGenericPipe.java:90)  
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)  
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)  
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)  
    at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)  
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)  
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)  
```

**Comment by Logos01** [comment]
Haven't observed any actual errors client-side related to this. But it has been showing up in the server console log.

**Comment by rallias** [comment]
Pipe at those coords is logistic satellite pipe.

**Comment by ShlongDongSilver** [comment]
i'm going to assume your running tekkit lite like I am if not the answer may still be the same, it is most likely a logistics pipe bug that tick threading has simply pointed out, my console will get spammed with them the bigger your system is. any ways read into it and it seemed to be a logistics pipe problem, I recommend if you haven't make a post on there aswell.
