### ISSUE TITLE
[LanteaCraft] Unhandled exception in ITickAgent. java.util.ConcurrentModificationException  

### ISSUE THREAD

**Issue by Logos01** [MinimallyCorrect/TickThreading#1238]
```
07-25 14:43:15 [WARNING] [LanteaCraft] Unhandled exception in ITickAgent.
```

java.util.ConcurrentModificationException  
            at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)  
            at java.util.ArrayList$Itr.next(ArrayList.java:831)  
            at pcl.lc.core.RemoteChunkLoading.advance(RemoteChunkLoading.java:226)  
            at pcl.common.base.TickHandler.tickChildren(TickHandler.java:51)  
            at pcl.lc.core.ServerTickHandler.tickStart(ServerTickHandler.java:33)  
            at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)  
            at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:22)  
            at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:55)  
            at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:295)  
            at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:473)  
            at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:606)  
            at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)  
            at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by Logos01** [comment]
This behavior is also seen with MystCraft portals (haven't tested with other portal varieties).  
Supplementally, the LanteaCraft method of preloading chunks for portal transit is failing; the chunks need to be loaded via chunkloader.
