### ISSUE TITLE
save-all gives NullPointerException in #854

### ISSUE THREAD

**Issue by SShadowS** [MinimallyCorrect/TickThreading#125]
Using build 854 and typed save-all in server terminal
2013-02-06 14:19:39 [INFO] [BukkitForge] Server issued server command: save-all
2013-02-06 14:19:39 [INFO] [STDOUT] CONSOLE: Forcing save..[m
2013-02-06 14:19:39 [INFO] [STDERR] java.lang.NullPointerException
2013-02-06 14:19:39 [INFO] [STDERR]     at in.a(WorldServer.java:830)
2013-02-06 14:19:39 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftWorld.save(CraftWorld.java:797)
2013-02-06 14:19:39 [INFO] [STDERR]     at org.bukkit.command.defaults.SaveCommand.execute(SaveCommand.java:30)
2013-02-06 14:19:39 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-02-06 14:19:39 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-02-06 14:19:39 [INFO] [STDERR]     at ho.al(DedicatedServer.java:308)
2013-02-06 14:19:39 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-02-06 14:19:39 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:178)
2013-02-06 14:19:39 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:103)
2013-02-06 14:19:39 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-02-06 14:19:39 [INFO] [STDOUT] CONSOLE: Save complete.[m

Se full log here:
https://gist.github.com/SShadowS/4722470

**Comment by SShadowS** [comment]
Crash 20 min later, dont know if it is related.

Log here:
https://gist.github.com/SShadowS/4722627

Close thread by mistake.

**Comment by clienthax** [comment]
possibly related to https://github.com/MinecraftPortCentral/MCPC-Plus/commit/a3c45e3973d7faf405694c6ae639b6a7945dd873 ?

**Comment by LunNova** [comment]
BukkitForge bug - it's trying to do stuff with unloaded worlds. Turn off "cleanWorlds" in the config.
