### ISSUE TITLE
Don`t launch on 1.10.2

### ISSUE THREAD

**Issue by BlayzerQ** [MinimallyCorrect/TickThreading#1261]
**Forge: forge-1.10.2-12.18.3.2185-universal (Auto Server Install)**

[22:50:07] [main/INFO] [STDOUT/]: [me.nallar.mixin.internal.MixinApplicator:logInfo:111]: Handling class nallar.tickthreading.mixin.world.MixinWorld with annotation Annotation(type=Type(descriptor=Lme/nallar/mixin/Mixin;, signature=null, simpleName=me.nallar.mixin.Mixin), values={})
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: java.lang.reflect.InvocationTargetException
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.getMethod0(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Class.getMethod(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:50:07] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	... 6 more
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassFormatError: Arguments can't fit into locals in class file net/minecraft/world/World
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[22:50:07] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 15 more

**Comment by rlemish** [comment]
`[22:37:44] [main/INFO] [STDOUT]: [me.nallar.mixin.internal.MixinApplicator:logInfo:111]: Found Mixin class 'nallar.tickthreading.mixin.forge.MixinFMLCommonHandler' targeting class 'net.minecraftforge.fml.common.FMLCommonHandler with 2 applicators.
[22:37:44] [main/INFO] [STDOUT]: [me.nallar.mixin.internal.MixinApplicator:logInfo:111]: Found Mixin class 'nallar.tickthreading.mixin.world.MixinWorld' targeting class 'net.minecraft.world.World with 12 applicators.
[22:37:47] [main/INFO] [STDOUT]: [me.nallar.mixin.internal.MixinApplicator:logInfo:111]: Handling class nallar.tickthreading.mixin.world.MixinWorld with annotation Annotation(type=Type(descriptor=Lme/nallar/mixin/Mixin;, signature=null, simpleName=me.nallar.mixin.Mixin), values={})
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: java.lang.reflect.InvocationTargetException
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]:       at java.lang.reflect.Method.invoke(Method.java:498)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at java.lang.Class.getDeclaredMethods0(Native Method)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at java.lang.Class.getMethod0(Class.java:3018)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at java.lang.Class.getMethod(Class.java:1784)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:37:47] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]:        ... 6 more
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     ... 13 more
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassFormatError: Arguments can't fit into locals in class file net/minecraft/world/World
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:     at java.lang.ClassLoader.defineClass1(Native Method)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[22:37:47] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]:     ... 15 more
`

**Comment by Cavesnakes** [comment]
It's not ready for use, I think nallar must be busy right now

**Comment by LunNova** [comment]
Yes, as Cavesnakes pointed out (and as the message at the top of the repo points out), TT for recent minecraft is still in development and doesn't work at all.

**Comment by Cavesnakes** [comment]
Glad to see you again, nallar
Any progress on this mod?
