### ISSUE TITLE
1.4.7 Server Deadlock

### ISSUE THREAD

**Issue by funnyzocker** [MinimallyCorrect/TickThreading#1262]
Error Code:
Definitely deadlocked: 
"Entities in Overworld/0 - 9" Id=122 BLOCKED on buildcraft.transport.TileGenericPipe@2dfcbf75 owned by "Entities in Overworld/0 - 6" Id=119
	at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:355)
	-  blocked on buildcraft.transport.TileGenericPipe@2dfcbf75
	at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:328)
	at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:317)
	at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:225)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
	at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
	-  locked buildcraft.transport.TileGenericPipe@19222fda
	at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
	-  locked nallar.tickthreading.util.concurrent.NativeMutex@9e3e894
	at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
	-  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@51ba519e
	at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
	at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
	at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

TT Version: 1.4.7
MCPC+ Version: 1.4.7-R1.1
Modpack Server: Tekkit Lite
My Question: is it possible to get the location of the pipe?

**Comment by funnyzocker** [comment]
Hello???
Nobody?!

**Comment by LunNova** [comment]
1.4.7 TT has not been supported for years. I do not have the time to work on this.

e: You might be able to take a heap dump when it deadlocks and match the object IDs.

Or possibly increase the tick region size to double what it currently is (must be a power of 2), if it is configurable in the version of TT you're using.
