### ISSUE TITLE
Build 918: TropiCraft bugs

### ISSUE THREAD

**Issue by keplersj** [MinimallyCorrect/TickThreading#135]
TropiCraft is installed as a core mod.

Either TickThreading or TropiCraft is throwing an error causing the server to crash without showing anything in the console relating to it, other than:

2013-02-11 20:28:30 [SEVERE] [TickThreading] Looks like another mod broke TickThreaded tile entities in world: Tropics/-127
2013-02-11 20:28:30 [SEVERE] [TickThreading] Looks like another mod broke TickThreaded entities in world: Tropics/-127

**Comment by LunNova** [comment]
Try latest, and disable world unloading. (Only added to the config in latest.)

**Comment by keplersj** [comment]
Looks like that fixed it. Thanks!

**Comment by keplersj** [comment]
Nevermind...

Caused by just being in the Tropics in looks like.

2013-02-12 22:28:03 [INFO] [STDERR] Exception in thread "Chunk Updates for Tropics/-127 - 5" java.lang.NoClassDefFoundError: l
2013-02-12 22:28:03 [INFO] [STDERR]     at a.<init>(CrashReport.java:27)
2013-02-12 22:28:03 [INFO] [STDERR]     at a.a(CrashReport.java:319)
2013-02-12 22:28:03 [INFO] [STDERR]     at yc.m(World.java:826)
2013-02-12 22:28:03 [INFO] [STDERR]     at yc.h(World.java:800)
2013-02-12 22:28:03 [INFO] [STDERR]     at yc.f(World.java:744)
2013-02-12 22:28:03 [INFO] [STDERR]     at yc.e(World.java:702)
2013-02-12 22:28:03 [INFO] [STDERR]     at aje.c(BlockFlower.java:71)
2013-02-12 22:28:03 [INFO] [STDERR]     at aje.b(BlockFlower.java:63)
2013-02-12 22:28:03 [INFO] [STDERR]     at ami.b(BlockStem.java:45)
2013-02-12 22:28:03 [INFO] [STDERR]     at in.run(WorldServer.java:403)
2013-02-12 22:28:03 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
2013-02-12 22:28:03 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)

**Comment by LunNova** [comment]
Closing this as no response after adding change to allow for a proper error log.
