### ISSUE TITLE
TT#943: Exception during tile entity tick ticking: c buildcraft.transport.TileGenericPipe 

### ISSUE THREAD

**Issue by WebMaka** [MinimallyCorrect/TickThreading#149]
Found this in my log this morning - I have my server set to restart every morning.

Error during server restart:

'''2013-02-16 08:05:45 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@7c2179dd x,y,z: 369, 52, 252 at x,y,z:369,52,252
Tick region: rX: 23, rZ: 15, hashCode: 983063:
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at buildcraft.additionalpipes.pipes.TeleportManager.getConnectedPipes(TeleportManager.java:56)
    at buildcraft.additionalpipes.pipes.PipeLiquidsTeleport.fill(PipeLiquidsTeleport.java:31)
    at buildcraft.transport.PipeTransportLiquids.fill(PipeTransportLiquids.java:526)
    at buildcraft.transport.PipeTransportLiquids.fill(PipeTransportLiquids.java:518)
    at buildcraft.transport.TileGenericPipe.fill(TileGenericPipe.java:539)
    at buildcraft.transport.PipeTransportLiquids.moveFromPipe(PipeTransportLiquids.java:359)
    at buildcraft.transport.PipeTransportLiquids.moveLiquids(PipeTransportLiquids.java:342)
    at buildcraft.transport.PipeTransportLiquids.updateEntity(PipeTransportLiquids.java:194)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:163)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:92)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)
'''

**Comment by WebMaka** [comment]
Had another one pop up - lessee if I can get the markup to work properly this time...

`2013-02-16 08:35:41 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@6dc59a3e x,y,z: -1268, 57, -2809 at x,y,z:-1268,57,-2809
Tick region: rX: -79, rZ: -175, hashCode: -11468879:
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at buildcraft.additionalpipes.pipes.TeleportManager.getConnectedPipes(TeleportManager.java:56)
    at buildcraft.additionalpipes.pipes.PipeLiquidsTeleport.fill(PipeLiquidsTeleport.java:31)
    at buildcraft.transport.PipeTransportLiquids.fill(PipeTransportLiquids.java:526)
    at buildcraft.transport.PipeTransportLiquids.fill(PipeTransportLiquids.java:518)
    at buildcraft.transport.TileGenericPipe.fill(TileGenericPipe.java:539)
    at buildcraft.transport.PipeTransportLiquids.moveFromPipe(PipeTransportLiquids.java:359)
    at buildcraft.transport.PipeTransportLiquids.moveLiquids(PipeTransportLiquids.java:342)
    at buildcraft.transport.PipeTransportLiquids.updateEntity(PipeTransportLiquids.java:194)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:163)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:92)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)`
