### ISSUE TITLE
TT#959:Failed to set up Security Manager (java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by WebMaka** [MinimallyCorrect/TickThreading#161]
2013-02-18 08:16:15 [INFO] [STDOUT] Failed to set up Security Manager
2013-02-18 08:16:15 [INFO] [STDERR] java.lang.NoClassDefFoundError: me/nallar/insecurity/InsecurityManager
2013-02-18 08:16:15 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:93)
2013-02-18 08:16:15 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-02-18 08:16:15 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: me.nallar.insecurity.InsecurityManager
2013-02-18 08:16:15 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
2013-02-18 08:16:15 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-02-18 08:16:15 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-02-18 08:16:15 [INFO] [STDERR]     ... 2 more
2013-02-18 08:16:15 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-02-18 08:16:15 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:174)
2013-02-18 08:16:15 [INFO] [STDERR]     ... 4 more

Was a direct stop/update/start/stop/repatch/start process on our MC/FTB server. I'll try refreshing the mods from backups and repatching fresh to see if things behave better.

**Comment by LunNova** [comment]
Can you paste the full FML log file?

**Comment by LunNova** [comment]
Also, I've added more debugging in a newer build, so a log from latest would probably be helpful. Also give a console log, there's a chance something will be logged before FML's logger is initialised.

**Comment by WebMaka** [comment]
I'd already updated to Feed the Beast 8.1.1, and with it, updated TT to #963, so I'll watch for any new errors.
