### ISSUE TITLE
Exception in Server Tick Loop

### ISSUE THREAD

**Issue by tubaboy26** [MinimallyCorrect/TickThreading#162]
cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.eloraam.redpower.RedPowerControl
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:130)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:504)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: com.eloraam.redpower.RedPowerControl
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:57)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:418)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:494)
    ... 5 more
Caused by: java.lang.SecurityException: class "com.eloraam.redpower.RedPowerControl"'s signer information does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(Unknown Source)
    at java.lang.ClassLoader.preDefineClass(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:174)
    ... 31 more

**Comment by LunNova** [comment]
Did you modify redpower? If so, you'll need to remove META-INFs from all redpower jars.

Else, please upload a copy of your entire server directory, except the the world(s). Not an easy issue to debug without that.

**Comment by tubaboy26** [comment]
The TickThreadingBackup was missing most of the mods. _facepalm_

**Comment by LunNova** [comment]
That's intended behaviour now. After a clean install, the TT backups folder should only contain the minecraft server jar, and possibly core mods if any were patched.

Other mods aren't actually patched now - patched classes are put in the patchedMods directory, but the mod jars in the mods folder aren't modified.
