### ISSUE TITLE
Thaumcraft 3 Golem Issues

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#163]
After I installed tickthreading my players have started complaining that their golems no longer work.

After remove the jar and booting the server they begin to work properly.
Any idea on what is going on?

Build: 942
FTB Mindcrack modpack v8.1.1

**Comment by LunNova** [comment]
Anything odd in console?

Can you give more detail on "won't work"? They seem to work for me in local testing, but I may not be testing whatever part was broken by TT.

**Comment by Drehmini** [comment]
My apologies.

The stone golems no longer take the items from a chest and transfer them to another chest.
Tallow golems assigned with a bucket will refill a crucible, but will no longer refill the bucket with water from a designated source.
Tallow golems if assigned to an alembic, will pull the essence from the alembic but not go anywhere.
Clay golems no longer move items to barrels.

All colors are assigned correctly.

Also, I haven't seen anything odd in the console.

**Comment by Drehmini** [comment]
I updated Forgebukkit and repatched TT and it seems to have fixed it.

I'm guess the version of Forgebukkit I had was not compatible with either Thaumcraft or TT.

Thanks for the help nallar. Much appreciated.

**Comment by LunNova** [comment]
Well, I'm still confused. I can't get a golem to work with a crucible for me - it does what you described, picking up the essentia but not placing it anywhere. I might just be using golems wrong though :p

**Comment by Drehmini** [comment]
They work, probably using the golems wrong like you stated.

Definitely updating Forgebukkit and repatching TT fixed the issue.

**Comment by Drehmini** [comment]
It looks like there is still an issue with the golems after all. Here's what the console gives me.

[SEVERE] [TickThreading] Exception during entity tick at rX: 48, rZ: -34, hashCode: -2228176:
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
        at java.util.HashMap$ValueIterator.next(HashMap.java:868)
        at thaumcraft.common.Utils.getMarkedContainerAdjacentToEntity(Utils.java:494)
        at thaumcraft.common.entities.ai.AITakeSupplyInv.a(AITakeSupplyInv.java:52)
        at nd.a(SourceFile:67)
        at thaumcraft.common.entities.golems.EntityGolemBase.bl(EntityGolemBase.java:118)
        at md.c(EntityLiving.java:67)
        at thaumcraft.common.entities.golems.EntityGolemBase.c(EntityGolemBase.java:140)
        at md.j_(EntityLiving.java:843)
        at yc.a(World.java:125)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2255)
        at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)
2013-02-20 03:03:51 [SEVERE] [TickThreading] Exception during entity tick at rX: 50, rZ: -33, hashCode: -2162638:
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
        at java.util.HashMap$ValueIterator.next(HashMap.java:868)
        at thaumcraft.common.Utils.getMarkedContainerAdjacentToEntity(Utils.java:494)
        at thaumcraft.common.entities.ai.AITakeSupplyInv.a(AITakeSupplyInv.java:52)
        at nd.a(SourceFile:67)
        at thaumcraft.common.entities.golems.EntityGolemBase.bl(EntityGolemBase.java:118)
        at md.c(EntityLiving.java:67)
        at thaumcraft.common.entities.golems.EntityGolemBase.c(EntityGolemBase.java:140)
        at md.j_(EntityLiving.java:843)
        at yc.a(World.java:125)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2255)
        at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)                                                    2013-02-20 03:04:04 [SEVERE] [TickThreading] Exception during entity tick at rX: 35, rZ: 30, hashCode: 1966115:
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
        at java.util.HashMap$ValueIterator.next(HashMap.java:868)
        at thaumcraft.common.Utils.getContainersWithRoom(Utils.java:437)
        at thaumcraft.common.entities.ai.AIGotoProvideInv.a(AIGotoProvideInv.java:39)
        at nd.a(SourceFile:67)
        at thaumcraft.common.entities.golems.EntityGolemBase.bl(EntityGolemBase.java:118)
        at md.c(EntityLiving.java:67)
        at thaumcraft.common.entities.golems.EntityGolemBase.c(EntityGolemBase.java:140)
        at md.j_(EntityLiving.java:843)
        at yc.a(World.java:125)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2255)
        at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)

The golems seem to stop working after an hour or two.

**Comment by LunNova** [comment]
Sorry about the very late fix :(
