### ISSUE TITLE
LogisticsPipes Provider Pipe causing Exception

### ISSUE THREAD

**Issue by eagl3s1ght** [MinimallyCorrect/TickThreading#173]
`2013-02-25 12:17:43 [SEVERE] [TickThreading] Exception during tile entity tick
icking: c logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC@30fd6f7f x,y,z: 1466, 105, 1132 at x,y,z:1466,105,1132
ick region: rX: 91, rZ: 70, hashCode: 4587611:
ava.lang.NoClassDefFoundError: logisticspipes/pipes/PipeItemsProviderLogistics$1
       at logisticspipes.pipes.PipeItemsProviderLogistics.getAdaptedInventoryUtil(PipeItemsProviderLogistics.java:160)
       at logisticspipes.pipes.PipeItemsProviderLogistics.getAllItems(PipeItemsProviderLogistics.java:262)
       at logisticspipes.pipes.PipeItemsProviderLogistics.updateInv(PipeItemsProviderLogistics.java:341)
       at logisticspipes.pipes.PipeItemsProviderLogistics.enabledUpdateEntity(PipeItemsProviderLogistics.java:192)
       at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:271)
       at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
       at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:94)
       at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
       at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
       at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
       at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)`

**Comment by LunNova** [comment]
That inner class doesn't even exist... :s

Can you try the latest dev build of logistics pipes?

**Comment by LunNova** [comment]
Classloading issue which is now fixed.
