### ISSUE TITLE
MCPC+ issues collection

### ISSUE THREAD

**Issue by clienthax** [MinimallyCorrect/TickThreading#178]
After patching mcpc for tickthreading it seems that the some bukkit plugins dont work, 
worldedit and worldguard seem to be dead
automessage doesnt print messages (related to ticks?)

**Comment by LunNova** [comment]
b5ff72157e06f9b6cc58 fixes worldedit, probably also worldguard.

**Comment by clienthax** [comment]
Any luck with automessage?

**Comment by LunNova** [comment]
> `<aaa801> nallar, going through a nether portal causes bad things`

**Comment by clienthax** [comment]
```
<aaa801> nallar, going through a nether portal causes bad things
<aaa801> http://i.imgur.com/oOiNz24.png
* TheLaughingMan (~TheLaughi@cpe-70-112-163-24.austin.res.rr.com) has joined #mcportcentral
<aaa801> also now no one can break blocks
<aaa801> :D
<nallar> aaa801, wait, you're running this on a non-test server?
<TheLaughingMan> What is going on?
<nallar> that's a bad idea! :P
<aaa801> ye, i have backups
<aaa801> :D
<aaa801> i think that may be related to groupmanager not assigning groups
<aaa801> as none of the players have there usaul default group stuff
<nallar> I have to go now, got an essay to write, so you should probably revert. You've found enough broken stuff :p
<aaa801> :D
<aaa801> ye essentials groupmanager, no commansd are working
<aaa801> wait, the commands are but it doesnt seem to apply default still
<aaa801> essentials chat seems to be acting derpy
```

**Comment by clienthax** [comment]
013-03-03 21:49:01 [SEVERE] java.lang.NullPointerException
2013-03-03 21:49:01 [SEVERE] java.util.ConcurrentModificationException
2013-03-03 21:49:01 [SEVERE]    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
2013-03-03 21:49:01 [SEVERE]    at java.util.ArrayList$Itr.next(ArrayList.java:791)
2013-03-03 21:49:01 [SEVERE]    at universalelectricity.core.electricity.Electricity.cleanUpNetworks(Electricity.java:123)
2013-03-03 21:49:01 [SEVERE]    at universalelectricity.core.electricity.Electricity.registerConductor(Electricity.java:30)
2013-03-03 21:49:01 [SEVERE]    at universalelectricity.prefab.tile.TileEntityConductor.reset(TileEntityConductor.java:175)
2013-03-03 21:49:01 [SEVERE]    at universalelectricity.prefab.tile.TileEntityConductor.<init>(TileEntityConductor.java:53)
2013-03-03 21:49:01 [SEVERE]    at electricexpansion.common.helpers.TileEntityConductorBase.<init>(TileEntityConductorBase.java:25)
2013-03-03 21:49:01 [SEVERE]    at electricexpansion.common.cables.TileEntityInsulatedWire.<init>(TileEntityInsulatedWire.java:16)
2013-03-03 21:49:01 [SEVERE]    at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
2013-03-03 21:49:01 [SEVERE]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2013-03-03 21:49:01 [SEVERE]    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
2013-03-03 21:49:01 [SEVERE]    at java.lang.Class.newInstance0(Class.java:374)
2013-03-03 21:49:01 [SEVERE]    at java.lang.Class.newInstance(Class.java:327)
2013-03-03 21:49:01 [SEVERE]    at any.c(TileEntity.java:142)
2013-03-03 21:49:01 [SEVERE]    at aam.loadEntities(AnvilChunkLoader.java:505)
2013-03-03 21:49:01 [SEVERE]    at aam.a(AnvilChunkLoader.java:77)
2013-03-03 21:49:01 [SEVERE]    at im.f(ChunkProviderServer.java:269)
2013-03-03 21:49:01 [SEVERE]    at im.getChunkAt(ChunkProviderServer.java:167)
2013-03-03 21:49:01 [SEVERE]    at im.c(ChunkProviderServer.java:136)
2013-03-03 21:49:01 [SEVERE]    at ik.a(PlayerManager.java:75)
2013-03-03 21:49:01 [SEVERE]    at ik.a_sync0(PlayerManager.java:175)
2013-03-03 21:49:01 [SEVERE]    at ik.a(PlayerManager.java)
2013-03-03 21:49:01 [SEVERE]    at gm.a(ServerConfigurationManager.java:210)
2013-03-03 21:49:01 [SEVERE]    at gm.c(ServerConfigurationManager.java:271)
2013-03-03 21:49:01 [SEVERE]    at gm.a_sync1(ServerConfigurationManager.java:166)
2013-03-03 21:49:01 [SEVERE]    at gm.a(ServerConfigurationManager.java)
2013-03-03 21:49:01 [SEVERE]    at it.completeConnection(NetLoginHandler.java:214)
2013-03-03 21:49:01 [SEVERE]    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:155)
2013-03-03 21:49:01 [SEVERE]    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:109)
2013-03-03 21:49:01 [SEVERE]    at it.d(NetLoginHandler.java:190)
2013-03-03 21:49:01 [SEVERE]    at it.c(NetLoginHandler.java:81)
2013-03-03 21:49:01 [SEVERE]    at hu.a(ServerListenThread.java:58)
2013-03-03 21:49:01 [SEVERE]    at ht.b(DedicatedServerListenThread.java:33)
2013-03-03 21:49:01 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:335)
2013-03-03 21:49:01 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-03-03 21:49:01 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:225)
2013-03-03 21:49:01 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:144)
2013-03-03 21:49:01 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)
2013-03-03 21:49:01 [SEVERE] java.lang.NullPointerException

**Comment by LunNova** [comment]
Closing as the UE issues are fixed, and now MCPC+ issues are as separate issues, so no need for this.
