### ISSUE TITLE
TT #1036 server freezing

### ISSUE THREAD

**Issue by xfloh22** [MinimallyCorrect/TickThreading#179]
The server randomly shows this error and the server lags a lot:

The server appears to have frozen on 'TickManager.DoTick: Random world/0' ....

if i remove TT this error doesnt show and the server doesnt freeze.

**Comment by xfloh22** [comment]
this error shows up after the server froze and restarted:

[SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at soaryn.xycraft.machines.block.XyCraftWorldExtension.defer(XyCraftWorldExtension.java:231)
    at soaryn.xycraft.machines.block.XyCraftChunkExtension.unload(XyCraftChunkExtension.java:137)
    at codechicken.xycraftcopy.core.world.WorldExtension.unloadChunk(WorldExtension.java:52)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:70)
    at net.minecraftforge.event.ASMEventHandler_193_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at im.finalizeUnload(ThreadedChunkProvider.java:194)
    at im.tick(ThreadedChunkProvider.java:165)
    at im.b(ThreadedChunkProvider.java:107)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:276)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:442)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

it looks like the same one as all the others

and when someone teleported to the spawn, the server load went from 36% to 180%. i dont know what is causing this, but this happens even without TT and TT just shows the error happening. Someone said it might be bukkitforge, just wanted to let you know incase you can do anything about it.

and another part of an error which caused the crash:

http://pastebin.com/u0ASpUP3

**Comment by xfloh22** [comment]
with the new debug features you added i was able to get the following bug report:

http://pastebin.com/KrUHfM4P

**Comment by LunNova** [comment]
Is this still happening?

**Comment by LunNova** [comment]
The crash log looks like the now fixed xycraft issue, so I'm assuming this is also fixed. If it's not, please comment and I will reopen it.
