### ISSUE TITLE
Issue with logistics pipes spamming the console

### ISSUE THREAD

**Issue by tubaboy26** [MinimallyCorrect/TickThreading#180]
03-03 16:26:23 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC logisticspipes.pr
oxy.cc.LogisticsTileGenericPipe_CC@793c5c6c x,y,z: 1051, 55, -1634 at x,y,z:1051
,55,-1634
Tick region: rX: 65, rZ: -102, hashCode: -6684607:
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at logisticspipes.routing.RouterManager.getOrCreateRouter(RouterManager.
java:78)
        at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.ja
va:483)
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe
.java:266)
        at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doT
ick(TileEntityTickRegion.java:99)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegio
n.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.j
ava:90)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.j
ava:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(
ThreadManager.java:157)

**Comment by LunNova** [comment]
This should no longer be an issue due to Logistics Pipes design changes.
