### ISSUE TITLE
issue with Terrain Control

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#181]
Happens on server statup :| 

it works if i remove it :D 
but ya it would be nice fi this could some how be solved XDDD probly not its probly a plugin issue XD but ya 

Description: Exception in server tick loop

java.lang.IllegalAccessError
    at com.khorn.terraincontrol.bukkit.BukkitWorld.Init(Unknown Source)
    at com.khorn.terraincontrol.bukkit.TCPlugin.onWorldInit(Unknown Source)
    at com.khorn.terraincontrol.bukkit.TCChunkGenerator.getDefaultPopulators(Unknown Source)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:457)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:346)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:117)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by Bucky420** [comment]
Status update? ;'( this is killing my server i rely don't want ocean biomes XDDD

**Comment by LunNova** [comment]
Will fix this after https://github.com/MinecraftPortCentral/MCPC-Plus/issues/802 is fixed.

**Comment by LunNova** [comment]
Assuming this no longer happens as you have made other issues which implies that you got the server started, reply with a new stack trace if it is not fixed, make sure to use newest MCPC+ legacy so the stack trace is usable.
