### ISSUE TITLE
Weard issue spams console a lot!

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#182]
03-05 06:21:09 [SEVERE] [TickThreading] Exception ticking block ali@2226a338 at x6-144y264z0288
java.lang.NullPointerException
        at ali.b(BlockRedstoneTorch.java:153)
        at in.run(WorldServer.java:457)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-05 06:21:09 [SEVERE] [TickThreading] Exception ticking block ali@2226a338 at x15-208y1248z0320
java.lang.NullPointerException
        at ali.b(BlockRedstoneTorch.java:153)
        at in.run(WorldServer.java:457)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Fixed via 02a9f00546d2390d3e.
