### ISSUE TITLE
Build #1071 - MFFS Field Fusion with Admin Card causing Exception

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#184]
<code>03-07 01:20:35 [SEVERE] [TickThreading] TickThreading v1.0.0.1071 for MC1.4.7 on 1.4.7 forge,fml, ForgeEssentials is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading
03-07 01:20:37 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@181f9969 x,y,z: -55, 46, -625 at x,y,z:-55,46,-625
Tick region: rX: -3, rZ: -39, hashCode: -2555907:
java.util.ConcurrentModificationException
    at java.util.Hashtable$Enumerator.next(Unknown Source)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:46)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:515)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:20:37 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@240934f2 x,y,z: -47, 38, -613 at x,y,z:-47,38,-613
Tick region: rX: -2, rZ: -38, hashCode: -2490370:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:515)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:20:38 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@240934f2 x,y,z: -47, 38, -613 at x,y,z:-47,38,-613
Tick region: rX: -2, rZ: -38, hashCode: -2490370:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:515)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:20:47 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@7c42ac3f x,y,z: -255, 87, 3169 at x,y,z:-255,87,3169
Tick region: rX: -15, rZ: 198, hashCode: 12976113:
java.lang.NullPointerException
    at codechicken.enderstorage.TileEnderChest.k_(TileEnderChest.java:160)
    at buildcraft.transport.pipes.PipeItemsWood.checkExtract(PipeItemsWood.java:157)
    at buildcraft.transport.pipes.PipeItemsWood.doWork(PipeItemsWood.java:105)
    at buildcraft.transport.TileGenericPipe.doWork(TileGenericPipe.java:344)
    at buildcraft.api.power.PowerProvider.update(PowerProvider.java:94)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:185)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:20:58 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@57053d6 x,y,z: -256, 85, 3189 at x,y,z:-256,85,3189
Tick region: rX: -16, rZ: 199, hashCode: 13041648:
java.lang.NullPointerException
    at codechicken.enderstorage.TileEnderChest.k_(TileEnderChest.java:160)
    at buildcraft.factory.TileAutoWorkbench.getNearbyItemFromOrientation(TileAutoWorkbench.java:265)
    at buildcraft.factory.TileAutoWorkbench.getNearbyItem(TileAutoWorkbench.java:225)
    at buildcraft.factory.TileAutoWorkbench.extractItem(TileAutoWorkbench.java:157)
    at buildcraft.factory.TileAutoWorkbench.extractItem(TileAutoWorkbench.java:379)
    at buildcraft.transport.pipes.PipeItemsWood.checkExtract(PipeItemsWood.java:134)
    at buildcraft.transport.pipes.PipeItemsWood.doWork(PipeItemsWood.java:105)
    at buildcraft.transport.TileGenericPipe.doWork(TileGenericPipe.java:344)
    at buildcraft.api.power.PowerProvider.update(PowerProvider.java:94)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:185)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:23:14 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@181f9969 x,y,z: -55, 46, -625 at x,y,z:-55,46,-625
Tick region: rX: -3, rZ: -39, hashCode: -2555907:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:546)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:23:14 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@240934f2 x,y,z: -47, 38, -613 at x,y,z:-47,38,-613
Tick region: rX: -2, rZ: -38, hashCode: -2490370:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:546)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:23:14 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@77da65e3 x,y,z: -58, 38, -613 at x,y,z:-58,38,-613
Tick region: rX: -3, rZ: -38, hashCode: -2490371:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:546)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-07 01:25:15 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at net.minecraft.server.MinecraftServer.n(MinecraftServer.java:87)
    at hk.b(SourceFile:20)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:337)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:227)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:145)
    at fy.run(SourceFile:849)
03-07 01:25:18 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at java.lang.Runtime.exit(Unknown Source)
    at java.lang.System.exit(Unknown Source)
    at ho.p(DedicatedServer.java:264)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
    at fy.run(SourceFile:849)
</code>

**Comment by alicheek** [comment]
@nallar 

on the 1437  build and its still doing it 

2013-04-27 02:41:50 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@2cdb87f x,y,z: 67, 55, 841 at x,y,z:67,55,841
Tick region: rX: 4, rZ: 52, hashCode: 3407876:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:515)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)

**Comment by alicheek** [comment]
@nallar 
Still getting it in build 1446

[SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@6dcddf5 x,y,z: 67, 55, 841 at x,y,z:67,55,841
Tick region: rX: 4, rZ: 52, hashCode: 3407876:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:515)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-28 02:19:38 [SEVERE] [TickThreading] Exception during tile entity tick
