### ISSUE TITLE
FTB Ultimate v1.0.1

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#191]
Last login: Sun Mar 10 18:17:13 on ttys000
Csorba-Mac-mini:~ csorbabalazs$ /Users/csorbabalazs/Desktop/Ultimate_Server/start.command ; exit;
java.lang.VerifyError: (class: cpw/mods/fml/relauncher/FMLLogFormatter, method: <init> signature: ()V) Constructor must call super() or this()
    at cpw.mods.fml.relauncher.FMLRelaunchLog.configureLogging(FMLRelaunchLog.java:155)
    at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:231)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.log(RelaunchClassLoader.java:47)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.construct(RelaunchClassLoader.java:117)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runConstructors(RelaunchClassLoader.java)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.<init>(RelaunchClassLoader.java:71)
    at cpw.mods.fml.relauncher.FMLRelauncher.<init>(FMLRelauncher.java:50)
    at cpw.mods.fml.relauncher.FMLRelauncher.instance(FMLRelauncher.java:40)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Exception in thread "main" java.lang.VerifyError: (class: cpw/mods/fml/relauncher/FMLLogFormatter, method: <init> signature: ()V) Constructor must call super() or this()
    at cpw.mods.fml.relauncher.FMLRelaunchLog.configureLogging(FMLRelaunchLog.java:155)
    at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:216)
    at cpw.mods.fml.relauncher.FMLRelaunchLog.info(FMLRelaunchLog.java:248)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:150)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)

**Comment by LunNova** [comment]
Try a newer build, that's been fixed.

**Comment by ghost** [comment]
install new build but didn't work

http://pastebin.com/pGBbDbhf
what's the problem?

**Comment by LunNova** [comment]
That deadlock should be fixed in build 1098. (71624e12fad04fd126819392)

**Comment by ghost** [comment]
thanks!:)
