### ISSUE TITLE
TT#1103: Constant NullPointerException from MoCreatures 4.5.1 (Running on MCPC+ 1.4.7-R1.1b243)

### ISSUE THREAD

**Issue by WebMaka** [MinimallyCorrect/TickThreading#193]
Apparently MoCreatures no likey TickThreading... These are -constant-...

03-10 19:02:23 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:24 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:25 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:25 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:25 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)
    at fy.run(ThreadMinecraftServer.java:16)
03-10 19:02:25 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:266)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:147)

**Comment by LunNova** [comment]
Does this still happen with world unloading disabled?

**Comment by WebMaka** [comment]
Lemme give that a try right quick...

EDIT: Using build 1110 of TT and the latest MCPC+ build (245), setting "B:allowWorldUnloading=false" stopped the errorspam from MoCreatures and allowed me to log into the test server.

Also, and I don't know if this will be a factor, I've disabled ChickenChunks since it seems to be a problem child in a lot of FTB server setups.

**Comment by LunNova** [comment]
Looks like that's just a MoCreatures bug with not handling world unloads properly, so there isn't really anything I can do other than tell people to disable world unloading if this happens.
