### ISSUE TITLE
TT #1106 Deadlock on server launch

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#195]
03-11 02:08:28 [SEVERE] [TickThreading] TickThreading v1.0.0.1106 for MC1.4.7 on 1.4.7 forge,fml, ForgeEssentials is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading
03-11 02:08:32 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.factory.TilePump buildcraft.factory.TilePump@3c841690 x,y,z: 339, 49, 31 at x,y,z:339,49,31
Tick region: rX: 21, rZ: 1, hashCode: 65557:
java.lang.NullPointerException
    at buildcraft.transport.PipeTransportLiquids.fill(PipeTransportLiquids.java:525)
    at buildcraft.transport.PipeTransportLiquids.fill(PipeTransportLiquids.java:518)
    at buildcraft.transport.TileGenericPipe.fill(TileGenericPipe.java:532)
    at buildcraft.factory.TilePump.g(TilePump.java:131)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-11 02:09:21 [SEVERE] [TickThreading] The server appears to have deadlocked.
Last tick 45s ago.
Ticking: TickManager.doTick: Overworld/0
Current Thread: AWT-EventQueue-0
    PID: 18 | Alive: true | State: WAITING | Daemon: false | Priority:6
    WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6ae56735
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6ae56735
    at java.util.concurrent.locks.LockSupport.park(Unknown Source)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
    at java.awt.EventQueue.getNextEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

Current Thread: AWT-Shutdown
    PID: 15 | Alive: true | State: WAITING | Daemon: false | Priority:5
    WAITING on java.lang.Object@37dedfcf
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.Object@37dedfcf
    at java.lang.Object.wait(Object.java:503)
    at sun.awt.AWTAutoShutdown.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Current Thread: AWT-Windows
    PID: 16 | Alive: true | State: RUNNABLE | Daemon: true | Priority:6
    RUNNABLE (in native)
    at sun.awt.windows.WToolkit.eventLoop(Native Method)
    at sun.awt.windows.WToolkit.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Current Thread: Abandoned connection cleanup thread
    PID: 37 | Alive: true | State: WAITING | Daemon: true | Priority:5
    WAITING on java.lang.ref.ReferenceQueue$Lock@617b1e68
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.ref.ReferenceQueue$Lock@617b1e68
    at java.lang.ref.ReferenceQueue.remove(Unknown Source)
    at java.lang.ref.ReferenceQueue.remove(Unknown Source)
    at com.mysql.jdbc.NonRegisteringDriver$1.run(NonRegisteringDriver.java:93)

Current Thread: Attach Listener
    PID: 6 | Alive: true | State: RUNNABLE | Daemon: true | Priority:5
    RUNNABLE

...Skipped many tick reports...

03-11 02:09:22 [INFO] [TickThreading] Attempting to save
03-11 02:09:23 [INFO] [TickThreading] Saved, now attempting to stop the server and disconnect players cleanly
03-11 02:09:24 [SEVERE] [TickThreading] Error stopping server
java.lang.NullPointerException
    at portalgun.common.core.TickHandlerServer.saveData(TickHandlerServer.java:730)
    at portalgun.common.PortalGun.serverStopping(PortalGun.java:210)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.serverStopping(Loader.java:740)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:325)
    at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:189)
    at me.nallar.tickthreading.minecraft.DeadLockDetector$2.run(DeadLockDetector.java:60)
    at java.lang.Thread.run(Unknown Source)
03-11 02:09:24 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at net.minecraft.server.MinecraftServer.n(MinecraftServer.java:91)
    at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:194)
    at me.nallar.tickthreading.minecraft.DeadLockDetector$2.run(DeadLockDetector.java:60)
    at java.lang.Thread.run(Unknown Source)</code>

**Comment by LunNova** [comment]
"Skipped"

...

Don't do that. Full Iog please.

**Comment by aquagene** [comment]
Full log got cut off here, sorry about that, only reason I did that. Here's a pastebin link to the entire log. http://pastebin.com/s09md621

**Comment by clienthax** [comment]
@nallar i also got a error about the lua stuff, but i lost the log, seems same issue but that was without tt on a ftb server

**Comment by LunNova** [comment]
Should be fixed in latest, also deadlock detector reports will be smaller after 8b6661cd900a91f.

**Comment by LunNova** [comment]
Actually fixed via 95821b568315daaa31c.
