### ISSUE TITLE
Wrong chunk with wierd coords (0,0, -1, -1) =/ ?

### ISSUE THREAD

**Issue by clienthax** [MinimallyCorrect/TickThreading#196]
03-11 04:56:39 [WARNING] [ForgeModLoader] Entity qd['Enderman'/1916877, l='world_the_end', x=-0.25, y=65.00, z=-4.54] added to the wrong chunk - expected x0 z0, got x-1 z-1
java.lang.Throwable
        at zz.a_lock(Chunk.java:161)
        at zz.a(Chunk.java)
        at aam.loadEntities(AnvilChunkLoader.java:493)
        at aam.a(AnvilChunkLoader.java:77)
        at im.f(ThreadedChunkProvider.java:353)
        at im.getChunkAt(ThreadedChunkProvider.java:268)
        at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:505)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
"Fixed" via 74725e4ba7fb69d3bd7d0b1.
