### ISSUE TITLE
BuildCraft NullPointerException

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#2]
Got this error in the console a few times, not sure what's triggering it besides what the code obviously states.
# 

2013-01-02 07:53:17 [SEVERE] [TickThreading] Exception during tile entity tick
2013-01-02 07:53:17 [SEVERE] [TickThreading] Tick region: rX: -778, rZ: -443, ha
shCode: -29033226:
java.lang.NullPointerException
        at buildcraft.transport.TileGenericPipe.blockCreated(TileGenericPipe.jav
a:440)
        at buildcraft.transport.TileGenericPipe.initialize(TileGenericPipe.java:
283)
        at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:160)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doT
ick(TileEntityTickRegion.java:61)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegio
n.java:79)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.j
ava:58)
        at me.nallar.tickthreading.minecraft.ThreadManager$WorkThread.run(Thread
# Manager.java:115)

**Comment by LunNova** [comment]
Should be fixed in build 194. Close this issue if that fixes it.

Kinda' surprised anyone's using TickThreading just now - not really ready for release, I still need to finish up automated error reporting and do more testing.

I'll look into the IC2 explosions issue later.

**Comment by Puremin0rez** [comment]
I literally only found out about this from your reddit post you linked someone, I really quite like it and it's very stable so far.... zero issues besides those reported :)

Definitely worth your time and I appreciate it.

I'll test the 2 issues later today.

**Comment by Puremin0rez** [comment]
Appears to be fixed, IC2 bug is fixed too.

Appreciate the work!

**Comment by Puremin0rez** [comment]
@nallar 

Seems like this has spawned another new issue:

2013-01-02 23:21:30 [SEVERE] [TickThreading] Exception during tile entity tick
2013-01-02 23:21:30 [SEVERE] [TickThreading] Tick region: rX: 83, rZ: 173, hashC
ode: 11337811:
java.lang.NullPointerException
        at buildcraft.transport.TileGenericPipe.initialize(TileGenericPipe.java)

```
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:160)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doT
```

ick(TileEntityTickRegion.java:61)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegio
n.java:79)
        at me.nallar.tickthreading.minecraft.ThreadManager$3.run(ThreadManager.j
ava:87)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.j
ava:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(
ThreadManager.java:138)

**Comment by LunNova** [comment]
It should be fixed now.

**Comment by Puremin0rez** [comment]
Okay, I'll try it out in a bit.

Thanks for the fast fixes :+1:

**Comment by Puremin0rez** [comment]
This particular null-pointer is fixed - will report if another one wiggles by

Resolved :+1:
