### ISSUE TITLE
#1111 Deadlock on Launch

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#202]
Still too long for github :( Pastebin link: http://pastebin.com/asE4Rt2Z

**Comment by LunNova** [comment]
Should be fixed in c796e3589320afb9, although I haven't had time to test.

**Comment by aquagene** [comment]
Server no longer crashes on launch, but now I constantly get this error only when I have tickthreading installed. Thanks again for all the hard work, love your mod:
<code>03-12 17:58:09 [WARNING] [ForgeModLoader] Exception attempting to save a chunk
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtension.saveChunkData(WorldExtension.java:62)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:45)
    at net.minecraftforge.event.ASMEventHandler_185_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at aam.a(AnvilChunkLoader.java:130)
    at im.b(ThreadedChunkProvider.java:408)
    at im.a(ThreadedChunkProvider.java:444)
    at in.a(WorldServer.java:844)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:373)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:259)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(SourceFile:849)</code>

**Comment by WebMaka** [comment]
I got the same. I tried running an unpatched copy of Xycraft and simply replaced net.minecraft.server.MinecraftServer.\* with nallar.tickthreading equivalents.

What's with the Chicken mods and being all uncooperative? <lol>

**Comment by LunNova** [comment]
Should be working after 56c761ad3db4d2a228f. Closing this issue as the deadlock is fixed, open another if the `Exception attempting to save a chunk... codechicken.xycraftcopy.core` issue isn't fixed after that commit.
