### ISSUE TITLE
#1116 Players disconnecting instantly on log in. Exception

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#204]
03-12 19:39:32 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtension.unloadChunk(WorldExtension.java:52)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:70)
    at net.minecraftforge.event.ASMEventHandler_187_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zz.d_lock(Chunk.java:137)
    at zz.d(Chunk.java)
    at im.tick(ThreadedChunkProvider.java:134)
    at im.b(ThreadedChunkProvider.java:104)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:276)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:442)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by ExecR** [comment]
Similar Issue:

java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtension.watchChunk(WorldExtension.java:72)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkWatch(WorldExtensionManager.java:101)
    at net.minecraftforge.event.ASMEventHandler_171_WorldExtensionEventHandler_onChunkWatch_Watch.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at iq.j_(EntityPlayerMP.java:348)
    at yc.a(World.java:2745)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at yc.h(World.java:2536)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:956)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
    at fy.run(ThreadMinecraftServer.java:16)

Crash log: http://www.jawshee.net/paste/index.php/view/e3ab61af

**Comment by LunNova** [comment]
This specific xycraft-related issue is fixed.
