### ISSUE TITLE
#1118 Crash on startup

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#205]
03-12 20:30:56 [INFO] [Minecraft] Preparing level "world"
03-12 20:30:56 [FINE] [fml.ItemTracker] The difference set is equal
03-12 20:30:56 [INFO] [ForgeModLoader] Loading dimension 0 (world) (ho@3c4b67b1)
03-12 20:30:56 [INFO] [ForgeModLoader] Loading dimension 7 (world) (ho@3c4b67b1)
03-12 20:30:56 [FINE] [TickThreading] Threading initialised for world Twilight Forest/7
03-12 20:30:56 [INFO] [ForgeModLoader] [TwilightForest] Loaded feature cache with 2376 chunks present.
03-12 20:30:56 [INFO] [ForgeModLoader] Loading dimension 1 (world) (ho@3c4b67b1)
03-12 20:30:56 [FINE] [TickThreading] Threading initialised for world The End/1
03-12 20:30:56 [INFO] [ForgeModLoader] Loading dimension -1 (world) (ho@3c4b67b1)
03-12 20:30:56 [INFO] [ForgeModLoader] [Thaumcraft] Loaded 87 aura nodes for world -1
03-12 20:30:56 [FINE] [TickThreading] Threading initialised for world Nether/-1
03-12 20:30:56 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNullPointerException
java.lang.NullPointerException
    at im.getChunkAt(ThreadedChunkProvider.java:283)
    at im.d(ThreadedChunkProvider.java:247)
    at yc.e(World.java:524)
    at yc.q(World.java:146)
    at portalgun.common.core.ChunkLoadHandler.ticketsLoaded(ChunkLoadHandler.java:34)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:514)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:279)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:139)
    at fy.run(SourceFile:849)

**Comment by 4poc** [comment]
same problem here, using the feed the beast mindcrack pack
