### ISSUE TITLE
#1119 + 1120 Players disconnected after ~5 minutes, then disconnected instantly on reconnect.

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#206]
Sorry for so many tickets, your work is greatly appreciated.
<code>03-12 21:17:55 [WARNING] [ForgeModLoader] Exception attempting to save a chunk
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtension.saveChunkData(WorldExtension.java:62)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:45)
    at net.minecraftforge.event.ASMEventHandler_187_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at aam.a(AnvilChunkLoader.java:130)
    at im.b(ThreadedChunkProvider.java:420)
    at im.a(ThreadedChunkProvider.java:463)
    at in.a(WorldServer.java:844)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:373)
    at net.minecraft.server.MinecraftServer.k(MinecraftServer.java:406)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:216)
    at fy.run(SourceFile:849)</code>

**Comment by HaoSs07** [comment]
+1 for this. and the one "Players disconnecting instantly on log in ". dont know if its from TT as there is no TT in the log. so i made a report on xycraft bitbucket

**Comment by Loonacy** [comment]
I moved from build 1110 to 1119 and the disconnections started immediately after that.
Using FTB Ultimate Pack + OpenCCSensors

03-13 07:22:26 [FINEST] [ForgeModLoader] Received valid FML login packet from /<IP ADDRESS>:51814
03-13 07:22:27 [INFO] [ForgeModLoader] User Bayamo connecting with mods [OCS, MFReloaded|CompatSufficientBiomes, BiblioCraft, RedPowerWiring, TwilightForest, OmniTools, BuildCraft|Transport, ChargePads, RedPowerCompat, WR-CBE|Core, MFReloaded|CompatIC2, ObsidiPlates, RedPowerLogic, ThermalExpansion|Energy, drceph.petrogen, Thaumcraft, Forestry, WR-CBE|RedPower, EnderStorage, XyCraftWorld, GraviGun, AdvancedMachines, BinnieCore, MFReloaded|CompatPams, mmmPowersuits, IronChest, MFReloaded|CompatRP2, BuildCraft|Energy, Railcraft, GregTech_Addon, EE3, ImmibisCore, MiscPeripherals, PortalGun, ChickenChunks, ModularForceFieldSystem, factorization, RedPowerLighting, AppliedEnergistics, RedPowerBase, MFReloaded|CompatExtraBiomes, MFReloaded, MFReloaded|CompatXycraft, XyCraft, ThermalExpansion, NetherOres, BuildCraft|Silicon, ThermalExpansion|Transport, GraviSuite, XyCraftMachines, BuildCraft|Core, IC2NuclearControl, ThermalExpansion|Factory, MFReloaded|CompatForestry, IC2, SecretRoomsMod, ExtrabiomesXL, ExtraBees, StevesCarts, Mystcraft, WR-CBE|Addons, ComputerCraft, AdvancedSolarPanel, BuildCraft|Factory, RedPowerMachine, XReliquary, SoulShards, RedPowerCore, MFReloaded|CompatThaumcraft, CCTurtle, Tubestuff, RedPowerControl, MFReloaded|CompatTwilightForest, MFReloaded|CompatSoulShards, RedPowerWorld, BuildCraft|Builders, PowerConverters]
03-13 07:22:27 [INFO] [Minecraft] Bayamo[/<IP ADDRESS>:51814] logged in with entity id 22518 at (-340.6336914465356, 56.0, 268.9571783934571)
03-13 07:22:27 [INFO] [STDOUT] Loading Player: Bayamo
03-13 07:22:27 [INFO] [STDOUT] Sending serverside check to: Bayamo
03-13 07:22:28 [INFO] [GraviGun] [1.4.7v2] Recieved client info from Bayamo
03-13 07:22:28 [INFO] [PortalGun] [1.4.7v4] Recieved client info from Bayamo
03-13 07:22:34 [SEVERE] [ForgeModLoader] Failed to handle packet from Bayamo
java.lang.NullPointerException
        at codechicken.xycraftcopy.core.world.WorldExtension.watchChunk(WorldExtension.java:72)
        at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkWatch(WorldExtensionManager.java:101)
        at net.minecraftforge.event.ASMEventHandler_197_WorldExtensionEventHandler_onChunkWatch_Watch.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at eb.sendChunks(SourceFile:147)
        at eb.a(SourceFile:92)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
03-13 07:22:34 [INFO] [Minecraft] Bayamo lost connection: disconnect.genericReason
03-13 07:22:34 [INFO] [STDOUT] Unloading Player: Bayamo

**Comment by HaoSs07** [comment]
it works with no TT installed. so probably its an error at TT end ? i'm sure nallar will fix it :)

**Comment by aquagene** [comment]
Was looking into this more, tickthreading modifies Chickencore, but Xycraft also does, quite extensively. Xycraft's modifications may be overriding Nallar's work.

**Comment by xfloh22** [comment]
same error here, but sometimes it doesnt happen, its very random. i hate xycrap

**Comment by LunNova** [comment]
This should be fixed in latest, had one confirmation so far in IRC. Closing, reply here if it happens again and I'll re-open it.
