### ISSUE TITLE
EndOfStream disconnects with new chunkprovider

### ISSUE THREAD

**Issue by kenneaal** [MinimallyCorrect/TickThreading#211]
Players experience disconnects with EndOfStream messages when moving around. Most often, these disconnects happen when entering areas of ungenerated land, but sometimes also just from moving around in already-generated land. The higher your speed, the more often this error seems to crop up.

Error messages can vary, but most often are this:
03-15 22:13:09 [SEVERE] [ForgeModLoader] Failed to handle packet from ****\* java.lang.NullPointerException
        at codechicken.xycraftcopy.core.world.WorldExtension.watchChunk(WorldExtension.java:72)
        at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkWatch(WorldExtensionManager.java:101)
        at net.minecraftforge.event.ASMEventHandler_187_WorldExtensionEventHandler_onChunkWatch_Watch.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at eb.sendChunks(Packet10Flying.java:147)
        at eb.a(Packet10Flying.java:78)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)

But sometimes turn up like this:

03-15 22:16:25 [SEVERE] [ForgeModLoader] Failed to handle packet from slozon
java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
        at java.util.LinkedList$ListItr.next(LinkedList.java:886)
        at eb.sendChunks(Packet10Flying.java:120)
        at eb.a(Packet10Flying.java:78)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)

**Comment by HaoSs07** [comment]
there are a lot of problems with chicken chunks and xycraft on a lot of server ...without TT. so we have to wait for xycraft fix

**Comment by kenneaal** [comment]
Does not fix. Still causes EoS.

**Comment by LunNova** [comment]
github auto-closed this as it had "fix #211" in the name. Only just realised this, so not reopening as it actually is fixed now.
