### ISSUE TITLE
[Build 1124] [FTB Ultimate latest!] New chunk / network error - client disconnect

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#215]
pahced and ran with [jdk 7 u17]
made a new server with this on it ftb untimate and pached it then hoped on the server and when ever you moved to a new chunk it disconnect the client and you had to reconnect alot 
shoulden't be to hard to recreate this error a very annoying one indeed

03-16 17:48:35 [SEVERE] [ForgeModLoader] Failed to handle packet from anonomis
java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(LinkedList.java:891)
        at eb.sendChunks(Packet10Flying.java:120)
        at eb.a(Packet10Flying.java:78)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)

**Comment by LunNova** [comment]
Fixed via be2f7804ca9a7165e85d.
