### ISSUE TITLE
ic2 patch error

### ISSUE THREAD

**Issue by npdev453** [MinimallyCorrect/TickThreading#217]
03-17 13:06:30 [FINE] [TickThreading] Patching ic2.core.EnergyNet with replaceInitializer(field:worldToEnergyNetMap,class:java.uti
l.HashMap)
03-17 13:06:30 [SEVERE] [TickThreading] Error patching ic2.core.EnergyNet with replaceInitializer
javassist.NotFoundException: field: worldToEnergyNetMap in ic2.core.EnergyNet
        at javassist.CtClassType.checkGetField(CtClassType.java:920)
        at javassist.CtClassType.getDeclaredField(CtClassType.java:969)
        at javassist.CtClassType.getDeclaredField(CtClassType.java:964)
        at me.nallar.tickthreading.patcher.Patches.replaceInitializer(Patches.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:311)
        at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:293)
        at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:218)
        at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:107)
        at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:32)
03-17 13:06:30 [FINE] [TickThreading] Patching ic2.core.EnergyNet with replaceInitializer(field:energySourceToEnergyPathMap,class:
java.util.HashMap)

**Comment by npdev453** [comment]
i use custom ported version from here http://www.mcportcentral.co.za/index.php?topic=4657.0

**Comment by LunNova** [comment]
That's not actually an error - the patch failed as IC2 changed recently, and it's no longer needed. Removed old patches in b51e579305f5037.
