### ISSUE TITLE
Mo'Creatures spaming after patch

### ISSUE THREAD

**Issue by npdev453** [MinimallyCorrect/TickThreading#218]
03-17 13:14:21 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
        at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
        at fy.run(ThreadMinecraftServer.java:16)
03-17 13:14:21 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
        at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
        at fy.run(ThreadMinecraftServer.java:16)
03-17 13:14:21 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
        at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
        at fy.run(ThreadMinecraftServer.java:16)
03-17 13:14:21 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
        at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
        at fy.run(ThreadMinecraftServer.java:16)
03-17 13:14:21 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:78)
        at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:286)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
        at fy.run(ThreadMinecraftServer.java:16)
03-17 13:14:21 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException

**Comment by npdev453** [comment]
hm mayber beacuse i use fix for mo'cretures from here  http://www.mcportcentral.co.za/index.php?topic=4657.0

**Comment by npdev453** [comment]
ah duplicate https://github.com/nallar/TickThreading/issues/193
