### ISSUE TITLE
#1147 Little console spam

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#221]
03-18 14:46:51 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z183,62,544
java.lang.IllegalStateException: Entity is already tracked!
at ii.a_lock(EntityTracker.java:196)
at ii.a(EntityTracker.java)
at ii.a_lock(EntityTracker.java:150)
at ii.a(EntityTracker.java)
at ij.a(SourceFile:24)
at yc.a(World.java:1554)
at in.a(WorldServer.java:865)
at yc.a(World.java:247)
at zz.threadUnsafeChunkLoad(Chunk.java:160)
at im.getChunkAt(ThreadedChunkProvider.java:393)
at im.d(ThreadedChunkProvider.java:279)
at yc.e(World.java:524)
at yc.a(World.java:96)
at and.b(BlockVine.java:279)
at in.run(WorldServer.java:473)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-18 14:46:51 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z183,63,544
java.lang.IllegalStateException: Entity is already tracked!
at ii.a_lock(EntityTracker.java:196)
at ii.a(EntityTracker.java)
at ii.a_lock(EntityTracker.java:150)
at ii.a(EntityTracker.java)
at ij.a(SourceFile:24)
at yc.a(World.java:1554)
at in.a(WorldServer.java:865)
at yc.a(World.java:247)
at zz.threadUnsafeChunkLoad(Chunk.java:160)
at im.getChunkAt(ThreadedChunkProvider.java:393)
at im.d(ThreadedChunkProvider.java:279)
at yc.e(World.java:524)
at yc.a(World.java:96)
at and.b(BlockVine.java:279)
at in.run(WorldServer.java:473)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-18 14:46:51 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z183,64,544
java.lang.IllegalStateException: Entity is already tracked!
at ii.a_lock(EntityTracker.java:196)
at ii.a(EntityTracker.java)
at ii.a_lock(EntityTracker.java:150)
at ii.a(EntityTracker.java)
at ij.a(SourceFile:24)
at yc.a(World.java:1554)
at in.a(WorldServer.java:865)
at yc.a(World.java:247)
at zz.threadUnsafeChunkLoad(Chunk.java:160)
at im.getChunkAt(ThreadedChunkProvider.java:393)
at im.d(ThreadedChunkProvider.java:279)
at yc.e(World.java:524)
at yc.a(World.java:96)
at and.b(BlockVine.java:279)
at in.run(WorldServer.java:473)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-18 14:46:51 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z183,62,545
java.lang.IllegalStateException: Entity is already tracked!
at ii.a_lock(EntityTracker.java:196)
at ii.a(EntityTracker.java)
at ii.a_lock(EntityTracker.java:150)
at ii.a(EntityTracker.java)
at ij.a(SourceFile:24)
at yc.a(World.java:1554)
at in.a(WorldServer.java:865)
at yc.a(World.java:247)
at zz.threadUnsafeChunkLoad(Chunk.java:160)
at im.getChunkAt(ThreadedChunkProvider.java:393)
at im.d(ThreadedChunkProvider.java:279)
at yc.e(World.java:524)
at yc.a(World.java:96)
at and.b(BlockVine.java:279)
at in.run(WorldServer.java:473)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-18 14:46:51 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z183,63,545
java.lang.IllegalStateException: Entity is already tracked!
at ii.a_lock(EntityTracker.java:196)
at ii.a(EntityTracker.java)
at ii.a_lock(EntityTracker.java:150)
at ii.a(EntityTracker.java)
at ij.a(SourceFile:24)
at yc.a(World.java:1554)
at in.a(WorldServer.java:865)
at yc.a(World.java:247)
at zz.threadUnsafeChunkLoad(Chunk.java:160)
at im.getChunkAt(ThreadedChunkProvider.java:393)
at im.d(ThreadedChunkProvider.java:279)
at yc.e(World.java:524)
at yc.a(World.java:96)
at and.b(BlockVine.java:279)
at in.run(WorldServer.java:473)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by HaoSs07** [comment]
using 1154:

03-19 23:28:27 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:28 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:28 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:29 [INFO] [Minecraft] [@: Saved the world]
03-19 23:28:29 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:30 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:30 [WARNING] [TickThreading] Failed to spawn entity yz@434eb0ec
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at ii.a_lock(EntityTracker.java:203)
at ii.a(EntityTracker.java)
at ii.a_lock(EntityTracker.java:146)
at ii.a(EntityTracker.java)
at ij.a(SourceFile:24)
at yc.a(World.java:1554)
at in.a(WorldServer.java:865)
at yc.d(World.java:1542)
at yp.spawnMobsQuickly(SpawnerAnimals.java:162)
at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:186)
at yp.a(SpawnerAnimals.java)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:273)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:442)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:30 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:31 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:31 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-19 23:28:31 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
at is.d(EntityTrackerEntry.java:442)
at is.b(EntityTrackerEntry.java:363)
at is.b(EntityTrackerEntry.java:449)
at is.a(EntityTrackerEntry.java:131)
at ii.a_lock(EntityTracker.java:238)
at ii.a(EntityTracker.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:449)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
