### ISSUE TITLE
#1167 Forgemodloader errors (do not occur without TT)

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#222]
<code>03-20 18:53:00 [SEVERE] [ForgeModLoader] A TileEntity type any@35a95b85 x,y,z: 318, 64, 2483 has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class any is missing a mapping! This is a bug!
    at any.b(TileEntity.java:107)
    at aam.a(AnvilChunkLoader.java:240)
    at aam.a(AnvilChunkLoader.java:129)
    at im.b(ThreadedChunkProvider.java:509)
    at im.a(ThreadedChunkProvider.java:559)
    at in.a(WorldServer.java:844)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:373)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:259)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(SourceFile:849)</code>
<code>03-20 18:54:35 [SEVERE] [ForgeModLoader] A TileEntity type any@35a95b85 x,y,z: 318, 64, 2483 has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class any is missing a mapping! This is a bug!
    at any.b(TileEntity.java:107)
    at aam.a(AnvilChunkLoader.java:240)
    at aam.a(AnvilChunkLoader.java:129)
    at im.b(ThreadedChunkProvider.java:509)
    at im.a(ThreadedChunkProvider.java:559)
    at in.a(WorldServer.java:844)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:373)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:259)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(SourceFile:849)</code>
<code>03-20 18:55:13 [SEVERE] [ForgeModLoader] A TileEntity type any@35a95b85 x,y,z: 318, 64, 2483 has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class any is missing a mapping! This is a bug!
    at any.b(TileEntity.java:107)
    at aam.a(AnvilChunkLoader.java:240)
    at aam.a(AnvilChunkLoader.java:129)
    at im.b(ThreadedChunkProvider.java:509)
    at im.finalizeUnload(ThreadedChunkProvider.java:224)
    at im.getChunkAt(ThreadedChunkProvider.java:356)
    at im.getChunkAt(ThreadedChunkProvider.java:311)
    at im.d(ThreadedChunkProvider.java:297)
    at yc.e(World.java:524)
    at yc.q(World.java:212)
    at thaumcraft.common.Utils.getMarkedContainerAdjacentToEntity(Utils.java:495)
    at thaumcraft.common.entities.ai.AITakeSupplyInv.a(AITakeSupplyInv.java:52)
    at nd.a(SourceFile:67)
    at thaumcraft.common.entities.golems.EntityGolemBase.bl(EntityGolemBase.java:118)
    at md.c(EntityLiving.java:208)
    at thaumcraft.common.entities.golems.EntityGolemBase.c(EntityGolemBase.java:140)
    at md.j_(EntityLiving.java:843)
    at yc.a(World.java:251)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2255)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)</code>

**Comment by LunNova** [comment]
Update to latest, break and replace the block. If it continues to happen,
paste the /dump for that coord.

**Comment by aquagene** [comment]
I unfortunately already removed the block with world edit, I'll let you know if it happens again with the newest version though.

**Comment by LunNova** [comment]
Closing this, as it hasn't happened again and it was probably the issue fixed in b4f64b341e9f8bbd685b40b.
