### ISSUE TITLE
#1168 Applied Energistics NPE

### ISSUE THREAD

**Issue by Loonacy** [MinimallyCorrect/TickThreading#223]
I'm getting this error sometimes when accessing an ME chest.  There's also some slight blinking on the chest's inventory, like it's reloading it every few seconds.

It seems to only happen with ME chests, not when you access the inventory through a terminal.  No items are missing, and the inventory is still accessible, so this is probably not a high priority bug.

03-20 20:04:13 [SEVERE] [TickThreading] Exception during entity tick at rX: -19, rZ: 79, hashCode: 5177325:
java.lang.NullPointerException
        at bq.b(NBTTagCompound.java:415)
        at ur.l(ItemStack.java:383)
        at rq.b(Container.java:110)
        at iq.j_(iq.java:22)
        at yc.a(World.java:251)
        at in.a(WorldServer.java:844)
        at yc.g(World.java:2707)
        at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Fixed via 99996982a4bac3.
