### ISSUE TITLE
#1173 Does not enable after patching

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#224]
Edit: Sorry miswrote the build number, my mistake, 1173 does not enable after patching, while #1169 works just fine.

03-21 16:15:46 [WARNING] [TickThreading] Patching required for D:\Direwolf20_Server\ftbserver.jar because it is out of date.
Expected 591302456, got -1006245832
03-21 16:15:57 [SEVERE] [TickThreading] TickThreading is disabled, because your server has not been patched or the patches are out of date
To patch your server, simply run the PATCHME.bat/sh file in your server directory
03-21 16:16:04 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at yc.h_net_minecraft_world_World_updateEntities_p0(World.java:681)
    at yc.h(World.java)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:444)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:340)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:249)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Can you try #1171 or newer? Changed the patch hashcode in it again.

**Comment by aquagene** [comment]
My mistake I meant #1173. I've updated the original post to say so. #1169 works fine, it's my current fallback, stability wise.

**Comment by LunNova** [comment]
Try 1174, and if it's still broken pastebin full console and patcher logs.

**Comment by aquagene** [comment]
#1175 instantly crashes the server on launch. This is with both trying to upgrade from #1169 and with a fresh TT install. It never gets as far as to generate the new PATCHME files.
<code>2013-03-21 18:05:20 [INFO] Starting minecraft server version 1.4.7
2013-03-21 18:05:25 [SEVERE] Encountered an unexpected exception Error
java.lang.Error: Missing patches.
    at me.nallar.tickthreading.minecraft.TickThreading.<init>(TickThreading.java:89)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:459)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:494)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)</code>

**Comment by LunNova** [comment]
Fixed the order, it'll write the patch files before stopping now. Oops.

Try latest, and if it still doesn't work I do actually need the full logs, not a trimmed log like the last one. (unless you didn't trim it? In that case, something broke badly... :s)

**Comment by aquagene** [comment]
Seems to work great in the #1178. The new checks are very elegant. The second log I pasted above your reply was the full log, it literally just loaded and crashed instantly.
