### ISSUE TITLE
Xycraft Console Spam - Attempted to place a tile entity (soaryn.xycraft.machines.block.multiblock.TileMultiCopy@2e2b6318)

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#225]
Running MCPC+ and the Direwolf20 modpack with the latest TickThreading (#1182). Once a few people start joining the server, the console spams this constantly making the log get to be a few GB.

2013-03-22 18:26:03 [INFO] Attempted to place a tile entity (soaryn.xycraft.machines.block.multiblock.TileMultiCopy@2e2b6318) at 4764,53,-6279 (AIR) where there was no entity tile!
2013-03-22 18:26:03 [INFO] Chunk coordinates: 4752,-6288
2013-03-22 18:26:03 [SEVERE] java.lang.Exception
2013-03-22 18:26:03 [SEVERE]    at zz.a(Chunk.java:1086)
2013-03-22 18:26:03 [SEVERE]    at zz.a(Chunk.java:1050)
2013-03-22 18:26:03 [SEVERE]    at aam.loadEntities(AnvilChunkLoader.java:509)
2013-03-22 18:26:03 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44)
2013-03-22 18:26:03 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:10)
2013-03-22 18:26:03 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:179)
2013-03-22 18:26:03 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:287)
2013-03-22 18:26:03 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:26)
2013-03-22 18:26:03 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:907)
2013-03-22 18:26:03 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-03-22 18:26:03 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
2013-03-22 18:26:03 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
2013-03-22 18:26:03 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
This is an MCPC+ bug, see https://github.com/MinecraftPortCentral/MCPC-Plus/issues/603.
