### ISSUE TITLE
GriefPrevention Console Spam

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#226]
So it's not just xycraft, but GriefPrevention is spamming the console as well over and over again with the same error. This only starts after a few people have joined. Running the latest TickThreading (#1182) and MCPC+.

2013-03-22 22:55:32 [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at aky.b(BlockFlowing.java:213)
    at in.a(WorldServer.java:236)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:287)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:443)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
Caused by: java.lang.NullPointerException
2013-03-22 22:55:32 [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at aky.b(BlockFlowing.java:213)
    at in.a(WorldServer.java:236)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:287)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:443)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
Caused by: java.lang.NullPointerException

**Comment by LunNova** [comment]
Can you paste the first occurrence of this in the logs? This has been shortened automatically by the JVM to "Caused by: java.lang.NullPointerException", without giving the stack trace, as it happened so many times.

**Comment by alexbegt** [comment]
We will do so.

**Comment by joey19982** [comment]
Oops, sorry. Here is the full error:

2013-03-23 12:02:03 [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at aky.b(BlockFlowing.java:213)
    at in.a(WorldServer.java:236)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:287)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:443)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:341)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:168)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getUID(CraftWorld.java:498)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.equals(CraftWorld.java:1169)
    at java.util.ArrayList.indexOf(ArrayList.java:269)
    at java.util.ArrayList.contains(ArrayList.java:252)
    at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
    ... 14 more

**Comment by LunNova** [comment]
Disable world unloading in TT's config, GriefPrevention is leaking world objects - it left an unloaded world in an ArrayList.

Report that the ArrayList<World> used in me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo is not having unloaded worlds removed from it to the mod dev.

**Comment by joey19982** [comment]
Will do, thanks nallar!
