### ISSUE TITLE
#1184 Exception getting block ID spam.

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#227]
03-23 20:33:25 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-260,52,1008
java.lang.NullPointerException
at yc.a(World.java:99)
at com.eloraam.redpower.world.WorldGenMarble.searchBlock(WorldGenMarble.java:32)
at com.eloraam.redpower.world.WorldGenMarble.a(WorldGenMarble.java:65)
at com.eloraam.redpower.world.WorldGenHandler.generate(WorldGenHandler.java:117)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1261)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

03-23 20:33:46 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-289,85,957
java.lang.NullPointerException
at yc.a(World.java:99)
at yc.c(World.java:433)
at forestry.apiculture.worldgen.WorldGenHiveForest.a(WorldGenHiveForest.java:25)
at forestry.plugins.PluginForestryApiculture.generateSurface(PluginForestryApiculture.java:607)
at forestry.core.WorldGenerator.generate(WorldGenerator.java:70)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1251)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
03-23 20:33:46 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-289,86,957
java.lang.NullPointerException
at yc.a(World.java:99)
at forestry.apiculture.worldgen.WorldGenHiveForest.a(WorldGenHiveForest.java:28)
at forestry.plugins.PluginForestryApiculture.generateSurface(PluginForestryApiculture.java:607)
at forestry.core.WorldGenerator.generate(WorldGenerator.java:70)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1251)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
03-23 20:33:47 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-294,46,964
java.lang.NullPointerException
at yc.a(World.java:99)
at yc.c(World.java:433)
at forestry.apiculture.worldgen.WorldGenHiveForest.a(WorldGenHiveForest.java:25)
at forestry.plugins.PluginForestryApiculture.generateSurface(PluginForestryApiculture.java:607)
at forestry.core.WorldGenerator.generate(WorldGenerator.java:70)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1261)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
03-23 20:33:47 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-294,47,964
java.lang.NullPointerException
at yc.a(World.java:99)
at forestry.apiculture.worldgen.WorldGenHiveForest.a(WorldGenHiveForest.java:28)
at forestry.plugins.PluginForestryApiculture.generateSurface(PluginForestryApiculture.java:607)
at forestry.core.WorldGenerator.generate(WorldGenerator.java:70)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1261)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
03-23 20:33:47 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-294,92,984
java.lang.NullPointerException
at yc.a(World.java:99)
at yc.c(World.java:433)
at forestry.apiculture.worldgen.WorldGenHiveForest.a(WorldGenHiveForest.java:25)
at forestry.plugins.PluginForestryApiculture.generateSurface(PluginForestryApiculture.java:607)
at forestry.core.WorldGenerator.generate(WorldGenerator.java:70)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1261)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
03-23 20:33:47 [SEVERE] [TickThreading] Exception getting block ID in Overworld/0 at x,y,z-294,93,984
java.lang.NullPointerException
at yc.a(World.java:99)
at forestry.apiculture.worldgen.WorldGenHiveForest.a(WorldGenHiveForest.java:28)
at forestry.plugins.PluginForestryApiculture.generateSurface(PluginForestryApiculture.java:607)
at forestry.core.WorldGenerator.generate(WorldGenerator.java:70)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:91)
at im.a(ThreadedChunkProvider.java:545)
at zz.a(Chunk.java:1261)
at im.getChunkAt(ThreadedChunkProvider.java:460)
at im.getChunkAt(ThreadedChunkProvider.java:313)
at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:658)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by HaoSs07** [comment]
that was fast :) thx. locks good now
