### ISSUE TITLE
#1206 rare deadlock ( sometime recovers ) an old friend ( codechicken.xycraftcopy.core )

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#239]
03-25 20:50:07 [INFO] [TickThreading] iq['eXpLoSiOn16'/10283, l='world', x=378.30, y=41.00, z=305.63] from Nether/-1 to Overworld/0
03-25 20:51:28 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:440)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-25 20:51:28 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:440)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-25 20:51:28 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:440)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-25 20:51:29 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:440)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-25 20:53:22 [INFO] [TickThreading] Server shutting down - requested at

**Comment by HaoSs07** [comment]
03-25 21:05:47 [INFO] [TickThreading] iq['eXpLoSiOn16'/1486, l='world', x=3353.74, y=64.00, z=3290.44] from Overworld/0 to Nether/-1
03-25 21:07:43 [SEVERE] [TickThreading] Exception ticking world The End/1
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:440)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
03-25 21:07:43 [INFO] [TickThreading] iq['TheBigU'/35764, l='world', x=292.13, y=31.92, z=1011.62] from Overworld/0 to The End/1

This one recovered :)

**Comment by clienthax** [comment]
xycraft has known issues with EVERYTHING
recommend disabling for now

**Comment by LunNova** [comment]
A workaround for this specific issue may be to disable world unloading.
