### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by ray73864** [MinimallyCorrect/TickThreading#244]
Not sure if 8be6109 resolves this on or not, it is basically the same error, but with a whole lot of extra stuff:

03-27 05:44:31 [SEVERE] [TickThreading] Exception ticking entity qk['Zombie Pigman'/677065, l='world', x=185.85, y=35.95, z=-982.61] in rX: 11, rZ: -61, hashCode: -3997685:
java.util.NoSuchElementException
        at java.util.LinkedList.removeLast(LinkedList.java:281)
        at com.eloraam.redpower.core.TubeBuffer.pop(TubeBuffer.java:61)
        at com.eloraam.redpower.machine.TileTranspose.drainBuffer(TileTranspose.java:251)
        at com.eloraam.redpower.machine.TileTranspose.suckEntities(TileTranspose.java:215)
        at com.eloraam.redpower.machine.TileTranspose.onEntityCollidedWithBlock(TileTranspose.java:265)
        at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:169)
        at lq.D(Entity.java:1011)
        at lq.d(Entity.java:308)
        at md.e(EntityLiving.java:124)
        at md.c(EntityLiving.java:242)
        at qj.c(SourceFile:26)
        at qr.c(SourceFile:130)
        at md.j_(EntityLiving.java:843)
        at qj.j_(SourceFile:31)
        at qr.j_(SourceFile:145)
        at qk.j_(SourceFile:38)
        at yc.a(World.java:253)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2255)
        at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Should also be fixed with 8be6109.
