### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#254]
04-01 00:45:23 [SEVERE] [ForgeModLoader] A TileEntity type any@46bab48f x,y,z: 2635, 65, 283 has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class any is missing a mapping! This is a bug!
at any.b(TileEntity.java:107)
at aam.a(AnvilChunkLoader.java:241)
at aam.a(AnvilChunkLoader.java:130)
at im.b(ThreadedChunkProvider.java:536)
at im.a(ThreadedChunkProvider.java:603)
at in.a(WorldServer.java:844)
at hf.b(SourceFile:34)
at x.a(CommandHandler.java:82)
at ann.a(SourceFile:34)
at ajo.b(SourceFile:44)
at in.a(WorldServer.java:235)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:286)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:443)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-01 00:45:23 [SEVERE] [ForgeModLoader] A TileEntity type any@38eab578 x,y,z: 2628, 65, 283 has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class any is missing a mapping! This is a bug!
at any.b(TileEntity.java:107)
at aam.a(AnvilChunkLoader.java:241)
at aam.a(AnvilChunkLoader.java:130)
at im.b(ThreadedChunkProvider.java:536)
at im.a(ThreadedChunkProvider.java:603)
at in.a(WorldServer.java:844)
at hf.b(SourceFile:34)
at x.a(CommandHandler.java:82)
at ann.a(SourceFile:34)
at ajo.b(SourceFile:44)
at in.a(WorldServer.java:235)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:286)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:443)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

error does not happen if TT is not installed

**Comment by LunNova** [comment]
Break and replace the block at those coords.

**Comment by HaoSs07** [comment]
is a little hard as the coordonates always change

**Comment by LunNova** [comment]
Oh, is it always with the same block, or a block from the same mod?

**Comment by HaoSs07** [comment]
my pc is dead, i cant enter the game to check , im waiting for it to get fixed, but in log is always other coordonate

**Comment by xfloh22** [comment]
this seems to not be TT related, i usually get it from xycraft.

**Comment by HaoSs07** [comment]
i also get some errors fro xycraft; but different , not related to this

**Comment by xfloh22** [comment]
well i found that bukkit plugins such as worldedit can start stuff like this when you edit a block with tileentitiesthat worldedit doesnt change (thats what im guessing). anyway, its also xycraft tanks for me, they throw this error one way or another after a while

**Comment by HaoSs07** [comment]
i dont use mcpc or other bukkit port

**Comment by xfloh22** [comment]
odd. anyway, i even get this without TT just not often. TT might just make it occur more often.

**Comment by dadealus** [comment]
this is a flaw with xycraft valve and tanks. so far no way of fixing unless disable valve or remove xycraft
