### ISSUE TITLE
#1220 Spotloader Exception

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#257]
I'm not sure if I is fixed with the newer builds, as I had issues with chunks not working right with anything past #1220. I'm getting this error on my server pretty often with this build those.

<code>04-01 17:34:03 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c codechicken.chunkloader.TileSpotLoader codechicken.chunkloader.TileSpotLoader@6fd99825 x,y,z: 155, 66, 1085 at x,y,z:155,66,1085
Tick region: rX: 9, rZ: 67, hashCode: 4390921:
java.lang.NullPointerException
    at codechicken.chunkloader.TileChunkLoaderBase.g(TileChunkLoaderBase.java:147)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
</code>

**Comment by aquagene** [comment]
Also just got this one:
<code>04-01 19:29:41 [SEVERE] [TickThreading] Exception ticking entity qk['Zombie Pigman'/14306, l='world', x=2906.30, y=73.25, z=-2748.30] in rX: 181, rZ: -171, hashCode: -11206475:
java.lang.NullPointerException
    at lq.a(Entity.java:1103)
    at md.a(EntityLiving.java:1385)
    at lq.a(Entity.java:1061)
    at md.a(EntityLiving.java:447)
    at lq.d(Entity.java:251)
    at md.e(EntityLiving.java:124)
    at md.c(EntityLiving.java:242)
    at qj.c(SourceFile:26)
    at qr.c(SourceFile:130)
    at md.j_(EntityLiving.java:843)
    at qj.j_(SourceFile:31)
    at qr.j_(SourceFile:145)
    at qk.j_(SourceFile:38)
    at yc.a(World.java:253)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2255)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)</code>

**Comment by LunNova** [comment]
95% sure this was fixed with the recent ChickenChunks changes, comment if it's still an issue.
