### ISSUE TITLE
1226 MCPC+ towny console spam/ breaks monster despawn

### ISSUE THREAD

**Issue by dadealus** [MinimallyCorrect/TickThreading#268]
Constently getting the following in the console.

2013-04-06 21:56:32 [WARNING] [Towny] Task #12 for Towny v0.82.1.0 generated an exception
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getName(CraftWorld.java:489)
    at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:318)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:168)
    at fy.run(ThreadMinecraftServer.java:16)

it seems to be complaining about monsters.    from what I can tell it has to do with despawning monsters within a town. which now doesn't work with TT

**Comment by LunNova** [comment]
Towny seems to be leaking worlds, report to Towny that that
MobRemovalTimerTask is using unloaded worlds. Turn off world unloading.
