### ISSUE TITLE
TT# 1274 debug crash's server

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#287]
Ran /debug and crashed server

04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:28 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 01:24:29 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.

**Comment by Nohau** [comment]
I ran the /debug command in Twilight Forest : 

Thread: Chunk Updates for Age 2/2 - 1
    PID: 107 | State: BLOCKED | Daemon: true | Priority:5
BLOCKED on java.util.concurrent.LinkedBlockingQueue@798d65f owned by "Chunk Updates for Age 2/2 - 2" Id=108
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:34)
        -  blocked on java.util.concurrent.LinkedBlockingQueue@798d65f
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

Thread: Chunk Updates for Age 2/2 - 2
    PID: 108 | State: WAITING | Daemon: true | Priority:5
WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6bdd2740
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6bdd2740
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:35)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

Thread: Chunk Updates for Age 2/2 - 3
    PID: 109 | State: BLOCKED | Daemon: true | Priority:5
BLOCKED on java.util.concurrent.LinkedBlockingQueue@798d65f owned by "Chunk Updates for Age 2/2 - 2" Id=108
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:34)
        -  blocked on java.util.concurrent.LinkedBlockingQueue@798d65f
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

Threads in same state: Chunk Updates for Age 2/2 - 4, Chunk Updates for Age 2/2 - 5

Thread: Chunk Updates for Nether/-1 - 1
    PID: 75 | State: BLOCKED | Daemon: true | Priority:5
BLOCKED on java.util.concurrent.LinkedBlockingQueue@1a1410a7 owned by "Chunk Updates for Nether/-1 - 5" Id=79
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:34)
        -  blocked on java.util.concurrent.LinkedBlockingQueue@1a1410a7
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Nohau** [comment]
04-13 01:23:25 [SEVERE] [ForgeModLoader] Failed to handle packet from LadyDivine
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at md.j_(EntityLiving.java:949)
        at qx.j_(EntityPlayer.java:328)
        at iq.g(EntityPlayerMP.java:286)
        at iv.a(NetServerHandler.java:310)
        at eb.a(SourceFile:39)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
04-13 01:23:25 [SEVERE] [TickThreading] Exception ticking world Age 2/2
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at kh.c(SourceFile:131)
        at in.run(WorldServer.java:407)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at 60129542197: 53,14 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at 8589934571: -21,1 before queued unload was processed.
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at kh.c(SourceFile:131)
        at in.run(WorldServer.java:407)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:25 [INFO] [Minecraft] LadyDivine lost connection: Internal error: null
04-13 01:23:25 [INFO] [STDOUT] Unloading Player: LadyDivine
04-13 01:23:25 [SEVERE] [TickThreading] Exception ticking world Age 2/2
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at kh.c(SourceFile:131)
        at in.run(WorldServer.java:485)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)

04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload -90194313216 - probably already unloaded.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload -85899345920 - probably already unloaded.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload -171798691824 - probably already unloaded.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload 64424509495 - probably already unloaded.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload 64424509491 - probably already unloaded.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload 60129542197 - probably already unloaded.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload 8589934571 - probably already unloaded.
04-13 01:23:25 [SEVERE] [ForgeModLoader] Failed to handle packet from Nohau
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at md.c(EntityLiving.java:235)
        at qx.c(EntityPlayer.java:560)
        at md.j_(EntityLiving.java:843)
        at qx.j_(EntityPlayer.java:328)
        at iq.g(EntityPlayerMP.java:286)
        at iv.a(NetServerHandler.java:310)
        at eb.a(SourceFile:39)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
04-13 01:23:25 [WARNING] [ForgeModLoader] Something's taking too long! 'root.levels.world.worldTick.root.levels.world.worldTick.world.worldTick.chunkTick' took aprox 131.184149 ms
04-13 01:23:25 [WARNING] [ForgeModLoader] Something's taking too long! 'root.levels.world.worldTick.root.levels.world.worldTick.iterate' took aprox 159.381424 ms
04-13 01:23:25 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
        at kh.b(SourceFile:37)
        at in.run(WorldServer.java:484)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:25 [SEVERE] [ForgeModLoader] Failed to handle packet from hosolon
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at md.y(EntityLiving.java:674)
        at lq.j_(Entity.java:431)
        at md.j_(EntityLiving.java:808)
        at qx.j_(EntityPlayer.java:328)
        at iq.g(EntityPlayerMP.java:286)
        at iv.a(NetServerHandler.java:310)
        at eb.a(SourceFile:39)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
04-13 01:23:25 [INFO] [Minecraft] Nohau lost connection: Internal error: null
04-13 01:23:25 [INFO] [STDOUT] Unloading Player: Nohau
04-13 01:23:25 [INFO] [Minecraft] hosolon lost connection: Internal error: null
04-13 01:23:25 [INFO] [STDOUT] Unloading Player: hosolon
04-13 01:23:25 [WARNING] [ForgeModLoader] Something's taking too long! 'root.levels.world.worldTick.root.levels.world' took aprox 239.609623 ms
04-13 01:23:25 [INFO] [STDERR] java.net.SocketException: Socket closed
04-13 01:23:25 [INFO] [STDERR]  at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
04-13 01:23:25 [INFO] [STDERR]  at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
04-13 01:23:25 [INFO] [STDERR]  at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
04-13 01:23:25 [INFO] [STDERR]  at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
04-13 01:23:25 [INFO] [STDERR]  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
04-13 01:23:25 [INFO] [STDERR]  at java.io.DataOutputStream.flush(DataOutputStream.java:123)
04-13 01:23:25 [INFO] [STDERR]  at ci.run(SourceFile:120)
04-13 01:23:25 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
        at kh.b(SourceFile:37)
        at kh.c(SourceFile:131)
        at yc.a(World.java:3137)
        at in.run(WorldServer.java:406)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:25 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at kh.b(SourceFile:37)
        at kh.c(SourceFile:131)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:339)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:25 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
        at kh.a(SourceFile:19)
        at kh.c(SourceFile:132)
        at in.run(WorldServer.java:429)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1481763717015: 105,-345 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1580547964847: 81,-368 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1584842932145: 79,-369 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1580547964849: 79,-368 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1584842932144: 80,-369 before queued unload was processed.
04-13 01:23:25 [WARNING] [ForgeModLoader] Something's taking too long! 'root.levels.world.worldTick.root.levels.root.levels.world.worldTick.chunkTick.root.levels.world.root' took aprox 148.606034 ms
04-13 01:23:25 [WARNING] [ForgeModLoader] Something's taking too long! 'root.levels.world.worldTick.root.levels.root.levels.world.worldTick.chunkTick.root.levels.world' took aprox 179.599378 ms
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1576252997553: 79,-367 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1576252997552: 80,-367 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1571958030256: 80,-366 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Couldn'nt unload -1481763717015 - probably already unloaded.
04-13 01:23:25 [WARNING] [ForgeModLoader] Something's taking too long! 'root.levels.world.worldTick.root.levels.root.levels.world.worldTick.chunkTick.root.levels.root' took aprox 253.569999 ms
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1576252997554: 78,-367 before queued unload was processed.
04-13 01:23:25 [FINE] [TickThreading] Reloaded chunk at -1567663062961: 79,-365 before queued unload was processed.
04-13 01:23:25 [SEVERE] [ForgeModLoader] Failed to handle packet from Lando9290
java.lang.NullPointerException
        at kh.a(SourceFile:19)
        at md.j_(EntityLiving.java:907)
        at qx.j_(EntityPlayer.java:328)
        at iq.g(EntityPlayerMP.java:286)
        at iv.a(NetServerHandler.java:310)
        at eb.a(SourceFile:39)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
04-13 01:23:26 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at kh.c(SourceFile:131)
        at yc.a(World.java:3162)
        at in.run(WorldServer.java:406)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 01:23:26 [INFO] [Minecraft] Lando9290 lost connection: Internal error: null
04-13 01:23:26 [INFO] [STDOUT] Unloading Player: Lando9290
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1571958030256 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1576252997554 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1584842932145 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1580547964849 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1576252997553 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1567663062961 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1584842932144 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1576252997552 - probably already unloaded.
04-13 01:23:26 [FINE] [TickThreading] Couldn'nt unload -1580547964847 - probably already unloaded.

**Comment by Nohau** [comment]
04-13 01:23:25 [INFO] [Minecraft] [Nohau: Started debug profiling]
04-13 01:23:25 [SEVERE] [ForgeModLoader] Failed to handle packet from LadyDivine
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at md.j_(EntityLiving.java:949)
        at qx.j_(EntityPlayer.java:328)
        at iq.g(EntityPlayerMP.java:286)
        at iv.a(NetServerHandler.java:310)
        at eb.a(SourceFile:39)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
04-13 01:23:25 [SEVERE] [TickThreading] Exception ticking world Age 2/2
java.lang.NullPointerException
        at kh.b(SourceFile:42)
        at kh.c(SourceFile:131)
        at in.run(WorldServer.java:407)
        at in.g_net_minecraft_world_WorldServer_tickBlocksAndAmbiance_p0(WorldServer.java:358)
        at in.g(WorldServer.java)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:288)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:334)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Use `/profile usage` or jvisualvm for profiling. /debug's profiler isn't threadsafe.
