### ISSUE TITLE
TT# 1278 Internal Server Error Possible New Chunk Error?

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#293]
When running around  and generating new chunks once you find a location and goto place a block in this case stone we are getting the following error and the user gets a Internal Server Error and disconnects. 

04-13 09:30:03 [FINE] [TickThreading] Couldn'nt unload -1503238553488 - probably already unloaded.
04-13 09:30:03 [FINE] [TickThreading] Couldn'nt unload -1503238553487 - probably already unloaded.
04-13 09:30:04 [INFO] [TickThreading] iq['hosolon'/212145, l='world', x=1738.55, y=29.41, z=-5683.98] changed dimension from Twilight Forest/7 to Overworld/0
04-13 09:30:05 [INFO] [STDOUT] Sending serverside check to: hosolonr
04-13 09:30:07 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 219180
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 09:30:07 [WARNING] [Minecraft] Failed to handle packet for Nohau/66.25.171.110: java.lang.NullPointerException
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
04-13 09:30:07 [INFO] [STDOUT] Unloading Player: Nohau
04-13 09:30:08 [FINE] [TickThreading] Reloaded chunk at -1511828488079: 113,-352 before queued unload was processed.
04-13 09:30:08 [FINE] [TickThreading] Reloaded chunk at -1507533520783: 113,-351 before queued unload was processed.
04-13 09:30:08 [FINE] [TickThreading] Couldn'nt unload -1511828488079 - probably already unloaded.
04-13 09:30:08 [FINE] [TickThreading] Couldn'nt unload -1507533520783 - probably already unloaded.

**Comment by LunNova** [comment]
> Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.

**Comment by Nohau** [comment]
04-13 09:41:38 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 1197
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
        at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:283)
        at net.minecraftforge.event.ASMEventHandler_120_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:579)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:353)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 09:41:38 [WARNING] [Minecraft] Failed to handle packet for Nohau/66.25.171.110: java.lang.NullPointerException
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
        at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:283)
        at net.minecraftforge.event.ASMEventHandler_120_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:579)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:353)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(SourceFile:849)
04-13 09:41:38 [INFO] [STDOUT] Unloading Player: Nohau

**Comment by LunNova** [comment]
Enable generateChunkOnProvideRequest, it's a bukkitforge bug and that's the workaround. https://github.com/keepcalm/BukkitForge/issues/593
