### ISSUE TITLE
TT 1278 & 1306 - Deadlock - Server Crash

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#296]
Crash Located : 

https://gist.github.com/Nohau/5379384

--- Snippet --

04-13 12:39:40 [SEVERE] [ForgeModLoader] Caught exception from PortalGun
java.lang.NullPointerException
        at portalgun.common.core.TickHandlerServer.saveData(TickHandlerServer.java:730)
        at portalgun.common.PortalGun.serverStopping(PortalGun.java:212)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
        at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
        at com.google.common.eventbus.EventBus.post(EventBus.java:268)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
        at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
        at com.google.common.eventbus.EventBus.post(EventBus.java:268)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
        at cpw.mods.fml.common.Loader.serverStopping(Loader.java:740)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:325)
        at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:213)
        at me.nallar.tickthreading.minecraft.DeadLockDetector$2.run(DeadLockDetector.java:60)
        at java.lang.Thread.run(Thread.java:722)

**Comment by LunNova** [comment]
That's portal gun failing to save after the server crashed, please give the full log. The deadlock detector report is cut off at the top, so I can't see what crashed it.

**Comment by Nohau** [comment]
How does this look : https://gist.github.com/Nohau/5381493

**Comment by Nohau** [comment]
Crash with 1306

https://gist.github.com/Nohau/5384541
