### ISSUE TITLE
[TT #1283] [1.4.7 MCPC+ L11] [SEVERE] [TickThreading] Exception ticking world Nether/-1 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#297]
@nallar 

This is what i got when i tried the customised startup.sh no idea whats causin it server seems to be running though.

04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:179)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap.put(LongObjectHashMap.java:105)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:120)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:51 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap.put(LongObjectHashMap.java:105)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:120)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap.put(LongObjectHashMap.java:105)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:120)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:52 [INFO] [GraviGun] [1.4.7v2] Recieved client info from ChubyBonBon
04-13 17:26:52 [INFO] [PortalGun] [1.4.7v5] Recieved client info from ChubyBonBon
04-13 17:26:52 [FINEST] [ForgeModLoader] Received valid FML login packet from /2.248.123.111:51642
04-13 17:26:53 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-13 17:26:53 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:322)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:356)
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$KeyIterator.next(LongObjectHashMap.java:340)
    at yp.getEntityCount(SpawnerAnimals.java:58)
    at yp.a_net_minecraft_world_SpawnerAnimals_findChunksForSpawning_p0(SpawnerAnimals.java:170)
    at yp.a(SpawnerAnimals.java)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:285)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:462)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by alicheek** [comment]
@nallar 

still getting streams of this error up to 12mbs in the forgemodloader log lol

**Comment by LunNova** [comment]
This is actually caused by the fix for spawning, Spigot's spawning isn't threadsafe. I'll fix it after chunk saving is fixed.

**Comment by alicheek** [comment]
ah ok cheers :)
