### ISSUE TITLE
RedPower Wires issue

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#3]
`2013-01-04 03:25:59 [SEVERE] [TickThreading] Exception during tile entity tick
2013-01-04 03:25:59 [SEVERE] [TickThreading] Tick region: rX: 19, rZ: 18, hashCode: 1179667:
java.util.NoSuchElementException
        at java.util.LinkedList.removeFirst(LinkedList.java:268)
        at com.eloraam.redpower.core.RedPowerLib.updateCurrent(RedPowerLib.java:725)
        at com.eloraam.redpower.wiring.TileWiring.onBlockNeighborChange(TileWiring.java:141)
        at com.eloraam.redpower.core.BlockMultipart.a(BlockMultipart.java:30)
        at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
        at com.eloraam.redpower.core.RedPowerLib.updateIndirectNeighbors(RedPowerLib.java:53)
        at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java:86)
        at com.eloraam.redpower.logic.TileLogicPointer.timerTick(TileLogicPointer.java:115)
        at com.eloraam.redpower.logic.TileLogicPointer.onTileTick(TileLogicPointer.java:230)
        at com.eloraam.redpower.core.TileExtended.g(TileExtended.java:123)
        at com.eloraam.redpower.logic.TileLogicPointer.g(TileLogicPointer.java:271)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:66)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:79)
        at me.nallar.tickthreading.minecraft.ThreadManager$3.run(ThreadManager.java:87)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:138)`

**Comment by LunNova** [comment]
Crash fixed. Leaving this open as a reminder that I need to improve performance: make blockUpdates threadlocal.

**Comment by LunNova** [comment]
Fixed via cff9fd7d
