### ISSUE TITLE
Build 342 Urgent - Console error spam - flooding log

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#31]
01-12 18:41:02 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.lang.ArrayIndexOutOfBoundsException: -4
    at a.a(CrashReport.java:259)
    at yc.a(World.java:4341)
    at net.minecraft.server.MinecraftServer.tickWorld(MinecraftServer.java:147)
    at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:186)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:36)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:142)

**Comment by LunNova** [comment]
This should be fixed in 41ec6af9923.
