### ISSUE TITLE
[Build #1315, MCPC+ L15] Servercrash blocked on java.util.concurrent.LinkedBlockingQueue, and some errors

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#314]
First of all a server crash with deadlock
http://pastebin.com/KrPTcfwu

And two errors related to AE, the bugged blocks are no longer functional.

04-15 23:49:06 [Grave] [TickThreading] Exception during tile entity tick
ticking: c appeng.me.tile.TileLevelEmitter appeng.me.tile.TileLevelEmitter@49b74c71 x,y,z: -382, 63, -786 at x,y,z:-382,63,-786
Tick region: rX: -23, rZ: -49, hashCode: -3211287:
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at appeng.me.CellInventory.countOfItemType(CellInventory.java:237)
    at appeng.me.MEInventoryHandler.countOfItemType(MEInventoryHandler.java:70)
    at appeng.me.MEInventoryArray.countOfItemType(MEInventoryArray.java:246)
    at appeng.me.tile.TileLevelEmitter.g(TileLevelEmitter.java:376)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

04-15 23:33:37 [Grave] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@7b816110 x,y,z: -390, 65, -811 at x,y,z:-390,65,-811
Tick region: rX: -24, rZ: -50, hashCode: -3276824:
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at appeng.me.CellInventory.countOfItemType(CellInventory.java:237)
    at appeng.me.CellInventory.containsItemType(CellInventory.java:224)
    at appeng.me.MEInventoryHandler.containsItemType(MEInventoryHandler.java:60)
    at appeng.me.MEInventoryArray.addItems(MEInventoryArray.java:289)
    at appeng.me.tile.TileController.signalInput(TileController.java:1451)
    at appeng.me.tile.TileController.requestUpdate(TileController.java:585)
    at appeng.me.GridInterface.requestUpdate(GridInterface.java:119)
    at appeng.me.tile.TileInterfaceBase.a(TileInterfaceBase.java:272)
    at buildcraft.core.inventory.TransactorSimple.addToSlot(TransactorSimple.java:80)
    at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:27)
    at buildcraft.core.inventory.Transactor.add(Transactor.java:16)
    at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:337)
    at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:320)
    at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:228)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by wormzjl** [comment]
Something to do with mystcraft?
http://pastebin.com/Yimxj2ZS

**Comment by Puremin0rez** [comment]
@nallar 

Did this issue not manage to get fixed? I got crashed overnight with this same problem

**Comment by LunNova** [comment]
The deadlock is fixed, the other issues are not.

**Comment by LunNova** [comment]
The AE issues are now also fixed.
