### ISSUE TITLE
Build 1315-Error with buildcraft Quarry

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#316]
Hey Nallar i found this in my log a couple times, not sure what it did but it didn't seem to break game play or anything.
04-16 04:39:17 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c buildcraft.factory.TileQuarry buildcraft.factory.TileQuarry@5fc5dbc7 x,y,z: 29, 67, 265 at x,y,z:29,67,265
Tick region: rX: 1, rZ: 16, hashCode: 1048577:
java.lang.NullPointerException
    at buildcraft.core.inventory.TransactorSimple.getPartialSlot(TransactorSimple.java:44)
    at buildcraft.core.inventory.TransactorSimple.getPartialSlot(TransactorSimple.java:34)
    at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java:21)
    at buildcraft.core.inventory.Transactor.add(Transactor.java:16)
    at buildcraft.core.utils.Utils.addToRandomInventory(Utils.java:81)
    at buildcraft.factory.TileQuarry.mineStack(TileQuarry.java:436)
    at buildcraft.factory.TileQuarry.positionReached(TileQuarry.java:404)
    at buildcraft.factory.TileQuarry.moveHead(TileQuarry.java:755)
    at buildcraft.factory.TileQuarry.g(TileQuarry.java:155)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Fixed another TransactorSimple issue, which should fix this. Reply if it is still broken.
