### ISSUE TITLE
[TT #1318] [1.4.7 mcpc+ L15] [SEVERE] The server has stopped responding! Computer Craft TT issue

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#318]
Seems to be an issue with TT and CC

http://pastebin.com/U2tZKTjd

**Comment by LunNova** [comment]
Correct, at line #722. Also, why did you give the Spigot deadlock detector report? It's a pain to read :P

_nallar scurries away to make a patch to disable it_

**Comment by alicheek** [comment]
lol sorry man just wanted to make sure i didnt leave any of it out :P

**Comment by LunNova** [comment]
Are you sure you didn't leave anything out? TT should also have given a deadlock report, and it's not in your pastebin :s

I'll need the TT log, as Spigot doesn't log enough information.

**Comment by alicheek** [comment]
ah from the TT logs?

**Comment by LunNova** [comment]
Yes.

**Comment by alicheek** [comment]
This bit sorry really nooby at this lol

Definitely deadlocked: 
"Thread-5319" Id=7920 BLOCKED on dan200.computer.core.Computer@48da8c01 owned by "Entities in Overworld/0 - 4" Id=94
    at dan200.computer.core.Computer.queueLuaEvent(Computer.java:1064)
    -  blocked on dan200.computer.core.Computer@48da8c01
    at dan200.computer.core.Computer.access$300(Computer.java:31)
    at dan200.computer.core.Computer$APIEnvironment.queueEvent(Computer.java:91)
    at dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper.queueEvent(PeripheralAPI.java:220)
    -  locked dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper@5099801
    at dan200.computer.shared.TileEntityDiskDrive.mountDisk(TileEntityDiskDrive.java:517)
    -  locked dan200.computer.shared.TileEntityDiskDrive@90778e5
    at dan200.computer.shared.TileEntityDiskDrive.attach(TileEntityDiskDrive.java:496)
    at dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper.attach(PeripheralAPI.java:82)
    -  locked dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper@5099801
    at dan200.computer.core.apis.PeripheralAPI$2.execute(PeripheralAPI.java:304)
    -  locked [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@4a24433c
    at dan200.computer.core.ComputerThread$1$1.run(ComputerThread.java:72)
    at java.lang.Thread.run(Thread.java:722)

"Entities in Overworld/0 - 4" Id=94 BLOCKED on [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@4a24433c owned by "Thread-5319" Id=7920
    at dan200.computer.core.apis.PeripheralAPI.advance(PeripheralAPI.java:347)
    -  blocked on [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@4a24433c
    at dan200.computer.core.Computer.advance(Computer.java:560)
    -  locked java.util.ArrayList@12bc751a
    -  locked dan200.computer.core.Computer@48da8c01
    at dan200.computer.shared.NetworkedComputerHelper.update(NetworkedComputerHelper.java:111)
    at dan200.computer.shared.TileEntityComputer.g(TileEntityComputer.java:95)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
That issue is a computercraft issue - update computercraft if you haven't already, if it still happens report it to dan200.
