### ISSUE TITLE
Forge-Dynmap 1.5 Console spam and blank map

### ISSUE THREAD

**Issue by NachtRaben** [MinimallyCorrect/TickThreading#325]
I have know that dynmap forge 1.6 wasn't working well with tick threading, but i looked around and found that 1.5 did work. so i installed it and now my console is being spammed about once a second and dynmap web map is entirely blank

10:02:29 [SEVERE] [dynmap] Exception while loading chunks
java.lang.IllegalAccessError: tried to access field zx.a from class org.dynmap.f
orge.ChunkSnapshot
        at org.dynmap.forge.ChunkSnapshot.<init>(ChunkSnapshot.java:169)
        at org.dynmap.forge.ForgeMapChunkCache.loadChunks(ForgeMapChunkCache.jav
a:1427)
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:61
2)
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:59
9)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEnd(DynmapPlugin.java:7
06)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandl
er.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87
)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandle
r.java:275)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:281)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
        at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Can't reproduce with latest, looks like it's only be an issue with the "stable-ish" build.
