### ISSUE TITLE
ender storage error keeps popping up 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#327]
04-17 21:53:06 [SEVERE] [TickThreading] Exception ticking world Nether/-1

java.util.ConcurrentModificationException

  at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)

  at java.util.LinkedList$ListItr.next(Unknown Source)

  at codechicken.enderstorage.api.EnderStorageManager.save(EnderStorageManager.java:181)

  at codechicken.enderstorage.api.EnderStorageManager.access$0(EnderStorageManager.java:177)

  at codechicken.enderstorage.api.EnderStorageManager$EnderStorageSaveHandler.onWorldSave(EnderStorageManager.java:64)

  at net.minecraftforge.event.ASMEventHandler_85_EnderStorageSaveHandler_onWorldSave_Save.invoke(.dynamic)

  at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)

  at net.minecraftforge.event.EventBus.post(EventBus.java:103)

  at in.a(WorldServer.java:133)

  at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:447)

  at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)

  at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)

  at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Puremin0rez** [comment]
I think @nallar fixed this in one of the recent builds?

I reported it yesterday and applied the fix and haven't seen it since.

**Comment by LunNova** [comment]
This might be a slightly different issue, looks like it's a different
exception?

**Comment by HaoSs07** [comment]
at the time of this report i had latest TT that included the ender chest fix. ( 98 % of the time i have latest  build when reporting a error )

**Comment by HaoSs07** [comment]
did not happen in latest builds, so im closing this
