### ISSUE TITLE
[TT #1336] [1.4.7 mcpc+ L15] [WARNING] [Towny] Task #7 for Towny v0.82.1.0 generated an exception java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#328]
Seems to be another issue with towny  not sure if its the same thing or not

[WARNING] [Towny] Task #7 for Towny v0.82.1.0 generated an exception
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getLivingEntities(CraftWorld.java:642)
    at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:311)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by Nohau** [comment]
I recently switched to mcpc and also started seeing this along with this : 

[SEVERE] Could not pass event PlayerMoveEvent to Towny v0.82.1.0

Also getting the PlayerMoveEvent error when world guard is enabled

**Comment by gorea01** [comment]
same here too

28.04 11:27:17 [Server] INFO at yc.c(World.java:740)
28.04 11:27:17 [Server] INFO at yc.a(World.java:762)
28.04 11:27:17 [Server] INFO at zz.a(Chunk.java:785)
28.04 11:27:17 [Server] INFO java.lang.NullPointerException
28.04 11:27:17 [Server] WARNING Task #7 for Towny v0.82.1.0 generated an exception

**Comment by gorea01** [comment]
is there a solutiion for this please?

[Towny] Task #7 for Towny v0.82.1.0 generated an exception
java.lang.NullPointerException
    at zz.a(Chunk.java:785)
    at yc.a(World.java:762)
    at yc.c(World.java:740)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:899)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
@gorea01 
See #662

Closing this, forgot to close it when fixing the issue.
