### ISSUE TITLE
TT#1343 Eception During Tile Entity Tick - code chicken chunnkloader

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#331]
Log Files : https://gist.github.com/Nohau/5408989

04-17 19:43:07 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c codechicken.chunkloader.TileChunkLoader codechicken.chunkloader.TileChunkLoader@181403f9 x,y,z: -1468, 64, -4056 at x,y,z:-1468,64,-4056
Tick region: rX: -91, rZ: -253, hashCode: -16580699:
java.lang.NullPointerException
    at codechicken.chunkloader.TileChunkLoaderBase.g(TileChunkLoaderBase.java:147)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Nohau** [comment]
TT # 1356 Same errors I have even broke the chunk loaders and put new ones down just in case

https://gist.github.com/Nohau/5417327

**Comment by LunNova** [comment]
Fixed in latest with the redpower frames fix. Caused when they set the world as a client world, which is completely unsafe.
