### ISSUE TITLE
SEVERE Exception during tile entity tick / INFO ticking: c buildcraft.transport.TileGenericPipe

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#334]
Ultimate 1.0.1 + TickThreading-1.4.7-1.0.0.1336.jar

See this in the logs today

18.04 10:14:21 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
18.04 10:14:21 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
18.04 10:14:21 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
18.04 10:14:21 [Server] INFO at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
18.04 10:14:21 [Server] INFO at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
18.04 10:14:21 [Server] INFO at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
18.04 10:14:21 [Server] INFO at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
18.04 10:14:21 [Server] INFO at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:225)
18.04 10:14:21 [Server] INFO at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:317)
18.04 10:14:21 [Server] INFO at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:328)
18.04 10:14:21 [Server] INFO at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:356)
18.04 10:14:21 [Server] INFO at buildcraft.transport.PipeTransportItems.entityEntering(PipeTransportItems.java:119)
18.04 10:14:21 [Server] INFO at buildcraft.transport.PipeTransportItems.groupEntities(PipeTransportItems.java:535)
18.04 10:14:21 [Server] INFO java.lang.NullPointerException
18.04 10:14:21 [Server] INFO Tick region: rX: -2, rZ: 12, hashCode: 786430:
18.04 10:14:21 [Server] INFO ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@7dffd1d4 x,y,z: -47, 78, 201 at x,y,z:-47,78,201
18.04 10:14:21 [Server] SEVERE Exception during tile entity tick

**Comment by geoffcorey** [comment]
Been running TickThreading-1.4.7-1.0.0.1423.jar since this morning.   This error no longer is appearing in the logs.
