### ISSUE TITLE
[TT #1356] [1.4.7 mcpc+ L15] concurrentNetworkTicks is over 20 tps normal?

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#337]
hey there thought id try out your concurrent network tick system got  a screen shot of what i got if typing tps , now i was just wondering if its normal of the network tps to be over 20 tps?
![netowrk](https://f.cloud.github.com/assets/3965516/400218/ebab7f30-a895-11e2-9250-0b925ad4bec3.jpg)

**Comment by Nohau** [comment]
Something to also note how would overall = 20.000 if it avg's it all? Unless Network is also different?

**Comment by alicheek** [comment]
well got some errors coming through also some weird glitches:

04-19 01:58:03 [SEVERE] [TickThreading] Tile Entity com.github.AbrarSyed.SecretRooms.common.TileEntityCamoChest@61114fc5 x,y,z: 4192, 214, 1939 failed to validate, it will be ignored.
java.lang.NullPointerException
    at com.github.AbrarSyed.SecretRooms.common.TileEntityCamoFull.s(TileEntityCamoFull.java:144)
    at yc.a(World.java:491)
    at zz.threadUnsafeChunkLoad(Chunk.java:164)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:504)
    at im.d(ThreadedChunkProvider.java:342)
    at yc.e(World.java:726)
    at yc.a(World.java:111)
    at buildcraft.BuildCraftFactory$QuarryChunkloadCallback.ticketsLoaded(BuildCraftFactory.java:110)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:507)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:346)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:142)
    at fy.run(ThreadMinecraftServer.java:16)
04-19 01:58:11 [SEVERE] [TickThreading] TickThreading v1.0.0.1356 for MC1.4.7 on 1.4.7 tickthreading,mcpc,spigot,craftbukkit,forge,fml is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading
04-19 01:58:13 [INFO] [TickThreading] Loaded 21/46 persistent chunks in Nether/-1
04-19 01:58:13 [INFO] [TickThreading] Loaded 61/154 persistent chunks in Overworld/0
04-19 01:59:18 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at ic2.core.network.NetworkManager.getFieldData(NetworkManager.java:531)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:307)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:300)
    at ic2.core.network.NetworkManager.onTick(NetworkManager.java:81)
    at ic2.core.IC2.tickStart(IC2.java:1637)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:432)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:547)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-19 02:00:33 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c ic2.core.block.generator.tileentity.TileEntityNuclearReactorElectric ic2.core.block.generator.tileentity.TileEntityNuclearReactorElectric@22954c89 x,y,z: -2524, 51, 503 at x,y,z:-2524,51,503
Tick region: rX: -157, rZ: 31, hashCode: 2031459:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at ic2.core.network.NetworkManager.getFieldData(NetworkManager.java:531)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:307)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:300)
    at ic2.core.network.NetworkManager.updateTileEntityField(NetworkManager.java:92)
    at ic2.core.block.generator.tileentity.TileEntityNuclearReactor.g(TileEntityNuclearReactor.java:148)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-19 02:11:55 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c ic2.core.block.generator.tileentity.TileEntityNuclearReactorElectric ic2.core.block.generator.tileentity.TileEntityNuclearReactorElectric@4ede96c2 x,y,z: 770, 33, 535 at x,y,z:770,33,535
Tick region: rX: 48, rZ: 33, hashCode: 2162736:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at ic2.core.network.NetworkManager.getFieldData(NetworkManager.java:531)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:307)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:300)
    at ic2.core.network.NetworkManager.updateTileEntityField(NetworkManager.java:92)
    at ic2.core.block.generator.tileentity.TileEntityNuclearReactor.g(TileEntityNuclearReactor.java:148)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
04-19 02:12:51 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c ic2.core.block.generator.tileentity.TileEntityNuclearReactorElectric ic2.core.block.generator.tileentity.TileEntityNuclearReactorElectric@43aac92d x,y,z: -2541, 51, 486 at x,y,z:-2541,51,486
Tick region: rX: -158, rZ: 30, hashCode: 1965922:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at ic2.core.network.NetworkManager.getFieldData(NetworkManager.java:531)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:307)
    at ic2.core.network.NetworkManager.sendUpdatePacket(NetworkManager.java:300)
    at ic2.core.network.NetworkManager.updateTileEntityField(NetworkManager.java:92)
    at ic2.core.block.generator.tileentity.TileEntityNuclearReactor.g(TileEntityNuclearReactor.java:148)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157

**Comment by alicheek** [comment]
also got another problem with solar panels where they seemto be glitching out and not facing upwords, meaning they are getting no power:

![glitch](https://f.cloud.github.com/assets/3965516/400244/ac40e28e-a897-11e2-9ff9-b31bded970a4.jpg)

**Comment by Puremin0rez** [comment]
The camo blocks error is unrelated to the Concurrent Network Ticks as far as I know - It's a bug with Camo Blocks itself that TT has patched to prevent it from crashing your server.

But yeah, the IC2 stuff is definitely related. @nallar might need to do some patching with IC2 to make it more compatible perhaps.

Looks promising though!

**Comment by LunNova** [comment]
Concurrent network TPS runs at a higher TPS, and it is completely unrelated to your normal TPS. This is to reduce lag. Currently with most things MC adds 50ms to the response time as it waits 'til the end of the current tick, doing this reduces it to 25ms.
