### ISSUE TITLE
Build #1356 - [SEVERE] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by DrFestus** [MinimallyCorrect/TickThreading#341]
[SEVERE] java.util.ConcurrentModificationException
2013-04-18 21:50:34 [SEVERE]    at java.util.ArrayList.writeObject(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at java.io.ObjectOutputStream.writeObject0(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at java.io.ObjectOutputStream.writeObject(Unknown Source)
2013-04-18 21:50:34 [SEVERE]    at twilightforest.TFFeatureCache.save(TFFeatureCache.java:120)
2013-04-18 21:50:34 [SEVERE]    at twilightforest.world.TFWorldChunkManager.saveFeatureCache(TFWorldChunkManager.java:415)
2013-04-18 21:50:34 [SEVERE]    at twilightforest.TFEventListener.worldSave(TFEventListener.java:429)
2013-04-18 21:50:34 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_135_TFEventListener_worldSave_Save.invoke(.dynamic)
2013-04-18 21:50:34 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-04-18 21:50:34 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-04-18 21:50:34 [SEVERE]    at in.a(WorldServer.java:135)
2013-04-18 21:50:34 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:450)
2013-04-18 21:50:34 [SEVERE]    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:547)
2013-04-18 21:50:34 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
2013-04-18 21:50:34 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Puremin0rez** [comment]
@nallar 

Bump ^_^

Getting this issue non stop, i think it might also be causing hangs
