### ISSUE TITLE
Divide by Zero in /tps - Build 366

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#35]
2013-01-12 20:52:05 [INFO] [STDERR] java.lang.ArithmeticException: / by zero
2013-01-12 20:52:05 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.Tic
kManager.getBasicStats(TickManager.java:230)
2013-01-12 20:52:05 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.com
mands.TPSCommand.processCommand(TPSCommand.java:28)
2013-01-12 20:52:05 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.com
mands.Command.b(Command.java:28)
2013-01-12 20:52:05 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-01-12 20:52:05 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-01-12 20:52:05 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-01-12 20:52:05 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-01-12 20:52:05 [INFO] [STDERR]     at cg.b(TcpConnection.java:454)
2013-01-12 20:52:05 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-12 20:52:05 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-12 20:52:05 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-12 20:52:05 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
r(MinecraftServer.java:114)
2013-01-12 20:52:05 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-12 20:52:05 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
q(MinecraftServer.java:52)
2013-01-12 20:52:05 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:497)
2013-01-12 20:52:05 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Fixed via 5ce2a9b1cad20a
