### ISSUE TITLE
RP2 Frame Motor not working (Exception while updating block neighbours)

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#357]
The motor itself uses the moving animation and appears as it should be working, but no matter what the circumstances it will not move anything.

Here's the error it spits out:
04-20 10:44:17 [SEVERE] [TickThreading] Exception while updating block neighbours
java.lang.IllegalAccessError
        at com.eloraam.redpower.machine.TileMotor.pickFrame(TileMotor.java:176)
        at com.eloraam.redpower.machine.TileMotor.onBlockNeighborChange(TileMotor.java:283)
        at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)
        at yc.m(World.java:234)
        at yc.h(World.java:1070)
        at yc.f(World.java:1009)
        at yc.c(World.java:920)
        at ajf.a(BlockButton.java:269)
        at ir.a(ItemInWorldManager.java:573)
        at iv.a(NetServerHandler.java:906)
        at fk.a(Packet15Place.java:79)
        at cg.b(TcpConnection.java:467)
        at iv.d(NetServerHandler.java:220)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:359)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:259)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:177)
        at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
ELORAAAAMM! https://gist.github.com/nallar/5426253

:anguished: 

Will have it fixed soon...

**Comment by alexbegt** [comment]
:(

**Comment by xfloh22** [comment]
getting this error again using the newest build

**Comment by xfloh22** [comment]
nallar ik this isnt the right place but ur awesome. you respond to all requests so quickly and actually care. thanks :smile:

**Comment by joey19982** [comment]
^Completely agree. You're the best <3

**Comment by alicheek** [comment]
I have to really agree with the other guys, probably one of the best devs ive known
