### ISSUE TITLE
[TT #1412] [1.4.7 mcpc+ L15] [SEVERE] [TickThreading] Exception ticking world World_VIP/13 java.lang.NullPointerException

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#366]
Using Multiverse to make a VIP world got around the issue of creating the world. with TT it would fail rendering the new world so just took it off then made it then put it back on , but getting these errors in the TT log now.

2013-04-22 00:41:53 [SEVERE] [TickThreading] Exception ticking world World_VIP/13
java.lang.NullPointerException
    at codechicken.wirelessredstone.core.RedstoneEtherServer.saveEther(RedstoneEtherServer.java:71)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.onWorldSave(WRCoreEventHandler.java:57)
    at net.minecraftforge.event.ASMEventHandler_100_WRCoreEventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at in.a_net_minecraft_world_WorldServer_saveAllChunks_p0(WorldServer.java:152)
    at in.a(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:465)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:564)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-22 00:59:26 [SEVERE] [TickThreading] Exception ticking world World_VIP/13
java.lang.NullPointerException
    at codechicken.wirelessredstone.core.RedstoneEtherServer.saveEther(RedstoneEtherServer.java:71)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.onWorldSave(WRCoreEventHandler.java:57)
    at net.minecraftforge.event.ASMEventHandler_100_WRCoreEventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at in.a_net_minecraft_world_WorldServer_saveAllChunks_p0(WorldServer.java:152)
    at in.a(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:465)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:564)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by DrFestus** [comment]
I have the same problem except on existing worlds. Console just getting spammed with this message for every world. Using build 1412.

**Comment by LunNova** [comment]
Could you try latest and give the server console log during startup? Won't fix the issue, will hopefully show what's happening.

**Comment by alicheek** [comment]
sure will do that now

**Comment by LunNova** [comment]
Oh, make sure it's build 1419 or newer. You might've been so quick you downloaded latest before the build with the debugging for this was finished.

**Comment by alicheek** [comment]
its cool just downloaded 1419 there :P

**Comment by alicheek** [comment]
Sorry accidentally deleted the link: http://pastebin.com/UzN3V1zh

**Comment by alicheek** [comment]
@nallar 
found this in the forge log : 

[SEVERE] [ForgeModLoader] Something raised an exception. The message was 'Wireless Redstone Save Manager'. 'stopGame' is true
java.lang.NullPointerException
    at java.io.File.<init>(File.java:334)
    at codechicken.core.CommonUtils.getWorldSaveLocation(CommonUtils.java:52)
    at codechicken.wirelessredstone.core.SaveManager.getEtherDir(SaveManager.java:163)
    at codechicken.wirelessredstone.core.SaveManager.<init>(SaveManager.java:124)
    at codechicken.wirelessredstone.core.SaveManager.reloadSave(SaveManager.java:78)
    at codechicken.wirelessredstone.core.RedstoneEtherServer.addEther(RedstoneEtherServer.java:49)
    at codechicken.wirelessredstone.core.RedstoneEther.loadServerWorld(RedstoneEther.java:122)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.onChunkDataLoad(WRCoreEventHandler.java:36)
    at net.minecraftforge.event.ASMEventHandler_100_WRCoreEventHandler_onChunkDataLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at aam.a(ThreadedChunkLoader.java:133)
    at aam.a(ThreadedChunkLoader.java:106)
    at im.f(ThreadedChunkProvider.java:556)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:435)
    at im.getChunkAt(ThreadedChunkProvider.java:409)
    at im.c(ThreadedChunkProvider.java:355)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:822)
    at org.bukkit.Bukkit.createWorld(Bukkit.java:156)
    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(Unknown Source)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(Unknown Source)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:291)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:273)
    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:602)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:568)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:447)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
2013-04-22 22:05:17 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event for 13,-36
java.lang.RuntimeException: Wireless Redstone Save Manager
    at cpw.mods.fml.server.FMLServerHandler.haltGame(FMLServerHandler.java:102)
    at cpw.mods.fml.common.FMLCommonHandler.raiseException(FMLCommonHandler.java:196)
    at codechicken.wirelessredstone.core.SaveManager.<init>(SaveManager.java:157)
    at codechicken.wirelessredstone.core.SaveManager.reloadSave(SaveManager.java:78)
    at codechicken.wirelessredstone.core.RedstoneEtherServer.addEther(RedstoneEtherServer.java:49)
    at codechicken.wirelessredstone.core.RedstoneEther.loadServerWorld(RedstoneEther.java:122)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.onChunkDataLoad(WRCoreEventHandler.java:36)
    at net.minecraftforge.event.ASMEventHandler_100_WRCoreEventHandler_onChunkDataLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at aam.a(ThreadedChunkLoader.java:133)
    at aam.a(ThreadedChunkLoader.java:106)
    at im.f(ThreadedChunkProvider.java:556)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:435)
    at im.getChunkAt(ThreadedChunkProvider.java:409)
    at im.c(ThreadedChunkProvider.java:355)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:822)
    at org.bukkit.Bukkit.createWorld(Bukkit.java:156)
    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(Unknown Source)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(Unknown Source)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:291)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:273)
    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:602)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:568)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:447)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
    at java.io.File.<init>(File.java:334)
    at codechicken.core.CommonUtils.getWorldSaveLocation(CommonUtils.java:52)
    at codechicken.wirelessredstone.core.SaveManager.getEtherDir(SaveManager.java:163)
    at codechicken.wirelessredstone.core.SaveManager.<init>(SaveManager.java:124)
    ... 32 more

**Comment by LunNova** [comment]
Ah, that explains the problem, thanks! :)

Also, none of TT's log entries or Forge's log entries seem to be in the console log you posted. Not sure why :s

**Comment by DrFestus** [comment]
Am still recieving this on build 1420

[SEVERE] [TickThreading] Exception ticking world MobArena/18
java.lang.NullPointerException
    at codechicken.wirelessredstone.core.RedstoneEtherServer.saveEther(RedstoneEtherServer.java:71)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.onWorldSave(WRCoreEventHandler.java:57)
    at net.minecraftforge.event.ASMEventHandler_95_WRCoreEventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at in.a_net_minecraft_world_WorldServer_saveAllChunks_p0(WorldServer.java:152)
    at in.a(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:465)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:564)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Can you pastebin your FML log?

**Comment by DrFestus** [comment]
http://pastebin.com/51MiXxKw

**Comment by DrFestus** [comment]
Now throwing these errors on startup on build 1423

[SEVERE] [Multiverse-Core] The world 'MobArena' could NOT be loaded because it contains errors!
2013-04-22 20:00:36 [SEVERE] [Multiverse-Core] Try using Chukster to repair your world! 'MobArena'
2013-04-22 20:00:36 [SEVERE] [Multiverse-Core] http://forums.bukkit.org/threads/admin-chunkster.8186/
2013-04-22 20:00:36 [SEVERE] java.lang.IllegalArgumentException: Failed to register dimension for id 14, provider type 14 does not exist
2013-04-22 20:00:36 [SEVERE]    at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:131)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:782)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.Bukkit.createWorld(Bukkit.java:156)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
2013-04-22 20:00:36 [SEVERE]    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
2013-04-22 20:00:36 [SEVERE]    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
2013-04-22 20:00:36 [SEVERE]    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(Unknown Source)
2013-04-22 20:00:36 [SEVERE]    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(Unknown Source)
2013-04-22 20:00:36 [SEVERE]    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(Unknown Source)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:291)
2013-04-22 20:00:36 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:273)
2013-04-22 20:00:36 [SEVERE]    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:602)
2013-04-22 20:00:36 [SEVERE]    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:568)
2013-04-22 20:00:36 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:447)
2013-04-22 20:00:36 [SEVERE]    at ho.c(DedicatedServer.java:203)
2013-04-22 20:00:36 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
2013-04-22 20:00:36 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

Also caused the server to shut down with:

[SEVERE] [TickThreading] Exception ticking world Spawn/14
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:53)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:446)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:345)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:264)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:177)
    at fy.run(ThreadMinecraftServer.java:16)
2013-04-22 20:01:04 [SEVERE] [TickThreading] Spawn/14 has become unstable, stopping.
2013-04-22 20:01:04 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at net.minecraft.server.MinecraftServer.n(MinecraftServer.java:95)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:497)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:345)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:264)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:177)
    at fy.run(ThreadMinecraftServer.java:16)
2013-04-22 20:01:12 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at java.lang.Runtime.exit(Unknown Source)
    at java.lang.System.exit(Unknown Source)
    at ho.p(DedicatedServer.java:304)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:236)
    at fy.run(ThreadMinecraftServer.java:16)

Threw these 2 errors on every world

**Comment by LunNova** [comment]
Won't be able to fix it until tomorrow afternoon, (18 hours), sorry. Maybe
try 1421.

**Comment by LunNova** [comment]
https://gist.github.com/nallar/5439817

**Comment by DrFestus** [comment]
Ok, thanks for all your awesome work though! Was build 1420 that allowed me to start the server without crashing
