### ISSUE TITLE
[TT #1423] [1.4.7 mcpc+ L15] [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 5

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#375]
Not sure if that is what causes the deadlock in this version of TT?

2013-04-23 12:17:09 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 5
java.lang.NoClassDefFoundError: me/nallar/tickthreading/util/MappingUtil
    at me.nallar.tickthreading.Log.toString(Log.java:226)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:102)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
Caused by: java.lang.ClassNotFoundException: me.nallar.tickthreading.util.MappingUtil
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:218)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 6 more
Caused by: java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:207)
    ... 8 more

**Comment by LunNova** [comment]
Increase your jvm's max permgen size.

**Comment by alicheek** [comment]
ok will do that

**Comment by alicheek** [comment]
hmm where is it i change this? (sorry not good at this stuff) :)

**Comment by LunNova** [comment]
Add "-XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=128m" before the "-jar"
in your server start command.

On 23 April 2013 16:33, Alistair notifications@github.com wrote:

> hmm where is it i change this? (sorry not good at this stuff) :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nallar/TickThreading/issues/375#issuecomment-16865830
> .

## 

Ross Allan
