### ISSUE TITLE
TT1423 / MCPC L15 PlayerMoveEvent

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#376]
I noticed the following : 

[SEVERE] Could not pass event PlayerMoveEvent to Towny v0.82.1.0

Also see the same when trying to use WorldGuard but states WorldGuard instead of Towny 

Nothing is showing up in FML log and TTLogs but it shows in server.log

2013-04-23 17:18:04 [SEVERE] Could not pass event PlayerMoveEvent to Towny v0.82.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at iv.a(NetServerHandler.java:344)
        at eb.a(Packet10Flying.java:38)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getChunkAt(CraftWorld.java:200)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:566)
        at org.bukkit.Location.getBlock(Location.java:82)
        at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMove(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        ... 8 more
2013-04-23 17:18:04 [SEVERE] Could not pass event PlayerMoveEvent to Towny v0.82.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at iv.a(NetServerHandler.java:344)
        at eb.a(Packet10Flying.java:38)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getChunkAt(CraftWorld.java:200)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:566)
        at org.bukkit.Location.getBlock(Location.java:82)
        at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMove(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        ... 8 more

**Comment by Nohau** [comment]
I disabled unload worlds and issue went away it appears..

**Comment by LunNova** [comment]
Towny is trying to use an unloaded world, not a TT issue. Added Towny to compatibility page.

**Comment by alicheek** [comment]
Think this is fixed with townys latest dev download issue is you get up another error that is a bit annoying for chests carts due to it being made for 1.5.1 but still works fine.
