### ISSUE TITLE
RedPower Wire issue

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#38]
2013-01-13 05:02:46 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: class com.eloraam.redpower.logic.TileLogicPointer at x,y,z:-345,48,-568
Tick region: rX: -21, rZ: -35, hashCode: -2293781:
t: Exception while updating neighbours
        at yc.m(World.java:841)
        at yc.h(World.java:801)
        at alv.l(BlockRedstoneWire.java:106)
        at alv.a(BlockRedstoneWire.java:421)
        at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
        at com.eloraam.redpower.core.RedPowerLib.updateIndirectNeighbors(RedPowerLib.java:53)
        at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java:86)
        at com.eloraam.redpower.logic.TileLogicPointer.timerTick(TileLogicPointer.java:115)
        at com.eloraam.redpower.logic.TileLogicPointer.onTileTick(TileLogicPointer.java:230)
        at com.eloraam.redpower.core.TileExtended.g(TileExtended.java:123)
        at com.eloraam.redpower.logic.TileLogicPointer.g(TileLogicPointer.java:271)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:75)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:88)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:83)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:36)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:142)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
        at java.util.HashMap$KeyIterator.next(HashMap.java:928)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at java.util.ArrayList.<init>(ArrayList.java:151)
        at alv.l(BlockRedstoneWire.java:100)
        at alv.a(BlockRedstoneWire.java:421)
        at yc.m(World.java:822)
        at yc.h(World.java:802)
        at alv.l(BlockRedstoneWire.java:106)
        at alv.a(BlockRedstoneWire.java:421)
        at yc.m(World.java:822)
        at yc.h(World.java:805)
        at alv.l(BlockRedstoneWire.java:106)
        at alv.a(BlockRedstoneWire.java:421)
        at yc.m(World.java:822)
        at yc.h(World.java:805)
        at alv.l(BlockRedstoneWire.java:106)
        at alv.a(BlockRedstoneWire.java:421)
        at yc.m(World.java:822)
        at yc.h(World.java:800)
        at alv.l(BlockRedstoneWire.java:106)
        at alv.a(BlockRedstoneWire.java:421)
        at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
        at com.eloraam.redpower.core.RedPowerLib.updateCurrent(RedPowerLib.java:742)
        at com.eloraam.redpower.machine.TileRedstoneTube.onBlockNeighborChange(TileRedstoneTube.java:87)
        at com.eloraam.redpower.core.BlockMultipart.a(BlockMultipart.java:30)
        at yc.m(World.java:822)

**Comment by LunNova** [comment]
Fixed via ee92b654d5c8f86a3
