### ISSUE TITLE
[SEVERE] Exception in main tick loop

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#380]
2013-04-26 05:20:28 [SEVERE] Exception in main tick loop
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.

This is beeing spammed in my console at the moment. I'm running the latest dev version of TT and lagest legacy version of MCPC+.

System is Ubuntu Server 12.04 with Java version 7.

Thanks for your continued fantastic support ! :+1:

**Comment by mainsheep** [comment]
Just to add, I didn't see this error before I implemented the latest build for TT, unless there is another error that came at the same time.

**Comment by LunNova** [comment]
Do as the warning requests, so we can actually see the issue.

**Comment by mainsheep** [comment]
2013-04-27 10:54:22 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(LinkedList.java:891)
        at codechicken.chunkloader.PlayerChunkViewerManager.update(PlayerChunkViewerManage
r.java:100)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler
.java:35)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22
)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:79)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275
)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:177)
        at fy.run(ThreadMinecraftServer.java:16)

That is the result when I entered that java parameter.

We also recently had a problem where new players would get "stuck" when entering the server. They cannot move or look around at all. When they log out and in again, they will be able to move. So I'm hoping this has something to do with that problem aswell.
