### ISSUE TITLE
Failed to generate a chunk in Broken world with ID -2147483648 at chunk coords 5,7

### ISSUE THREAD

**Issue by clienthax** [MinimallyCorrect/TickThreading#381]
2013-04-26 09:43:05 [SEVERE] [TickThreading] Failed to generate a chunk in Broken world with ID -2147483648 at chunk coords 5,7
2013-04-26 09:43:05 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.NullPointerException
        at yc.E(World.java:4608)
        at aaz.a(MapGenBase.java:22)
        at aax.d(ChunkProviderHell.java:297)
        at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.d(NormalChunkGenerator.java:38)
        at im.getChunkAtInternal(ThreadedChunkProvider.java:480)
        at im.getChunkAt(ThreadedChunkProvider.java:409)
        at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:749)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09:43:05 [INFO] clienthax issued server command: /profile

**Comment by LunNova** [comment]
Fixed via 17a4a3511d485a20f.
