### ISSUE TITLE
[TT 1429] [MCPC+ L19] [SEVERE] [TickThreading] Exception ticking entity px['item.tile.dirt'/75570

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#382]
Havent noticed any issues with this error but thought I should post it to u anyways :)

2013-04-26 19:01:16 [SEVERE] [TickThreading] Exception ticking entity px['item.tile.dirt'/75570, l='overworld', x=-1993.62, y=65.15, z=-1147.09] in rX: -124, rZ: -71, hashCode: -4653180:
java.lang.NullPointerException
    at lq.teleportTo(Entity.java:2793)
    at lq.b(Entity.java:2786)
    at px.b(EntityItem.java:475)
    at lq.y(Entity.java:556)
    at lq.j_(Entity.java:508)
    at px.j_(EntityItem.java)
    at yc.a(World.java:361)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:48)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Do you have world unloading enabled? What's located at the coordinates in the error?

**Comment by alicheek** [comment]
world unloading is set to false. ill check what is over there at the coordinates

**Comment by alicheek** [comment]
The area was just a grassy biome with nothing altered bit weird tbh lol seems the block was a grass block also or a dirt turning to grass?

**Comment by LunNova** [comment]
Definitely checked the right coordinates? `x=-1993.62, y=65.15, z=-1147.09`, not `rX: -124, rZ: -71`. There should be a portal of some kind there. :s

**Comment by alicheek** [comment]
Oh sorry didn't put the minuses in there! yea its right next to a nether portal
