### ISSUE TITLE
TT1423 / MCPC L15 Failed to hand chunk event

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#384]
Here is the gist https://gist.github.com/Nohau/5471644

2013-04-26 21:16:25 [SEVERE] [TickThreading] A mod failed to handle a ChunkWatch event
java.lang.NullPointerException
        at codechicken.xycraftcopy.core.world.WorldExtension.watchChunk(WorldExtension.java:72)
        at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkWatch(WorldExtensionManager.java:101)
        at net.minecraftforge.event.ASMEventHandler_197_WorldExtensionEventHandler_onChunkWatch_Watch.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at eb.sendChunks(Packet10Flying.java:113)
        at eb.a(Packet10Flying.java:39)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
2013-04-26 21:17:03 [FINEST] [ForgeModLoader] Received valid FML login packet from /211.27.104.131:49804
2013-04-26 21:17:05 [INFO] [GraviGun] [1.4.7v2] Recieved client info from steve761954
2013-04-26 21:17:05 [INFO] [PortalGun] [1.4.7v5] Recieved client info from steve761954
2013-04-26 21:17:22 [SEVERE] [TickThreading] A mod failed to handle a ChunkWatch event
java.lang.NullPointerException
        at codechicken.xycraftcopy.core.world.WorldExtension.watchChunk(WorldExtension.java:72)
        at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkWatch(WorldExtensionManager.java:101)
        at net.minecraftforge.event.ASMEventHandler_197_WorldExtensionEventHandler_onChunkWatch_Watch.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at eb.sendChunks(Packet10Flying.java:113)
        at eb.a(Packet10Flying.java:53)
        at cg.i(TcpConnection.java:348)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)

Thanks

**Comment by Puremin0rez** [comment]
Same here +1

**Comment by LunNova** [comment]
Xycraft's included CodeChickenCore is just broken. This also occurs under MCPC+. I have partially fixed it, but would recommend just not using xycraft if you dislike the console spam.
