### ISSUE TITLE
#1450 Crash on Launch (after patching) 

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#393]
<code>2013-04-28 11:48:56 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2013-04-28 11:48:56 [SEVERE] [ForgeModLoader] Caught exception from ModularForceFieldSystem
java.lang.VerifyError: (class: chb/mods/mffs/common/tileentity/TileEntityProjector, method: calculateField signature: (Z)Z) Incompatible type for getting or setting field
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at chb.mods.mffs.common.MFFSMaschines.<init>(MFFSMaschines.java:64)
    at chb.mods.mffs.common.MFFSMaschines.<clinit>(MFFSMaschines.java:36)
    at chb.mods.mffs.common.ModularForceFieldSystem.load(ModularForceFieldSystem.java:445)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:94)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:356)
    at ho.c(DedicatedServer.java:135)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(SourceFile:849)
2013-04-28 11:48:56 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionLoaderException
cpw.mods.fml.common.LoaderException: java.lang.VerifyError: (class: chb/mods/mffs/common/tileentity/TileEntityProjector, method: calculateField signature: (Z)Z) Incompatible type for getting or setting field
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:130)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:677)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:94)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:356)
    at ho.c(DedicatedServer.java:135)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(SourceFile:849)
Caused by: java.lang.VerifyError: (class: chb/mods/mffs/common/tileentity/TileEntityProjector, method: calculateField signature: (Z)Z) Incompatible type for getting or setting field
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at chb.mods.mffs.common.MFFSMaschines.<init>(MFFSMaschines.java:64)
    at chb.mods.mffs.common.MFFSMaschines.<clinit>(MFFSMaschines.java:36)
    at chb.mods.mffs.common.ModularForceFieldSystem.load(ModularForceFieldSystem.java:445)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:676)
    ... 5 more
2013-04-28 11:48:56 [SEVERE] [Minecraft] This crash report has been saved to: D:\Direwolf20_Server.\crash-reports\crash-2013-04-28_11.48.56-server.txt
2013-04-28 11:48:56 [INFO] [Minecraft] Stopping server
2013-04-28 11:48:56 [INFO] [Minecraft] Saving worlds
2013-04-28 11:48:56 [SEVERE] [ForgeModLoader] Exception while attempting to stop the server
java.lang.NullPointerException
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.k(MinecraftServer.java:406)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:231)
    at fy.run(SourceFile:849)
2013-04-28 11:48:56 [INFO] [STDERR] java.net.SocketException: socket closed
2013-04-28 11:48:56 [INFO] [STDERR]     at java.net.DualStackPlainSocketImpl.accept0(Native Method)
2013-04-28 11:48:56 [INFO] [STDERR]     at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
2013-04-28 11:48:56 [INFO] [STDERR]     at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
2013-04-28 11:48:56 [INFO] [STDERR]     at java.net.PlainSocketImpl.accept(Unknown Source)
2013-04-28 11:48:56 [INFO] [STDERR]     at java.net.ServerSocket.implAccept(Unknown Source)
2013-04-28 11:48:56 [INFO] [STDERR]     at java.net.ServerSocket.accept(Unknown Source)
2013-04-28 11:48:56 [INFO] [STDERR]     at hu.run(ServerListenThread.java:81)
2013-04-28 11:48:56 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at java.lang.Runtime.exit(Unknown Source)
    at java.lang.System.exit(Unknown Source)
    at ho.p(DedicatedServer.java:264)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:236)
    at fy.run(SourceFile:849)
2013-04-28 11:48:56 [INFO] [STDOUT] Closing listening thread
2013-04-28 11:48:56 [INFO] [Minecraft] Stopping server
2013-04-28 11:48:56 [INFO] [Minecraft] Saving worlds</code>

**Comment by LunNova** [comment]
Fixed in 2e5c57c48ab25f.
