### ISSUE TITLE
TT1446 | MCPC L5  Exception during tile entity tick

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#394]
Here is the logs

https://gist.github.com/Nohau/5477717

Error from what i can see :  

2013-04-28 12:44:35 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c forestry.core.gadgets.TileEngine forestry.core.gadgets.TileEngine@4bf9ecf0 x,y,z: 1, 68, 5 at x,y,z:1,68,5
Tick region: rX: 0, rZ: 0, hashCode: 0:
java.lang.NullPointerException
at forestry.core.gadgets.BlockMachine.b(BlockMachine.java:185)
at yc.l(World.java:883)
at yc.B(World.java:4461)
at forestry.core.gadgets.TileForestry.isActivated(TileForestry.java:139)
at forestry.core.gadgets.TileEngine.canPowerTo(TileEngine.java:163)
at forestry.core.gadgets.TileEngine.g(TileEngine.java:132)
at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Probably caused by 7be906647665db19e38.

**Comment by LunNova** [comment]
Can you screenshot whatever's near to x,y,z: 1, 68, 5?

**Comment by Nohau** [comment]
Nothing is near 1,68,5 dug a whole and just blocks of ore, dirt etc.. maybe a age world but their is over 400..

**Comment by Nohau** [comment]
TT 1460 logs . 

Still don't see world but i been accused of being blind before though..

https://gist.github.com/Nohau/5478007

**Comment by Nohau** [comment]
Found some Iron Golems (thaumcraft) nearby at bedrock level that was about now

**Comment by Nohau** [comment]
That was at like 0,0,20

**Comment by LunNova** [comment]
That's odd... looks like something's wrong with the build, it's missing my changes.

**Comment by LunNova** [comment]
Nope, I derped and added the world in the wrong place.

**Comment by Nohau** [comment]
Ok i have 1461 running  .. looks like i am getting a 131 age book and will send back screen shots..

2013-04-28 17:37:41 [SEVERE] [TickThreading] Exception ticking TileEntity c forestry.core.gadgets.TileEngine forestry.core.gadgets.TileEngine@432bf928 x,y,z: 1, 68, 5 at x,y,z:1,68,5
 World: Main/131
java.lang.NullPointerException
        at forestry.core.gadgets.BlockMachine.b(BlockMachine.java:185)
        at yc.l(World.java:883)
        at yc.B(World.java:4461)
        at forestry.core.gadgets.TileForestry.isActivated(TileForestry.java:139)
        at forestry.energy.gadgets.EngineTin.generateHeat(EngineTin.java:125)
        at forestry.core.gadgets.TileEngine.g(TileEngine.java:145)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Nohau** [comment]
Raided user base lol Elecctrical Engine it appears.

![2013-04-28_17 52 30](https://f.cloud.github.com/assets/4019875/436541/644ab4e8-b056-11e2-8684-532019ee03cd.png)
![2013-04-28_17 52 37](https://f.cloud.github.com/assets/4019875/436542/678edcf6-b056-11e2-979e-f17a63dd9a11.png)

**Comment by LunNova** [comment]
disregard that last question, I'm an idiot, you already gave coords in the first report. Oops.

**Comment by LunNova** [comment]
Can you break and replace the machine next to the engine? If that doesn't fix the issue, does the issue only happen if people are not in the area?

**Comment by Nohau** [comment]
I upgraded to 1471 and this area doesn't give errors anymore but now getting them for different locations which I been knocking them out and replacing .. There has been 1 case where rather in creative or not in creative a pneumatic tube was causing anyone who tried to knock it out crash . I went ahead and cleaned it up via world edit which fixed that problem. 

So far It does appear to be when people are not around it that I can tell.

**Comment by Nohau** [comment]
This is with MCPC L19 + TT 1471

https://gist.github.com/Nohau/5491184

**Comment by LunNova** [comment]
Still happening?
