### ISSUE TITLE
[TT 1463] [MCPC+ L20]  [SEVERE] Could not load 'plugins/WorldBorder.jar' in folder 'plugins' like this for all my plugins now

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#398]
[SEVERE] Could not load 'plugins/WorldBorder.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/WorldEdit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/CleanChat.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/Buycraft.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/GravesPlus_v1.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/Vault.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/Multiverse-Core-2.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/PermissionsEx-1.19.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/MyCommand.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/Questioner.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/PvPTimer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/TekkitCustomizer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/announcer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/CoreProtect_2.04.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/iDisguise_v1.5.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more
2013-04-28 23:25:30 [SEVERE] Could not load 'plugins/disablecraft_147_.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:252)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:230)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IncompatibleClassChangeError: Class me.nallar.tickthreading.collections.CHashMap does not implement the requested interface java.util.concurrent.ConcurrentMap
    at org.bukkit.plugin.java.PluginClassLoader.getJarMapping(PluginClassLoader.java:134)
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:110)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:162)
    ... 9 more

**Comment by LunNova** [comment]
Use L19 for now, the issue fixed in L20 is already fixed in TT, and the
fixes conflicted.

**Comment by alicheek** [comment]
ah ok cheers man will give that a try now

**Comment by alicheek** [comment]
@nallar 

Does that mean I can use L20 now? :)

**Comment by LunNova** [comment]
Yes
