### ISSUE TITLE
Exception Removing Player

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#400]
Caused Mass spam of user leaving in chat console over and over had to kill server and wouldn't stop on it's own

TTLOG https://gist.github.com/Nohau/5479028

2013-04-28 18:59:47 [SEVERE] [TickThreading] Exception removing a player entity
java.lang.NullPointerException
    at yc.e(World.java:164)
    at gm.disconnect(ServerConfigurationManager.java:330)
    at iv.c(NetServerHandler.java:284)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:69)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:364)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:264)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:177)
    at fy.run(ThreadMinecraftServer.java:16)
2013-04-28 18:59:47 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at gm.disconnect(ServerConfigurationManager.java:331)
    at iv.c(NetServerHandler.java:284)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:69)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.jav

**Comment by Nohau** [comment]
MCPC L21  + TT 1471 brought this bug back

2013-04-29 22:24:07 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at gm.disconnect(ServerConfigurationManager.java:331)
        at iv.c(NetServerHandler.java:284)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:69)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:367)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:267)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:180)
        at fy.run(ThreadMinecraftServer.java:16)
2013-04-29 22:24:07 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at gm.disconnect(ServerConfigurationManager.java:331)
        at iv.c(NetServerHandler.java:284)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:69)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:367)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:267)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:180)
        at fy.run(ThreadMinecraftServer.java:16)
2013-04-29 22:24:07 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
        at gm.disconnect(ServerConfigurationManager.java:331)
        at iv.c(NetServerHandler.java:284)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:69)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:367)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:267)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:180)
        at fy.run(ThreadMinecraftServer.java:16)
