### ISSUE TITLE
[TT 1465] [MCPC+ L21] [SEVERE] [TickThreading] Tile Entity com.github.AbrarSyed.SecretRooms.common.TileEntityCamoFull@4c1e71a1 x,y,z: -2526, 63, 499 failed to validate, it will be ignored.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#406]
I do remember a issue being posted about this already but couldn't find it again so don't know if this is a new error for the secret rooms or if im just picking up an error you already know.

2013-04-29 11:20:45 [SEVERE] [TickThreading] Tile Entity com.github.AbrarSyed.SecretRooms.common.TileEntityCamoFull@4c1e71a1 x,y,z: -2526, 63, 499 failed to validate, it will be ignored.
java.lang.NullPointerException
    at com.github.AbrarSyed.SecretRooms.common.TileEntityCamoFull.s(TileEntityCamoFull.java:144)
    at yc.a(World.java:583)
    at zz.threadUnsafeChunkLoad(Chunk.java:173)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:517)
    at im.d(ThreadedChunkProvider.java:359)
    at yc.e(World.java:726)
    at yc.q(World.java:309)
    at in.q(WorldServer.java:161)
    at railcraft.common.util.misc.ChunkManager.playerTicketsLoaded(ChunkManager.java:220)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:529)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:346)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)
2013-04-29 11:20:45 [SEVERE] [TickThreading] Tile Entity com.github.AbrarSyed.SecretRooms.common.TileEntityCamoFull@2500a6b8 x,y,z: -2526, 63, 501 failed to validate, it will be ignored.
java.lang.NullPointerException
    at com.github.AbrarSyed.SecretRooms.common.TileEntityCamoFull.s(TileEntityCamoFull.java:144)
    at yc.a(World.java:583)
    at zz.threadUnsafeChunkLoad(Chunk.java:173)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:517)
    at im.d(ThreadedChunkProvider.java:359)
    at yc.e(World.java:726)
    at yc.q(World.java:309)
    at in.q(WorldServer.java:161)
    at railcraft.common.util.misc.ChunkManager.playerTicketsLoaded(ChunkManager.java:220)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:529)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:346)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:149)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by floh22** [comment]
this is not TT. i get this all the time even when its not installed. also, these errors are really not that important. they dont break anything, cause lag, or crash the server.

**Comment by alicheek** [comment]
ah ok I realised it wasn't causing issues just thought I should post it I haven't had it before TT though (not had the server that long with out it though :P)

**Comment by LunNova** [comment]
It's a bug with secret rooms mid which causes issues when its tile entities
are chunk loaded.

**Comment by alicheek** [comment]
ah cool
