### ISSUE TITLE
[TT #1465, MCPC+ L21] Exception ticking world Nether/-1 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#409]
Got these messages in my log file
2013-04-29 11:35:33 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(Unknown Source)
    at codechicken.wirelessredstone.core.RedstoneEtherServer.unloadJammedMap(RedstoneEtherServer.java:662)
    at codechicken.wirelessredstone.core.RedstoneEtherServer.tick(RedstoneEtherServer.java:651)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.tickEnd(WRCoreEventHandler.java:122)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:79)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:457)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:568)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

Here is the full log:
http://pastebin.com/uQjhwE9u

**Comment by wormzjl** [comment]
Still getting this in build 1484...

**Comment by LunNova** [comment]
Can you delete your patchedMods folder and repatch? I don't see what could cause that, also decompiled the patched code and checked that it's correct.

**Comment by wormzjl** [comment]
Tried a fresh install but I'm still getting this error.

**Comment by LunNova** [comment]
Can you upload a copy of wireless redstone core from your patchedMods folder, and a _console_ log of the server starting? Has to actually be a console log, need to see the classloader logs.

**Comment by wormzjl** [comment]
Startup log:
http://pastebin.com/UNT7TuLs
patching log:
http://pastebin.com/EU3H9ma7
Patched wrcbe core:
http://www.mediafire.com/?ydc8027glhmtopg

**Comment by LunNova** [comment]
Console log confirms that it's not finding/loading the patched classes from WR-CBE Core.

**Comment by LunNova** [comment]
Can you get another console log on latest?

**Comment by Nohau** [comment]
Do you have rptweaks installed that can be injecting code and messing with the patch? I haven't tested this yet but possible maybe?

**Comment by wormzjl** [comment]
Pretty much the same startlog:
http://pastebin.com/wK1VJeGL

Yes I do have rptweaks installed.

**Comment by LunNova** [comment]
Another console log on latest please? And the file definitely exists in the patchedMods folder, with the same name as the file in the mods folder?

**Comment by wormzjl** [comment]
Here:
http://pastebin.com/dgf7HysH

Also getting some strange stuff on server start:
http://pastebin.com/D6Tw5x5Z
http://pastebin.com/Ju2DdpE7

**Comment by LunNova** [comment]
edit: disregard that, it doesn't. :(

**Comment by wormzjl** [comment]
Yes the file name is the same as the one in the mods folder (sorry didn't see that)

Edit: seem that the one for wrcbe is loaded now
http://pastebin.com/e7ewnZzB
still getting this through
http://pastebin.com/Ju2DdpE7
