### ISSUE TITLE
#1465 Crash when player enters Twilight Forest.

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#410]
This error starts spamming the server log until it crashes.
<code>2013-04-29 13:18:06 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:53)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:450)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:568)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)</code>

**Comment by LunNova** [comment]
Full log, until that starts spamming? There's probably another exception which happens, then that starts being spammed.

If there is another related exception, it will probably have "onWorldLoad" in the stack trace.

**Comment by aquagene** [comment]
Other than some admin notifies there's no other exceptions in the log. I'll update it tickthreading with the new fix and see if it happens again.

**Comment by Nohau** [comment]
FYI

http://desk.feed-the-beast.com/index.php?/Knowledgebase/Article/View/24/8/twilightforest-1154-crash-on-server-join

**Comment by LunNova** [comment]
Should be fixed now, with the world loading/unloading changed to be like MCPC+'s.
