### ISSUE TITLE
#1471 Exception ticking TileEntity TIlemarker

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#413]
Server started spamming this this evening, not quite sure what it is, but I figured I'd report it. <code>2013-04-29 18:38:42 [SEVERE] [TickThreading] Exception ticking TileEntity c thaumcraft.common.blocks.TileMarker thaumcraft.common.blocks.TileMarker@528c1084 x,y,z: -1380, 148, -1815 at x,y,z:-1380,148,-1815
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at thaumcraft.common.blocks.TileMarker.g(TileMarker.java:57)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)</code>

**Comment by Nohau** [comment]
TT 1500 / MCPC L22

2013-05-02 21:10:59 [SEVERE] [TickThreading] Exception ticking TileEntity c thaumcraft.common.blocks.TileMarker thaumcraft.common.blocks.TileMarker@81f5a92 x,y,z: 19, 62, -8 at x,y,z:19,62,-8
 World: Age 326/326
java.lang.ArrayIndexOutOfBoundsException: 4
        at java.util.LinkedList.toArray(LinkedList.java:1040)
        at java.util.ArrayList.addAll(ArrayList.java:530)
        at me.nallar.tickthreading.collections.ArrayListReplaceIterateTempListClear.clear(ArrayListReplaceIterateTempListClear.java:35)
        at thaumcraft.common.blocks.TileMarker.g(TileMarker.java:60)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Nohau** [comment]
TT 1500 /MCPC L22

2013-05-02 21:08:29 [SEVERE] [TickThreading] Exception ticking TileEntity c 
thaumcraft.common.blocks.TileMarker thaumcraft.common.blocks.TileMarker@65d4c598 x,y,z: 1781, 64, -5649 at x,y,z:1781,64,-5649
 World: Overworld/0
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
        at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1175)
        at thaumcraft.common.blocks.TileMarker.g(TileMarker.java:58)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Nohau** [comment]
There is a couple different ones here is gist..

https://gist.github.com/Nohau/5506853
