### ISSUE TITLE
[TT 1471] [MCPC+ L21]   [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@68af98d4 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#416]
2013-04-30 18:05:53 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@68af98d4 x,y,z: -1967, 67, 1075 at x,y,z:-1967,67,1075
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-30 18:06:14 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@68af98d4 x,y,z: -1967, 67, 1075 at x,y,z:-1967,67,1075
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-30 18:07:06 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@68af98d4 x,y,z: -1967, 67, 1075 at x,y,z:-1967,67,1075
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-30 18:15:14 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@3978d05c x,y,z: -1968, 66, 1074 at x,y,z:-1968,66,1074
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-30 18:15:28 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@3978d05c x,y,z: -1968, 66, 1074 at x,y,z:-1968,66,1074
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-30 18:39:42 [SEVERE] [TickThreading] Failed to handle packet from phoenex66
java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.getOnlinePlayers(CraftServer.java:329)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.getPlayerExact(CraftServer.java:357)
    at org.bukkit.Bukkit.getPlayerExact(Bukkit.java:264)
    at org.bukkit.craftbukkit.v1_4_R1.map.CraftMapRenderer.render(CraftMapRenderer.java:37)
    at org.bukkit.craftbukkit.v1_4_R1.map.CraftMapView.render(CraftMapView.java:145)
    at aho.a(MapInfo.java:65)
    at ahn.a(MapData.java:288)
    at twilightforest.item.ItemTFMagicMap.c(ItemTFMagicMap.java:444)
    at iq.g(EntityPlayerMP.java:364)
    at iv.a(NetServerHandler.java:499)
    at eb.a(Packet10Flying.java:38)
    at cg.i(TcpConnection.java:348)
    at cg.readNetworkPacket(TcpConnection.java:36)
    at ch.run(PatchTcpReaderThread.java:24)

**Comment by Nohau** [comment]
Similar to what i posted in https://github.com/nallar/TickThreading/issues/394

**Comment by alicheek** [comment]
still getting it on build 1484:

2013-05-01 11:21:12 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@10203864 x,y,z: 1117, 96, 3904 at x,y,z:1117,96,3904
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by Nohau** [comment]
+1 I have gone around and replaced these pipes but it seems as soon as a i replace one a new one comes up..

2013-05-01 12:13:22 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.machine.TileTube com.eloraam.redpower.machine.TileTube@8b000df x,y,z: 512, 60, -5029 at x,y,z:512,60,-5029
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at com.eloraam.redpower.core.TubeFlow.update(TubeFlow.java:52)
    at com.eloraam.redpower.machine.TileTube.g(TileTube.java:167)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
@Nohau 
Don't just replace every block which throws an exception, it was only in that one case earlier! Mostly the types of errors with TT could be thrown by any block of that type seemingly spontaneously.

Looks like something else is replacing the contents field, will look into it.

**Comment by mainsheep** [comment]
Same issue with [TT 1473] [MCPC+ L22]

**Comment by LunNova** [comment]
Still happening after 1495 for anyone?

**Comment by alicheek** [comment]
not used it yet ill put it on later when the server isn't as busy and ill let u know

**Comment by alicheek** [comment]
@nallar 

Its seemed to stop but im now getting these errors with TT 1500

2013-05-02 23:15:20 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid thermalexpansion.transport.tileentity.TileConduitLiquid@1b626452 x,y,z: -222, 36, 3487 at x,y,z:-222,36,3487
 World: Overworld/0
java.lang.NullPointerException
    at thermalexpansion.transport.tileentity.TileConduitLiquid.extractLiquid(TileConduitLiquid.java:601)
    at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:238)
    at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-05-02 23:42:18 [SEVERE] [TickThreading] Exception in main tick loop
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$EntryIterator.next(HashMap.java:880)
    at java.util.HashMap$EntryIterator.next(HashMap.java:878)
    at codechicken.enderstorage.storage.liquid.TankSynchroniser.tickEnd(TankSynchroniser.java:306)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:79)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:299)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:184)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
These are new errors, make new issues.
