### ISSUE TITLE
TT 1471 / MCPC L19 Towny Exception

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#417]
2013-04-30 06:17:31 [WARNING] [Towny] Task #8 for Towny v0.82.1.11 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getChunk(Location.java:73)
    at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:325)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:267)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:180)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by Nohau** [comment]
Is this or could this be related to the clear lag one as well https://github.com/nallar/TickThreading/issues/411 ?

**Comment by LunNova** [comment]
Is world unloading enabled? On my phone, so can't check, but it's either
caused by getting a chunk which doesn't exist or getting a chunk in a world
which isn't loaded.

**Comment by Nohau** [comment]
Yes world unloading enabled For TT and this is the dev version that was mentioned that supported world unloading. In another issue.

**Comment by Nohau** [comment]
Yep and just noticed I think they fixed this with another build going to be trying that as I am runnging .11

v0.82.1.14:
- Trap NPE's caused by Spigot unloading a world yet still reporting the world in the world list
