### ISSUE TITLE
Build 391 Unhandled exception in worker thread, chunkloader

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#42]
01-13 16:01:49 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at codechicken.chunkloader.PlayerChunkViewerManager.calculateChunkChanges(PlayerChunkViewerManager.java:155)
    at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:40)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:31)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:53)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
    at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:251)
    at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:277)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:36)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:142)

**Comment by gustav9797** [comment]
This is still spamming the console in build 431.

**Comment by gustav9797** [comment]
Closing this one as its a duplicate of the newer, but it persists.
