### ISSUE TITLE
[TT #1484, MCPC+ L21] Heavy console spam with Exception ticking TileEntity c buildcraft.energy.TileEngine buildcraft.energy.TileEngine@4af9d108

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#422]
I'm getting this error spam when any player tries to enter this region.
TT log size reached 6 mb and the chunks won't load.

2013-05-01 00:50:19 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.energy.TileEngine buildcraft.energy.TileEngine@4af9d108 x,y,z: 197, 77, -137 at x,y,z:197,77,-137
 World: Overworld/0
java.lang.NullPointerException
    at buildcraft.energy.TileEngine.createEngineIfNeeded(TileEngine.java:173)
    at buildcraft.energy.TileEngine.initialize(TileEngine.java:71)
    at buildcraft.core.TileBuildCraft.g(TileBuildCraft.java:55)
    at buildcraft.energy.TileEngine.g(TileEngine.java:82)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment]
Worldedit/MCedit/whatever out that block and its tile entity. Did the server crash at some point? Looks like a corrupt engine.

**Comment by wormzjl** [comment]
No the server didn't crash, only slowed down by the spam, it only happened when I updated TT to the latest version.

**Comment by LunNova** [comment]
If that doesn't fix it, can you try a clean reinstall? Otherwise that error doesn't actually make sense, it indicates that the ForgeDirection.VALID_DIRECTIONS array is null, which should be impossible.

**Comment by wormzjl** [comment]
The problem is fixed, seems that it's caused by moving bc engines on redpower frames.
