### ISSUE TITLE
TT1488 / MCPC L22 Exception ticking TileEntity c thaumcraft

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#426]
Here you go 

https://gist.github.com/Nohau/5499987

Overall TPS 20
Age & Overworld is loaded and getting error across multiple ones.

Error in nutshell : 

2013-05-01 21:55:25 [SEVERE] [TickThreading] Exception ticking TileEntity c thaumcraft.common.blocks.TileMarker thaumcraft.common.blocks.TileMarker@435e23fe x,y,z: 33, 64, 2 at x,y,z:33,64,2
 World: Age 326/326
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at thaumcraft.common.blocks.TileMarker.g(TileMarker.java:57)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by alicheek** [comment]
yea don't use L 22  I just had that issue there its because nallar has fixed that already in his mod I think so they both conflict with each other got to L21

**Comment by Nohau** [comment]
I was getting it before L22 as well

**Comment by alicheek** [comment]
hm oh might be a different issue lemme see what my log was again

**Comment by alicheek** [comment]
2013-05-02 02:53:08 [SEVERE] [TickThreading] Exception ticking TileEntity c thaumcraft.common.blocks.TileMarker thaumcraft.common.blocks.TileMarker@7678959a x,y,z: -955, 62, 1629 at x,y,z:-955,62,1629
 World: Overworld/0
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at thaumcraft.common.blocks.TileMarker.g(TileMarker.java:57)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by alicheek** [comment]
seems it might be a TT build issue then

**Comment by Nohau** [comment]
Did you just get it? I assume your on L21?

**Comment by aquagene** [comment]
Exact same issue as what I posted a few days ago: https://github.com/nallar/TickThreading/issues/413 I can confirm it still occurs in #1488.
