### ISSUE TITLE
Instability

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#43]
I've been playing on the server with around 20 players online for some hours, and it has frozen around 5 times, for about 2-3 minutes. After that it works normally again. When the server is full the overall load is around 50%. Is this caused by TickThreading?

When it freezes:

2013-01-13 20:47:22 [INFO] [STDERR] java.net.SocketException: Broken pipe
2013-01-13 20:47:22 [INFO] [STDERR]     at java.net.SocketOutputStream.socketWrite0(Native Method)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
2013-01-13 20:47:22 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.io.DataOutputStream.flush(DataOutputStream.java:123)
2013-01-13 20:47:22 [INFO] [STDERR]     at ci.run(SourceFile:120)
2013-01-13 20:47:22 [INFO] [STDERR] java.net.SocketException: Broken pipe
2013-01-13 20:47:22 [INFO] [STDERR]     at java.net.SocketOutputStream.socketWrite0(Native Method)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
2013-01-13 20:47:22 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
2013-01-13 20:47:22 [INFO] [STDERR]     at java.io.DataOutputStream.flush(DataOutputStream.java:123)
2013-01-13 20:47:22 [INFO] [STDERR]     at ci.run(SourceFile:120)

**Comment by LunNova** [comment]
If it has frozen for that long, it should trigger the deadlock detector.
Was there a report in the TT log?

I've been playing on the server with around 20 players online for some
hours, and it has frozen around 5 times, for about 2-3 minutes. After that
it works normally again. When the server is full the overall load is around
50%. Is this caused by TickThreading?

—
Reply to this email directly or view it on
GitHubhttps://github.com/nallar/TickThreading/issues/43.

**Comment by gustav9797** [comment]
Flushed the logs yesterday, I'll check.

**Comment by gustav9797** [comment]
I've noticed that the server goes up to around 3.5gb ram usage really quick with less than 10 people online, build 417 and previous.
