### ISSUE TITLE
TT 1488 / MCPC L22 ticks r

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#438]
So i was going threw the commit history and looking for details on some commands and found /ticks  r when running this command you get the following error now when ran from console. 

2013-05-03 14:01:45 [INFO] An unknown error occurred while attempting to perform this command
2013-05-03 14:01:45 [SEVERE] java.lang.ClassCastException: ho cannot be cast to iq
2013-05-03 14:01:45 [SEVERE]    at me.nallar.tickthreading.minecraft.commands.TicksCommand.processCommand(TicksCommand.java:51)
2013-05-03 14:01:45 [SEVERE]    at me.nallar.tickthreading.minecraft.commands.Command.b(Command.java:34)
2013-05-03 14:01:45 [SEVERE]    at x.a(CommandHandler.java:91)
2013-05-03 14:01:45 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:51)
2013-05-03 14:01:45 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchVanillaCommand(CraftServer.java:550)
2013-05-03 14:01:45 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchServerCommand(CraftServer.java:528)
2013-05-03 14:01:45 [SEVERE]    at ho.al(DedicatedServer.java:353)
2013-05-03 14:01:45 [SEVERE]    at ho.r(DedicatedServer.java:310)
2013-05-03 14:01:45 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:268)
2013-05-03 14:01:45 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:181)
2013-05-03 14:01:45 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

**Comment by Nohau** [comment]
I think it is more because it meant to be ran inside the game not within console as it resends chunks right by grabbing your location.
