### ISSUE TITLE
#1513 Exception in main tick loop (Different than #380)

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#443]
I get a bunch of the first error then the second one, which forces a deadlock shutdown.

<code>2013-05-03 19:58:57 [SEVERE] [TickThreading] Failed to handle packet from aquagene
java.lang.IllegalArgumentException: end before start
    at javax.swing.JTextArea.replaceRange(Unknown Source)
    at ic.publish(SourceFile:64)
    at java.util.logging.Logger.log(Unknown Source)
    at java.util.logging.Logger.doLog(Unknown Source)
    at java.util.logging.Logger.log(Unknown Source)
    at ee.lutsu.alpha.mc.mytown.Log.direct(Log.java:47)
    at ee.lutsu.alpha.mc.mytown.commands.CmdChat.sendToChannel(CmdChat.java:218)
    at ee.lutsu.alpha.mc.mytown.commands.CmdChat.sendToChannelFromDirectTalk(CmdChat.java:186)
    at ee.lutsu.alpha.mc.mytown.event.PlayerEvents.serverChat(PlayerEvents.java:380)
    at net.minecraftforge.event.ASMEventHandler_202_PlayerEvents_serverChat_ServerChatEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at iv.a(NetServerHandler.java:745)
    at cu.a(SourceFile:44)
    at cg.i(TcpConnection.java:347)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:24)</code>

<code>2013-05-03 19:59:39 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.IllegalArgumentException: end before start
    at javax.swing.JTextArea.replaceRange(Unknown Source)
    at ic.publish(SourceFile:64)
    at java.util.logging.Logger.log(Unknown Source)
    at java.util.logging.Logger.doLog(Unknown Source)
    at java.util.logging.Logger.log(Unknown Source)
    at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:233)
    at cpw.mods.fml.common.FMLLog.log(FMLLog.java:27)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:67)
    at iw.b(NetworkListenThread.java)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:371)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:271)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:184)
    at fy.run(SourceFile:849)</code>

**Comment by aquagene** [comment]
To clarify I'm connecting to the server locally so network issues can be ruled out in relation to packet problems.

**Comment by LunNova** [comment]
Looks like the GUI log handler can't handle anything that isn't plain text, for example MyTown's colours.

**Comment by aquagene** [comment]
Ah, oh well. Consider my request for the gui to show tickthreading info unrequested. Thanks for the hard work dude.
