### ISSUE TITLE
[TT 1538 ] [MCPC+ L22] [SEVERE] [ForgeModLoader] A TileEntity forestry.Grower(forestry.core.gadgets.TileMill) has thrown an exception during loading, its state cannot be restored. Report this to the mod author

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#446]
Getting a load of this in my forgemodloader log but not in the TT log

2013-05-05 21:05:51 [SEVERE] [ForgeModLoader] A TileEntity forestry.Grower(forestry.core.gadgets.TileMill) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException: 1
    at forestry.core.utils.PlainInventory.a(PlainInventory.java:50)
    at forestry.core.utils.GenericInventoryAdapter.readFromNBT(GenericInventoryAdapter.java:314)
    at forestry.cultivation.gadgets.MillGrower.readFromNBT(MillGrower.java:63)
    at forestry.core.gadgets.TileMachine.a(TileMachine.java:214)
    at any.c(TileEntity.java:154)
    at aam.a(ThreadedChunkLoader.java:412)
    at aam.a(ThreadedChunkLoader.java:133)
    at aam.a(ThreadedChunkLoader.java:109)
    at im.f(ThreadedChunkProvider.java:629)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:478)
    at im.getChunkAt(ThreadedChunkProvider.java:452)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:828)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed with #452. If the issue keeps happening, break and replace the block, it was likely corrupted due to that issue.
