### ISSUE TITLE
Unhandled Exception in Worker thread (Build 403)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#45]
01-13 18:59:43 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.lang.NullPointerException
    at ik.b(SourceFile:156)
    at in.b(WorldServer.java:182)
    at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:237)
    at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:265)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)

**Comment by Puremin0rez** [comment]
I should also mention all mobs on the server "freeze" when this happens, which is around 5~ minutes after the server is up.

**Comment by LunNova** [comment]
Sorry, somehow missed this issue. Got another report, and it should be fixed now. Closing this, see #48.
