### ISSUE TITLE
[TT 1539 ] [MCPC+ L22] [SEVERE] [TickThreading] Exception ticking world Nether/-1

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#450]
2013-05-06 01:52:59 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NullPointerException
    at thaumcraft.common.blocks.TileSensor.getNoteBlockEvents_sync0(TileSensor.java:99)
    at thaumcraft.common.blocks.TileSensor.getNoteBlockEvents(TileSensor.java)
    at thaumcraft.common.BETeleporter.a(BETeleporter.java:45)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:405)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:467)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:590)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

**Comment by mainsheep** [comment]
TT1547, MCPC+ L22

2013-05-06 10:41:21 [SEVERE] Exception ticking world Overworld/0
java.lang.NullPointerException
        at yp.getPseudoRandomHeightValue(SpawnerAnimals.java:42)
        at yp.spawnMobsQuickly(SpawnerAnimals.java:167)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:466)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:589)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

**Comment by mainsheep** [comment]
Problem is gone in the previous build 1523.

**Comment by LunNova** [comment]
@mainsheep 
Your issue isn't the same issue as @alicheek posted, yours is issue #451.

**Comment by LunNova** [comment]
Fixed via aba1b194621604fbadd9.
