### ISSUE TITLE
[SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.1 || WorldGuard v5.7.1

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#454]
I've been having these errors from time to time, up through the TT versions. The latest version TT1550 is spamming me with these errors. I never thought they were that important, but since my logs is beeing clogged with these messages now, I'm hoping you have a solution.

I have set both options to false in TT.cfg for GP to work from earlier.

[SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at aky.b(BlockFlowing.java:220)
        at ace.a(WorldGenLiquids.java:81)
        at twilightforest.biomes.TFBiomeDecorator.decorateUnderground(TFBiomeDecorator.java:207)
        at twilightforest.biomes.TFBiomeDecorator.a(TFBiomeDecorator.java:99)
        at yy.a(BiomeGenBase.java:366)
        at twilightforest.world.ChunkProviderTwilightForest.a(ChunkProviderTwilightForest.java:927)
        at im.populate(ThreadedChunkProvider.java:685)
        at im.tryPopulateChunks(ThreadedChunkProvider.java:578)
        at im.getChunkAtInternal(ThreadedChunkProvider.java:550)
        at im.getChunkAt(ThreadedChunkProvider.java:452)
        at im.c(ThreadedChunkProvider.java:395)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getChunkAt(CraftWorld.java:200)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:161)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:169)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:165)
        at org.bukkit.event.block.BlockFromToEvent.getToBlock(BlockFromToEvent.java:49)
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at aky.b(BlockFlowing.java:220)
        at in.run(WorldServer.java:587)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:161)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:169)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:165)
        at org.bukkit.event.block.BlockFromToEvent.getToBlock(BlockFromToEvent.java:49)
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        ... 32 more

2013-05-06 17:48:37 [SEVERE] Could not pass event BlockFromToEvent to WorldGuard v5.7.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at aky.b(BlockFlowing.java:220)
        at ace.a(WorldGenLiquids.java:81)
        at twilightforest.biomes.TFBiomeDecorator.decorateUnderground(TFBiomeDecorator.java:207)
        at twilightforest.biomes.TFBiomeDecorator.a(TFBiomeDecorator.java:99)
        at yy.a(BiomeGenBase.java:366)
        at twilightforest.world.ChunkProviderTwilightForest.a(ChunkProviderTwilightForest.java:927)
        at im.populate(ThreadedChunkProvider.java:685)
        at im.tryPopulateChunks(ThreadedChunkProvider.java:578)
        at im.getChunkAtInternal(ThreadedChunkProvider.java:550)
        at im.getChunkAt(ThreadedChunkProvider.java:452)
        at im.c(ThreadedChunkProvider.java:395)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getChunkAt(CraftWorld.java:200)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:161)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:169)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:165)
        at org.bukkit.event.block.BlockFromToEvent.getToBlock(BlockFromToEvent.java:49)
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at aky.b(BlockFlowing.java:220)
        at in.run(WorldServer.java:587)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:161)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:169)
        at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:165)
        at org.bukkit.event.block.BlockFromToEvent.getToBlock(BlockFromToEvent.java:49)
        at com.sk89q.worldguard.bukkit.WorldGuardBlockListener.onBlockFromTo(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        ... 32 more

Thank you.

**Comment by LunNova** [comment]
Occurs during worldgen. Waiting for a javassist issue to be fixed before I can patch this sensibly.

**Comment by joey19982** [comment]
This appears to still be happening in TT1560 and MCPC-L22

**Comment by LunNova** [comment]
@joey19982 Could you paste the exception? Might be a different issue.

**Comment by joey19982** [comment]
@nallar 

This probably is a different issue, I was about to make a new one when I saw you replied here. When going to the nether either by /tpx or a portal, the server deadlocks. A few chunks will load and then the deadlock message will appear. This is the exception that starts when going to the nether then spams until the server stops, similar to the one in this issue.

2013-05-07 13:52:20 [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at aky.b(BlockFlowing.java:220)
    at abr.a(WorldGenHellLava.java:87)
    at aax.a(ChunkProviderHell.java:490)
    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
    at im.populate(ThreadedChunkProvider.java:692)
    at im.tryPopulateChunks(ThreadedChunkProvider.java:585)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:557)
    at im.getChunkAt(ThreadedChunkProvider.java:459)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:835)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:161)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:169)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.getRelative(CraftBlock.java:165)
    at org.bukkit.event.block.BlockFromToEvent.getToBlock(BlockFromToEvent.java:49)
    at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
    ... 16 more

Resetting the nether produces the same thing.

**Comment by joey19982** [comment]
The error is gone, but nether crash still occurs.

**Comment by LunNova** [comment]
Make a new issue with the deadlock detector report.

**Comment by joey19982** [comment]
Went to do that, then found it hard to do because of #460 

I'll downgrade in a few minutes since this wasn't happening until recently.

EDIT: Appears that #460 is the error it gives when crashing the nether. Will update there.
EDIT2: Nether issue was being caused by MCPC+ L22. Downgraded to L15 and all is well with the nether, however #460  is still happening.
