### ISSUE TITLE
AE Crashes Daily - at appeng.me.tile.TileController.g(TileController.java:1024)

### ISSUE THREAD

**Issue by xKillerbees** [MinimallyCorrect/TickThreading#455]
java.lang.NullPointerException
    at appeng.me.tile.TileController.g(TileController.java:1024)
    at yc.h(World.java:2597)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:956)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
    at fy.run(ThreadMinecraftServer.java:16)

http://pastebin.com/dGEmijK4

This happens several times a day. Using 1.4.7 MCPC+, on build L16 since the official 22 was causing much rage from railcraft tanks.

**Comment by LunNova** [comment]
I htink you opened an issue on the wrong project... :s

**Comment by xKillerbees** [comment]
Ha, it all looks the same to me. My bad.
