### ISSUE TITLE
TT1554 / MCPC L22  - Nuke Failed to Explod

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#457]
Here you go

2013-05-06 22:24:18 [SEVERE] [TickThreading] Exception ticking entity EntityNuke['entity.IC2.Nuke.name'/1088087, l='world_myst/age463', x=233.48, y=73.49, z=-182.70] in rX: 14, rZ: -11, hashCode: -720882/Main #2/463:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at ic2.core.ExplosionIC2.shootRay(ExplosionIC2.java:316)
    at ic2.core.ExplosionIC2.doExplosion(ExplosionIC2.java:175)
    at ic2.core.block.EntityIC2Explosive.explode(EntityIC2Explosive.java:134)
    at ic2.core.block.EntityIC2Explosive.j_(EntityIC2Explosive.java:120)
    at yc.a(World.java:366)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:49)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

**Comment by LunNova** [comment]
There is another issue which could cause this, which is a bug in IC2 without TT.

If there are entities within range of a nuke, but none of the entities are items or instances of EntityLiving (normal mobs and players) then this will happen.

**Comment by LunNova** [comment]
Confirmed as an IC2 issue.

> &lt;nallar&gt; Player, ExplosionIC2.doExplosion throws an AIOOBE at ic2.core.ExplosionIC2.shootRay(ExplosionIC2.java:316) if there are entities in range, but none are instances of EntityLiving/EntityItem.  
> &lt;Player&gt; fixed, ty
