### ISSUE TITLE
TT1554 / MCPC L22 - Age Memory Leak Detected

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#458]
2013-05-06 22:21:38 [WARNING] [TickThreading] Probable memory leak detected. "Age 518/518 : class ih@1178231178:-92011965542456456" has not been garbage collected after 1200s.

After this happened no one was no longer able to get back to that age  it appears

013-05-06 22:23:21 [INFO] [TickThreading] Threading initialised for world Age 518/518
2013-05-06 22:24:18 [SEVERE] [TickThreading] Exception ticking entity EntityNuke['entity.IC2.Nuke.name'/1088087, l='world_myst/age463', x=233.48, y=73.49, z=-182.70] in rX: 14, rZ: -11, hashCode: -720882/Main #2/463:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at ic2.core.ExplosionIC2.shootRay(ExplosionIC2.java:316)
    at ic2.core.ExplosionIC2.doExplosion(ExplosionIC2.java:175)
    at ic2.core.block.EntityIC2Explosive.explode(EntityIC2Explosive.java:134)
    at ic2.core.block.EntityIC2Explosive.j_(EntityIC2Explosive.java:120)
    at yc.a(World.java:366)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:49)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
2013-05-06 22:24:21 [INFO] [TickThreading] Threading initialised for world Age 518/518
2013-05-06 22:24:21 [SEVERE] [TickThreading] Not sent WorldEvent.Load for loaded world Age 518/518, sending it now.
2013-05-06 22:24:21 [INFO] [TickThreading] Threading initialised for world Age 518/518
2013-05-06 22:24:21 [SEVERE] [TickThreading] World ih@6d112fd9's world load event was fired twice.
java.lang.Throwable
    at me.nallar.tickthreading.minecraft.TickThreading.onWorldLoad(TickThreading.java:195)
    at net.minecraftforge.event.ASMEventHandler_181_TickThreading_onWorldLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:460)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:604)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

**Comment by LunNova** [comment]
There's not really much I can do to fix the leak, it's a warning used primarily when debugging. If you're running with cleanWorlds enabled it's probably not an issue, as the leaked memory will only be ~400 bytes.

The IC2 issue is already reported in #457.

Fixed handling of load/unload events in fddd84bee4ed940808.
