### ISSUE TITLE
[TT1560+] Exception ticking TileEntity c * - NullPointerException/IllegalMonitorStateException Log Spam

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#460]
In ForgeModLoader-server.0.log, this is being spammed constantly, filling up the log a ton.

2013-05-07 15:27:52 [SEVERE] [TickThreading] Exception ticking TileEntity c dan200.turtle.shared.RedPowerTileEntityTurtle dan200.turtle.shared.RedPowerTileEntityTurtle@117a57d x,y,z: -352, 12, -282 at x,y,z:-352,12,-282
 World: Overworld/0
java.lang.NullPointerException
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:86)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
2013-05-07 15:27:52 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 4
java.lang.IllegalMonitorStateException
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:117)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
2013-05-07 15:27:52 [SEVERE] [TickThreading] Exception ticking TileEntity c dan200.turtle.shared.RedPowerTileEntityTurtle dan200.turtle.shared.RedPowerTileEntityTurtle@117a57d x,y,z: -352, 12, -282 at x,y,z:-352,12,-282
 World: Overworld/0
java.lang.NullPointerException
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:86)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
2013-05-07 15:27:52 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 5
java.lang.IllegalMonitorStateException
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:117)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
2013-05-07 15:27:53 [SEVERE] [TickThreading] Exception ticking TileEntity c dan200.turtle.shared.RedPowerTileEntityTurtle dan200.turtle.shared.RedPowerTileEntityTurtle@117a57d x,y,z: -352, 12, -282 at x,y,z:-352,12,-282
 World: Overworld/0
java.lang.NullPointerException
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:86)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

Same error also fills up the TT logs.

**Comment by joey19982** [comment]
Trying to figure out what causes this to start. It doesn't happen immediately and hard to track with 60 people doing 60 different things.

**Comment by LunNova** [comment]
That fix won't work.

**Comment by LunNova** [comment]
I need to go read the JVM spec, it is likely that latest is still broken.
