### ISSUE TITLE
Error Message with #1570

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#461]
2013-05-07 18:03:11 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoSuchFieldError
java.lang.NoSuchFieldError: forcedChunks
    at net.minecraftforge.common.ForgeChunkManager.staticConstruct(ForgeChunkManager.java:30)
    at net.minecraftforge.common.ForgeChunkManager.<clinit>(ForgeChunkManager.java:101)
    at net.minecraftforge.common.ForgeDummyContainer.preInit(ForgeDummyContainer.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:505)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:86)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:157)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by alicheek** [comment]
yea L23 and TT aren't compatible give nallar tomoz to fix it and he will :)
