### ISSUE TITLE
Patching issues

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#464]
2013-05-08 23:10:26 [SEVERE] [TickThreading] Unhandled patching failure
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(Unknown Source)
    at javassist.ClassPool.createCtClass(ClassPool.java:563)
    at javassist.ClassPool.get0(ClassPool.java:539)
    at javassist.ClassPool.get(ClassPool.java:447)
    at me.nallar.tickthreading.patcher.ClassRegistry.getClass(ClassRegistry.java:178)
    at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:208)
    at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:106)
    at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:31)

**Comment by alicheek** [comment]
yea im getting this too
