### ISSUE TITLE
TT 1582 / MCPC L22 place tile where there is no tile

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#469]
It isn't showing up in the TT Logs but this is the first time i seen them since upgrading. Had to grab them via threw server.log - Could this be because I am running on L22 as well as I know alot of changes was done on L23

2013-05-08 15:30:08 [INFO] Attempted to place a tile entity (jds.bibliocraft.tileentities.TileEntityArmorStand@50d10edb x,y,z: 398, 64, -2755) at 398,64,-2755 (BIBLIOCRAFT_ARMOR_STAND) where there was no entity tile!
2013-05-08 15:30:08 [INFO] Chunk coordinates: 384,-2768
2013-05-08 15:30:08 [SEVERE] java.lang.Exception
2013-05-08 15:30:08 [SEVERE]    at zz.a(Chunk.java:1089)
2013-05-08 15:30:08 [SEVERE]    at yc.a(World.java:3291)
2013-05-08 15:30:08 [SEVERE]    at akb.g(BlockContainer.java:27)
2013-05-08 15:30:08 [SEVERE]    at zz.a(Chunk.java:406)
2013-05-08 15:30:08 [SEVERE]    at yc.a(World.java:762)
2013-05-08 15:30:08 [SEVERE]    at yc.c(World.java:740)
2013-05-08 15:30:08 [SEVERE]    at jds.bibliocraft.blocks.BlockArmorStand.a(BlockArmorStand.java:158)
2013-05-08 15:30:08 [SEVERE]    at vq.placeBlockAt(ItemBlock.java:268)
2013-05-08 15:30:08 [SEVERE]    at vq.a(ItemBlock.java:106)
2013-05-08 15:30:08 [SEVERE]    at ur.a(ItemStack.java:135)
2013-05-08 15:30:08 [SEVERE]    at ir.a(ItemInWorldManager.java:580)
2013-05-08 15:30:08 [SEVERE]    at iv.a(NetServerHandler.java:906)
2013-05-08 15:30:08 [SEVERE]    at fk.a(Packet15Place.java:79)
2013-05-08 15:30:08 [SEVERE]    at cg.b(TcpConnection.java:467)
2013-05-08 15:30:08 [SEVERE]    at iv.d(NetServerHandler.java:220)
2013-05-08 15:30:08 [SEVERE]    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
2013-05-08 15:30:08 [SEVERE]    at iw.b(NetworkListenThread.java)
2013-05-08 15:30:08 [SEVERE]    at ht.b(DedicatedServerListenThread.java:34)
2013-05-08 15:30:08 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:393)
2013-05-08 15:30:08 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-05-08 15:30:08 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:279)
2013-05-08 15:30:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:185)
2013-05-08 15:30:08 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

2013-05-08 15:30:08 [INFO] Attempted to place a tile entity (jds.bibliocraft.tileentities.TileEntityArmorStand@39444a47 x,y,z: 398, 64, -2755) at 398,64,-2755 (BIBLIOCRAFT_ARMOR_STAND) where there was no entity tile!
2013-05-08 15:30:08 [INFO] Chunk coordinates: 384,-2768
2013-05-08 15:30:08 [SEVERE] java.lang.Exception
2013-05-08 15:30:08 [SEVERE]    at zz.a(Chunk.java:1089)
2013-05-08 15:30:08 [SEVERE]    at yc.a(World.java:3291)
2013-05-08 15:30:08 [SEVERE]    at akb.g(BlockContainer.java:27)
2013-05-08 15:30:08 [SEVERE]    at zz.a(Chunk.java:406)
2013-05-08 15:30:08 [SEVERE]    at yc.a(World.java:762)
2013-05-08 15:30:08 [SEVERE]    at yc.c(World.java:740)
2013-05-08 15:30:08 [SEVERE]    at jds.bibliocraft.blocks.BlockArmorStand.a(BlockArmorStand.java:158)
2013-05-08 15:30:08 [SEVERE]    at vq.placeBlockAt(ItemBlock.java:268)
2013-05-08 15:30:08 [SEVERE]    at yc.a(World.java:4358)
2013-05-08 15:30:08 [SEVERE]    at vq.a(ItemBlock.java:98)
2013-05-08 15:30:08 [SEVERE]    at ur.a(ItemStack.java:135)
2013-05-08 15:30:08 [SEVERE]    at ir.a(ItemInWorldManager.java:580)
2013-05-08 15:30:08 [SEVERE]    at iv.a(NetServerHandler.java:906)
2013-05-08 15:30:08 [SEVERE]    at fk.a(Packet15Place.java:79)
2013-05-08 15:30:08 [SEVERE]    at cg.b(TcpConnection.java:467)
2013-05-08 15:30:08 [SEVERE]    at iv.d(NetServerHandler.java:220)
2013-05-08 15:30:08 [SEVERE]    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
2013-05-08 15:30:08 [SEVERE]    at iw.b(NetworkListenThread.java)
2013-05-08 15:30:08 [SEVERE]    at ht.b(DedicatedServerListenThread.java:34)
2013-05-08 15:30:08 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:393)
2013-05-08 15:30:08 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-05-08 15:30:08 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:279)
2013-05-08 15:30:08 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:185)
2013-05-08 15:30:08 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

ere there was no entity tile!
2013-05-08 15:29:30 [INFO] Chunk coordinates: 384,-2768
2013-05-08 15:29:30 [SEVERE] java.lang.Exception
2013-05-08 15:29:30 [SEVERE]    at zz.a(Chunk.java:1089)
2013-05-08 15:29:30 [SEVERE]    at yc.a(World.java:3291)
2013-05-08 15:29:30 [SEVERE]    at akb.g(BlockContainer.java:27)
2013-05-08 15:29:30 [SEVERE]    at zz.a(Chunk.java:406)
2013-05-08 15:29:30 [SEVERE]    at yc.a(World.java:762)
2013-05-08 15:29:30 [SEVERE]    at yc.c(World.java:740)
2013-05-08 15:29:30 [SEVERE]    at jds.bibliocraft.blocks.BlockArmorStand.a(BlockArmorStand.java:158)
2013-05-08 15:29:30 [SEVERE]    at vq.placeBlockAt(ItemBlock.java:268)
2013-05-08 15:29:30 [SEVERE]    at vq.a(ItemBlock.java:106)
2013-05-08 15:29:30 [SEVERE]    at ur.a(ItemStack.java:135)
2013-05-08 15:29:30 [SEVERE]    at ir.a(ItemInWorldManager.java:580)
2013-05-08 15:29:30 [SEVERE]    at iv.a(NetServerHandler.java:906)
2013-05-08 15:29:30 [SEVERE]    at fk.a(Packet15Place.java:79)
2013-05-08 15:29:30 [SEVERE]    at cg.b(TcpConnection.java:467)
2013-05-08 15:29:30 [SEVERE]    at iv.d(NetServerHandler.java:220)
2013-05-08 15:29:30 [SEVERE]    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
2013-05-08 15:29:30 [SEVERE]    at iw.b(NetworkListenThread.java)
2013-05-08 15:29:30 [SEVERE]    at ht.b(DedicatedServerListenThread.java:34)
2013-05-08 15:29:30 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:393)
2013-05-08 15:29:30 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-05-08 15:29:30 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:279)
2013-05-08 15:29:30 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:185)
2013-05-08 15:29:30 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
This is an MCPC+ issue. iirc you can disable it in bukkit.yml, although that might only be on 1.5.
