### ISSUE TITLE
[TT 1585] [MCPC+ L23] [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#473]
No idea if its causing any issues most probably not at least noticeably but there are the error logs:

2013-05-09 00:25:22 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
    at aky.b(BlockFlowing.java:62)
    at add.a(ComponentNetherBridgeEntrance.java:118)
    at afb.a(StructureStart.java:35)
    at aev.a(MapGenStructure.java:71)
    at aax.a(ChunkProviderHell.java:478)
    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
    at im.populate(ThreadedChunkProvider.java:698)
    at im.tryPopulateChunks(ThreadedChunkProvider.java:591)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:563)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-09 00:25:22 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
    at aky.b(BlockFlowing.java:62)
    at add.a(ComponentNetherBridgeEntrance.java:118)
    at afb.a(StructureStart.java:35)
    at aev.a(MapGenStructure.java:71)
    at aax.a(ChunkProviderHell.java:478)
    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
    at im.populate(ThreadedChunkProvider.java:698)
    at im.tryPopulateChunks(ThreadedChunkProvider.java:591)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:563)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-09 00:25:23 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
    at aky.b(BlockFlowing.java:62)
    at add.a(ComponentNetherBridgeEntrance.java:118)
    at afb.a(StructureStart.java:35)
    at aev.a(MapGenStructure.java:71)
    at aax.a(ChunkProviderHell.java:478)
    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
    at im.populate(ThreadedChunkProvider.java:698)
    at im.tryPopulateChunks(ThreadedChunkProvider.java:591)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:563)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-09 00:25:23 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
    at aky.b(BlockFlowing.java:62)
    at add.a(ComponentNetherBridgeEntrance.java:118)
    at afb.a(StructureStart.java:35)
    at aev.a(MapGenStructure.java:71)
    at aax.a(ChunkProviderHell.java:478)
    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
    at im.populate(ThreadedChunkProvider.java:698)
    at im.tryPopulateChunks(ThreadedChunkProvider.java:591)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:563)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Still happening? Should be fixed.
