### ISSUE TITLE
TT patch and AE. Method not found ? 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#475]
2013-05-09 18:47:04 [WARNING] [TickThreading] 
java.lang.RuntimeException: Method not found: g() was not found in appeng.me.basetiles.TileME
at me.nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:317)
at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:222)
at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:106)
at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:31)

2013-05-09 18:47:04 [WARNING] [TickThreading] 
java.lang.RuntimeException: Method not found: resetCache() was not found in appeng.me.tile.TileController
at me.nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:317)
at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:222)
at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:106)
at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:31)
2013-05-09 18:47:04 [WARNING] [TickThreading] Method: appeng.me.tile.TileController.g() is already synchronized

2013-05-09 18:47:04 [WARNING] [TickThreading] 
java.lang.RuntimeException: Method not found: resetCache() was not found in appeng.me.tile.TileStorageBus
at me.nallar.tickthreading.mappings.MethodDescription.inClass(MethodDescription.java:109)
at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:317)
at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:222)
at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:106)
at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:31)

i'm the only one who is getting this ? is it normal ?

**Comment by Nohau** [comment]
No I get this as well but thought it was normal this is during the patch process right your talking about.

**Comment by Nohau** [comment]
Posting Patcher Log just in case as there is a few warnings but figured since it is patching multiple things may have changed or versions may have changed which may cause this like in most patch programs or may not have that mod which all give different types of errrors.

https://gist.github.com/Nohau/5558631

**Comment by HaoSs07** [comment]
what ftb pack do you use ?

**Comment by Nohau** [comment]
Ultimate 1.0.1 but remember they have done several "silent updates" to ultimate which means your pack might not be the same as mine even though the same version ... :(

**Comment by LunNova** [comment]
The second two warnings are fine, the first was a bug, and that may be why the AE fix didn't work correctly. #246 may finally be fixed now?

**Comment by HaoSs07** [comment]
yah. was about to report the second 2. good you posted this first. 
i'm also retesting the 246 fix. will replay there
