### ISSUE TITLE
mmm Randomly Crashing again..

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#479]
2013-05-10 09:35:18 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-05-10 09:35:28 [INFO] [TickThreading] Threading initialised for world Overworld/0
2013-05-10 09:35:28 [INFO] [TickThreading] Threading initialised for world The End/1
2013-05-10 09:35:28 [INFO] [TickThreading] Threading initialised for world Nether/-1
2013-05-10 09:35:33 [SEVERE] [TickThreading] TickThreading v1.0.0.1589 for MC1.4.7 on 1.4.7 tickthreading,mcpc,spigot,craftbukkit,forge,fml is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading
2013-05-10 10:52:43 [SEVERE] [TickThreading] Exception ticking TileEntity c mekanism.common.TileEntitySmeltingFactory mekanism.common.TileEntitySmeltingFactory@47736493 x,y,z: 1013, 64, 4367 at x,y,z:1013,64,4367
 World: Overworld/0
java.lang.NullPointerException
    at mekanism.common.TileEntitySmeltingFactory.onUpdate(TileEntitySmeltingFactory.java:136)
    at mekanism.common.TileEntityBasicBlock.g(TileEntityBasicBlock.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:104)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)
2013-05-10 12:09:12 [SEVERE] [TickThreading] The server appears to have deadlocked.
Last tick 46s ago.
Waiting ThreadManagers: Entities in Nether/-1, World Tick

"Async ChunkLoader" TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6f9c7571
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6f9c7571
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
    at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

"Connection #109 read thread", "Connection #11 read thread", "Connection #30 read thread", "Connection #383 read thread", "Connection #543 read thread", "Connection #637 read thread", "Connection #659 read thread", "Connection #686 read thread", "Connection #690 read thread", "Connection #692 read thread", "Connection #717 read thread", "Connection #721 read thread", "Connection #725 read thread", "Connection #732 read thread", "Connection #770 read thread", "Connection #811 read thread", "Connection #833 read thread", "Connection #853 read thread", "Connection #862 read thread", "Connection #867 read thread", "Connection #874 read thread", "Connection #882 read thread", "Connection #886 read thread" RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
    at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at ef.a(Packet.java:150)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:24)

"Connection #109 write thread", "Connection #11 write thread", "Connection #30 write thread", "Connection #383 write thread", "Connection #543 write thread", "Connection #637 write thread", "Connection #659 write thread", "Connection #686 write thread", "Connection #690 write thread", "Connection #692 write thread", "Connection #717 write thread", "Connection #721 write thread", "Connection #725 write thread", "Connection #732 write thread", "Connection #770 write thread", "Connection #811 write thread", "Connection #833 write thread", "Connection #853 write thread", "Connection #859 write thread", "Connection #862 write thread", "Connection #867 write thread", "Connection #874 write thread", "Connection #882 write thread", "Connection #886 write thread", "Connection #897 write thread", "Connection #898 write thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at ci.run(TcpWriterThread.java:49)

"Connection #859 read thread" BLOCKED on iv@52a3010d owned by "Entities in Nether/-1 - 7" Id=80
    at eb.a(Packet10Flying.java:45)
    -  blocked on iv@52a3010d
    at cg.i(TcpConnection.java:348)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:24)

"Connection #897 read thread", "Connection #898 read thread" RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at java.net.SocketInputStream.read(SocketInputStream.java:203)
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at ef.a(Packet.java:150)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:24)

"Deadlock Detector" RUNNABLE
    at sun.management.ThreadImpl.dumpThreads0(Native Method)
    at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
    at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:120)
    at me.nallar.tickthreading.minecraft.DeadLockDetector$1.run(DeadLockDetector.java:39)
    at java.lang.Thread.run(Thread.java:722)

"DestroyJavaVM", "Signal Dispatcher" RUNNABLE

"Entities in Nether/-1 - 7" WAITING on me.nallar.tickthreading.util.concurrent.TwoWayReentrantReadWriteLock@792e7b40
    at java.lang.Object.wait(Native Method)
    -  waiting on me.nallar.tickthreading.util.concurrent.TwoWayReentrantReadWriteLock@792e7b40
    at java.lang.Object.wait(Object.java:503)
    at me.nallar.tickthreading.util.concurrent.TwoWayReentrantReadWriteLock.lockWrite(TwoWayReentrantReadWriteLock.java:88)
    at me.nallar.tickthreading.util.concurrent.TwoWayReentrantReadWriteLock$2.lock(TwoWayReentrantReadWriteLock.java:30)
    at me.nallar.tickthreading.collections.LockArrayList.remove(LockArrayList.java:24)
    at universalelectricity.core.electricity.ElectricityNetwork.cleanConductors(ElectricityNetwork.java:295)
    at universalelectricity.core.electricity.Electricity.splitConnection(Electricity.java:87)
    -  locked universalelectricity.core.electricity.Electricity@e246c00
    at electricexpansion.common.helpers.TileEntityConductorBase.updateConnection(TileEntityConductorBase.java:180)
    at universalelectricity.prefab.tile.TileEntityConductor.refreshConnectedBlocks(TileEntityConductor.java:186)
    at universalelectricity.prefab.BlockConductor.a(BlockConductor.java:49)
    at yc.m(World.java:293)
    at yc.h(World.java:1066)
    at yc.f(World.java:1010)
    at yc.e(World.java:968)
    at amq.removeBlockByPlayer(Block.java:1577)
    at ir.d(ItemInWorldManager.java:345)
    at ir.b(ItemInWorldManager.java:466)
    at ir.a(ItemInWorldManager.java:135)
    at iq.j_(EntityPlayerMP.java:20)
    at yc.a(World.java:367)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2708)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:52)
    -  locked iv@52a3010d
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

"File IO Thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at aiw.b(ThreadedFileIOBase.java:61)
    at aiw.run(ThreadedFileIOBase.java:27)
    at java.lang.Thread.run(Thread.java:722)

"Finalizer" WAITING on java.lang.ref.ReferenceQueue$Lock@6fb16f41
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.ref.ReferenceQueue$Lock@6fb16f41
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:177)

"Keep-Alive-SocketCleaner" WAITING on sun.net.www.http.KeepAliveStreamCleaner@2b96a6b8
    at java.lang.Object.wait(Native Method)
    -  waiting on sun.net.www.http.KeepAliveStreamCleaner@2b96a6b8
    at sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:101)
    at java.lang.Thread.run(Thread.java:722)

"Leak Detector" WAITING on java.util.TaskQueue@35088266
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@35088266
    at java.lang.Object.wait(Object.java:503)
    at java.util.TimerThread.mainLoop(Timer.java:526)
    at java.util.TimerThread.run(Timer.java:505)

"Listen thread" RUNNABLE
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:522)
    at java.net.ServerSocket.accept(ServerSocket.java:490)
    at hu.run(ServerListenThread.java:83)

"NPC Manager read thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at ch.run(ReplaceTcpReaderThread.java:26)

"Reference Handler" WAITING on java.lang.ref.Reference$Lock@69ff4db0
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.ref.Reference$Lock@69ff4db0
    at java.lang.Object.wait(Object.java:503)
    at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)

"Server thread" TIMED_WAITING on java.lang.Object@4acf8c0a
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.Object@4acf8c0a
    at me.nallar.tickthreading.minecraft.ThreadManager.waitForCompletion(ThreadManager.java:79)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:388)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:185)
    at fy.run(ThreadMinecraftServer.java:16)

"Snooper Timer" TIMED_WAITING on java.util.TaskQueue@7ff30ae4
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@7ff30ae4
    at java.util.TimerThread.mainLoop(Timer.java:552)
    at java.util.TimerThread.run(Timer.java:505)

"Spigot Metrics Gathering Thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at org.bukkit.craftbukkit.v1_4_R1.util.TimedThread.run(TimedThread.java:29)

"Thread-1" WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2d50405c
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2d50405c
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at cpw.mods.fml.relauncher.FMLRelaunchLog$ConsoleLogThread.run(FMLRelaunchLog.java:68)
    at java.lang.Thread.run(Thread.java:722)

"Thread-14" RUNNABLE (in native)
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:522)
    at java.net.ServerSocket.accept(ServerSocket.java:490)
    at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:114)

"Thread-22" RUNNABLE
    at java.net.PlainDatagramSocketImpl.peekData(Native Method)
    -  locked java.net.PlainDatagramSocketImpl@7b42539a
    at java.net.DatagramSocket.receive(DatagramSocket.java:726)
    -  locked java.net.DatagramPacket@23542e13
    -  locked java.net.DatagramSocket@e2e1db8
    at jb.run(RConThreadQuery.java:317)
    at java.lang.Thread.run(Thread.java:722)

"Thread-6" RUNNABLE (in native)
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:242)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
    -  locked java.io.BufferedInputStream@41a911bd
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167)
    at org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267)
    -  locked org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1@42cbb0f8
    at org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204)
    -  locked org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1@42cbb0f8
    at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995)
    at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167)
    at hq.run(DedicatedServerCommandThread.java:37)

"Timer-0" TIMED_WAITING on java.util.TaskQueue@d3754a7
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@d3754a7
    at java.util.TimerThread.mainLoop(Timer.java:552)
    at java.util.TimerThread.run(Timer.java:505)

"World Tick - 5" TIMED_WAITING on java.lang.Object@500a8508
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.Object@500a8508
    at me.nallar.tickthreading.minecraft.ThreadManager.waitForCompletion(ThreadManager.java:79)
    at me.nallar.tickthreading.minecraft.TickManager.doTick(TickManager.java:517)
    at yc.h_net_minecraft_world_World_updateEntities_p0(World.java:725)
    at yc.h(World.java)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:487)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:608)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

"com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0", "com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1", "com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2" TIMED_WAITING on com.mchange.v2.async.ThreadPoolAsynchronousRunner@6b9cf383
    at java.lang.Object.wait(Native Method)
    -  waiting on com.mchange.v2.async.ThreadPoolAsynchronousRunner@6b9cf383
    at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:534)

"pool-1-thread-101" TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4b9a26dd
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4b9a26dd
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
    at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
    at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

"pool-2-thread-1" TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f9b9063
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f9b9063
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090)
    at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

"process reaper" TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@756d9df1
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@756d9df1
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
    at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
    at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

2013-05-10 12:09:14 [INFO] [TickThreading] Attempting to save
2013-05-10 12:09:20 [INFO] [TickThreading] Saved, now attempting to stop the server and disconnect players cleanly
2013-05-10 12:09:29 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at net.minecraft.server.MinecraftServer.n(MinecraftServer.java:100)
    at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:202)
    at me.nallar.tickthreading.minecraft.DeadLockDetector$1.run(DeadLockDetector.java:39)
    at java.lang.Thread.run(Thread.java:722)
2013-05-10 12:09:30 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:29)
    at java.lang.Runtime.exit(Runtime.java:105)
    at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:205)
    at me.nallar.tickthreading.minecraft.DeadLockDetector$1.run(DeadLockDetector.java:39)
    at java.lang.Thread.run(Thread.java:722)
Using Latest and greatest #1589

**Comment by LunNova** [comment]
The UE API is a badly designed mess composed almost entirely of lists. Yes, I'm being harsh about it, but it's almost impossible to make threadsafe.

I'll fix this when I have time, but it's undoubtedly going to be a huge pain.

**Comment by JohnPark234** [comment]
damn... freaking UE... honestly waiting for an update heard they re-did most of UE

**Comment by mainsheep** [comment]
UE?
