### ISSUE TITLE
Unhandled Exception handled in workerthread spam - Console

### ISSUE THREAD

**Issue by Nessiroj** [MinimallyCorrect/TickThreading#48]
Build 290
Nothing to see in the serverlog (cause it hasn't crashed yet) CPU and Mem usage are going wacky atm (both 100%). and the following error just keeps getting spamming in my FML logfile:

2013-01-14 19:30:34 [SEVERE] [TickThreading] Unhandled exception in worker thread
t: Exception ticking world
    at net.minecraft.server.MinecraftServer.tickWorld(MinecraftServer.java:142)
    at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:175)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:40)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:140)
Caused by: java.lang.NullPointerException
    at im.b(ChunkProviderServer.java:327)
    at in.b(WorldServer.java:166)
    at net.minecraft.server.MinecraftServer.tickWorld(MinecraftServer.java:138)
    ... 3 more

Link to github paste since pastbin is down :( of the FML log:https://gist.github.com/4532361
Removed the spam of the above error since it was otherwise to big for pastebin ;)
Below a screenshot of the console, it just keeps spamming the same error.

![consolespam](https://f.cloud.github.com/assets/3266883/65410/fc106d64-5e7a-11e2-9526-4377ae650881.png)

**Comment by LunNova** [comment]
This should be fixed in 349f65b2e56c8a9. Close this if the error doesn't happen again.

**Comment by Nessiroj** [comment]
Installed .405 build. so far 1 hour uptime of the server no error yet, and it feels more stable then before. Will see how it goes overnight

**Comment by Nessiroj** [comment]
4 hours uptime no problems so far, we even stresstested the server for 3 hours under full load (lag ftw but it was for a good cause) so far i love the .405 build
