### ISSUE TITLE
console spam, ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#482]
2013-05-11 19:42:54 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:54 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:54 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:54 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:55 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:55 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:55 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:55 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:55 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:56 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:56 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:56 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:56 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)
at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:380)
at in.b(WorldServer.java)
at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:485)
at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:609)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-11 19:42:56 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.ArrayIndexOutOfBoundsException: 0
at me.nallar.tickthreading.collections.LongList.add(LongList.java:25)
at yp.spawnMobsQuickly(SpawnerAnimals.java:138)

**Comment by LunNova** [comment]
Which build is this on? Should already be fixed in 1598.

**Comment by HaoSs07** [comment]
1597, i will update now
