### ISSUE TITLE
Issue with a plugin? Anti Relog

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#488]
2013-05-12 15:48:09 [SEVERE] java.lang.NumberFormatException: For input string: "AntiRelog v25"
2013-05-12 15:48:09 [SEVERE]    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2013-05-12 15:48:09 [SEVERE]    at java.lang.Integer.parseInt(Integer.java:492)
2013-05-12 15:48:09 [SEVERE]    at java.lang.Integer.parseInt(Integer.java:527)
2013-05-12 15:48:09 [SEVERE]    at com.github.r0306.AntiRelog.Util.Util.updateAvaliable(Util.java:166)
2013-05-12 15:48:09 [SEVERE]    at com.github.r0306.AntiRelog.AntiRelog$1.run(AntiRelog.java:166)
2013-05-12 15:48:09 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
2013-05-12 15:48:09 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
2013-05-12 15:48:09 [SEVERE]    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
2013-05-12 15:48:09 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:336)
2013-05-12 15:48:09 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-05-12 15:48:09 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:279)
2013-05-12 15:48:09 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:185)
2013-05-12 15:48:09 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

**Comment by JohnPark234** [comment]
Sorry wrong mod!
