### ISSUE TITLE
[TickThreading] Exception ticking entity!

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#489]
2013-05-12 16:37:51 [SEVERE] [TickThreading] Exception ticking entity EZhaPin['Explosion'/235166, l='world', x=-4320.49, y=18.96, z=5081.17] in rX: -270, rZ: 317, hashCode: 20774642/Overworld/0:
java.lang.ArrayIndexOutOfBoundsException: 128
    at il.a(PlayerInstance.java:126)
    at ik.a(PlayerManager.java:147)
    at ij.a(WorldManager.java:77)
    at in.i(WorldServer.java:613)
    at yc.b(World.java:864)
    at yc.e(World.java:966)
    at universalelectricity.core.vector.Vector3.setBlockWithNotify(Vector3.java:148)
    at icbm.common.zhapin.ex.ExFanWuSu.doBaoZha(ExFanWuSu.java:64)
    at icbm.common.zhapin.ZhaPin.doBaoZha(ZhaPin.java:285)
    at icbm.common.zhapin.EZhaPin.j_(EZhaPin.java:133)
    at yc.a(World.java:375)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2708)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)

**Comment by LunNova** [comment]
Fixed in recent PlayerInstance changes.
