### ISSUE TITLE
[TT #1600, MCPC+ L25] Console spam with Exception ticking TileEntity c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#493]
Spammed about 10 Mb

2013-05-13 00:28:45 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@55ae0215 x,y,z: -1054, 72, -201 at x,y,z:-1054,72,-201
 World: Overworld/0
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.pipes.PipePowerWood.updateEntity(PipePowerWood.java:80)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:104)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:106)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:48)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by NachtRaben** [comment]
Try using MCEdit to remove the pipes at these coors
 x,y,z: -1054, 72, -201 at x,y,z:-1054,72,-201

**Comment by LunNova** [comment]
It looks like a block next to the pipe, a gregtech machine, is broken.

**Comment by wormzjl** [comment]
It's a bit strange since there is no pipe at given coordinate, and these greg machines are not connected to any pipes...

**Comment by LunNova** [comment]
Are you missing a minus when teleporting maybe? Is the issue still happening now? Maybe there's an invisible corrupt pipe there, try using worldedit to clear the exact coordinates shown in the log.

**Comment by wormzjl** [comment]
This issue only happend once, after an automatic reboot it's no longer spamming...

**Comment by Shybella** [comment]
It's something about loaded chunks on startup. I fixed it by unloading chunks on startup with clearlagg.
