### ISSUE TITLE
[TT 1605] [MCPC+ L27] [SEVERE] [TickThreading] Exception ticking world Nether/-1 spam

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#495]
Got about 600kbs of this spam in the tick threading log:

2013-05-14 07:32:29 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at thaumcraft.common.blocks.TileSensor.getNoteBlockEvents_sync0(TileSensor.java:98)
    at thaumcraft.common.blocks.TileSensor.getNoteBlockEvents(TileSensor.java)
    at thaumcraft.common.BETeleporter.a(BETeleporter.java:45)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:406)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:486)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:610)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-14 07:32:38 [SEVERE] [TickThreading] Exception ticking world Nether/-1

**Comment by HaoSs07** [comment]
latest build failed.

**Comment by LunNova** [comment]
Fixed.
