### ISSUE TITLE
[TT 1614] [MCPC+ L28] [SEVERE] [TickThreading] Exception ticking TileEntity c factorization.common.TileEntityBarrel Barrel of 7618 64xtile.stonebrick@0 at x,y,z:183,95,409

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#498]
[SEVERE] [TickThreading] Exception ticking TileEntity c factorization.common.TileEntityBarrel Barrel of 7618 64xtile.stonebrick@0 at x,y,z:183,95,409
 World: Overworld/0
java.lang.NullPointerException
    at factorization.common.TileEntityBarrel.updateStacks(TileEntityBarrel.java:97)
    at factorization.common.TileEntityBarrel.g(TileEntityBarrel.java:506)
    at any.tickTT(TileEntity.java:50)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:103)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:29)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
Issue has not occurred in quite a while so guess is that it is sorted now , will open if I get this error again
