### ISSUE TITLE
Server fails to start "java.lang.ClassFormatError" (Build #215)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#5]
I'm applying this build to FTB MindCrack v6
# 

Exception in thread "main" java.lang.ClassFormatError: Duplicate method name&sig
nature in class file yc
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.getMainMethod(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by Puremin0rez** [comment]
This commit appears to be to blame:
https://github.com/nallar/TickThreading/commit/c3be1caf710d0978a859f35fbed7847270b8a264

**Comment by LunNova** [comment]
Fixed in build 216. Sorry about the delay, I went to sleep shortly after commiting :(

**Comment by Puremin0rez** [comment]
It's fixed :+1:
