### ISSUE TITLE
414

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#50]
2013-01-15 04:01:37 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.remove(HashMap.java:912)
        at codechicken.wirelessredstone.core.RedstoneEtherServer.unloadJammedMap(RedstoneEtherServer.java:652)
        at codechicken.wirelessredstone.core.RedstoneEtherServer.tick(RedstoneEtherServer.java:641)
        at codechicken.wirelessredstone.core.WRCoreEventHandler.tickEnd(WRCoreEventHandler.java:120)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:31)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:50)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:237)
        at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:263)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)
2013-01-15 04:01:37 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.remove(HashMap.java:912)
        at codechicken.wirelessredstone.core.RedstoneEtherServer.unloadJammedMap(RedstoneEtherServer.java:652)
        at codechicken.wirelessredstone.core.RedstoneEtherServer.tick(RedstoneEtherServer.java:641)
        at codechicken.wirelessredstone.core.WRCoreEventHandler.tickEnd(WRCoreEventHandler.java:120)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:31)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:50)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.doTick(MinecraftServer.java:237)
        at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:263)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)

**Comment by LunNova** [comment]
Fixed in f9f3db97ca6024b
