### ISSUE TITLE
Total Server Annihilation? Pretty bad crash.

### ISSUE THREAD

**Issue by NachtRaben** [MinimallyCorrect/TickThreading#502]
So i know no one has posted about this mod on this thread before, but i am running an Ultimate/DivineRPG server, i heard reports of issues with the extra dimmensions added by this mod. I figured it was an issue with the mod and mcpc+, but it wasn't. then noticed the header of the crash was [TickThreading] so i decided to post it on here. Sorry to cause you trouble Nallar.
When this crash started the log file jumped over 200Mb....(Mediafire wouldn't allow me to upload) so if you have any idea how i can get you the log can you help? and here is an image of the realm before the server crashed. (Deadlock didn't work for some odd reason)
![untitled](https://f.cloud.github.com/assets/4164436/515181/71aa5758-be6e-11e2-862b-e271a5f5560a.png)

**Comment by Nohau** [comment]
Since it is text you can zip the file up which will reduce the size dramatically and send it to him via email or post it on a web server that he can download it from just make sure it is zipped :)

**Comment by NachtRaben** [comment]
i figured as much, but whats the email? and will 7-zip be a valid utility or do i have to use winzip?
you can obviously tell somethings broke just by the photo xD

**Comment by NachtRaben** [comment]
Nvmd, found the email.

**Comment by LunNova** [comment]
Looking at the code, I can't see how this is a TT bug!

Can you confirm that it doesn't happen without TT?

Is there some sort of block in that mod which places torches automatically or something? It looks like some invalid torch placement is causing infinite recursion.

**Comment by NachtRaben** [comment]
No blocks placing torches (Other than maybe a dungeon? lemme test it without, i will give you the results. Give me about 10 minutes. I only posted here cause TT is what noticed it first xD nothing in bukkit or even FML.

**Comment by NachtRaben** [comment]
Im laughing my butt off so much right now, i do believe this is acctually a mod incompatability as i was able to recreate the issue without TT and that this time i get Shrooms and torches :)
![untitled2](https://f.cloud.github.com/assets/4164436/515509/2896149e-be78-11e2-96c4-724dde91cc3b.png)

as for the exception (Caught by bukkit this time)
2013-05-16 18:27:24 [INFO] Sending serverside check to: Stilleraben
2013-05-16 18:27:38 [SEVERE] t: Exception ticking world
2013-05-16 18:27:38 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:958)
2013-05-16 18:27:38 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-05-16 18:27:38 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:864)
2013-05-16 18:27:38 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:751)
2013-05-16 18:27:38 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)
2013-05-16 18:27:38 [SEVERE] Caused by: java.lang.NoClassDefFoundError: yd
2013-05-16 18:27:38 [SEVERE]    at yc.m(World.java:1120)
2013-05-16 18:27:38 [SEVERE]    at yc.h(World.java:1066)
2013-05-16 18:27:38 [SEVERE]    at yc.f(World.java:1010)
2013-05-16 18:27:38 [SEVERE]    at yc.e(World.java:968)
2013-05-16 18:27:38 [SEVERE]    at amx.n(BlockTorch.java:222)
2013-05-16 18:27:38 [SEVERE]    at amx.g(BlockTorch.java:164)
2013-05-16 18:27:38 [SEVERE]    at amx.b(BlockTorch.java:131)
2013-05-16 18:27:38 [SEVERE]    at in.g(WorldServer.java:603)
2013-05-16 18:27:38 [SEVERE]    at in.b(WorldServer.java:312)
2013-05-16 18:27:38 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:952)
2013-05-16 18:27:38 [SEVERE]    ... 4 more
2013-05-16 18:27:38 [SEVERE] Encountered an unexpected exception t
t: Exception ticking world
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:958)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:864)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:751)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NoClassDefFoundError: yd
    at yc.m(World.java:1120)
    at yc.h(World.java:1066)
    at yc.f(World.java:1010)
    at yc.e(World.java:968)
    at amx.n(BlockTorch.java:222)
    at amx.g(BlockTorch.java:164)
    at amx.b(BlockTorch.java:131)
    at in.g(WorldServer.java:603)
    at in.b(WorldServer.java:312)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:952)
    ... 4 more
2013-05-16 18:27:38 [SEVERE] This crash report has been saved to: C:\Users\Stilleraben\Desktop\UltimateRPGImmersions.\crash-reports\crash-2013-05-16_18.27.38-server.txt

**Comment by NachtRaben** [comment]
i have to admit, one of the weirdest things i've ever seen other than Sethblings custom map. it has that same effect

**Comment by NachtRaben** [comment]
ya this isn't ur mod. Sorry for bothering you.
