### ISSUE TITLE
[TT 1606] java.lang.NullPointerException when entering Mystcraft Ages

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#507]
2013-05-17 09:48:00 [INFO] [STDERR] java.lang.NullPointerException
2013-05-17 09:48:00 [INFO] [STDERR]     at com.xcompwiz.mystcraft.generation.AgeData.getStorageObject(AgeData.java:375)
2013-05-17 09:48:00 [INFO] [STDERR]     at com.xcompwiz.mystcraft.world.AgeController.reconstruct(AgeController.java:228)
2013-05-17 09:48:00 [INFO] [STDERR]     at com.xcompwiz.mystcraft.world.AgeController.<init>(AgeController.java:98)
2013-05-17 09:48:00 [INFO] [STDERR]     at com.xcompwiz.mystcraft.world.WorldProviderMyst.b(WorldProviderMyst.java:60)
2013-05-17 09:48:00 [INFO] [STDERR]     at aaq.a(WorldProvider.java:61)
2013-05-17 09:48:00 [INFO] [STDERR]     at yc.<init>(World.java:281)
2013-05-17 09:48:00 [INFO] [STDERR]     at in.<init>(WorldServer.java:103)
2013-05-17 09:48:00 [INFO] [STDERR]     at ih.<init>(SourceFile:10)
2013-05-17 09:48:00 [INFO] [STDERR]     at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:242)
2013-05-17 09:48:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
2013-05-17 09:48:00 [INFO] [STDERR]     at com.xcompwiz.mystcraft.command.CommandTPX.b(CommandTPX.java:113)
2013-05-17 09:48:00 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-05-17 09:48:00 [INFO] [STDERR]     at iv.d(NetServerHandler.java:769)
2013-05-17 09:48:00 [INFO] [STDERR]     at iv.a(NetServerHandler.java:735)
2013-05-17 09:48:00 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-05-17 09:48:00 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-05-17 09:48:00 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-05-17 09:48:00 [INFO] [STDERR]     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
2013-05-17 09:48:00 [INFO] [STDERR]     at iw.b(NetworkListenThread.java)
2013-05-17 09:48:00 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-05-17 09:48:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:394)
2013-05-17 09:48:00 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-05-17 09:48:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:280)
2013-05-17 09:48:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
2013-05-17 09:48:00 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by Drehmini** [comment]
This happens when players try to enter a certain mystcraft age.

**Comment by Drehmini** [comment]
This was actually a corrupted .dat age file. This issue was fixed.
