### ISSUE TITLE
[TT 1621][MCPC+ 28] Just after server start up some [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#511]
[SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 17760
java.lang.NullPointerException
    at forestry.arboriculture.items.ItemGermlingGE.a(ItemGermlingGE.java:144)
    at ur.a(ItemStack.java:135)
    at ir.a(ItemInWorldManager.java:580)
    at iv.a(NetServerHandler.java:906)
    at fk.a(Packet15Place.java:79)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:394)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:280)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at fy.run(ThreadMinecraftServer.java:16)
2013-05-17 14:40:55 [FINE] [ForgeModLoader] Entity px['item.item.snowball'/20873, l='overworld', x=-2922.24, y=71.77, z=1072.57] added to the wrong chunk - expected x-183 z66, got x-183 z67
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-17 14:40:57 [FINEST] [ForgeModLoader] Received valid FML login packet from /109.247.25.126:57428
2013-05-17 14:40:59 [INFO] [GraviGun] [1.4.7v2] Recieved client info from Desecrati0n
2013-05-17 14:40:59 [INFO] [PortalGun] [1.4.7v5] Recieved client info from Desecrati0n
2013-05-17 14:41:02 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 21069
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at vswe.stevescarts.CommonProxy.getCart(CommonProxy.java:179)
    at vswe.stevescarts.CommonProxy.getServerGuiElement(CommonProxy.java:110)
    at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:345)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:337)
    at vswe.stevescarts.Carts.entMCBase.onInteract(entMCBase.java:1169)
    at vswe.stevescarts.Carts.entMCBase.doInteract(entMCBase.java:1162)
    at vswe.stevescarts.Listeners.cartEventListener.invoke(cartEventListener.java:17)
    at net.minecraftforge.event.ASMEventHandler_165_cartEventListener_invoke_MinecartInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at py.a(EntityMinecart.java:1215)
    at qx.p(EntityPlayer.java:1291)
    at iv.a(NetServerHandler.java:1562)
    at dp.a(Packet7UseEntity.java:57)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:394)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:280)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at fy.run(ThreadMinecraftServer.java:16)
2013-05-17 14:41:02 [FINEST] [ForgeModLoader] Received valid FML login packet from /90.220.160.121:61242
2013-05-17 14:41:05 [INFO] [GraviGun] [1.4.7v2] Recieved client info from Cookie1010101
2013-05-17 14:41:05 [INFO] [PortalGun] [1.4.7v5] Recieved client info from Cookie1010101
2013-05-17 14:41:06 [FINEST] [ForgeModLoader] Received valid FML login packet from /109.247.25.126:57446
2013-05-17 14:41:08 [INFO] [GraviGun] [1.4.7v2] Recieved client info from Desecrati0n
2013-05-17 14:41:08 [INFO] [PortalGun] [1.4.7v5] Recieved client info from Desecrati0n
2013-05-17 14:41:14 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 21575
java.lang.NullPointerException
    at forestry.arboriculture.items.ItemGermlingGE.a(ItemGermlingGE.java:144)
    at ur.a(ItemStack.java:135)
    at ir.a(ItemInWorldManager.java:580)
    at iv.a(NetServerHandler.java:906)
    at fk.a(Packet15Place.java:79)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:394)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:280)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at fy.run(ThreadMinecraftServer.java:16)
2013-05-17 14:41:24 [FINEST] [ForgeModLoader] Received valid FML login packet from /90.220.160.121:61252
2013-05-17 14:41:26 [INFO] [GraviGun] [1.4.7v2] Recieved client info from Cookie1010101
2013-05-17 14:41:26 [INFO] [PortalGun] [1.4.7v5] Recieved client info from Cookie1010101

**Comment by LunNova** [comment]
The ItemGermlingGE issue is a forestry issue, the others are now fixed.
