### ISSUE TITLE
[TT 1621][MCPC+ 28] lag spike detector findings 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#512]
http://pastebin.com/UTPxD2Uc

**Comment by LunNova** [comment]
This shows that BC pumps are causing lag spikes, somewhere in the nether.

**Comment by alicheek** [comment]
ill check it out see if its a stupid setup or something

**Comment by alicheek** [comment]
another dead lock but this is with TT 1625

http://pastebin.com/xnF5qigv

**Comment by alicheek** [comment]
this is a couple of seconds after the deadlock happens :

[FINE] [ForgeModLoader] Entity px['item.tile.stonebrick'/5001, l='world_twilightforest', x=-2816.78, y=28.29, z=2336.31] added to the wrong chunk - expected x-176 z146, got x-177 z146
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:13:28 [FINE] [ForgeModLoader] Entity px['item.item.stick'/5016, l='world_twilightforest', x=-2816.35, y=28.73, z=2335.58] added to the wrong chunk - expected x-176 z145, got x-177 z145
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:13:28 [FINE] [ForgeModLoader] Entity px['item.tile.marble'/5060, l='world_twilightforest', x=-2817.60, y=27.35, z=2336.71] added to the wrong chunk - expected x-177 z145, got x-177 z146
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
it seems to be its all about the wrong chunks with these errors , herese another one :  
[FINE] [ForgeModLoader] Entity px['item.tile.sapling.oak'/30867, l='world_twilightforest', x=-750.56, y=35.80, z=5968.70] added to the wrong chunk - expected x-47 z372, got x-47 z373
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
FINE] [ForgeModLoader] Entity px['item.tile.stonebrick'/57975, l='overworld', x=2425.50, y=78.25, z=160.50] added to the wrong chunk - expected x151 z9, got x151 z10
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:30:29 [FINEST] [ForgeModLoader] Received valid FML login packet from /37.5.76.230:50042
2013-05-18 04:30:31 [INFO] [GraviGun] [1.4.7v2] Recieved client info from braizne
2013-05-18 04:30:31 [INFO] [PortalGun] [1.4.7v5] Recieved client info from braizne
2013-05-18 04:32:16 [FINE] [ForgeModLoader] Entity px['item.tile.mushroom'/69301, l='world_twilightforest', x=-81.58, y=19.70, z=3322.43] added to the wrong chunk - expected x-5 z207, got x-6 z207
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:33:12 [FINE] [ForgeModLoader] Entity px['item.tile.mushroom'/79372, l='world_twilightforest', x=-81.58, y=19.70, z=3322.43] added to the wrong chunk - expected x-5 z207, got x-6 z207
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:34:21 [FINE] [ForgeModLoader] Entity px['item.tile.mushroom'/93967, l='world_twilightforest', x=-81.58, y=19.70, z=3322.43] added to the wrong chunk - expected x-5 z207, got x-6 z207
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:34:28 [FINEST] [ForgeModLoader] Received valid FML login packet from /91.155.211.208:52834
2013-05-18 04:34:30 [INFO] [GraviGun] [1.4.7v2] Recieved client info from Kaketeus
2013-05-18 04:34:30 [INFO] [PortalGun] [1.4.7v5] Recieved client info from Kaketeus
2013-05-18 04:35:26 [FINEST] [ForgeModLoader] Received valid FML login packet from /87.50.35.250:53596
2013-05-18 04:35:28 [INFO] [GraviGun] [1.4.7v2] Recieved client info from mrzappy
2013-05-18 04:35:28 [INFO] [PortalGun] [1.4.7v5] Recieved client info from mrzappy
2013-05-18 04:35:47 [FINEST] [ForgeModLoader] Received valid FML login packet from /85.201.4.45:49877
2013-05-18 04:35:49 [INFO] [GraviGun] [1.4.7v2] Recieved client info from byJoga
2013-05-18 04:35:49 [INFO] [PortalGun] [1.4.7v5] Recieved client info from byJoga
2013-05-18 04:35:55 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 4997
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getBlockAt(CraftWorld.java:164)
    at org.bukkit.craftbukkit.v1_4_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:140)
    at org.bukkit.craftbukkit.v1_4_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:130)
    at iv.a(NetServerHandler.java:861)
    at fk.a(Packet15Place.java:79)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:394)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:280)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at fy.run(ThreadMinecraftServer.java:16)
2013-05-18 04:36:03 [FINEST] [ForgeModLoader] Received valid FML login packet from /188.220.191.70:59782
2013-05-18 04:36:04 [INFO] [GraviGun] [1.4.7v2] Recieved client info from EwokPD
2013-05-18 04:36:04 [INFO] [PortalGun] [1.4.7v5] Recieved client info from EwokPD
2013-05-18 04:36:22 [FINEST] [ForgeModLoader] Received valid FML login packet from /124.181.135.16:50029
2013-05-18 04:36:24 [INFO] [GraviGun] [1.4.7v2] Recieved client info from envyc965
2013-05-18 04:36:24 [INFO] [PortalGun] [1.4.7v5] Recieved client info from envyc965
2013-05-18 04:36:53 [FINE] [ForgeModLoader] Entity px['item.tile.extrabiomes.sapling.4'/120128, l='overworld', x=3584.70, y=76.18, z=-886.62] added to the wrong chunk - expected x223 z-56, got x224 z-56
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-18 04:37:34 [FINE] [ForgeModLoader] Entity EntityBlock['entity.GraviGun.gravigun_entityblock.name'/124762, l='overworld_nether', x=-1259.63, y=63.12, z=-1166.26] added to the wrong chunk - expected x-10 z-10, got x-79 z-73
java.lang.Throwable
    at zz.a(Chunk.java:193)
    at aam.a(ThreadedChunkLoader.java:413)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:841)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Looks like it's a pump again.

**Comment by floh22** [comment]
i get these errors and similar ones so often, but even without TT just not logged as well. i really hope nallar can fix this, cause its causing huge problems. its our largest source of lag along with tileentities. i can post errors if you want but they might have been posted already

**Comment by LunNova** [comment]
See https://github.com/BuildCraft/BuildCraft/issues/861
