### ISSUE TITLE
Build 1625-Update question

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#517]
Everything works fine from what i can tell.
But when i try to update to version 5.3.0 of the direwolf20 pack i get this error then the server crashes when placing a chickenchunk loader:
[SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoSuchMethodError
java.lang.NoSuchMethodError: codechicken.core.packet.PacketCustom.sendToPlayer(Liq;)V
    at codechicken.chunkloader.BlockChunkLoader.a(BlockChunkLoader.java:103)
    at ir.a(ItemInWorldManager.java:411)
    at iv.a(NetServerHandler.java:579)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:394)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:280)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at fy.run(SourceFile:849)

My question is will you be updating to support the probably last updates for 1.4.7 mods or should i stay on the 5.2.0 version of the pack?

**Comment by Maximuscr31** [comment]
That is because the new update uses the wrong version of chickenchunks. It causes any chunkloader that is right clicked to crash. It comes with 1.3.1.1 chickenchunks, and you need 1.3.1.2. Someone has derped badly at FTB and no one can get them to fix it even though the fix is there. You either need to downgrade or have all your users put in the 1.3.1.2 file themselves.

**Comment by Kusinagie** [comment]
Ah okay that did the trick thanks. So to answer my end question I can update and keep giving error reports as i find them?

**Comment by LunNova** [comment]
Closing as this isn't a TT issue, just an FTB pack bug.

I will be supporting any 1.4.7 mods, hopefully within a few weeks also 1.5.
