### ISSUE TITLE
Applied energistics error

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#523]
2013-05-19 15:38:28 [SEVERE] [TickThreading] Exception getting block ID in in Overworld/0 at -2792, 58, -2544
java.lang.VerifyError: (class: appeng/me/tile/TileController, method: <init> signature: ()V) Expecting to find unitialized object on stack
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at any.c(TileEntity.java:139)
at aam.a(ThreadedChunkLoader.java:432)
at aam.a(ThreadedChunkLoader.java:153)
at aam.a(ThreadedChunkLoader.java:127)
at im.f(ThreadedChunkProvider.java:667)
at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
at im.d(ThreadedChunkProvider.java:395)
at yc.getChunkIfExists(World.java:890)
at yc.getBlockIdWithoutLoad(World.java:199)
at yc.k(World.java:873)
at yc.A(World.java:3856)
at yc.l(World.java:884)
at yc.B(World.java:3882)
at ic2.core.block.wiring.TileEntityTransformer.updateRedstone(TileEntityTransformer.java:134)
at ic2.core.block.wiring.TileEntityTransformer.g(TileEntityTransformer.java:113)
at any.tickTT(TileEntity.java:51)
at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-19 15:38:28 [SEVERE] [TickThreading] Exception getting block ID in in Overworld/0 at -2800, 46, -2534
java.lang.VerifyError: (class: appeng/me/tile/TileController, method: <init> signature: ()V) Expecting to find unitialized object on stack
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at any.c(TileEntity.java:139)
at aam.a(ThreadedChunkLoader.java:432)
at aam.a(ThreadedChunkLoader.java:153)
at aam.a(ThreadedChunkLoader.java:127)
at im.f(ThreadedChunkProvider.java:667)
at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
at im.d(ThreadedChunkProvider.java:395)
at yc.e(World.java:210)
at yc.a(World.java:186)
at factorization.common.TileEntityWrathLamp$InitialBuild.update(TileEntityWrathLamp.java:286)
at factorization.common.TileEntityWrathLamp.g(TileEntityWrathLamp.java:135)
at any.tickTT(TileEntity.java:51)
at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

Description: Exception in server tick loop

java.lang.VerifyError: (class: appeng/me/tile/TileController, method: <init> signature: ()V) Expecting to find unitialized object on stack
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at any.c(TileEntity.java:139)
    at aam.a(ThreadedChunkLoader.java:432)
    at aam.a(ThreadedChunkLoader.java:153)
    at aam.a(ThreadedChunkLoader.java:127)
    at im.f(ThreadedChunkProvider.java:667)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:491)
    at im.getChunkAt(ThreadedChunkProvider.java:465)
    at im.c(ThreadedChunkProvider.java:406)
    at yc.getTEWithLoad(World.java:342)
    at chb.mods.mffs.common.ModularForceFieldSystem$MFFSChunkloadCallback.ticketsLoaded(ModularForceFieldSystem.java:549)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:506)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:279)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:158)
    at fy.run(SourceFile:849)

**Comment by HaoSs07** [comment]
![2013-05-19_15 42 00](https://f.cloud.github.com/assets/3189195/522954/9a545bee-c081-11e2-828b-9edf37592df2.png)

**Comment by alicheek** [comment]
lol yea that happened to one of my players except it just reset it didn't loose the chunk

**Comment by HaoSs07** [comment]
at first reboot :) server crash,
second reboot, server starts with console spam, and chunk does not load :), i downgraded to last version i used, chunk is there,

Side not, Did nallar fix mobs not spawning in gamemode ? now it works

**Comment by alicheek** [comment]
what version was it u used when it happened?

**Comment by HaoSs07** [comment]
1639, i usually update to latest before i report bugs.

**Comment by HaoSs07** [comment]
updated to 1940
https://gist.github.com/HaoSs07/5607591 (full log)
https://gist.github.com/HaoSs07/5607587 (patchlog)
