### ISSUE TITLE
[TT 1634][MCPC+ 28] [SEVERE] [TickThreading] Exception ticking entity EntityGolemWood['Wood Golem'/2650, l='overworld', x=4343.34, y=155.08, z=-386.53] in rX: 271, rZ: -24, hashCode: -1572593/Overworld/0:

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#525]
2013-05-19 15:40:14 [SEVERE] [TickThreading] Exception ticking entity EntityGolemWood['Wood Golem'/2650, l='overworld', x=4343.34, y=155.08, z=-386.53] in rX: 271, rZ: -24, hashCode: -1572593/Overworld/0:
java.lang.NullPointerException
    at thaumcraft.common.Utils.mergeItemStackIntoInventory(Utils.java:228)
    at thaumcraft.common.Utils.mergeItemStackIntoInventory(Utils.java:202)
    at thaumcraft.common.entities.ai.AIPlaceHomeInv.a(AIPlaceHomeInv.java:44)
    at nd.a(EntityAITasks.java:77)
    at thaumcraft.common.entities.golems.EntityGolemBase.bl(EntityGolemBase.java:118)
    at md.c(EntityLiving.java:209)
    at thaumcraft.common.entities.golems.EntityGolemBase.c(EntityGolemBase.java:140)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
issue hasn't occurred in a while now
