### ISSUE TITLE
[TT 1634][MCPC+ 28] [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#526]
[SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:45 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:46 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-20 05:57:50 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/493339, l='world_twilightforest', x=4354.46, y=33.00, z=767.47] in rX: 272, rZ: 47, hashCode: 3080464/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.faceEntity(HydraHeadContainer.java:1117)
    at twilightforest.entity.HydraHeadContainer.setHeadFacing(HydraHeadContainer.java:523)
    at twilightforest.entity.HydraHeadContainer.onUpdate(HydraHeadContainer.java:369)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:135)
    at md.j_(EntityLiving.java:913)
    at yc.a(World.java:376)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2707)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:62)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
Chunk loading for TF is becoming really slow, though over world is ok, tps is now dropping as well not really sure what is up still having that same problem where the server is slowing down every like 3 hours

**Comment by alicheek** [comment]
that's the full TT log here : http://pastebin.com/wss9eUk1

**Comment by LunNova** [comment]
This isn't actually a TT bug, but I can fix it anyway. :P

**Comment by alicheek** [comment]
haha cheers man :)
