### ISSUE TITLE
Patcher Error - Build 437

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#53]
01-15 17:57:02 [FINE] [TickThreading] Patching any with addMethod(return:java.lang.String,name:toString,code:return super.toString() + " x,y,x: " + xCoord + ", " + yCoord + ", " + zCoord;)
01-15 17:57:02 [SEVERE] [TickThreading] Error patching any with addMethod
javassist.CannotCompileException: [source error] no such field: xCoord
    at javassist.CtBehavior.setBody(CtBehavior.java:446)
    at javassist.CtBehavior.setBody(CtBehavior.java:412)
    at me.nallar.tickthreading.patcher.Patches.addMethod(Patches.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:286)
    at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:268)
    at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:190)
    at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:72)
    at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:26)
Caused by: compile error: no such field: xCoord
    at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:819)
    at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:777)
    at javassist.compiler.TypeChecker.atMember(TypeChecker.java:962)
    at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
    at javassist.compiler.ast.Member.accept(Member.java:39)
    at javassist.compiler.TypeChecker.atPlusExpr(TypeChecker.java:358)
    at javassist.compiler.TypeChecker.atPlusExpr(TypeChecker.java:356)
    at javassist.compiler.TypeChecker.atPlusExpr(TypeChecker.java:356)
    at javassist.compiler.TypeChecker.atPlusExpr(TypeChecker.java:356)
    at javassist.compiler.TypeChecker.atPlusExpr(TypeChecker.java:356)
    at javassist.compiler.TypeChecker.atBinExpr(TypeChecker.java:312)
    at javassist.compiler.ast.BinExpr.accept(BinExpr.java:41)
    at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
    at javassist.compiler.CodeGen.compileExpr(CodeGen.java:229)
    at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:598)
    at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:425)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
    at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
    at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
    at javassist.compiler.Javac.compileBody(Javac.java:223)
    at javassist.CtBehavior.setBody(CtBehavior.java:438)
    ... 11 more

**Comment by LunNova** [comment]
Fixed in build 440.
