### ISSUE TITLE
load event was fired twice. ( + lagspike mode question )

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#534]
2013-05-21 17:38:34 [SEVERE] [TickThreading] World Age 18/18's world load event was fired twice.
java.lang.Throwable
at me.nallar.tickthreading.minecraft.TickThreading.onWorldLoad(TickThreading.java:200)
at net.minecraftforge.event.ASMEventHandler_209_TickThreading_onWorldLoad_Load.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:244)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
at gm.a(ServerConfigurationManager.java:406)
at ee.lutsu.alpha.mc.mytown.entities.Resident.respawnPlayer(Resident.java:562)
at ee.lutsu.alpha.mc.mytown.entities.Resident.asyncEndSpawnTeleport(Resident.java:823)
at ee.lutsu.alpha.mc.mytown.entities.Resident.update(Resident.java:664)
at ee.lutsu.alpha.mc.mytown.event.PlayerEvents.livingUpdate(PlayerEvents.java:394)
at net.minecraftforge.event.ASMEventHandler_254_PlayerEvents_livingUpdate_LivingUpdateEvent.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:333)
at md.j_(EntityLiving.java:803)
at qx.j_(EntityPlayer.java:328)
at iq.g(EntityPlayerMP.java:286)
at iv.a(NetServerHandler.java:310)
at eb.a(SourceFile:56)
at cg.i(TcpConnection.java:347)
at cg.readNetworkPacket(TcpConnection.java:71)
at ch.run(ReplaceTcpReaderThread.java:22)

Sometimes happens in twilight forest too
I saw topic about lag-spike mode, i probably missed that, how exactly does it work ? cant find in config any setting for that.

**Comment by HaoSs07** [comment]
you missed the lagspike question :P

" I saw topic about lag-spike mode, i probably missed that, how exactly does it work ? cant find in config any setting for that. " probably best to add it to the wiki ?

**Comment by LunNova** [comment]
It's just setting the deadLockTime to 1.
