### ISSUE TITLE
Mass errors when unloaded world is force loaded.

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#537]
2013-05-21 17:34:17 [SEVERE] [ForgeModLoader] Exception posting event: net.minecraftforg                            e.event.terraingen.PopulateChunkEvent$Post@77fe4bb5
2013-05-21 17:34:17 [SEVERE] java.lang.NullPointerException
2013-05-21 17:34:18 [INFO] Preparing spawn area for anew_the_end, 97%
2013-05-21 17:34:18 [SEVERE] [ForgeModLoader] Exception posting event: net.m                                        e.event.terraingen.PopulateChunkEvent$Post@6a79b0ce

This is only a small snip from the mass amounts of errors, all essentially the same thing

**Comment by LunNova** [comment]
Can you get the error from the start of the log? The ones later on are missing the stack trace, the first few should actually show it. Without the stack trace I can't tell what's causing it.

**Comment by Tencao** [comment]
Sadly, the forge log was wiped since then, since the server is rebooted every 3 hours, but I did find this which affected dynmap at the time, not sure if it's of help

2013-05-21 17:34:11 [SEVERE] java.lang.NullPointerException
2013-05-21 17:34:11 [SEVERE]    at org.dynmap.forge.DynmapPlugin$WorldTracker.handleChunkPopulate(DynmapPlugin.java:1329)
2013-05-21 17:34:11 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_208_WorldTracker_handleChunkPopulate_Post.invoke(.dynamic)
2013-05-21 17:34:11 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-05-21 17:34:11 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-05-21 17:34:11 [SEVERE]    at abb.a(ChunkProviderGenerate.java:601)
2013-05-21 17:34:11 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
2013-05-21 17:34:11 [SEVERE]    at im.populate(ThreadedChunkProvider.java:590)
2013-05-21 17:34:11 [SEVERE]    at im.tryPopulateChunks(ThreadedChunkProvider.java:610)
2013-05-21 17:34:11 [SEVERE]    at im.getChunkAtInternal(ThreadedChunkProvider.java:575)
2013-05-21 17:34:11 [SEVERE]    at im.getChunkAt(ThreadedChunkProvider.java:465)
2013-05-21 17:34:11 [SEVERE]    at im.c(ThreadedChunkProvider.java:406)
2013-05-21 17:34:11 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:825)
2013-05-21 17:34:11 [SEVERE]    at me.dretax.SaveIt.Main.WorldSaveDelayed(Main.java:272)
2013-05-21 17:34:11 [SEVERE]    at me.dretax.SaveIt.Main$1.run(Main.java:128)
2013-05-21 17:34:11 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
2013-05-21 17:34:11 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
2013-05-21 17:34:11 [SEVERE]    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
2013-05-21 17:34:11 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:338)
2013-05-21 17:34:11 [SEVERE]    at ho.r(DedicatedServer.java:309)
2013-05-21 17:34:11 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:281)
2013-05-21 17:34:11 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
2013-05-21 17:34:11 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)

Also, if it helps, at the time, the world was unloaded by tickthreading, but the save plugin tried to force load it again, causing the errors. I'm not sure if the plugin simply tried to just load it, or try and create a new one, as it was preparing spawn as it was happening. Not sure if that's any help

**Comment by LunNova** [comment]
Should be fixed now, have redone world unloading.
