### ISSUE TITLE
[TT 1666][MCPC+ 28] [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#538]
[SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:475)
        at im.getChunkAt(ThreadedChunkProvider.java:465)
        at im.c(ThreadedChunkProvider.java:406)
        at yc.getBlockIdWithLoad(World.java:228)
        at buildcraft.BuildCraftFactory$QuarryChunkloadCallback.ticketsLoaded(BuildCraftFactory.java:110)
        at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:512)
        at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
        at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:471)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:346)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:159)
        at fy.run(ThreadMinecraftServer.java:16)

**Comment by mainsheep** [comment]
I'm having the same issue.. This is spammed into the console for a few seconds when the server starts.

TT1669, MCPC L28
