### ISSUE TITLE
[TT 1666][MCPC+ 28] [WARNING] Failed to handle packet for nichnich3/92.251.32.247: java.lang.IllegalStateException: Must synchronize to iterate over EntityList.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#540]
[WARNING] Failed to handle packet for nichnich3/92.251.32.247: java.lang.IllegalStateException: Must synchronize to iterate over EntityList.
java.lang.IllegalStateException: Must synchronize to iterate over EntityList.
        at me.nallar.tickthreading.minecraft.entitylist.EntityList.iterator(EntityList.java:64)
        at vswe.stevescarts.CommonProxy.getCart(CommonProxy.java:179)
        at vswe.stevescarts.CommonProxy.getServerGuiElement(CommonProxy.java:110)
        at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:345)
        at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:337)
        at vswe.stevescarts.Carts.entMCBase.onInteract(entMCBase.java:1169)
        at vswe.stevescarts.Carts.entMCBase.doInteract(entMCBase.java:1162)
        at vswe.stevescarts.Listeners.cartEventListener.invoke(cartEventListener.java:17)
        at net.minecraftforge.event.ASMEventHandler_171_cartEventListener_invoke_MinecartInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at py.a(EntityMinecart.java:1215)
        at qx.p(EntityPlayer.java:1291)
        at iv.a(NetServerHandler.java:1562)
        at dp.a(Packet7UseEntity.java:57)
        at cg.b(TcpConnection.java:467)
        at iv.d(NetServerHandler.java:220)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:402)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:283)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:187)
        at fy.run(ThreadMinecraftServer.java:16)

**Comment by alicheek** [comment]
[SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 2961
java.lang.IllegalStateException: Must synchronize to iterate over EntityList.
        at me.nallar.tickthreading.minecraft.entitylist.EntityList.iterator(EntityList.java:64)
        at vswe.stevescarts.CommonProxy.getCart(CommonProxy.java:179)
        at vswe.stevescarts.CommonProxy.getServerGuiElement(CommonProxy.java:110)
        at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:345)
        at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:337)
        at vswe.stevescarts.Carts.entMCBase.onInteract(entMCBase.java:1169)
        at vswe.stevescarts.Carts.entMCBase.doInteract(entMCBase.java:1162)
        at vswe.stevescarts.Listeners.cartEventListener.invoke(cartEventListener.java:17)
        at net.minecraftforge.event.ASMEventHandler_171_cartEventListener_invoke_MinecartInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at py.a(EntityMinecart.java:1215)
        at qx.p(EntityPlayer.java:1291)
        at iv.a(NetServerHandler.java:1562)
        at dp.a(Packet7UseEntity.java:57)
        at cg.b(TcpConnection.java:467)
        at iv.d(NetServerHandler.java:220)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:402)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:283)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:187)
        at fy.run(ThreadMinecraftServer.java:16)

**Comment by alicheek** [comment]
this is related to b94c310f9dcd3629f6b2147503c37834050b1d79)

**Comment by cjm721** [comment]
When I updated my direwolf server to 1666 I am getting this also, and you can force and error with /gc from essentials, while ultimate crashes for me #543
