### ISSUE TITLE
[TT 1666][MCPC+ 28]  [SEVERE] Could not pass event PlayerJoinEvent to Multiverse-Core v2.5-b666

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#541]
[INFO] asam48005[/216.36.9.10:57111] logged in with entity id 57205 at ([overworld] -295.5, 68.62000000476837, 248.5)

> 20:21:23 [WARNING] [Multiverse-Core] The world specified as the spawn world (null) did not exist!!
> 
> 20:21:23 [SEVERE] Could not pass event PlayerJoinEvent to Multiverse-Core v2.5-b666
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
>         at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
>         at gm.c(ServerConfigurationManager.java:255)
>         at gm.a(ServerConfigurationManager.java:166)
>         at it.completeConnection(NetLoginHandler.java:214)
>         at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:155)
>         at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:109)
>         at it.d(NetLoginHandler.java:190)
>         at it.c(NetLoginHandler.java:81)
>         at hu.a(ServerListenThread.java:58)
>         at ht.b(DedicatedServerListenThread.java:33)
>         at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:402)
>         at ho.r(DedicatedServer.java:309)
>         at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:283)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:187)
>         at fy.run(ThreadMinecraftServer.java:16)
> Caused by: java.lang.NullPointerException
>         at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerJoin(Unknown Source)
>         at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:601)
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
>         ... 18 more
> 
> 20:21:23 [INFO] Loading Player: asam48005
> 
> 20:21:23 [INFO] Sending serverside check to: asam48005
> 
> 20:21:23 [INFO] Creating empty config: /home/minecraft/plugins/Essentials/userdata/asam48005.yml

**Comment by alicheek** [comment]
think this may of been related to the entity issue with 1666 will open again if I get it again
