### ISSUE TITLE
Exception ticking TileEntity c appeng.me.tile.TileStorageBus

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#542]
some storage bus spam that happens for some days now, not always at 2062, 7, -3663.

2013-05-21 23:10:47 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @1962183090 in Overworld/0 at x, y, z: 2062, 7, -3663

java.util.ConcurrentModificationException

  at java.util.ArrayList$Itr.checkForComodification(Unknown Source)

  at java.util.ArrayList$Itr.next(Unknown Source)

  at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)

  at any.tickTT(TileEntity.java:51)

  at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:101)

  at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)

  at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)

  at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)

  at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

2013-05-21 23:11:24 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @1962183090 in Overworld/0 at x, y, z: 2062, 7, -3663

java.util.ConcurrentModificationException

  at java.util.ArrayList$Itr.checkForComodification(Unknown Source)

  at java.util.ArrayList$Itr.next(Unknown Source)

  at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)

  at any.tickTT(TileEntity.java:51)

  at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:101)

  at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)

  at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)

  at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)

  at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by HaoSs07** [comment]
2013-05-22 15:54:07 [SEVERE] [TickThreading] Exception ticking TileEntity c factorization.common.TileEntityBarrel Barrel of 2266 64xnull@0 x, y, z: 3251, 61, -3750
java.lang.NullPointerException
at factorization.common.TileEntityBarrel.getItemCount(TileEntityBarrel.java:65)
at factorization.common.TileEntityBarrel.updateStacks(TileEntityBarrel.java:84)
at factorization.common.TileEntityBarrel.g(TileEntityBarrel.java:506)
at any.tickTT(TileEntity.java:51)
at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:101)
at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by HaoSs07** [comment]
closing this because does not happen anymore. probably already fixed

**Comment by DJGummikuh** [comment]
We are having this concurrent modification exception as well on FTB Ultimate (1.1.2). I do not know which version of appeng this relates to but has there since been a fix for this issue?

**Comment by HaoSs07** [comment]
was for 1.4.7. and never seen it in months :P also. TT is closed. no updates will be made for now

**Comment by DJGummikuh** [comment]
Well it definitely IS happening on our server right now (running Minecraft 1.4.7 With FTB Ultimate 1.1.2).
It happens most of the time with appeng when a storage bus is attached to a chest and ME is both pushing and pulling items to and from this chest at the same time. Consequently removing all storagebus->chest constellations on the server removed the errors from  our logs but this clearly is not really a TT issue but an appeng issue.
Do you know where to contact the ME guys? (actually, I thought it was you :P)

**Comment by HaoSs07** [comment]
well never had a setup that pulls and puts items on the same chest. also version in 1.4.7 is old. ME was mostly rewritten in 1.5.2.
