### ISSUE TITLE
Loaded chunk before world load event

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#554]
2013-05-24 19:39:52 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
        at im.d(ThreadedChunkProvider.java:431)
        at yc.e(World.java:215)
        at yc.a(World.java:191)
        at yc.c(World.java:628)
        at yc.b(World.java:570)
        at aaq.a(WorldProvider.java:100)
        at in.canSpawn(WorldServer.java:249)
        at in.b(WorldServer.java:1025)
        at in.a(WorldServer.java:191)
        at yc.<init>(World.java:395)
        at in.<init>(WorldServer.java:125)
        at ih.<init>(WorldServerMulti.java:13)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:423)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
        at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 19:39:52 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
        at im.d(ThreadedChunkProvider.java:431)
        at yc.e(World.java:215)
        at yc.a(World.java:191)
        at yc.c(World.java:628)
        at yc.b(World.java:570)
        at aaq.a(WorldProvider.java:100)
        at in.canSpawn(WorldServer.java:249)
        at in.b(WorldServer.java:1025)
        at in.a(WorldServer.java:191)
        at yc.<init>(World.java:395)
        at in.<init>(WorldServer.java:125)
        at ih.<init>(WorldServerMulti.java:13)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:423)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
        at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 19:39:52 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
        at im.d(ThreadedChunkProvider.java:431)
        at yc.e(World.java:215)
        at yc.a(World.java:191)
        at yc.c(World.java:628)
        at yc.b(World.java:570)
        at aaq.a(WorldProvider.java:100)
        at in.canSpawn(WorldServer.java:249)
        at in.b(WorldServer.java:1025)
        at in.a(WorldServer.java:191)
        at yc.<init>(World.java:395)
        at in.<init>(WorldServer.java:125)
        at ih.<init>(WorldServerMulti.java:13)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:423)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
        at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 19:39:52 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
        at im.d(ThreadedChunkProvider.java:431)
        at yc.e(World.java:215)
        at yc.a(World.java:191)
        at yc.c(World.java:628)
        at yc.b(World.java:570)
        at aaq.a(WorldProvider.java:100)
        at in.canSpawn(WorldServer.java:249)
        at in.b(WorldServer.java:1025)
        at in.a(WorldServer.java:191)
        at yc.<init>(World.java:395)
        at in.<init>(WorldServer.java:125)
        at ih.<init>(WorldServerMulti.java:13)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:423)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
        at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 19:39:52 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
        at im.d(ThreadedChunkProvider.java:431)
        at yc.e(World.java:215)
        at yc.a(World.java:191)
        at yc.c(World.java:628)
        at yc.b(World.java:570)
        at aaq.a(WorldProvider.java:100)
        at in.canSpawn(WorldServer.java:249)
        at in.b(WorldServer.java:1025)
        at in.a(WorldServer.java:191)
        at yc.<init>(World.java:395)
        at in.<init>(WorldServer.java:125)
        at ih.<init>(WorldServerMulti.java:13)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:423)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
        at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 19:39:52 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
        at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
        at im.d(ThreadedChunkProvider.java:431)
        at yc.e(World.java:215)
        at yc.a(World.java:191)
        at yc.c(World.java:628)
        at yc.b(World.java:570)
        at aaq.a(WorldProvider.java:100)
        at in.canSpawn(WorldServer.java:249)
        at in.b(WorldServer.java:1025)
        at in.a(WorldServer.java:191)
        at yc.<init>(World.java:395)
        at in.<init>(WorldServer.java:125)
        at ih.<init>(WorldServerMulti.java:13)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:423)
        at ho.c(DedicatedServer.java:203)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
        at fy.run(ThreadMinecraftServer.java:16)

I got this quite a few times, running on debian 6 btw.
rev1674, FTB 1.1.0 with MCPC-Plus (mcpc-plus-legacy-1.4.7-R1.1-SNAPSHOT-f534-L31)

**Comment by LunNova** [comment]
Was this when starting up a new server or creating a new world?

**Comment by ThuGie** [comment]
Yes it indeed was with creating a new world/server a fresh start. and btw your damn fast!

**Comment by alicheek** [comment]
its still doing it for me on startup and its not a new world for me it seems its got something to do with multiverse though:

[WARNING] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:541)
    at im.getChunkAt(ThreadedChunkProvider.java:501)
    at im.c(ThreadedChunkProvider.java:442)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:819)
    at org.bukkit.Bukkit.createWorld(Bukkit.java:156)
    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:409)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:390)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:365)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:664)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:300)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:298)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:280)
    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:542)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:508)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:454)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
    at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 23:27:14 [WARNING] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:541)
    at im.getChunkAt(ThreadedChunkProvider.java:501)
    at im.c(ThreadedChunkProvider.java:442)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:819)
    at org.bukkit.Bukkit.createWorld(Bukkit.java:156)
    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:409)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:390)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:365)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:664)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:300)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:298)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:280)
    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:542)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:508)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:454)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
    at fy.run(ThreadMinecraftServer.java:16)
2013-05-24 23:27:14 [WARNING] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:541)
    at im.getChunkAt(ThreadedChunkProvider.java:501)
    at im.c(ThreadedChunkProvider.java:442)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.createWorld(CraftServer.java:819)
    at org.bukkit.Bukkit.createWorld(Bukkit.java:156)
    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:235)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:409)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:390)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:365)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:664)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:300)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:396)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:298)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:280)
    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:542)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:508)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:454)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:165)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
@alicheek 
Are you using the latest MCPC+ build? There have been MCPC+ fixes for wrong chunkloading as well recently.

**Comment by alicheek** [comment]
yea on L33
