### ISSUE TITLE
[TT 1674, MCPC+ L31]A few "Loaded chunk before world load event fired"

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#558]
2013-05-23 21:46:31 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:511)
    at im.d(ThreadedChunkProvider.java:431)
    at yc.e(World.java:215)
    at yc.a(World.java:191)
    at yc.c(World.java:628)
    at yc.b(World.java:570)
    at com.xcompwiz.mystcraft.world.WorldProviderMyst.a(WorldProviderMyst.java:435)
    at in.canSpawn(WorldServer.java:249)
    at in.b(WorldServer.java:1025)
    at in.a(WorldServer.java:191)
    at yc.<init>(World.java:395)
    at in.<init>(WorldServer.java:125)
    at ih.<init>(WorldServerMulti.java:13)
    at net.minecraftforge.common.DimensionManager.initMystWorld(DimensionManager.java:324)
    at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:259)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1053)
    at com.xcompwiz.mystcraft.linking.LinkController.travelEntity(LinkController.java:42)
    at com.xcompwiz.mystcraft.tileentity.TileEntityBookDisplay.link(TileEntityBookDisplay.java:78)
    at com.xcompwiz.mystcraft.inventory.ContainerBook.processMessage(ContainerBook.java:224)
    at com.xcompwiz.mystcraft.network.MPacketGUIMessage.handle(MPacketGUIMessage.java:36)
    at com.xcompwiz.mystcraft.network.MystcraftPacketHandler.onPacketData(MystcraftPacketHandler.java:45)
    at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:253)
    at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:242)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:73)
    at iv.a(NetServerHandler.java:2073)
    at di.a(Packet250CustomPayload.java:70)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:408)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:289)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:193)
    at fy.run(ThreadMinecraftServer.java:16)

2013-05-23 10:35:36 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:484)
    at im.getChunkAt(ThreadedChunkProvider.java:474)
    at im.c(ThreadedChunkProvider.java:415)
    at yc.getTEWithLoad(World.java:345)
    at portalgun.common.core.ChunkLoadHandler.ticketsLoaded(ChunkLoadHandler.java:34)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:530)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:478)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:347)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:159)
    at fy.run(ThreadMinecraftServer.java:16)

2013-05-23 10:35:36 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:484)
    at im.getChunkAt(ThreadedChunkProvider.java:474)
    at im.c(ThreadedChunkProvider.java:415)
    at yc.getTEWithLoad(World.java:345)
    at chb.mods.mffs.common.ModularForceFieldSystem$MFFSChunkloadCallback.ticketsLoaded(ModularForceFieldSystem.java:549)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:522)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:478)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:347)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:159)
    at fy.run(ThreadMinecraftServer.java:16)

2013-05-23 10:35:37 [SEVERE] [TickThreading] Loaded chunk before world load event fired, this can cause many issues, including loss of multiblock data.
java.lang.Throwable
    at im.getChunkAtInternal(ThreadedChunkProvider.java:484)
    at im.getChunkAt(ThreadedChunkProvider.java:474)
    at im.c(ThreadedChunkProvider.java:415)
    at yc.getTEWithLoad(World.java:345)
    at railcraft.common.util.misc.ChunkManager.ticketsLoaded(ChunkManager.java:191)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:522)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:478)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:347)
    at ho.c(DedicatedServer.java:203)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:159)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
It seems that any under "in.canSpawn(" are an MCPC+ issue, the others should now be fixed if you either update TT or update MCPC+.
