### ISSUE TITLE
Failed to handle packet for /54.224.229.102:60959

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#561]
Does not have TT in it, but only modification i have done to the server in past months was updating TT, Anything sound familiar ? its always the same IP, and is not a players IP

2013-05-25 13:17:27 [WARNING] [Minecraft] Failed to handle packet for /54.224.229.102:60959: java.lang.ClassCastException: it cannot be cast to iv
java.lang.ClassCastException: it cannot be cast to iv
at eb.a(SourceFile:33)
at cg.b(TcpConnection.java:458)
at it.c(NetLoginHandler.java:84)
at hu.a(ServerListenThread.java:56)
at ht.b(SourceFile:29)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:397)
at ho.r(DedicatedServer.java:269)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:283)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:187)
at fy.run(SourceFile:849)

**Comment by HaoSs07** [comment]
Latest version:

2013-05-25 14:02:31 [WARNING] [Minecraft] Failed to handle packet for /54.224.229.102:56740: java.lang.ClassCastException: it cannot be cast to iv
java.lang.ClassCastException: it cannot be cast to iv
at eb.a(SourceFile:34)
at cg.b(TcpConnection.java:458)
at it.c(NetLoginHandler.java:84)
at hu.a(ServerListenThread.java:56)
at ht.b(SourceFile:29)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:408)
at ho.r(DedicatedServer.java:269)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:289)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:193)
at fy.run(SourceFile:849)
2013-05-25 14:02:31 [WARNING] [Minecraft] Failed to handle packet for /54.224.229.102:56740: java.lang.ClassCastException: it cannot be cast to iv
java.lang.ClassCastException: it cannot be cast to iv
at eb.a(SourceFile:34)
at cg.b(TcpConnection.java:458)
at it.c(NetLoginHandler.java:84)
at hu.a(ServerListenThread.java:56)
at ht.b(SourceFile:29)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:408)
at ho.r(DedicatedServer.java:269)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:289)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:193)
at fy.run(SourceFile:849)
