### ISSUE TITLE
[TT 1680, MCPC+ L33] [SEVERE] [TickThreading] Exception ticking entity EntityTurret['Sentry Turret'/1365589, l='overworld', x=-597.50, y=28.00, z=-4725.50] in rX: -37, rZ: -295, hashCode: -19267621/Overworld/0:

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#562]
[SEVERE] [TickThreading] Exception ticking entity EntityTurret['Sentry Turret'/1365589, l='overworld', x=-597.50, y=28.00, z=-4725.50] in rX: -37, rZ: -295, hashCode: -19267621/Overworld/0:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at portalgun.common.entity.EntityTurret.handleSingStatus(EntityTurret.java:323)
    at portalgun.common.entity.EntityTurret.bn(EntityTurret.java:462)
    at md.c(EntityLiving.java:214)
    at portalgun.common.entity.EntityTurret.c(EntityTurret.java:646)
    at md.j_(EntityLiving.java:914)
    at yc.a(World.java:381)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2712)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-25 08:03:57 [SEVERE] [TickThreading] Exception ticking entity EntityTurret['Sentry Turret'/1365589, l='overworld', x=-597.50, y=28.00, z=-4725.50] in rX: -37, rZ: -295, hashCode: -19267621/Overworld/0:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at portalgun.common.entity.EntityTurret.handleSingStatus(EntityTurret.java:323)
    at portalgun.common.entity.EntityTurret.bn(EntityTurret.java:462)
    at md.c(EntityLiving.java:214)
    at portalgun.common.entity.EntityTurret.c(EntityTurret.java:646)
    at md.j_(EntityLiving.java:914)
    at yc.a(World.java:381)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2712)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-25 08:03:57 [SEVERE] [TickThreading] Exception ticking entity EntityTurret['Sentry Turret'/1365589, l='overworld', x=-597.50, y=28.00, z=-4725.50] in rX: -37, rZ: -295, hashCode: -19267621/Overworld/0:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at portalgun.common.entity.EntityTurret.handleSingStatus(EntityTurret.java:323)
    at portalgun.common.entity.EntityTurret.bn(EntityTurret.java:462)
    at md.c(EntityLiving.java:214)
    at portalgun.common.entity.EntityTurret.c(EntityTurret.java:646)
    at md.j_(EntityLiving.java:914)
    at yc.a(World.java:381)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2712)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-25 08:03:58 [SEVERE] [TickThreading] Exception ticking entity EntityTurret['Sentry Turret'/1365589, l='overworld', x=-597.50, y=28.00, z=-4725.50] in rX: -37, rZ: -295, hashCode: -19267621/Overworld/0:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at portalgun.common.entity.EntityTurret.handleSingStatus(EntityTurret.java:323)
    at portalgun.common.entity.EntityTurret.bn(EntityTurret.java:462)
    at md.c(EntityLiving.java:214)
    at portalgun.common.entity.EntityTurret.c(EntityTurret.java:646)
    at md.j_(EntityLiving.java:914)
    at yc.a(World.java:381)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2712)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Possibly related to #383?

**Comment by alicheek** [comment]
don't know was never coming up before until I updated it to 1680 yesterday

**Comment by LunNova** [comment]
Looking at the code, it's clearly wrong but accidentally works because vanilla minecraft reuses the same ArrayList instance in collision code. iChun got lucky there, will fix it soon.
