### ISSUE TITLE
Exception ticking entity  Hydra, (twilight forest )

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#563]
Only appeared when hydra was taking dmg

2013-05-25 13:29:07 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/358598, l='world', x=2559.76, y=33.00, z=-254.21] in rX: 159, rZ: -15, hashCode: -982881/Twilight Forest/7:

java.lang.NullPointerException

  at twilightforest.entity.HydraHeadContainer.setTargetEntity(HydraHeadContainer.java)

  at twilightforest.entity.EntityTFHydra.bn(EntityTFHydra.java:451)

  at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:214)

  at md.j_(EntityLiving.java:843)

  at yc.a(World.java:377)

  at in.a(WorldServer.java:647)

  at yc.g(World.java:2255)

  at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)

  at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)

  at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)

  at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)

  at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
I get it in 1860 also :  

2013-05-25 11:23:12 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/1694336, l='world_twilightforest', x=254.30, y=33.00, z=254.77] in rX: 15, rZ: 15, hashCode: 983055/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.setTargetEntity(HydraHeadContainer.java)
    at twilightforest.entity.EntityTFHydra.bn(EntityTFHydra.java:451)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:214)
    at md.j_(EntityLiving.java:914)
    at yc.a(World.java:381)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2712)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-25 11:23:12 [SEVERE] [TickThreading] Exception ticking entity EntityTFHydra['Hydra'/1694336, l='world_twilightforest', x=254.30, y=33.00, z=254.77] in rX: 15, rZ: 15, hashCode: 983055/Twilight Forest/7:
java.lang.NullPointerException
    at twilightforest.entity.HydraHeadContainer.setTargetEntity(HydraHeadContainer.java)
    at twilightforest.entity.EntityTFHydra.bn(EntityTFHydra.java:451)
    at twilightforest.entity.EntityTFHydra.c(EntityTFHydra.java:214)
    at md.j_(EntityLiving.java:914)
    at yc.a(World.java:381)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2712)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:63)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
