### ISSUE TITLE
Aperf entity list command ( /ap e l ) broke + question:P

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#564]
2013-05-25 14:09:45 [SEVERE] [aPerf] [31;1mThere is bogus command handler for aperf command. [0m
java.lang.IllegalStateException: Must synchronize to iterate over EntityList.
at me.nallar.tickthreading.minecraft.entitylist.EntityList.iterator(EntityList.java:64)
at ee.lutsu.alpha.mc.aperf.commands.BaseCommand.getGroupedCounts(BaseCommand.java:58)
at ee.lutsu.alpha.mc.aperf.commands.BaseCommand.sendWorldGroupedList(BaseCommand.java:133)
at ee.lutsu.alpha.mc.aperf.sys.entity.cmd.EntityList.list(EntityList.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at ee.lutsu.alpha.mc.aperf.commands.CommandsManager$CommandBinding.call(CommandsManager.java:248)
at ee.lutsu.alpha.mc.aperf.commands.CommandsManager.execute(CommandsManager.java:103)
at ee.lutsu.alpha.mc.aperf.commands.CmdPerf.b(CmdPerf.java:46)
at x.a(CommandHandler.java:82)
at ho.al(DedicatedServer.java:308)
at ho.r(DedicatedServer.java:270)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:289)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:193)
at fy.run(SourceFile:849)

**Comment by HaoSs07** [comment]
Question: Seems to be a rumor that alphaest will not update mytown/aperf/pex any more, will you ever consider taking over ? Probably not. but i had to ask :P

**Comment by LunNova** [comment]
It should be working now in latest, but it will likely still show that error once. Is that correct?

**Comment by HaoSs07** [comment]
will test when i get home , what about the question ?

**Comment by LunNova** [comment]
Possibly, they are all very useful mods. However, as usual, time constraints...

**Comment by HaoSs07** [comment]
I hope if it comes to that you will do it :D never seen a dev so dedicated to his work, aperf you could probably integrate in TT, usually users have it for the excellent entity lists/remove.

**Comment by HaoSs07** [comment]
this is working now. no error.
