### ISSUE TITLE
[TT1690, MCPC+ L38] Could not pass event BlockBurnEvent to GriefPrevention v7.7

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#567]
This error is spamming throughout the log. Not sure when it started, but currently using TT1690 and MCPC L38.

[SEVERE] Could not pass event BlockBurnEvent to GriefPrevention v7.7
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at akf.tryToCatchBlockOnFire(BlockFire.java:285)
    at akf.b(BlockFire.java:176)
    at in.a(WorldServer.java:346)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:405)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:499)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:623)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_4_R1.CraftWorld cannot be cast to me.ryanhamshire.GriefPrevention.Configuration.WorldConfig
    at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockBurn(BlockEventHandler.java:612)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
    ... 13 more

**Comment by joey19982** [comment]
My bad, this is a confirmed GriefPrevention Issue.
