### ISSUE TITLE
[TT1690, MCPC+ L33]Tried to unload null entity java.lang.Throwable

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#568]
2013-05-25 22:26:55 [WARNING] [TickThreading] Tried to unload null entity
java.lang.Throwable
    at yc.b(World.java:665)
    at zz.d(Chunk.java:186)
    at im.tick(ThreadedChunkProvider.java:177)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:398)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:499)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:623)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
These changes should make this error impossible, instead it will either be fixed, or you'll get a different error showing where something tried to add a null to a chunk's entity list. Closing this, as the most likely cause is fixed, and any other causes would be a different issue.
