### ISSUE TITLE
Build 442 - Squid error spam!

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#57]
STDERR]     at yc.g(World.java:2257)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:37)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:88)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:88)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)
2013-01-16 15:50:55 [INFO] [STDERR] java.lang.Exception: Stack trace
2013-01-16 15:50:55 [INFO] [STDERR]     at java.lang.Thread.dumpStack(Thread.java:1342)
2013-01-16 15:50:55 [INFO] [STDERR]     at zz.a_nolock(Chunk.java:923)
2013-01-16 15:50:55 [INFO] [STDERR]     at zz.a(Chunk.java)
2013-01-16 15:50:55 [INFO] [STDERR]     at yc.a(World.java:2340)
2013-01-16 15:50:55 [INFO] [STDERR]     at in.a(WorldServer.java:647)
2013-01-16 15:50:55 [INFO] [STDERR]     at yc.g(World.java:2257)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:37)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:88)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:88)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
2013-01-16 15:50:55 [INFO] [STDOUT] Wrong location! ph['Squid'/2683, l='world', x=2863.33, y=59.38, z=3975.95]
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)
2013-01-16 15:50:55 [INFO] [STDERR] java.lang.Exception: Stack trace
2013-01-16 15:50:55 [INFO] [STDERR]     at java.lang.Thread.dumpStack(Thread.java:1342)
2013-01-16 15:50:55 [INFO] [STDERR]     at zz.a_nolock(Chunk.java:923)
2013-01-16 15:50:55 [INFO] [STDERR]     at zz.a(Chunk.java)
2013-01-16 15:50:55 [INFO] [STDERR]     at yc.a(World.java:2340)
2013-01-16 15:50:55 [INFO] [STDOUT] Wrong location! ph['Squid'/2648, l='world', x=2747.75, y=56.39, z=3977.94]
2013-01-16 15:50:55 [INFO] [STDERR]     at in.a(WorldServer.java:647)
2013-01-16 15:50:55 [INFO] [STDERR]     at yc.g(World.java:2257)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:37)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:88)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:88)
2013-01-16 15:50:55 [INFO] [STDERR]     at me.nallar.tickthreading.minecraft.ThreadManager

**Comment by LunNova** [comment]
Damnit, squid! you ruin everything :(

Looks like a chunk has been loaded in the wrong coordinates (what?!) or minecraft's entity moving algorithm is broken, probably TT causing one of the above. For now, restart.

**Comment by gustav9797** [comment]
Worked, thankyou.

**Comment by gustav9797** [comment]
Closing, haven't noticed in newer builds. Reopen if you want.
