### ISSUE TITLE
[Question] Will TT work for FTB Ultimate 1.1.1?

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#574]
Just wondering encase its ok to update the server with TT to that version?

**Comment by LunNova** [comment]
Maybe? Haven't tried myself, but I don't see why not. Make a backup first (as you hopefully would anyway) and test it.

**Comment by alicheek** [comment]
OK here come the spams of errors :P 

[SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @335528718 in Overworld/0 at x, y, z: -2545, 49, -2737
java.lang.NoSuchMethodError: gregtechmod.api.IDigitalChest.isQuantumChest()Z
    at appeng.proxy.ProxyGregTech.isQuantumChest(ProxyGregTech.java:51)
    at appeng.proxy.helpers.GregTechHandler.canHandle(GregTechHandler.java:13)
    at appeng.common.AppEngExternalStorageRegistry.getHandler(AppEngExternalStorageRegistry.java:24)
    at appeng.me.tile.TileStorageBus.getInv(TileStorageBus.java:494)
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:102)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-27 22:53:25 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @595235690 in Overworld/0 at x, y, z: -2300, 59, -245
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-27 22:53:25 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @1293499776 in Overworld/0 at x, y, z: -2530, 38, -2751
java.lang.NoSuchMethodError: gregtechmod.api.IDigitalChest.isQuantumChest()Z
    at appeng.proxy.ProxyGregTech.isQuantumChest(ProxyGregTech.java:51)
    at appeng.proxy.helpers.GregTechHandler.canHandle(GregTechHandler.java:13)
    at appeng.common.AppEngExternalStorageRegistry.getHandler(AppEngExternalStorageRegistry.java:24)
    at appeng.me.tile.TileStorageBus.getInv(TileStorageBus.java:494)
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:102)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-27 22:53:25 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @595235690 in Overworld/0 at x, y, z: -2300, 59, -245
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-27 22:53:25 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @595235690 in Overworld/0 at x, y, z: -2300, 59, -245
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-27 22:53:25 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @595235690 in Overworld/0 at x, y, z: -2300, 59, -245
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-27 22:53:25 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @595235690 in Overworld/0 at x, y, z: -2300, 59, -245
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by HaoSs07** [comment]
im on 1.1.2 and latest TT. is working as intended :)

**Comment by LunNova** [comment]
1.1.1 did have its own set of issues. @alicheek are those errors still happening after updating to 1.1.2?

**Comment by floh22** [comment]
those errors dont happen for me, but the ic2 ones still do. i am on 1.1.2

**Comment by alicheek** [comment]
yep here are the logs here on TT 1718 MCPC+ L38

http://pastebin.com/St914cnX

**Comment by LunNova** [comment]
Fixed the IC2 issue in latest, still need to fix that AE issue.
