### ISSUE TITLE
Cant pass CreatureSpawnEvent, BlockIgniteEvent, and WorldUnloadEvent

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#578]
Im not sure if these are related to tickthreading, or the latest mcpc+, so I'll post them here first.
[SEVERE] Could not pass event WorldUnloadEvent to MobArena v0.94.4.96
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at net.minecraftforge.common.DimensionManager.fireBukkitWorldUnload(DimensionManager.java)
    at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:37)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:415)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getName(CraftWorld.java:489)
    at com.garbagemule.MobArena.ArenaMasterImpl.unloadArenasInWorld(ArenaMasterImpl.java:527)
    at com.garbagemule.MobArena.listeners.MAGlobalListener.worldUnloadEvent(MAGlobalListener.java:312)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
    ... 10 more
2013-05-28 04:11:00 [SEVERE] Could not pass event CreatureSpawnEvent to MobArena v0.94.4.96
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at org.bukkit.craftbukkit.v1_4_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:211)
    at yc.addEntity(World.java:1843)
    at yc.d(World.java:1806)
    at yp.spawnMobsQuickly(SpawnerAnimals.java:205)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:390)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:502)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:626)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getName(CraftWorld.java:489)
    at com.garbagemule.MobArena.region.ArenaRegion.contains(ArenaRegion.java:151)
    at com.garbagemule.MobArena.ArenaListener.onCreatureSpawn(ArenaListener.java:291)
    at com.garbagemule.MobArena.listeners.MAGlobalListener.creatureSpawn(MAGlobalListener.java:119)
    at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
    ... 13 more
2013-05-28 04:17:58 [SEVERE] Could not pass event BlockIgniteEvent to MobArena v0.94.4.96
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at org.bukkit.craftbukkit.v1_4_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:65)
    at akz.b(BlockStationary.java:88)
    at in.run(WorldServer.java:597)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException

**Comment by LunNova** [comment]
Looks like these plugins are trying to use unloaded worlds. Turn off world unloading in TT's config.
