### ISSUE TITLE
Mmory errors? [TT1718][MCPC+ L32

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#587]
2013-05-28 23:29:02 [SEVERE] Exception in thread "Thread-75"
2013-05-28 23:29:02 [SEVERE] java.lang.OutOfMemoryError: PermGen space
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.getDeclaredConstructors0(Native Method)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.getConstructor0(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.newInstance0(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.newInstance(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.security.AccessController.doPrivileged(Native Method)
2013-05-28 23:29:02 [SEVERE]    at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.lang.reflect.Constructor.newInstance(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.newInstance0(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Class.newInstance(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.LibFunction.bind(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.LibFunction.bind(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.MathLib.call(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.jse.JseMathLib.call(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.OneArgFunction.call(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.LuaValue.load(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.jse.JsePlatform.standardGlobals(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at org.luaj.vm2.lib.jse.JsePlatform.debugGlobals(Unknown Source)
2013-05-28 23:29:02 [SEVERE]    at dan200.computer.core.LuaJLuaMachine.<init>(LuaJLuaMachine.java:32)
2013-05-28 23:29:02 [SEVERE]    at dan200.computer.core.Computer.initLua(Computer.java:806)
2013-05-28 23:29:02 [SEVERE]    at dan200.computer.core.Computer.access$1300(Computer.java:31)
2013-05-28 23:29:02 [SEVERE]    at dan200.computer.core.Computer$1.execute(Computer.java:925)
2013-05-28 23:29:02 [SEVERE]    at dan200.computer.core.ComputerThread$1$1.run(ComputerThread.java:72)
2013-05-28 23:29:02 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2013-05-28 23:29:03 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.OutOfMemoryError: PermGen space
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
        at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at yp.spawnMobsQuickly(SpawnerAnimals.java:200)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:390)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:505)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-28 23:29:04 [INFO] Bud1980 issued server command: /tp cody
2013-05-28 23:29:06 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.OutOfMemoryError: PermGen space
        at sun.misc.Unsafe.defineClass(Native Method)
        at sun.reflect.ClassDefiner.defineClass(Unknown Source)
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
        at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at yp.spawnMobsQuickly(SpawnerAnimals.java:200)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:390)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:505)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-28 23:29:07 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.OutOfMemoryError: PermGen space
        at sun.misc.Unsafe.defineClass(Native Method)
        at sun.reflect.ClassDefiner.defineClass(Unknown Source)
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
        at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
        at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at yp.spawnMobsQuickly(SpawnerAnimals.java:200)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:390)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:505)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-28 23:29:09 [SEVERE] [TickThreading] Exception ticking world Overworld/0
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
2013-05-28 23:29:11 [SEVERE] [TickThreading] Exception ticking world Overworld/0
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
2013-05-28 23:29:26 [SEVERE] Exception in thread "Deadlock Detector"
2013-05-28 23:29:26 [SEVERE] java.lang.NoClassDefFoundError: me/nallar/tickthreading/minecraft/DeadLockDetector$2
2013-05-28 23:29:26 [SEVERE]    at me.nallar.tickthreading.minecraft.DeadLockDetector.sendChatSafely(DeadLockDetector.java:71)
2013-05-28 23:29:26 [SEVERE]    at me.nallar.tickthreading.minecraft.DeadLockDetector.checkForDeadlocks(DeadLockDetector.java:117)
2013-05-28 23:29:26 [SEVERE]    at me.nallar.tickthreading.minecraft.DeadLockDetector$1.run(DeadLockDetector.java:46)
2013-05-28 23:29:26 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2013-05-28 23:29:26 [SEVERE] Caused by: java.lang.ClassNotFoundException: me.nallar.tickthreading.minecraft.DeadLockDetector$2
2013-05-28 23:29:26 [SEVERE]    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:218)
2013-05-28 23:29:26 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-28 23:29:26 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-28 23:29:26 [SEVERE]    ... 4 more
2013-05-28 23:29:26 [SEVERE] Caused by: java.lang.OutOfMemoryError: PermGen space

**Comment by LunNova** [comment]
Add -XX:MaxPermSize=192m to your java parameters.
