### ISSUE TITLE
Overworld tick errors [TT1721] [MCPC+ L44] 

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#588]
2013-05-29 00:02:26 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
        at java.util.LinkedList.unlink(Unknown Source)
        at java.util.LinkedList.remove(Unknown Source)
        at thaumcraft.common.AuraWorldTicker.tickEnd(AuraWorldTicker.java:63)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at me.nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:77)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:283)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:509)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 00:02:26 [SEVERE] [TickThreading] Exception ticking world Overworld/15
java.lang.NullPointerException
        at java.util.LinkedList.unlink(Unknown Source)
        at java.util.LinkedList.remove(Unknown Source)
        at thaumcraft.common.AuraWorldTicker.tickEnd(AuraWorldTicker.java:63)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at me.nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:77)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:283)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:509)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 00:02:40 [INFO] Giving robogift1 1 of Nether Brick Fence
2013-05-29 00:02:45 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
        at java.util.LinkedList.get(Unknown Source)
        at thaumcraft.common.AuraWorldTicker.tickEnd(AuraWorldTicker.java:46)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at me.nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:77)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:283)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:509)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Can you try updating MCPC+ to L48? Quite a few known issues with dimensions in the version you're using.

**Comment by Bucky420** [comment]
if i do that then the spawn world wont load ;_;

**Comment by LunNova** [comment]
Have you reported that issue to MCPC+? If not, make sure to report to them, after checking that someone else hasn't already reported it.

I can't really do anything here to fix it, it's an MCPC+ issue which just happens to be more of a problem under TT.

**Comment by LunNova** [comment]
Fixed with newer MCPC+ builds.
