### ISSUE TITLE
Build 442 - Failed to send chunk updates

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#59]
2013-01-16 16:11:04 [SEVERE] [TickThreading] Failed to send some chunk updates
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at ik.b(SourceFile:145)
        at in.b(WorldServer.java:182)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:253)
        at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:318)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)

**Comment by LunNova** [comment]
Should be fixed in build 443.

**Comment by LunNova** [comment]
erm, 444.
