### ISSUE TITLE
[TT1728, MCPC L48] [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#593]
Console is spammed with these errors. My admins had to go around and remove the "bugging" conductive pipes to remove console spam.

2013-05-29 07:56:57 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @893324479 in Overworld/0 at x, y, z: 2644, 61, 1140
java.lang.NullPointerException

> ```
>   at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
>   at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
>   at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
>   at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
>   at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
>   at any.tickTT(TileEntity.java:51)
>   at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
>   at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>   at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
>   at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
>   at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
> ```

**Comment by mainsheep** [comment]
Probably happening when a chunk is loading, the pipe doesn't "remember" how it was placed.

**Comment by alicheek** [comment]
Yea im getting this too on TT 1728:

2013-05-29 13:58:59 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @1526881819 in Overworld/0 at x, y, z: 839, 58, 1866
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 13:58:59 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @1526881819 in Overworld/0 at x, y, z: 839, 58, 1866
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 13:58:59 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @1526881819 in Overworld/0 at x, y, z: 839, 58, 1866
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 13:58:59 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @1526881819 in Overworld/0 at x, y, z: 839, 58, 1866
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 13:58:59 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @1526881819 in Overworld/0 at x, y, z: 839, 58, 1866
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-29 13:58:59 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @1526881819 in Overworld/0 at x, y, z: 839, 58, 1866
java.lang.NullPointerException
    at gregtechmod.api.BaseMetaTileEntityMJ.powerRequest(BaseMetaTileEntityMJ.java:51)
    at buildcraft.transport.PipeTransportPower.updateEntity_sync0(PipeTransportPower.java:164)
    at buildcraft.transport.PipeTransportPower.updateEntity(PipeTransportPower.java)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
