### ISSUE TITLE
Support for MCPC-Plus 1.4.7

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#61]
http://www.mcportcentral.co.za/index.php?topic=4657.0

It has forge and bukkit combined, you don't have to port plugins. Maybe it's possible to support it some time in the future?

**Comment by LunNova** [comment]
It should just work - no remapping is needed, that uses obfuscated names.

**Comment by gustav9797** [comment]
I'll look more into this tomorrow as I did get an error. TickThreading with MCPC plus would do the perfect server.

**Comment by gustav9797** [comment]
This is what I get after running the server once with tickthreading 453 and then patching and on startup:

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.ja
va:138)
        at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelaunc
her.java:33)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1656)
        at org.bukkit.craftbukkit.Main.main(Main.java:18)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.fuseso
urce.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSu
pport.java:50)
        at jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:176)
        at jline.WindowsTerminal.init(WindowsTerminal.java:80)
        at jline.TerminalFactory.create(TerminalFactory.java:93)
        at jline.TerminalFactory.get(TerminalFactory.java:151)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:140)
        at jline.console.ConsoleReader.<init>(ConsoleReader.java:126)
        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:238)
        at ho.<init>(DedicatedServer.java:53)
        at net.minecraft.server.MinecraftServer.fmlReentry(MinecraftServer.java:
1721)
        ... 8 more

**Comment by LunNova** [comment]
Try adding "-nojline" after the -jar <jarname> part of your start.bat.

**Comment by gustav9797** [comment]
It now starts properly, but running into this error: http://pastebin.com/f8g80c5X

**Comment by LunNova** [comment]
Can you repatch with build 458 and try again?

**Comment by gustav9797** [comment]
Not any difference. Didn't mcpc plus have problems with world generation?
This error I gave you was when loading a previously generated world.

**Comment by LunNova** [comment]
I gave the wrong build number in my comment then edited - did you use 458?

If you did, can I see the patcher.log?

**Comment by LunNova** [comment]
Oh, this was an MCPC+ bug! You were loading chunks.

edit: Or unloading chunks

`<blood> public LongObjectHashMap<Chunk> loadedChunks = new LongObjectHashMap<Chunk>();
<blood> changed to loadedChunks
<blood> which should now obfuscate properly`

**Comment by gustav9797** [comment]
Still getting

Time: 1/18/13 4:46 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: b
    at im.c(ChunkProviderServer.java:78)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:509)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:461)
    at ho.c(DedicatedServer.java:194)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
    at fy.run(ThreadMinecraftServer.java:16)

with the build 471 and 0.3 mcpc+
