### ISSUE TITLE
[MCPC +31] [TT1780] AE NPE

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#611]
Just a client boot with "Internal Server Error" when I tried to open a crafting monitor. Don't have a clue what caused it but I am currently unable to open my ME System and trying to change one thing at a time untill it stops happening..

> 2013-05-31 02:14:11 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @422108167 in CJ_Bunker/35 at x, y, z: 375, 40, 233
> java.lang.NullPointerException
>     at appeng.me.tile.TileController.g(TileController.java:1024)
>     at any.tickTT(TileEntity.java:51)
>     at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
>     at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>     at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
>     at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
>     at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
> 02:14:14 [INFO] even2001 issued server command: /home
> 2013-05-31 02:15:09 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 3594
> java.lang.NullPointerException
>     at appeng.me.tile.TileController.getFullCellArray(TileController.java:803)
>     at appeng.me.GridInterface.getFullCellArray(GridInterface.java:161)
>     at appeng.me.tile.TileTerminal.provideCell(TileTerminal.java:76)
>     at appeng.me.NetworkedIMEI.update(NetworkedIMEI.java:107)
>     at appeng.common.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:438)
>     at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:253)
>     at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:242)
>     at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:73)
>     at iv.a(NetServerHandler.java:2073)
>     at di.a(Packet250CustomPayload.java:70)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:419)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:294)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
>     at fy.run(ThreadMinecraftServer.java:16)
> 02:15:09 [WARNING] Failed to handle packet for cjm721/50.122.85.15: java.lang.NullPointerException
> java.lang.NullPointerException
>     at appeng.me.tile.TileController.getFullCellArray(TileController.java:803)
>     at appeng.me.GridInterface.getFullCellArray(GridInterface.java:161)
>     at appeng.me.tile.TileTerminal.provideCell(TileTerminal.java:76)
>     at appeng.me.NetworkedIMEI.update(NetworkedIMEI.java:107)
>     at appeng.common.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:438)
>     at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:253)
>     at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:242)
>     at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:73)
>     at iv.a(NetServerHandler.java:2073)
>     at di.a(Packet250CustomPayload.java:70)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:419)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:294)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
>     at fy.run(ThreadMinecraftServer.java:16)

**Comment by cjm721** [comment]
Breaking and replacing the controller fixed the issue. Tried taking out the cells before and had no effect on fixing it.
