### ISSUE TITLE
[TT 1780, MCPC+ L38] [SEVERE] [TickThreading] The server appears to have deadlocked.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#614]
http://pastebin.com/3xt99fPH

**Comment by alicheek** [comment]
at gregtechmod.common.tileentities.GT_MetaTileEntity_AdvancedPump.scanForFluid(GT_MetaTileEntity_AdvancedPump.java:174)
    at gregtechmod.common.tileentities.GT_MetaTileEntity_AdvancedPump.scanForFluid(GT_MetaTileEntity_AdvancedPump.java:174)
    at gregtechmod.common.tileentities.GT_MetaTileEntity_AdvancedPump.onPostTick(GT_MetaTileEntity_AdvancedPump.java:126)
    at gregtechmod.api.BaseMetaTileEntity.g(BaseMetaTileEntity.java:299)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    -  locked me.nallar.tickthreading.util.concurrent.NativeMutex@67dc2853
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    -  locked me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@26db966a
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

"File IO Thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at aiw.b(ThreadedFileIOBase.java:61)
    at aiw.run(ThreadedFileIOBase.java:27)
    at java.lang.Thread.run(Thread.java:722)

"Finalizer" WAITING on java.lang.ref.ReferenceQueue$Lock@7e5c6ebd
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.ref.ReferenceQueue$Lock@7e5c6ebd
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:177)

"Immibis Core background task" TIMED_WAITING on java.util.TaskQueue@649fd65f
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@649fd65f
    at java.util.TimerThread.mainLoop(Timer.java:552)
    at java.util.TimerThread.run(Timer.java:505)

"Leak Detector" WAITING on java.util.TaskQueue@79193005
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@79193005
    at java.lang.Object.wait(Object.java:503)
    at java.util.TimerThread.mainLoop(Timer.java:526)
    at java.util.TimerThread.run(Timer.java:505)

"Listen thread" RUNNABLE
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:522)
    at java.net.ServerSocket.accept(ServerSocket.java:490)
    at hu.run(ServerListenThread.java:83)

"PermissionsEx-Cleaner" WAITING on java.util.TaskQueue@4db3d6c3
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@4db3d6c3
    at java.lang.Object.wait(Object.java:503)
    at java.util.TimerThread.mainLoop(Timer.java:526)
    at java.util.TimerThread.run(Timer.java:505)

"RMI TCP Accept-0" RUNNABLE (in native)
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:522)
    at java.net.ServerSocket.accept(ServerSocket.java:490)
    at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
    at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:387)
    at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:359)
    at java.lang.Thread.run(Thread.java:722)

"Reference Handler" WAITING on java.lang.ref.Reference$Lock@666a7b1a
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.ref.Reference$Lock@666a7b1a
    at java.lang.Object.wait(Object.java:503)
    at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)

"Server thread" TIMED_WAITING on java.lang.Object@4597604e
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.Object@4597604e
    at me.nallar.tickthreading.minecraft.ThreadManager.waitForCompletion(ThreadManager.java:86)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:414)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:294)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)

"Snooper Timer" TIMED_WAITING on java.util.TaskQueue@5533c493
    at java.lang.Object.wait(Native Method)
    -  waiting on java.util.TaskQueue@5533c493
    at java.util.TimerThread.mainLoop(Timer.java:552)
    at java.util.TimerThread.run(Timer.java:505)

"Spigot Metrics Gathering Thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at org.bukkit.craftbukkit.v1_4_R1.util.TimedThread.run(TimedThread.java:29)

"Thread-1863" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at cj.run(TcpMasterThread.java:17)

"Thread-43" RUNNABLE (in native)
    at java.net.PlainSocketImpl.socketAccept(Native Method)
    at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
    at java.net.ServerSocket.implAccept(ServerSocket.java:522)
    at java.net.ServerSocket.accept(ServerSocket.java:490)
    at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:114)

"Thread-46" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at cosine.boseconomy.BOSEconomyThread.run(BOSEconomyThread.java:104)

"Thread-48" RUNNABLE
    at java.net.PlainDatagramSocketImpl.peekData(Native Method)
    -  locked java.net.PlainDatagramSocketImpl@5496b98
    at java.net.DatagramSocket.receive(DatagramSocket.java:726)
    -  locked java.net.DatagramPacket@261b5a08
    -  locked java.net.DatagramSocket@4ab7def2
    at jb.run(RConThreadQuery.java:317)
    at java.lang.Thread.run(Thread.java:722)

"Thread-6" RUNNABLE (in native)
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:242)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
    -  locked java.io.BufferedInputStream@39b32a95
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167)
    at org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267)
    -  locked org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1@5975cfb4
    at org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204)
    -  locked org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1@5975cfb4
    at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995)
    at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167)
    at hq.run(DedicatedServerCommandThread.java:37)

"World Tick - 7" TIMED_WAITING on java.lang.Object@2fa557eb
    at java.lang.Object.wait(Native Method)
    -  waiting on java.lang.Object@2fa557eb
    at me.nallar.tickthreading.minecraft.ThreadManager.waitForCompletion(ThreadManager.java:86)
    at me.nallar.tickthreading.minecraft.TickManager.postTick(TickManager.java:533)
    at me.nallar.tickthreading.minecraft.TickManager.doTick(TickManager.java:519)
    at yc.h_net_minecraft_world_World_updateEntities_p0(World.java:726)
    at yc.h(World.java)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:512)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

"pool-1-thread-1" WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@102f1dbd
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@102f1dbd
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
    at java.util.concurrent.DelayQueue.take(DelayQueue.java:209)
    at org.wargamer2010.signshop.player.MessageWorker.run(MessageWorker.java:86)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

```
Number of locked synchronizers = 1
- java.util.concurrent.ThreadPoolExecutor$Worker@5d74359c
```

"process reaper" TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@6a91757
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@6a91757
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
    at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
    at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

Attempting to recover without restarting.

**Comment by LunNova** [comment]
It didn't deadlock, just GT pumps are badly designed. Even worse than BC's, apparently, it took more than a minute to scan for fluids.

**Comment by LunNova** [comment]
Not something I can fix without rewriting GT pumps.
