### ISSUE TITLE
[TT 1780, MCPC+ L38] [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.logic.TileLogicSimple @2037314962 in Overworld/0 at x, y, z: 5243, 68, 3408

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#616]
2013-05-31 11:35:53 [SEVERE] [TickThreading] Exception ticking TileEntity c com.eloraam.redpower.logic.TileLogicSimple @2037314962 in Overworld/0 at x, y, z: 5243, 68, 3408
java.lang.NullPointerException
    at any.sendTileWithNotify(TileEntity.java:61)
    at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java)
    at com.eloraam.redpower.logic.TileLogicSimple.simpleTick(TileLogicSimple.java:485)
    at com.eloraam.redpower.logic.TileLogicSimple.lightTick(TileLogicSimple.java:410)
    at com.eloraam.redpower.logic.TileLogicSimple.onTileTick(TileLogicSimple.java:570)
    at com.eloraam.redpower.core.TileExtended.g(TileExtended.java:123)
    at com.eloraam.redpower.logic.TileLogicSimple.g(TileLogicSimple.java:664)
    at any.tickTT(TileEntity.java:51)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed, forgot to close this.
