### ISSUE TITLE
[TT 1793, MCPC+ L38] [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 6

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#625]
Getting huge amounts of spam from this about 36mbs in 2 hours

013-06-01 00:34:35 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 6
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:35 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 6
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:35 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 6
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:35 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 6
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:36 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 6
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:36 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 9
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:36 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 2
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 00:34:36 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Nether/-1 - 10
java.lang.IllegalStateException: Already iterating.
    at me.nallar.collections.LinkedHashSetTempSetNoClear.startIteration(LinkedHashSetTempSetNoClear.java:40)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:30)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
[SEVERE] [TickThreading] Exception ticking world World_VIP/13
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:00:47 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:00:52 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:00:55 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:00:55 [SEVERE] [TickThreading] Exception ticking world World_VIP/13
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:00:57 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:02 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:05 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at in.a(WorldServer.java:161)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:532)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:05 [SEVERE] [TickThreading] Exception ticking world World_VIP/13
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at in.a(WorldServer.java:161)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:532)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:07 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at in.a(WorldServer.java:161)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:532)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:12 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at in.a(WorldServer.java:161)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:532)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:15 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:15 [SEVERE] [TickThreading] Exception ticking world World_VIP/13
java.lang.NoSuchFieldError: h
    at im.a(ThreadedChunkProvider.java:779)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:535)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-01 01:01:17 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NoSuchFieldError: h

**Comment by alicheek** [comment]
one hell of a speedy fix thanks nallar :)
