### ISSUE TITLE
[TT 1796, MCPC+ L38] [SEVERE] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#627]
2013-06-01 01:54:50 [SEVERE] java.util.ConcurrentModificationException
2013-06-01 01:54:50 [SEVERE]    at java.util.ArrayList.writeObject(ArrayList.java:713)
2013-06-01 01:54:50 [SEVERE]    at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
2013-06-01 01:54:50 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-06-01 01:54:50 [SEVERE]    at java.lang.reflect.Method.invoke(Method.java:601)
2013-06-01 01:54:50 [SEVERE]    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:975)
2013-06-01 01:54:50 [SEVERE]    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1480)
2013-06-01 01:54:50 [SEVERE]    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
2013-06-01 01:54:50 [SEVERE]    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
2013-06-01 01:54:50 [SEVERE]    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
2013-06-01 01:54:50 [SEVERE]    at twilightforest.TFFeatureCache.save_sync0(TFFeatureCache.java:120)
2013-06-01 01:54:50 [SEVERE]    at twilightforest.TFFeatureCache.save(TFFeatureCache.java)
2013-06-01 01:54:50 [SEVERE]    at twilightforest.world.TFWorldChunkManager.saveFeatureCache(TFWorldChunkManager.java:415)
2013-06-01 01:54:50 [SEVERE]    at twilightforest.TFEventListener.worldSave(TFEventListener.java:429)
2013-06-01 01:54:50 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_117_TFEventListener_worldSave_Save.invoke(.dynamic)
2013-06-01 01:54:50 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-06-01 01:54:50 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-06-01 01:54:50 [SEVERE]    at in.a(WorldServer.java:164)
2013-06-01 01:54:50 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:532)
2013-06-01 01:54:50 [SEVERE]    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:634)
2013-06-01 01:54:50 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
2013-06-01 01:54:50 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by darkdeath1332** [comment]
My error links to this.
