### ISSUE TITLE
[TT1800][MCPC+53]java.lang.ClassCastException: abb cannot be cast to org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#631]
2013-06-01 01:07:02 [INFO] ICBM Rejuvenation Failed!
2013-06-01 01:07:02 [SEVERE] java.lang.ClassCastException: abb cannot be cast to org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator
2013-06-01 01:07:02 [SEVERE]    at icbm.common.zhapin.ex.ExHuanYuan.doBaoZha(ExHuanYuan.java:41)
2013-06-01 01:07:02 [SEVERE]    at icbm.common.zhapin.ZhaPin.createBaoZha(ZhaPin.java:379)
2013-06-01 01:07:02 [SEVERE]    at icbm.common.zhapin.EZhaDan.explode(EZhaDan.java:107)
2013-06-01 01:07:02 [SEVERE]    at icbm.common.zhapin.EZhaDan.j_(EZhaDan.java:92)
2013-06-01 01:07:02 [SEVERE]    at yc.a(World.java:390)
2013-06-01 01:07:02 [SEVERE]    at in.a(WorldServer.java:844)
2013-06-01 01:07:02 [SEVERE]    at yc.g(World.java:2716)
2013-06-01 01:07:02 [SEVERE]    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:60)
2013-06-01 01:07:02 [SEVERE]    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
2013-06-01 01:07:02 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
2013-06-01 01:07:02 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
2013-06-01 01:07:02 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
This is an MCPC+ issue, can you make an issue there?
