### ISSUE TITLE
long deadlock 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#632]
https://gist.github.com/HaoSs07/5690301

**Comment by HaoSs07** [comment]
also the deadlock seems to no longer stop the server completely ?

Attempting to recover without restarting.
2013-06-01 16:07:14 [SEVERE] [TickThreading] Failed to recover from the deadlock.
2013-06-01 16:07:14 [INFO] [STDERR] java.net.SocketException: Socket closed
2013-06-01 16:07:14 [INFO] [STDERR] at java.net.PlainSocketImpl.socketAccept(Native Method)
2013-06-01 16:07:14 [INFO] [STDERR] at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
2013-06-01 16:07:14 [INFO] [STDERR] at java.net.ServerSocket.implAccept(Unknown Source)
2013-06-01 16:07:14 [INFO] [STDERR] at java.net.ServerSocket.accept(Unknown Source)
2013-06-01 16:07:14 [INFO] [STDERR] at hu.run(ServerListenThread.java:81)
2013-06-01 16:07:14 [INFO] [STDOUT] Closing listening thread
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: Unfaxth
2013-06-01 16:07:15 [INFO] [STDERR] java.net.SocketException: Broken pipe
2013-06-01 16:07:15 [INFO] [STDERR] at java.net.SocketOutputStream.socketWrite0(Native Method)
2013-06-01 16:07:15 [INFO] [STDERR] at java.net.SocketOutputStream.socketWrite(Unknown Source)
2013-06-01 16:07:15 [INFO] [STDERR] at java.net.SocketOutputStream.write(Unknown Source)
2013-06-01 16:07:15 [INFO] [STDERR] at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
2013-06-01 16:07:15 [INFO] [STDERR] at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
2013-06-01 16:07:15 [INFO] [STDERR] at java.io.BufferedOutputStream.flush(Unknown Source)
2013-06-01 16:07:15 [INFO] [STDERR] at java.io.DataOutputStream.flush(Unknown Source)
2013-06-01 16:07:15 [INFO] [STDERR] at ci.run(SourceFile:120)
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: NFEN
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: HaoSs07
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: Paris
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: Lonelly
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: Hugna
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: KenVelo
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: Jexeld
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: SilverCrow
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: PH77SER
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: mihneaG
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: xZocker
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: HRT
2013-06-01 16:07:15 [INFO] [STDOUT] Unloading Player: ErcHaos
2013-06-01 16:07:16 [INFO] [TickThreading] Attempting to save
2013-06-01 16:07:16 [INFO] [Minecraft] Saving chunks for level 'world'/Overworld
2013-06-01 16:07:16 [INFO] [Minecraft] Saving chunks for level 'world'/Nether
2013-06-01 16:07:16 [INFO] [Minecraft] Saving chunks for level 'world'/The End
2013-06-01 16:07:16 [INFO] [Minecraft] Saving chunks for level 'world'/Twilight Forest
2013-06-01 16:07:17 [INFO] [Minecraft] Saving chunks for level 'world'/Age 18
2013-06-01 16:07:23 [INFO] [TickThreading] Saved, now attempting to stop the server and disconnect players cleanly
2013-06-01 16:07:23 [INFO] [Minecraft] Stopping server
2013-06-01 16:07:23 [INFO] [Minecraft] Saving players
2013-06-01 16:07:23 [INFO] [STDOUT] Unloading Player: ErcHaos

2013-06-01 16:12:16 [SEVERE] [TickThreading] Froze while attempting to stop - halting server.
2013-06-01 16:12:16 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:31)
at java.lang.Runtime.exit(Unknown Source)
at me.nallar.tickthreading.minecraft.DeadLockDetector$6.run(DeadLockDetector.java:258)

and thats all. gamecp still see's server online.

**Comment by HaoSs07** [comment]
fix also include the slow shutdown ?

**Comment by LunNova** [comment]
It'll now deliberately crash the JVM if it takes more than 6 minutes to stop.

**Comment by HaoSs07** [comment]
ill test this next deadlock. i waited like 4-5 minutes after the deliberately crash and gamecp was seeing the server online ( query probability was still on ? )
