### ISSUE TITLE
[TT1807 - MCPC+ L53] java.lang.NullPointerException at thaumcraft.common.AuraManager.generateNodeNeighbours(AuraManager.java:111)

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#633]
About 5 minutes after the server starts this starts appearing and spams the log.

2013-06-01 09:44:11 [SEVERE] java.lang.NullPointerException
2013-06-01 09:44:11 [SEVERE]    at thaumcraft.common.AuraManager.generateNodeNeighbours(AuraManager.java:111)
2013-06-01 09:44:11 [SEVERE]    at thaumcraft.common.EventHandler.chunkLoad(EventHandler.java:213)
2013-06-01 09:44:11 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_83_EventHandler_chunkLoad_Load.invoke(.dynamic)
2013-06-01 09:44:11 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-06-01 09:44:11 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-06-01 09:44:11 [SEVERE]    at aam.a(ThreadedChunkLoader.java:188)
2013-06-01 09:44:11 [SEVERE]    at aam.a(ThreadedChunkLoader.java:159)
2013-06-01 09:44:11 [SEVERE]    at im.f(ThreadedChunkProvider.java:705)
2013-06-01 09:44:11 [SEVERE]    at im.getChunkAtInternal(ThreadedChunkProvider.java:518)
2013-06-01 09:44:11 [SEVERE]    at im.getChunkAt(ThreadedChunkProvider.java:492)
2013-06-01 09:44:11 [SEVERE]    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:883)
2013-06-01 09:44:11 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2013-06-01 09:44:11 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2013-06-01 09:44:11 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Duplicates #630, which I had closed as fixed but actually isn't.
