### ISSUE TITLE
[TT1816 - MCPC+ L55] Continuous Crashing - Expecting to find unitialized object on stack

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#635]
Every few minutes the server automatically restarts with this error:

2013-06-01 21:29:24 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.VerifyError: (class: appeng/me/tile/TileStorageBus, method: g signature: ()V) Expecting to find unitialized object on stack
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at any.c(TileEntity.java:142)
    at aam.a(ThreadedChunkLoader.java:463)
    at aam.a(ThreadedChunkLoader.java:185)
    at aam.a(ThreadedChunkLoader.java:159)
    at im.f(ThreadedChunkProvider.java:705)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:518)
    at im.d(ThreadedChunkProvider.java:422)
    at yc.e(World.java:215)
    at yc.q(World.java:325)
    at in.q(WorldServer.java:161)
    at miscperipherals.core.ChunkLoadingCallback.ticketsLoaded(ChunkLoadingCallback.java:49)
    at net.minecraftforge.common.ForgeChunkManager.loadForcedChunks(ForgeChunkManager.java:261)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:365)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:510)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:399)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-01 21:38:18 [INFO] [TickThreading] Stopping the server. serverRunning: true, serverIsRunning: true, is crash: true
2013-06-01 21:38:31 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:31)
    at java.lang.Runtime.exit(Unknown Source)
    at java.lang.System.exit(Unknown Source)
    at ho.p(DedicatedServer.java:304)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:259)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by alexbegt** [comment]
oh no
