### ISSUE TITLE
TT1817 / MCPC L57 - Deadlock

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#636]
Gist : https://gist.github.com/Nohau/5693247

Server was only able to stay up for maybe 1 min then deadlocked.

I have rolled back to TickThreading-1.4.7-1.0.0.1786.jar and seems stable at this point.

Also noticed Load raised up to pass 400% right before the deadlock failed..

**Comment by floh22** [comment]
ME storage bus seem to deadlock the server. no error yet, sorry

**Comment by floh22** [comment]
dealock is fixed and they are functional but i get this error spammed:

2013-06-02 19:22:24 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @812827371 in Overworld/0 at x, y, z: 102, 64, -4618
java.lang.NullPointerException
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:166)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
