### ISSUE TITLE
[TT 1818, MCPC+ L38] [SEVERE] [TickThreading] Started iterating when not previously done

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#641]
[SEVERE] [TickThreading] Started iterating when not previously done
        at me.nallar.collections.ArrayListTempSetNoClear.startIteration(ArrayListTempSetNoClear.java:43)
        at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:132)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
just an update ive got 52mb of this spam in 3 hours :P

**Comment by alicheek** [comment]
@nallar 

on TT build 1822 and getting this now already got 6mb of spam in 3 mins :P 

2013-06-03 03:51:30 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @300499158 in overworld/0 at x, y, z: 4311, 151, -412
java.lang.NullPointerException
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:166)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
