### ISSUE TITLE
[TT 1818, MCPC+ L38]  [SEVERE] [TickThreading] Started iterating when not previously done

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#642]
2013-06-02 17:39:14 [SEVERE] [TickThreading] Started iterating when not previously done
    at me.nallar.collections.ArrayListTempSetNoClear.startIteration(ArrayListTempSetNoClear.java:43)
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:132)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
sorry copy of #641
