### ISSUE TITLE
 Exception ticking TileEntity c appeng.me.tile.TileStorageBus

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#645]
[SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @1688301205 in anew/0 at x, y, z: 451, 84, 1556
java.lang.NullPointerException
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:166)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

This is spammed constantly, essentially crashing the server

**Comment by Tencao** [comment]
From speaking to the owner of the base, he said this

I'll remove all my unconnected buses when the server recovers
Apparently it doesn't like unconnected storage buses :(

**Comment by Nohau** [comment]
+1 seen this as well when the bus is not connected to the network it causes the exception.

**Comment by CappyT** [comment]
@Tencao It's nallar fault, yesterday we talked on IRC, and he tried to fix a problem with MFFS reported by me. I suggest you tu use TT 1816, it's perfect and stable in my opinion.
