### ISSUE TITLE
[TT 1826, MCPC+ L38] [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @436863127 in overworld/0 at x, y, z: 3191, 47, -876

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#649]
2013-06-03 14:57:10 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @436863127 in overworld/0 at x, y, z: 3191, 47, -876
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by wormzjl** [comment]
Didn't see this one...
https://github.com/nallar/TickThreading/issues/657

**Comment by OriginalMadman** [comment]
I have a ton of exactly the same and its driving me nuts. Server deadlocks all the time and does not recover.

Still on TT1870 and MCPC L67

**Comment by alicheek** [comment]
Don't think the dead locking is to do with that I've had these errors for a whole now and had no relations to a deadlock with it , don't worry nallar will fix it when he has the time just e patient :)

**Comment by alicheek** [comment]
OH My Days! Thank you Nallar ill test it when I can get it on (probs will be later on tonight when its a bit quieter)
