### ISSUE TITLE
[WARNING] [TickThreading] Tried to set invalid block ID

### ISSUE THREAD

**Issue by xiph3r** [MinimallyCorrect/TickThreading#662]
2013-06-05 06:04:33 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-06-05 06:04:36 [INFO] [TickThreading] Skipping version tick handler c com.pahimar.ee3.core.handlers.VersionCheckTickHandler com.pahimar.ee3.core.handlers.VersionCheckTickHandler@16dffda7
2013-06-05 06:04:47 [INFO] [TickThreading] Threading initialised for world Twilight Forest/7
2013-06-05 06:04:48 [INFO] [TickThreading] Threading initialised for world The End/1
2013-06-05 06:04:48 [INFO] [TickThreading] Threading initialised for world Nether/-1
2013-06-05 06:04:48 [INFO] [TickThreading] Threading initialised for world Overworld/0
2013-06-05 06:04:50 [INFO] [TickThreading] Threading initialised for world Hyrule/336
2013-06-05 06:05:06 [SEVERE] [TickThreading] TickThreading v1.0.0.1830 for MC1.4.7 on 1.4.7 tickthreading,mcpc,spigot,craftbukkit,forge,fml is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading

Also, you really should be making regular backups. (You should be doing that even when not using TT.)
2013-06-05 06:05:08 [INFO] [TickThreading] Threading initialised for world DIM_MYST74/74
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:2
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 208:0
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:2
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:4
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:1
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:2
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:3
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 208:0
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:1
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-05 06:05:47 [WARNING] [TickThreading] Tried to set invalid block ID 209:0
    at zz.a(Chunk.java:427)
    at yc.a(World.java:767)
    at yc.c(World.java:745)
    at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:124)
    at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
    at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:358)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Towny's trying to do something stupid - restore a changed plot to an old version with IDs which no longer exist?

I can't disable the warning, as it may mean that something has gone badly wrong. In this case, it just looks like towny did something odd, but it probably won't break anything, and should be ignored.

If it's constantly spamming this then something's a bit more broken, comment if that's the case.

**Comment by xiph3r** [comment]
i didnt know what was causing it but when u said townys i cleared the regen.txt  in /towny/settings/data/  and no more errors. thanks for pointing me int he right direction. LOVE YOUR MOD!!!
