### ISSUE TITLE
Problem with chunks ?

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#672]
2013-05-24 20:03:27 [SEVERE] java.lang.Exception
2013-05-24 20:03:27 [SEVERE]    at zz.a(Chunk.java:1095)
2013-05-24 20:03:27 [SEVERE]    at yc.a(World.java:3296)
2013-05-24 20:03:27 [SEVERE]    at com.xcompwiz.mystcraft.block.BlockWritingDesk.g(BlockWritingDesk.java:230)
2013-05-24 20:03:27 [SEVERE]    at zz.a(Chunk.java:406)
2013-05-24 20:03:27 [SEVERE]    at yc.a(World.java:763)
2013-05-24 20:03:27 [SEVERE]    at yc.c(World.java:741)
2013-05-24 20:03:27 [SEVERE]    at aez.a(StructureComponent.java:544)
2013-05-24 20:03:27 [SEVERE]    at afs.a(ComponentVillage.java:220)
2013-05-24 20:03:27 [SEVERE]    at com.xcompwiz.mystcraft.world.gen.structure.ComponentVillageArchivistHouse.placeDeskAt(ComponentVillageArchivistHouse.java:187)
2013-05-24 20:03:27 [SEVERE]    at com.xcompwiz.mystcraft.world.gen.structure.ComponentVillageArchivistHouse.a(ComponentVillageArchivistHouse.java:118)
2013-05-24 20:03:27 [SEVERE]    at afb.a(StructureStart.java:35)
2013-05-24 20:03:27 [SEVERE]    at aev.a(MapGenStructure.java:71)
2013-05-24 20:03:27 [SEVERE]    at abb.a(ChunkProviderGenerate.java:533)
2013-05-24 20:03:27 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:46)
2013-05-24 20:03:27 [SEVERE]    at im.populate(ThreadedChunkProvider.java:630)
2013-05-24 20:03:27 [SEVERE]    at im.tryPopulateChunks(ThreadedChunkProvider.java:650)
2013-05-24 20:03:27 [SEVERE]    at im.getChunkAtInternal(ThreadedChunkProvider.java:615)
2013-05-24 20:03:27 [SEVERE]    at im.getChunkAt(ThreadedChunkProvider.java:501)
2013-05-24 20:03:27 [SEVERE]    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:881)
2013-05-24 20:03:27 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2013-05-24 20:03:27 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2013-05-24 20:03:27 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

TickThreading 1818
FTB Ultimate 1.1.2 with a few bukkit plugins.

**Comment by alicheek** [comment]
pretty sure that one is already fixed just use latest

**Comment by LunNova** [comment]
Set mcpc.warn-place-no-tile-entity to false in your MCPC+ config.
