### ISSUE TITLE
GriefPrevention problem.

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#673]
2013-06-08 02:08:19 [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.6.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at aky.b(BlockFlowing.java:220)
    at in.a(WorldServer.java:346)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:405)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:510)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:633)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException

TickThreading 1818 ftb ult 1.1.2
hope tickthreading can solve this :$

**Comment by Tencao** [comment]
This can be fixed by disabling cleanworlds
    B:cleanWorlds=false

**Comment by ThuGie** [comment]
I think you are right, i noticed it happened when people where going to the twighlight forest.
Disabled cleanWorls like you said and its gone!

Wont this have any bad effects though ?

**Comment by Tencao** [comment]
It will have some, but nothing regular restarts cant fix

**Comment by ThuGie** [comment]
OH,
Well i don't really plan to restart the server daily, perhaps once a week but not more then that.
Currently still having random shutdowns.. gota find the cause, though this was the cause but it seems not.
