### ISSUE TITLE
[MCPC 61] [TT 1839] [SEVERE] [TickThreading] Failed to handle packet from unknown

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#674]
2013-06-08 03:54:16 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (7680 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by HaoSs07** [comment]
also getting spammed with this in latest TT 1943

2013-06-25 12:18:38 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at java.io.FilterInputStream.read(Unknown Source)
at ef.a(Packet.java:142)
at cg.i(TcpConnection.java:324)
at cg.readNetworkPacket(TcpConnection.java:71)
at ch.run(ReplaceTcpReaderThread.java:22)
2013-06-25 12:18:38 [INFO] [Minecraft] /94.6 lost connection
2013-06-25 12:18:39 [INFO] [Minecraft] /173lost connection
2013-06-25 12:19:46 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at java.io.FilterInputStream.read(Unknown Source)
at ef.a(Packet.java:142)
at cg.i(TcpConnection.java:324)
at cg.readNetworkPacket(TcpConnection.java:71)
at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by HaoSs07** [comment]
also after every failed to handle packet i get this
94.**.40.38:42131 lost connection 
(94.**.40.38 is the server ip, always different port,only change i made is update the gamecp. and now i use gamespy4 to scan server for online/offline, but i don't see problems there. its online. )

**Comment by LunNova** [comment]
`java.net.SocketTimeoutException: Read timed out` just means that the player disconnected. Is your host having network problems?

**Comment by HaoSs07** [comment]
nop. no network problems.

**Comment by LunNova** [comment]
Not a TT issue, confirmed that it happens with just forge. Not sure what causes it.
