### ISSUE TITLE
Unhandled exception in worker thread entities

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#676]
2013-06-08 09:30:07 [SEVERE] [TickThreading] Unhandled exception in worker thread En                                                                                                                                                         tities in anew/0 - 1
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManage                                                                                                                                                         r.java:589)
        at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:                                                                                                                                                         44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:1                                                                                                                                                         6)

**Comment by LunNova** [comment]
Which TT build?

**Comment by Tencao** [comment]
1834

**Comment by LunNova** [comment]
Fixed in latest.
