### ISSUE TITLE
Another issue pops up

### ISSUE THREAD

**Issue by xiph3r** [MinimallyCorrect/TickThreading#680]
hopefully you can point me in the right direction again nallar,

 [SEVERE] java.lang.NullPointerException
 [SEVERE]   at thaumcraft.common.AuraManager.generateNodeNeighbours(AuraManager.java:111)
 [SEVERE]   at thaumcraft.common.EventHandler.chunkLoad_sync0(EventHandler.java:213)
 [SEVERE]   at thaumcraft.common.EventHandler.chunkLoad(EventHandler.java)
 [SEVERE]   at net.minecraftforge.event.ASMEventHandler_81_EventHandler_chunkLoad_Load.invoke(.dynamic)
 [SEVERE]   at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
 [SEVERE]   at net.minecraftforge.event.EventBus.post(EventBus.java:104)
 [SEVERE]   at aam.a(ThreadedChunkLoader.java:188)
 [SEVERE]   at aam.a(ThreadedChunkLoader.java:159)
 [SEVERE]   at im.f(ThreadedChunkProvider.java:705)
 [SEVERE]   at im.getChunkAtInternal(ThreadedChunkProvider.java:518)
 [SEVERE]   at im.getChunkAt(ThreadedChunkProvider.java:492)
 [SEVERE]   at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:882)
 [SEVERE]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 [SEVERE]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 [SEVERE]   at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by xiph3r** [comment]
Seems to be fixed in the new TT build thanks
