### ISSUE TITLE
Unhandled exception in worker thread Entities

### ISSUE THREAD

**Issue by xiph3r** [MinimallyCorrect/TickThreading#681]
2013-06-08 15:43:17 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Hyrule/339 - 2
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManager.java:589)
    at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-08 15:51:53 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 4
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManager.java:589)
    at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-08 15:57:26 [INFO] [TickThreading] Server shutting down - requested at 
me.nallar.insecurity.ThisIsNotAnError: This is not an error.
    at me.nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:31)
    at net.minecraft.server.MinecraftServer.n(MinecraftServer.java:109)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.shutdown(CraftServer.java:1081)
    at org.bukkit.Bukkit.shutdown(Bukkit.java:252)
    at org.bukkit.command.defaults.StopCommand.execute(StopCommand.java:28)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:549)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchServerCommand(CraftServer.java:535)
    at ho.al(DedicatedServer.java:353)
    at ho.r(DedicatedServer.java:310)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:293)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-08 15:57:26 [INFO] [TickThreading] Stopping the server. serverRunning: false, serverIsRunning: true, is crash: false
2013-06-08 15:57:34 [SEVERE] [TickThreading] When removing Hyrule/339, its provider dimension ID was not already in the world dimension ID set.
Worlds in bukkitWorlds: 
loaded world Twilight Forest/7@815729237, dimension: 7, provider dimension: 7, original dimension: 0
loaded world Nether/-1@1345475293, dimension: -1, provider dimension: -1, original dimension: 0
loaded world Hyrule/339@1349388248, dimension: 339, provider dimension: 0, original dimension: 0
Worlds in dimensionManager: 
loaded world Hyrule/339@1349388248, dimension: 339, provider dimension: 0, original dimension: 0
loaded world Twilight Forest/7@815729237, dimension: 7, provider dimension: 7, original dimension: 0
loaded world Nether/-1@1345475293, dimension: -1, provider dimension: -1, original dimension: 0
Worlds in minecraftServer: 
loaded world Nether/-1@1345475293, dimension: -1, provider dimension: -1, original dimension: 0
loaded world Hyrule/339@1349388248, dimension: 339, provider dimension: 0, original dimension: 0
loaded world Twilight Forest/7@815729237, dimension: 7, provider dimension: 7, original dimension: 0

**Comment by xiph3r** [comment]
seems to be fixed with the newest builds of TT and MCPC
