### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by dezil** [MinimallyCorrect/TickThreading#682]
getting this message on all the storage buss' on the map basically spams every second

2013-06-08 16:47:06 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @331199158 in Overworld/0 at x, y, z: 314, 64, 497
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed with recent AE changes.
