### ISSUE TITLE
[MCPC +67] [TT 1852]  [SEVERE] [TickThreading] Exception ticking entity iq['peethimself'/2023048, l='overworld', x=3107.68, y=63.00, z=1379.90](peethimself at 3107.681792056792,63.0,1379.898476478032) in rX: 194, rZ: 86, hashCode: 5636290/overworld/0:

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#696]
[SEVERE] [TickThreading] Exception ticking entity iq['peethimself'/2023048, l='overworld', x=3107.68, y=63.00, z=1379.90](peethimself at 3107.681792056792,63.0,1379.898476478032) in rX: 194, rZ: 86, hashCode: 5636290/overworld/0:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$EntryIterator.next(HashMap.java:880)
    at java.util.HashMap$EntryIterator.next(HashMap.java:878)
    at java.util.AbstractMap.hashCode(AbstractMap.java:494)
    at bq.equals(NBTTagCompound.java:426)
    at ur.d(ItemStack.java:407)
    at ur.b(ItemStack.java:399)
    at rq.b(Container.java:108)
    at iq.j_(EntityPlayerMP.java:22)
    at yc.a(World.java:391)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2717)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment]
@nallar 

Got this again on TT build 1870:

[TickThreading] Exception ticking entity iq['peethimself'/3359942, l='overworld', x=3105.70, y=63.00, z=1379.66](peethimself at 3105.699999988079,63.0,1379.6573677831514) in rX: 194, rZ: 86, hashCode: 5636290/overworld/0:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$EntryIterator.next(HashMap.java:880)
    at java.util.HashMap$EntryIterator.next(HashMap.java:878)
    at bq.b(NBTTagCompound.java:25)
    at ur.l(ItemStack.java:383)
    at rq.b(Container.java:110)
    at iq.j_(EntityPlayerMP.java:22)
    at yc.a(World.java:391)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2717)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
