### ISSUE TITLE
generateAuraNode NPE spam, groupEntities NPE.

### ISSUE THREAD

**Issue by xiph3r** [MinimallyCorrect/TickThreading#698]
Using MCPC+ L67 build & TT build 1852

getting these errors but there not being logged anywhere, I checked forgemodserver.log, serverlog, tickthreadinglogs,

so i included a pic of the error
![screenshot from 2013-06-10 17 38 21](https://f.cloud.github.com/assets/4541235/634376/0ff38ce2-d218-11e2-8974-e118dd1039f0.png)

**Comment by LunNova** [comment]
Probably broken world lists - check TT's log file for any errors including "Worlds in dimensionManager:", and paste the error if it's there.

**Comment by xiph3r** [comment]
i did a complete reboot and this is what the logs have 

tickthreading.log   http://pastebin.com/XsiWfRve
server.log             http://pastebin.com/AEsV1REH

**Comment by xiph3r** [comment]
another screenshot

![screenshot from 2013-06-10 19 35 18](https://f.cloud.github.com/assets/4541235/634786/8bb2e842-d226-11e2-9bd6-31dcd9091c6f.png)

**Comment by LunNova** [comment]
First issue from the tickthreading.log file is fixed, will look at the others tomorrow.

**Comment by xiph3r** [comment]
thanks, dont kill yourself ive noticed you been coding all day on jenkins, take a day or two to yourself. Im sure we all appreciate your dedication to this wonderful mod :) you should relax and chill to :)

**Comment by xiph3r** [comment]
upgraded to the latest build TT-1862

and got these errors

![screenshot from 2013-06-11 15 57 46](https://f.cloud.github.com/assets/4541235/639375/6de335c8-d2d1-11e2-9ed0-ce45719ef39f.png)

logs are dropped in here  
http://ftb.survivalzcraft.com/server/

**Comment by LunNova** [comment]
Looks like you're using 1.5 Towny version.

**Comment by xiph3r** [comment]
should i downgrade or upgrade towny, i was using the towny dev

**Comment by xiph3r** [comment]
ok i downgraded and this is the only error that i have now

2013-06-11 17:56:15 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-06-11 17:56:19 [INFO] [TickThreading] Skipping version tick handler c com.pahimar.ee3.core.handlers.VersionCheckTickHandler com.pahimar.ee3.core.handlers.VersionCheckTickHandler@36767aa0
2013-06-11 17:56:32 [INFO] [TickThreading] Threading initialised for world Twilight Forest/7
2013-06-11 17:56:32 [INFO] [TickThreading] Threading initialised for world The End/1
2013-06-11 17:56:32 [INFO] [TickThreading] Threading initialised for world Nether/-1
2013-06-11 17:56:32 [INFO] [TickThreading] Threading initialised for world Overworld/0
2013-06-11 17:56:33 [INFO] [TickThreading] Threading initialised for world Hyrule/341
2013-06-11 17:56:45 [SEVERE] [TickThreading] TickThreading v1.0.0.1862 for MC1.4.7 on 1.4.7 tickthreading,mcpc,spigot,craftbukkit,forge,fml - 1.7.0_19-mockbuild_2013_04_17_19_18-b00 is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading

Also, you really should be making regular backups. (You should be doing that even when not using TT.)
2013-06-11 18:04:38 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Hyrule/341 - 5
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManager.java:589)
    at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-11 18:11:40 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 3
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManager.java:589)
    at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-11 18:23:46 [SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 2
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManager.java:589)
    at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
