### ISSUE TITLE
NPE on chunk loading - Build 498

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#71]
2013-01-18 23:53:14 [INFO] [STDERR] java.lang.NullPointerException
2013-01-18 23:53:14 [INFO] [STDERR]     at aam.a(AnvilChunkLoader.java:54)
2013-01-18 23:53:14 [INFO] [STDERR]     at im.f(ChunkProviderServer.java:182)
2013-01-18 23:53:14 [INFO] [STDERR]     at im.c(ChunkProviderServer.java:103)
2013-01-18 23:53:14 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:304)
2013-01-18 23:53:14 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
2013-01-18 23:53:14 [INFO] [STDERR]     at ho.c(DedicatedServer.java:179)
2013-01-18 23:53:14 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:49)
2013-01-18 23:53:14 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Fixed via d62969acc8bd8cf8db2bc
