### ISSUE TITLE
[1867] Deadlock AE/Turtles

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#719]
Here's the full TT log : https://gist.github.com/Drehmini/5778181

**Comment by LunNova** [comment]
Known CC/Peripherals issue. I can't fix it, needs to be fixed in CC. Set wireless ranges to 0 to avoid it.

`Definitely deadlocked: 
"Coroutine-229" Id=3443 BLOCKED on dan200.computer.core.Computer@21f00fe7 owned by "Entities in Overworld/0 - 5" Id=120
    at dan200.computer.core.Computer.queueLuaEvent(Computer.java:1062)
    -  blocked on dan200.computer.core.Computer@21f00fe7
    at dan200.computer.core.Computer.access$300(Computer.java:31)
    at dan200.computer.core.Computer$APIEnvironment.queueEvent(Computer.java:91)
    at dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper.queueEvent(PeripheralAPI.java:220)
    -  locked dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper@4dbe016f
    at dan200.computer.shared.WirelessModemPeripheral.receive(WirelessModemPeripheral.java:138)
    -  locked dan200.turtle.shared.TurtleModem$Peripheral@75504648
    at dan200.computer.shared.WirelessModemPeripheral$SingleChannelReceiver.receive(WirelessModemPeripheral.java:50)
    at dan200.computer.shared.WirelessNetwork.tryTransmit(WirelessNetwork.java:87)
    at dan200.computer.shared.WirelessNetwork.transmit(WirelessNetwork.java:75)
    -  locked dan200.computer.shared.WirelessNetwork@69365d23
    at dan200.computer.shared.WirelessModemPeripheral.callMethod(WirelessModemPeripheral.java:269)
    -  locked dan200.turtle.shared.TurtleModem$Peripheral@701cdacb
    at dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper.call(PeripheralAPI.java:116)
    -  locked dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper@76607eed
    at dan200.computer.core.apis.PeripheralAPI.callMethod(PeripheralAPI.java:464)
    at dan200.computer.core.LuaJLuaMachine$2.invoke(LuaJLuaMachine.java:304)
    -  locked dan200.computer.core.LuaJLuaMachine$2@392d3652
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    -  locked org.luaj.vm2.LuaThread$State@47495ed1
    at java.lang.Thread.run(Unknown Source)

"Entities in Overworld/0 - 5" Id=120 BLOCKED on dan200.turtle.shared.TurtleModem$Peripheral@75504648 owned by "Coroutine-229" Id=3443
    at dan200.computer.shared.WirelessModemPeripheral.pollChanged(WirelessModemPeripheral.java:90)
    -  blocked on dan200.turtle.shared.TurtleModem$Peripheral@75504648
    at dan200.turtle.shared.TurtleModem$Peripheral.update(TurtleModem.java:72)
    at dan200.computer.core.apis.PeripheralAPI$PeripheralWrapper.update(PeripheralAPI.java:105)
    at dan200.computer.core.apis.PeripheralAPI.advance(PeripheralAPI.java:354)
    -  locked [Ldan200.computer.core.apis.PeripheralAPI$PeripheralWrapper;@3e12576a
    at dan200.computer.core.Computer.advance(Computer.java:560)
    -  locked java.util.ArrayList@32eadad9
    -  locked dan200.computer.core.Computer@21f00fe7
    at dan200.computer.shared.NetworkedComputerHelper.update(NetworkedComputerHelper.java:111)
    at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2350)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    -  locked me.nallar.tickthreading.util.concurrent.NativeMutex@58c5f6ac
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    -  locked me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@2cc5c3bc
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)`

**Comment by Drehmini** [comment]
Nallar,

I know you stated that this is a problem with CC/Peripherals, but does this recent commit fix the issue, or is this something else entirely?

**Comment by LunNova** [comment]
I mentioned the wrong issue, that fix was actually for the AE storage bus deadlock.
