### ISSUE TITLE
[MCPC+ L67] [TT 1907] Server Startup Crash

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#727]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:138)
        at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1612)
        at org.bukkit.craftbukkit.Main.main(Main.java:21)
Caused by: java.lang.NoClassDefFoundError: me/nallar/collections/ListSet
        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:204)
        at ho.<init>(DedicatedServer.java:61)
        at net.minecraft.server.MinecraftServer.fmlReentry(MinecraftServer.java:1632)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: me.nallar.collections.ListSet
        at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 11 more
Caused by: java.lang.NullPointerException
        at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:207)
        ... 13 more

**Comment by LunNova** [comment]
Patch the server before starting it, change the TT jar path in PATCHME.sh.

Alternatively, use a clean server jar before patching.

**Comment by alicheek** [comment]
ah cool cheers will try that

**Comment by alicheek** [comment]
Yep that's it worked now thanks man :D
