### ISSUE TITLE
Nullpointer exception server tick loop

### ISSUE THREAD

**Issue by bogie** [MinimallyCorrect/TickThreading#73]
Using bukkitforge r52 plugins:
Clearlag
Craftconomy3
OnTime
PEX
Residence
Vault
WorldEdit

enableWorldTickThreading=false

Description: Exception in server tick loop

java.lang.NullPointerException
        at im.b_nosynchronize(ChunkProviderServer.java:66)
        at im.b(ChunkProviderServer.java)
        at in.b(WorldServer.java:166)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:254)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:194)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:130)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:64)
        at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Can you try the latest TT build? I added some debugging so we can see what broke, instead of getting a log here at some unknown time after the chunk was unloaded.

**Comment by bogie** [comment]
http://paste2.org/p/2777566

**Comment by LunNova** [comment]
Is this resolved?

**Comment by LunNova** [comment]
Closing because 36cf82b29bd9eeb makes this impossible.
