### ISSUE TITLE
[TT 1909] Exception ticking TileEntity c appeng.me.tile.TileController

### ISSUE THREAD

**Issue by turol** [MinimallyCorrect/TickThreading#734]
FTB 1.1.2 server with TT 1909 gives this:

2013-06-16 14:35:37 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @1958077899 in Overworld/0 at x, y, z: -183, 63, -128
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at appeng.me.tile.TileController.getJobList(TileController.java:189)
    at appeng.me.container.ContainerCraftingMonitor.updateClient(ContainerCraftingMonitor.java:137)
    at appeng.me.container.ContainerCraftingMonitor.updateClient(ContainerCraftingMonitor.java:126)
    at appeng.me.tile.TileController.advanceCraftingCursor(TileController.java:512)
    at appeng.me.tile.TileController.g(TileController.java:968)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-16 14:36:30 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @1958077899 in Overworld/0 at x, y, z: -183, 63, -128
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at appeng.me.tile.TileController.getJobStatus(TileController.java:210)
    at appeng.me.container.ContainerCraftingMonitor.updateClient(ContainerCraftingMonitor.java:133)
    at appeng.me.container.ContainerCraftingMonitor.updateClient(ContainerCraftingMonitor.java:126)
    at appeng.me.tile.TileController.advanceCraftingCursor(TileController.java:512)
    at appeng.me.tile.TileController.g(TileController.java:968)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

Standard FTB 1.1.2 server doesn't give errors but warns it can't keep up. This is an AE system but completely in one chunk. The system keeps working even when this error happens.

This is my test world, I can provide world download if necessary (18 MB 7zipped).

**Comment by LunNova** [comment]
Also, could you provide the world download?
