### ISSUE TITLE
[MCPC+ L67] [TT 1922] [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 64664

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#740]
[SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 64664
java.lang.NullPointerException
        at forestry.arboriculture.items.ItemGermlingGE.a(ItemGermlingGE.java:144)
        at ur.a(ItemStack.java:135)
        at ir.a(ItemInWorldManager.java:580)
        at iv.a(NetServerHandler.java:906)
        at fk.a(Packet15Place.java:79)
        at cg.b(TcpConnection.java:467)
        at iv.d(NetServerHandler.java:220)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
        at ho.r(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
        at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
They tried to place a corrupted forestry sapling. There's an option in forestry's config to clean broken saplings iirc.
