### ISSUE TITLE
TT 1.5.2

### ISSUE THREAD

**Issue by nylser** [MinimallyCorrect/TickThreading#741]
I just tried to start the server with the first TickThreading 1.5.2 Build and this happened:

``` java
2013-06-16 21:16:34 [SEVERE] [ForgeModLoader] The mod TickThreading does not wish to run in Minecraft version Minecraft 1.5.2. You will have to remove it to play.
21:16:34 [SEVERE] cpw.mods.fml.common.WrongMinecraftVersionException
21:16:34 [SEVERE]       at cpw.mods.fml.common.Loader.sortModList(Loader.java:216)
21:16:34 [SEVERE]       at cpw.mods.fml.common.Loader.loadMods(Loader.java:486)
21:16:34 [SEVERE]       at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:85)
21:16:34 [SEVERE]       at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
21:16:34 [SEVERE]       at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:94)
21:16:34 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579)
21:16:34 [SEVERE]       at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
21:16:34 [SEVERE] Encountered an unexpected exception WrongMinecraftVersionException
cpw.mods.fml.common.WrongMinecraftVersionException
        at cpw.mods.fml.common.Loader.sortModList(Loader.java:216)
        at cpw.mods.fml.common.Loader.loadMods(Loader.java:486)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:85)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:94)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
```

**Comment by LunNova** [comment]
For now, please don't report any 1.5.2 issues until I say that it's supposed to be working in issue #448.

**Comment by LunNova** [comment]
Also, didn't know github had syntax colouring for code blocks, that's nice :)

**Comment by nylser** [comment]
Sorry, and yeah a pretty nice feature :)

**Comment by LunNova** [comment]
It's fine, I should've made that clear before setting up builds.
