### ISSUE TITLE
Console crash on latest version

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#745]
2013-06-16 22:25:05 [SEVERE] [TickThreading] Exception ticking entity iq['did4321'/16383, l='world', x=14472,71, y=59,00, z=14726,28](did4321 at 14472.705930832586,59.0,14726.28356116848) in rX: 904, rZ: 920, hashCode: 60294024/Overworld/0:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$EntryIterator.next(HashMap.java:880)
    at java.util.HashMap$EntryIterator.next(HashMap.java:878)
    at bq.b(NBTTagCompound.java:25)
    at ur.l(ItemStack.java:383)
    at rq.b(Container.java:110)
    at iq.j_(EntityPlayerMP.java:22)
    at yc.a(World.java:390)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2717)
    at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
By the time you ran into this problem, you weren't on the latest version, it's fixed now :)
