### ISSUE TITLE
[1927] Wand of Equal Trade Error

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#746]
2013-06-16 17:23:34 [SEVERE] [TickThreading] Recursive TC add.
java.lang.Throwable
        at thaumcraft.common.WorldTicker.addSwapper(WorldTicker.java)
        at thaumcraft.common.items.wands.ItemWandTrade.onItemUseFirst(ItemWandTr
ade.java:58)
        at ir.a(ItemInWorldManager.java:397)
        at iv.a(NetServerHandler.java:579)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(Network
ListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
        at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Are you from the future, or do you mean 1927? :P

**Comment by Drehmini** [comment]
Oh I guess my cover is ruined! Anyways, yes I meant 1927

**Comment by cjm721** [comment]
Also on warded block place:

> 2013-06-17 03:40:57 [SEVERE] [TickThreading] Recursive TC add.
>     at thaumcraft.common.WorldTicker.addBlockToRestore(WorldTicker.java)
>     at thaumcraft.common.blocks.BlockWarded.h(BlockWarded.java:97)
>     at zz.a(Chunk.java:475)
>     at zz.a(Chunk.java:681)
>     at yc.b(World.java:862)
>     at yc.e(World.java:971)
>     at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlock.setTypeId(CraftBlock.java:109)
>     at org.bukkit.craftbukkit.v1_4_R1.block.CraftBlockState.update(CraftBlockState.java:121)
>     at yc.a(World.java:4383)
>     at vq.a(ItemBlock.java:98)
>     at ur.a(ItemStack.java:135)
>     at ir.a(ItemInWorldManager.java:580)
>     at iv.a(NetServerHandler.java:906)
>     at fk.a(Packet15Place.java:79)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>     at fy.run(ThreadMinecraftServer.java:16)
