### ISSUE TITLE
[TT 1897 and 1927] [Latest MCPC L] [SEVERE] [ForgeModLoader] Failed to load chunk at 27,-350

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#752]
Beeing spammed into console from time to time.

2013-06-17 07:18:05 [SEVERE] [ForgeModLoader] Failed to load chunk at 27,-350
java.lang.NullPointerException
        at aam.a(ThreadedChunkLoader.java:172)
        at aam.a(ThreadedChunkLoader.java:161)
        at im.f(ThreadedChunkProvider.java:708)
        at im.getChunkAtInternal(ThreadedChunkProvider.java:519)
        at im.getChunkAt(ThreadedChunkProvider.java:493)
        at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:895)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by mainsheep** [comment]
These problems did not occur when I was running TT189X yesterday, and we had no errors for 1day 12hours. Now after upgrading to TT1927, and downgrading to TT1897 again, I've been getting errors both from chunks which cannot load, and this.

**Comment by mainsheep** [comment]
Problem fixed itself by installing openjdk 7 instead of oracle java 7
