### ISSUE TITLE
[TT 1897] [MCPC L67] [SEVERE] Exception in thread "Connection #132 read thread"

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#753]
Shows up from time to time.

These problems did not occur when I was running TT189X yesterday, and we had no errors for 1day 12hours. Now after upgrading to TT1927, and downgrading to TT1897 again, I've been getting errors both from chunks which cannot load, and this:

07:26:09 [SEVERE] Exception in thread "Connection #132 read thread"
07:26:09 [SEVERE] java.lang.NoClassDefFoundError: Could not initialize class miscperipherals.util.Util
07:26:09 [SEVERE]       at miscperipherals.asm.ASMHelper.getTurtleBlockDropped(ASMHelper.java:113)
07:26:09 [SEVERE]       at dan200.turtle.shared.BlockTurtle.getBlockDropped(BlockTurtle.java)
07:26:09 [SEVERE]       at dan200.computer.shared.BlockComputerBase.removeBlockByPlayer(BlockComputerBase.java:117)
07:26:09 [SEVERE]       at ir.d(ItemInWorldManager.java:345)
07:26:09 [SEVERE]       at ir.b(ItemInWorldManager.java:466)
07:26:09 [SEVERE]       at ir.a(ItemInWorldManager.java:301)
07:26:09 [SEVERE]       at iv.a(NetServerHandler.java:787)
07:26:09 [SEVERE]       at ei.a(Packet14BlockDig.java:67)
07:26:09 [SEVERE]       at cg.i(TcpConnection.java:348)
07:26:09 [SEVERE]       at cg.readNetworkPacket(TcpConnection.java:71)
07:26:09 [SEVERE]       at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by mainsheep** [comment]
Problem fixed itself by uninstalling oracle java 7 and installing openjdk 7.
