### ISSUE TITLE
[TT1863] TileStorageBus

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#754]
2013-06-17 15:06:11 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @539468716 in Overworld/0 at x, y, z: 1510, 63, 555
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed in latest.
