### ISSUE TITLE
[TT1863]  Player ticking entity

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#755]
2013-06-17 10:01:54 [SEVERE] [TickThreading] Exception ticking entity iq['Husky89'/193473, l='world', x=1189.95, y=72.00, z=-679.32](Husky89 at 1189.9482552564593,72.0,-679.3223194870516) in rX: 74, rZ: -42, hashCode: -2752438/Overworld/0:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$EntryIterator.next(HashMap.java:880)
    at java.util.HashMap$EntryIterator.next(HashMap.java:878)
    at bq.b(NBTTagCompound.java:25)
    at ur.l(ItemStack.java:383)
    at rq.b(Container.java:110)
    at iq.j_(EntityPlayerMP.java:22)
    at yc.a(World.java:391)
    at in.a(WorldServer.java:844)
    at yc.g(World.java:2717)
    at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed in latest.
