### ISSUE TITLE
[TT1929]permission note vanilla

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#763]
2013-06-17 18:44:33 [INFO] Registered command debug with permission node vanilla.command.debug
2013-06-17 18:44:34 [SEVERE] java.lang.ClassNotFoundException: me.nallar.collections.SynchronizedList
2013-06-17 18:44:34 [SEVERE]    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:218)
2013-06-17 18:44:34 [SEVERE]    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-06-17 18:44:34 [SEVERE]    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-06-17 18:44:34 [SEVERE]    at java.lang.Class.forName0(Native Method)
2013-06-17 18:44:34 [SEVERE]    at java.lang.Class.forName(Class.java:266)
2013-06-17 18:44:34 [SEVERE]    at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:622)
2013-06-17 18:44:34 [SEVERE]    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1593)
2013-06-17 18:44:34 [SEVERE]    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1514)
2013-06-17 18:44:34 [SEVERE]    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1750)
2013-06-17 18:44:34 [SEVERE]    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
2013-06-17 18:44:34 [SEVERE]    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
2013-06-17 18:44:34 [SEVERE]    at twilightforest.TFFeatureCache.load(TFFeatureCache.java:146)
2013-06-17 18:44:34 [SEVERE]    at twilightforest.world.TFWorldChunkManager.loadFeatureCache(TFWorldChunkManager.java:422)
2013-06-17 18:44:34 [SEVERE]    at twilightforest.TFEventListener.worldLoad(TFEventListener.java:448)
2013-06-17 18:44:34 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_117_TFEventListener_worldLoad_Load.invoke(.dynamic)
2013-06-17 18:44:34 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-06-17 18:44:34 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-06-17 18:44:34 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:415)
2013-06-17 18:44:34 [SEVERE]    at ho.c(DedicatedServer.java:203)
2013-06-17 18:44:34 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:166)
2013-06-17 18:44:34 [SEVERE]    at fy.run(ThreadMinecraftServer.java:16)
2013-06-17 18:44:34 [SEVERE] Caused by: java.lang.NullPointerException

**Comment by LunNova** [comment]
Same problem as before, you need to use a clean (unpatched) server jar.

**Comment by LunNova** [comment]
If that doesn't work, also delete everything in the patchedMods folder before repatching.

**Comment by Slind14** [comment]
thanks, u should realy add a update section to year readme
