### ISSUE TITLE
TT + MCPC+ error thread

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#77]
1:

2013-01-22 21:06:38 [SEVERE] Exception in thread "World Tick - 5" 
2013-01-22 21:06:38 [SEVERE] Exception in thread "World Tick - 6" 
2013-01-22 21:06:38 [SEVERE] java.lang.NoSuchMethodError: im.getLoadedChunks()Ljava/util/List;
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.ChunkGarbageCollector.garbageCollect(ChunkGarbageCollector.java:22)
2013-01-22 21:06:38 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:263)
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:326)
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:149)
2013-01-22 21:06:38 [SEVERE] java.lang.NoSuchMethodError: im.getLoadedChunks()Ljava/util/List;
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.ChunkGarbageCollector.garbageCollect(ChunkGarbageCollector.java:22)
2013-01-22 21:06:38 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:263)
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:326)
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
2013-01-22 21:06:38 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:149)

**Comment by LunNova** [comment]
Fixed via c9442281cdfc64376.

**Comment by gustav9797** [comment]
TT build 564 + MCPC+ build 19

Description: Exception getting block type in world

java.lang.NoSuchFieldError: b
    at im.c(ChunkProviderServer.java:129)
    at im.d(ChunkProviderServer.java:239)
    at yc.e(World.java:698)
    at yc.a(World.java:576)
    at yc.c(World.java:605)
    at yc.b(World.java:547)
    at aaq.a(WorldProvider.java:100)
    at in.canSpawn(WorldServer.java:270)
    at in.b(WorldServer.java:1005)
    at in.a(WorldServer.java:946)
    at yc.<init>(World.java:459)
    at in.<init>(WorldServer.java:124)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:380)
    at ho.c(DedicatedServer.java:194)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:51)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Please paste the patcher log.

**Comment by gustav9797** [comment]
http://pastebin.com/zr8ysMhf

**Comment by LunNova** [comment]
Fixed in build 568.

**Comment by gustav9797** [comment]
> 2013-01-23 18:15:05 [SEVERE] [TickThreading] Unhandled exception in worker thre
> ad World Tick - 1
> java.lang.NullPointerException
>         at aok.a(Vec3Pool.java:123)
>         at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java
> :240)
>         at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRu
> nnable.run(PatchMinecraftServer.java:326)
>         at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.j
> ava:39)
>         at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(
> ThreadManager.java:149)
> 2013-01-23 18:15:49 [SEVERE] [TickThreading] Unhandled exception in worker threa
> d Tile/Entity Tick for Overworld/0 - 1
> java.lang.ArrayIndexOutOfBoundsException: -1
>         at zd.b(WorldChunkManager.java:123)
>         at zb.<init>(BiomeCacheBlock.java:34)
>         at za.a(BiomeCache.java:40)
>         at za.b(BiomeCache.java:54)
>         at zd.a(WorldChunkManager.java:67)
>         at yc.getBiomeGenForCoordsBody(World.java:251)
>         at aaq.getBiomeGenForCoords(WorldProvider.java:425)
>         at yc.a(World.java:236)
>         at yc.canBlockFreezeBody(World.java:3608)
>         at aaq.canBlockFreeze(WorldProvider.java:474)
>         at yc.c(World.java:3603)
>         at yc.x(World.java:3594)
>         at in.run(WorldServer.java:108)
>         at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.j
> ava:39)
>         at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(
> ThreadManager.java:149)

Build 568

**Comment by LunNova** [comment]
The first issue reported there should be fixed now, the second looks like an invalid biome was generated and may be an MCPC issue.
