### ISSUE TITLE
[MCPC 67] [TT1929] [SEVERE] [ForgeModLoader] Error handling login related packet - connection from kierangreen123 [/90.205.60.166:50243] refused

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#772]
[SEVERE] [ForgeModLoader] Error handling login related packet - connection from kierangreen123 [/90.205.60.166:50243] refused
java.lang.NullPointerException
    at gm.attemptLogin(ServerConfigurationManager.java:420)
    at it.completeConnection(NetLoginHandler.java:201)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:157)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:111)
    at it.d(NetLoginHandler.java:190)
    at it.c(NetLoginHandler.java:81)
    at hu.a(ServerListenThread.java:58)
    at ht.b(DedicatedServerListenThread.java:33)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by alicheek** [comment]
ah is the logins servers
