### ISSUE TITLE
[TT 1929]AE and TE (or MFR) deadlocks

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#779]
I did update to the latest (1932) but I wanted to report this as it caused an issue several times this morning.

https://gist.github.com/Drehmini/5814598

**Comment by Drehmini** [comment]
I actually think it's not TE as much as it is MFR's Deep Storage Units.

2013-06-19 11:02:55 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit @496504216 in Overworld/0 at x, y, z: -19, 62, 226
java.lang.NullPointerException
    at powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit.checkInput(TileEntityDeepStorageUnit.java:160)
    at powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit.g(TileEntityDeepStorageUnit.java:138)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

After removing the DSU at the coords above it seems to have stopped the deadlocks.

**Comment by LunNova** [comment]
Oh, nice... a cyclic deadlock involving three threads. Looks "fun" to fix :P

**Comment by LunNova** [comment]
Also, did the server manage to recover from the deadlock or did it need to restart?

**Comment by Drehmini** [comment]
It needed to restart.

**Comment by Drehmini** [comment]
This seems to be resolved with the latest AE re-writes!
