### ISSUE TITLE
TT 1929 - Server inst saving Map with restart

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#785]
Hey,

if the server autorestart, it doesnt save the map, but it in the log it looks like this:

2013-06-19 22:19:28 [INFO] Saving players
2013-06-19 22:19:28 [WARNING] DSCT: Socket closed
2013-06-19 22:19:28 [INFO] Saving worlds
2013-06-19 22:19:28 [INFO] Closing listening thread
2013-06-19 22:19:28 [INFO] Saving chunks for level 'world'/Overworld
2013-06-19 22:19:29 [INFO] Saving chunks for level 'DIM7'/Twilight Forest
2013-06-19 22:19:29 [INFO] Saving chunks for level 'DIM1'/The End
2013-06-19 22:19:29 [INFO] Saving chunks for level 'DIM-1'/Nether
2013-06-19 22:19:29 [INFO] Saving chunks for level 'DIM_MYST13'/Age 13
2013-06-19 22:19:29 [INFO] Saving chunks for level 'DIM_MYST29'/Age 29
2013-06-19 22:19:43 [INFO] Starting minecraft server version 1.4.7

.
.

The following is the only Error i can find in all 3 logs:

2013-06-19 22:19:29 [SEVERE] [ForgeModLoader] A TileEntity type thermalexpansion.transport.tileentity.TileTeleportEnergy at DIM_MYST29/29,-642,106,89 has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.IllegalArgumentException: Empty string not allowed
    at cc.<init>(NBTTagString.java:24)
    at bq.a(NBTTagCompound.java:138)
    at thermalexpansion.transport.tileentity.TileTeleportRoot.b(TileTeleportRoot.java:376)
    at thermalexpansion.transport.tileentity.TileTeleportEnergy.b(TileTeleportEnergy.java:201)
    at aam.a(ThreadedChunkLoader.java:361)
    at aam.a(ThreadedChunkLoader.java:212)
    at im.b(ThreadedChunkProvider.java:740)
    at im.a(ThreadedChunkProvider.java:806)
    at in.a(WorldServer.java:159)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:525)
    at net.minecraft.server.MinecraftServer.k(MinecraftServer.java:564)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:250)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by joey19982** [comment]
I was having this issue recently too, although it hasn't happened the past few days. I assumed it was my problem.

It was very strange, as the player.dats were still intact but any changes made within the past few minutes were gone. even doing a /save-all right before restarting didn't help. Like I said though, it fixed itself for me, so I can't really supply any errors.

**Comment by Slind14** [comment]
exactly as u say it.

**Comment by Slind14** [comment]
2013-06-20 01:31:17 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionDuplicateModsFoundException
cpw.mods.fml.common.DuplicateModsFoundException
    at cpw.mods.fml.common.Loader.identifyDuplicates(Loader.java:77)
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:339)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:470)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:86)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(ThreadMinecraftServer.java:16)

.
.

2013-06-20 01:31:17 [SEVERE] [TickThreading] Failed to perform shutdown save.
java.lang.NullPointerException
    at net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:611)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:250)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by joey19982** [comment]
That isn't a tickthreading issue. You have two jars for the same mod in your mods or coremods folder. You probably didn't delete the old version of TickThreading.
