### ISSUE TITLE
[MCPC 67] [TT1932] [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1449031317 in overworld/0 at x, y, z: -2158, 64, -235

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#793]
[SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1449031317 in overworld/0 at x, y, z: -2158, 64, -235
java.lang.NullPointerException
    at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
    at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by andremiller** [comment]
As per the referenced issue above, I'm getting the same error using TickThreading-1.4.7-1.0.0.2005 with FTB Ultimate 1.1.2, Minecraft 1.4.7

**Comment by andremiller** [comment]
Oops, and this also looks like a duplicate of Issue #848 which is fixed in Build 2007. I'll give it a test tonight.

**Comment by andremiller** [comment]
Updated to Tickthreading TickThreading-1.4.7-1.0.0.2034.jar and I'm no longer getting the error.
