### ISSUE TITLE
Failed to handle packet

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#796]
I'm trying to get 2 servers using transporter to link up the server chat, however tickthreading keeps spitting out this error

2013-06-21 05:52:48 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Bad packet id 58
        at ef.a(Packet.java:160)
        at cg.i(TcpConnection.java:325)
        at cg.readNetworkPacket(TcpConnection.java:71)
        at ch.run(ReplaceTcpReaderThread.java:22)
2013-06-21 05:52:48 [INFO] Disconnecting /127.0.0.1:58211: Protocol error
2013-06-21 05:52:48 [INFO] /127.0.0.1:58211 lost connection

**Comment by LunNova** [comment]
Can you try this without TT? Don't think it's a TT issue.

**Comment by LunNova** [comment]
Closing as no response, and unlikely to be a TT issue.
