### ISSUE TITLE
Hexxit patching errors 

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#801]
http://ntgvps.site.nfoservers.com/temp/

if you need more info let me know ill do it asap! 

also im not sure if tick threading supports 1.5.2 :\ LOL it it doesn't then this makes sense

**Comment by LunNova** [comment]
"2013-06-21 13:44:57 [INFO] [TickThreading] Patching with TickThreading v1.0.0.1942 for **MC1.4.7** - 1.7.0_21-b11"

:P

There's a 1.5 build, see TickThreading-1.5.2 on the buildservice. Very buggy though.

**Comment by Bucky420** [comment]
2013-06-21 14:41:45 [INFO] [TickThreading] Running TickThreading v1.5.2.29 for MC1.5.2 - 1.7.0_21-b11
2013-06-21 14:41:46 [SEVERE] [TickThreading] An error occurred while patching, can't continue
java.lang.NoClassDefFoundError: org/objectweb/asm/commons/Remapper
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:52)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.Remapper
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more

what am i dong wrong?
