### ISSUE TITLE
TT1942 Exception ticking TileEntity c powercrystals.minefactoryreloaded.animals.TileEntityGrinder

### ISSUE THREAD

**Issue by nylser** [MinimallyCorrect/TickThreading#802]
I just found this error in console:

``` java
[TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.animals.TileEntityGrinder @1143822732 in Overworld/0 at x, y, z: 22149, 34, 2369
java.lang.NullPointerException
        at buildcraft.core.inventory.TransactorSimple.getPartialSlot(TransactorSimple.java:44)
        at buildcraft.core.inventory.TransactorSimple.getPartialSlot(TransactorSimple.java:34)
        at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java)
        at buildcraft.core.inventory.Transactor.add(Transactor.java:16)
        at buildcraft.transport.PipeTransportItems.canReceivePipeObjects(PipeTransportItems.java:217)
        at buildcraft.transport.PipeTransportItems.getPossibleMovements(PipeTransportItems.java:185)
        at buildcraft.transport.PipeTransportItems.resolveDestination(PipeTransportItems.java:165)
        at buildcraft.transport.PipeTransportItems.entityEntering(PipeTransportItems.java:107)
        at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:356)
        at buildcraft.transport.TileGenericPipe.entityEntering(TileGenericPipe.java:373)
        at thermalexpansion.core.Utils.addToAdjPipe(Utils.java:117)
        at thermalexpansion.transport.tileentity.TileTeleportItem.receiveItem(TileTeleportItem.java:126)
        at thermalexpansion.transport.tileentity.TileTeleportItem.sendItem(TileTeleportItem.java:107)
        at thermalexpansion.transport.tileentity.TileTeleportItem.a(TileTeleportItem.java:234)
        at powercrystals.core.util.UtilInventory.addToInventory(UtilInventory.java:45)
        at powercrystals.minefactoryreloaded.core.MFRUtil.dropStack(MFRUtil.java:144)
        at powercrystals.minefactoryreloaded.animals.TileEntityGrinder.activateMachine(TileEntityGrinder.java:113)
        at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

**Comment by Slind14** [comment]
i think it is related to rangeupgrades

**Comment by Slind14** [comment]
same with harvester

**Comment by LunNova** [comment]
After the build with that fix? The fix should fix both, if it's the same error.

**Comment by Slind14** [comment]
k, thanks
