### ISSUE TITLE
1.5.2 ChunkProviderServer issues? Not ready for MCPC+?

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#803]
2013-06-21 17:28:46 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoSuchFieldError
java.lang.NoSuchFieldError: b
        at net.minecraft.world.gen.ChunkProviderServer.<init>(ThreadedChunkProvider.java:94)
        at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:961)
        at net.minecraft.world.World.<init>(World.java:382)
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:138)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:317)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:166)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-06-21 17:28:46 [SEVERE] This crash report has been saved to: /home/NTG/hexxit/./crash-reports/crash-2013-06-21_17.28.46-server.txt

using the 1.5.2 version of TT and TT1.5.2 #29

**Comment by Bucky420** [comment]
PLZ fix ;_; i need this very very bad

**Comment by Bucky420** [comment]
oh this actually has nothing to do with hexxit but TT just doesn't work on 1.5.2 ..... iv taken off all mods and core mods and tried with various version of mcpc+ all ending up with this error

**Comment by Bucky420** [comment]
what version of mcpc+ did you build this with? like what version does this work with?

**Comment by Bucky420** [comment]
im guessing you this doesn't work for 1.5.2 MCPC+?

**Comment by LunNova** [comment]
Yes, 1.5.2 TT is not yet MCPC+ compatible, need to get vanilla working more reliably before attempting that.

**Comment by Bucky420** [comment]
new error 

java.lang.NoSuchFieldError: M
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:186)
    at net.minecraft.world.World.<init>(World.java:384)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:138)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:317)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:166)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by Tencao** [comment]
Still happening on build 55 sadly
