### ISSUE TITLE
Architect Table 

### ISSUE THREAD

**Issue by EricSihaoLin** [MinimallyCorrect/TickThreading#809]
2013-06-23 17:39:36 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.builders.TileArchitect @1784200125 in Overworld/0 at x, y, z: -2469, 115, 4140
java.lang.NullPointerException:  - This function is disabled; call version with metadata instead.
    at appeng.common.AppEngMultiBlock.a(AppEngMultiBlock.java:413)
    at buildcraft.api.blueprints.BptBlock.getSignature(BptBlock.java:201)
    at buildcraft.api.blueprints.BlueprintManager.getBlockSignature(BlueprintManager.java:25)
    at buildcraft.core.blueprints.BptBlueprint.saveAttributes(BptBlueprint.java:125)
    at buildcraft.core.blueprints.BptBase.save(BptBase.java:154)
    at buildcraft.core.blueprints.BptRootIndex.storeBluePrint(BptRootIndex.java:170)
    at buildcraft.builders.TileArchitect.createBpt(TileArchitect.java:126)
    at buildcraft.builders.TileArchitect.g(TileArchitect.java:57)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-23 17:39:36 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.builders.TileArchitect @1784200125 in Overworld/0 at x, y, z: -2469, 115, 4140
java.lang.NullPointerException:  - This function is disabled; call version with metadata instead.
    at appeng.common.AppEngMultiBlock.a(AppEngMultiBlock.java:413)
    at buildcraft.api.blueprints.BptBlock.getSignature(BptBlock.java:201)
    at buildcraft.api.blueprints.BlueprintManager.getBlockSignature(BlueprintManager.java:25)
    at buildcraft.core.blueprints.BptBlueprint.saveAttributes(BptBlueprint.java:125)
    at buildcraft.core.blueprints.BptBase.save(BptBase.java:154)
    at buildcraft.core.blueprints.BptRootIndex.storeBluePrint(BptRootIndex.java:170)
    at buildcraft.builders.TileArchitect.createBpt(TileArchitect.java:126)
    at buildcraft.builders.TileArchitect.g(TileArchitect.java:57)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Not a TT issue, the BC version you're using is not compatible with the AE version that you're using. One of them probably needs updated.
