### ISSUE TITLE
[Crash] [MCPC+ 67] [TT 1942] AE Crash on chunk being loaded.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#810]
Soon as the chunk is loaded (still looking where this one is) server crashes.

> Definitely deadlocked: 
> "Entities in Overworld/0 - 2" Id=127 BLOCKED on appeng.me.tile.TileController@949cefd owned by "Entities in Overworld/0 - 1" Id=126
>     at appeng.me.tile.TileController.signalInput(TileController.java:1440)
>     -  blocked on appeng.me.tile.TileController@949cefd
>     at appeng.me.GridInterface.signalInput(GridInterface.java:256)
>     at appeng.me.tile.TileStorageBus.g(TileStorageBus.java)
>     -  locked nallar.collections.SynchronizedList@5d97183
>     at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
>     at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>     -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@6ab5275
>     at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
>     at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
>     at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

"Entities in Overworld/0 - 1" Id=126 BLOCKED on nallar.collections.SynchronizedList@5d97183 owned by "Entities in Overworld/0 - 2" Id=127
    at nallar.collections.SynchronizedList.add(SynchronizedList.java:22)
    -  blocked on nallar.collections.SynchronizedList@5d97183
    at appeng.util.Platform.addStackToList(Platform.java:654)
    at appeng.me.tile.TileStorageBus.signalInput(TileStorageBus.java:553)
    -  locked appeng.me.tile.TileStorageBus@4caef30c
    at appeng.me.MEInventoryHandler.updateSrc(MEInventoryHandler.java:124)
    at appeng.me.MEInventoryHandler.addItems(MEInventoryHandler.java:149)
    at appeng.me.MEInventoryArray.addItems(MEInventoryArray.java:328)
    -  locked appeng.me.MEInventoryArray@56a5b5f3
    at appeng.me.tile.TileController.signalInput(TileController.java:1451)
    -  locked appeng.me.tile.TileController@949cefd
    at appeng.me.crafting.Crafting.craftItem(Crafting.java:51)
    at appeng.me.crafting.CraftRequest.Craft(CraftRequest.java:187)
    at appeng.me.tile.TileController.advanceCraftingCursor(TileController.java:481)
    -  locked appeng.me.tile.TileController@949cefd
    at appeng.me.tile.TileController.g(TileController.java:968)
    -  locked appeng.me.tile.TileController@949cefd
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@194c90f6
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed with AE threading rework in latest.
