### ISSUE TITLE
Exception Ticking world

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#811]
2013-06-24 17:26:44 [SEVERE] [TickThreading] Exception ticking world Overworld/0
Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
2013-06-24 17:26:44 [SEVERE] [TickThreading] The server appears to have deadlocked.
Last tick 51s ago.
Waiting ThreadManagers: Entities in Overworld/0, World Tick

"Async ChunkLoader" TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@8368f87
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@8368f87
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
    at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

"Citizens Script Compiler" WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b36d569
    at sun.misc.Unsafe.park(Native Method)
    -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b36d569
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:374)
    at net.citizensnpcs.api.scripting.ScriptCompiler.run(ScriptCompiler.java:134)
    at java.lang.Thread.run(Thread.java:722)

**Comment by LunNova** [comment]
"Stack trace unavailable. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces."

Please do this, can't actually see the error here. Also, do you have a full log? You only gave part of the deadlock detector report.

**Comment by LunNova** [comment]
Assuming fixed as multiple deadlocks have been fixed since this was reported, and have not had a reply with the full log.
