### ISSUE TITLE
[TT1943] Macerator

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#813]
2013-06-24 19:29:02 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 682145
java.lang.ClassCastException: ic2.advancedmachines.common.TileEntityRotaryMacerator cannot be cast to gregtechmod.api.BaseMetaTileEntity
    at gregtechmod.common.items.GT_MetaMachine_Item.placeBlockAt(GT_MetaMachine_Item.java:143)
    at yc.a(World.java:4367)
    at vq.a(ItemBlock.java:98)
    at ur.a(ItemStack.java:135)
    at ir.a(ItemInWorldManager.java:580)
    at iv.a(NetServerHandler.java:906)
    at fk.a(Packet15Place.java:79)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:426)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:301)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
    at fy.run(ThreadMinecraftServer.java:16)
2013-06-24 19:29:04 [SEVERE] [TickThreading] Pointless repeat set on threadlocal
    at nallar.tickthreading.util.BooleanThreadLocal.set(BooleanThreadLocal.java:33)
    at nallar.tickthreading.util.BooleanThreadLocal.set(BooleanThreadLocal.java:13)
    at vq.processBlockPlace(ItemBlock.java:131)
    at vq.a(ItemBlock.java:116)
    at ur.a(ItemStack.java:135)
    at ir.a(ItemInWorldManager.java:580)
    at iv.a(NetServerHandler.java:906)
    at fk.a(Packet15Place.java:79)
    at cg.b(TcpConnection.java:467)
    at iv.d(NetServerHandler.java:220)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(DedicatedServerListenThread.java:34)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:426)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:301)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Not a TT issue, happening in code which I have not patched, during network ticks which aren't concurrent under TT unless you enable that in the config.
