### ISSUE TITLE
Huge error after updating

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#814]
Just updated to latest version and installed Towny, now hitting this error;

2013-06-24 21:59:03 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-06-24 21:59:07 [INFO] [TickThreading] Skipping version tick handler c com.pahimar.ee3.core.handlers.VersionCheckTickHandler com.pahimar.ee3.core.handlers.VersionCheckTickHandler@6943aef6
2013-06-24 21:59:18 [INFO] [TickThreading] Threading initialised for world Twilight Forest/7
2013-06-24 21:59:20 [INFO] [TickThreading] Threading initialised for world The End/1
2013-06-24 21:59:20 [INFO] [TickThreading] Threading initialised for world Nether/-1
2013-06-24 21:59:20 [INFO] [TickThreading] Threading initialised for world Overworld/0
2013-06-24 21:59:27 [SEVERE] [TickThreading] TickThreading v1.0.0.1943 for MC1.4.7 on 1.4.7 tickthreading,mcpc,spigot,craftbukkit,forge,fml - 1.7.0_21-b11 is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading

Also, you really should be making regular backups. (You should be doing that even when not using TT.)
2013-06-24 22:15:09 [SEVERE] [TickThreading] The server appears to have lag spiked.
Last tick 1s ago.
Waiting ThreadManagers: World Tick

"Async ChunkLoader" BLOCKED on nallar.collections.SynchronizedList@441d6259 owned by "World Tick - 6" Id=236
    at nallar.collections.SynchronizedList.add(SynchronizedList.java:22)
    -  blocked on nallar.collections.SynchronizedList@441d6259
    at twilightforest.TFFeatureCache.addData(TFFeatureCache.java:75)
    at twilightforest.world.TFWorldChunkManager.cacheFeatureData(TFWorldChunkManager.java:408)
    at twilightforest.TFEventListener.chunkLoad(TFEventListener.java:328)
    at net.minecraftforge.event.ASMEventHandler_114_TFEventListener_chunkLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
    at zz.threadUnsafeChunkLoad(Chunk.java:295)
    -  locked java.lang.Class@27797b14
    at im.getChunkAtInternal(ThreadedChunkProvider.java:602)
    -  locked java.util.concurrent.atomic.AtomicInteger@5728a67d
    at im.getChunkAt(ThreadedChunkProvider.java:503)
    at nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:922)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

```
Number of locked synchronizers = 1
- java.util.concurrent.ThreadPoolExecutor$Worker@b28c89d
```

"Connection #100 read thread", "Connection #106 read thread", "Connection #113 read thread", "Connection #116 read thread", "Connection #119 read thread", "Connection #123 read thread", "Connection #124 read thread", "Connection #128 read thread", "Connection #139 read thread", "Connection #143 read thread", "Connection #147 read thread", "Connection #148 read thread", "Connection #152 read thread", "Connection #159 read thread", "Connection #161 read thread", "Connection #163 read thread", "Connection #166 read thread", "Connection #172 read thread", "Connection #205 read thread", "Connection #223 read thread", "Connection #231 read thread", "Connection #238 read thread", "Connection #241 read thread", "Connection #246 read thread", "Connection #249 read thread", "Connection #257 read thread", "Connection #258 read thread", "Connection #261 read thread", "Connection #30 read thread", "Connection #31 read thread", "Connection #32 read thread", "Connection #4 read thread", "Connection #41 read thread", "Connection #45 read thread", "Connection #46 read thread", "Connection #49 read thread", "Connection #53 read thread", "Connection #57 read thread", "Connection #59 read thread", "Connection #63 read thread", "Connection #67 read thread", "Connection #71 read thread", "Connection #74 read thread", "Connection #76 read thread", "Connection #80 read thread", "Connection #93 read thread", "Connection #96 read thread" RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
    at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at ef.a(Packet.java:151)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

"Connection #100 write thread", "Connection #106 write thread", "Connection #113 write thread", "Connection #116 write thread", "Connection #119 write thread", "Connection #123 write thread", "Connection #124 write thread", "Connection #128 write thread", "Connection #139 write thread", "Connection #143 write thread", "Connection #147 write thread", "Connection #148 write thread", "Connection #152 write thread", "Connection #159 write thread", "Connection #161 write thread", "Connection #163 write thread", "Connection #166 write thread", "Connection #172 write thread", "Connection #205 write thread", "Connection #223 write thread", "Connection #231 write thread", "Connection #238 write thread", "Connection #241 write thread", "Connection #246 write thread", "Connection #249 write thread", "Connection #257 write thread", "Connection #258 write thread", "Connection #30 write thread", "Connection #31 write thread", "Connection #32 write thread", "Connection #4 write thread", "Connection #41 write thread", "Connection #45 write thread", "Connection #49 write thread", "Connection #53 write thread", "Connection #57 write thread", "Connection #59 write thread", "Connection #63 write thread", "Connection #67 write thread", "Connection #71 write thread", "Connection #74 write thread", "Connection #76 write thread", "Connection #80 write thread", "Connection #90 write thread", "Connection #93 write thread", "Connection #96 write thread" TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at ci.run(TcpWriterThread.java:49)

"Connection #261 write thread" RUNNABLE
    at java.util.zip.Deflater.deflateBytes(Native Method)
    at java.util.zip.Deflater.deflate(Unknown Source)
    -  locked java.util.zip.ZStreamRef@3728735d
    at java.util.zip.Deflater.deflate(Unknown Source)
    at dt.deflate(Packet56MapChunks.java:107)
    at dt.a(Packet56MapChunks.java:195)
    at ef.a(Packet.java:210)
    at cg.h(TcpConnection.java:201)
    at cg.d(TcpConnection.java:561)
    at ci.run(TcpWriterThread.java:25)

"Connection #46 write thread" RUNNABLE
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(Unknown Source)
    at java.net.SocketOutputStream.write(Unknown Source)
    at org.bouncycastle.crypto.io.CipherOutputStream.write(Unknown Source)
    at java.io.BufferedOutputStream.write(Unknown Source)
    -  locked java.io.BufferedOutputStream@395c418b
    at java.io.DataOutputStream.write(Unknown Source)
    -  locked java.io.DataOutputStream@6870bab3
    at dt.a(Packet56MapChunks.java:203)
    at ef.a(Packet.java:210)
    at cg.h(TcpConnection.java:201)
    at cg.d(TcpConnection.java:561)
    at ci.run(TcpWriterThread.java:25)

"Connection #90 read thread" RUNNABLE
    at net.machinemuse.api.MuseItemUtils.isModuleOnline(MuseItemUtils.java:68)
    at net.machinemuse.api.MuseItemUtils.itemHasActiveModule(MuseItemUtils.java:530)
    at net.machinemuse.api.ModuleManager.computeModularProperty(ModuleManager.java:50)
    at net.machinemuse.api.ElectricItemUtils.getMaxJoules(ElectricItemUtils.java:134)
    at net.machinemuse.api.ElectricItemUtils.getJoules(ElectricItemUtils.java:121)
    at net.machinemuse.powersuits.item.ItemPowerArmor.getJoules(ItemPowerArmor.java:301)
    at net.machinemuse.api.ElectricItemUtils.getPlayerEnergy(ElectricItemUtils.java:22)
    at net.machinemuse.powersuits.tick.PlayerTickHandler.handle(PlayerTickHandler.java:63)
    at net.machinemuse.powersuits.tick.PlayerTickHandler.tickStart(PlayerTickHandler.java:49)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickStart(WrappedScheduledTickHandler.java:23)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:57)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:384)
    at qx.j_(EntityPlayer.java:293)
    at iq.g(EntityPlayerMP.java:359)
    at iv.a(NetServerHandler.java:499)
    at eb.a(Packet10Flying.java:76)
    -  locked iv@50516e6d
    at cg.i(TcpConnection.java:348)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

"Coroutine-1" TIMED_WAITING on org.luaj.vm2.LuaThread$State@4e01a082
    at java.lang.Object.wait(Native Method)
    -  waiting on org.luaj.vm2.LuaThread$State@4e01a082
    at org.luaj.vm2.LuaThread$State.lua_yield(Unknown Source)
    at org.luaj.vm2.LuaThread.yield(Unknown Source)
    at org.luaj.vm2.lib.CoroutineLib.invoke(Unknown Source)
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

"Coroutine-10" TIMED_WAITING on org.luaj.vm2.LuaThread$State@60efcc51
    at java.lang.Object.wait(Native Method)
    -  waiting on org.luaj.vm2.LuaThread$State@60efcc51
    at org.luaj.vm2.LuaThread$State.lua_yield(Unknown Source)
    at org.luaj.vm2.LuaThread.yield(Unknown Source)
    at org.luaj.vm2.lib.CoroutineLib.invoke(Unknown Source)
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

"Coroutine-103" TIMED_WAITING on org.luaj.vm2.LuaThread$State@5fa91a21
    at java.lang.Object.wait(Native Method)
    -  waiting on org.luaj.vm2.LuaThread$State@5fa91a21
    at org.luaj.vm2.LuaThread$State.lua_yield(Unknown Source)
    at org.luaj.vm2.LuaThread.yield(Unknown Source)
    at org.luaj.vm2.lib.CoroutineLib.invoke(Unknown Source)
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

"Coroutine-104" TIMED_WAITING on org.luaj.vm2.LuaThread$State@3aadaacf
    at java.lang.Object.wait(Native Method)
    -  waiting on org.luaj.vm2.LuaThread$State@3aadaacf
    at org.luaj.vm2.LuaThread$State.lua_yield(Unknown Source)
    at org.luaj.vm2.LuaThread.yield(Unknown Source)
    at org.luaj.vm2.lib.CoroutineLib.invoke(Unknown Source)
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

"Coroutine-105" TIMED_WAITING on org.luaj.vm2.LuaThread$State@3b27eec8
    at java.lang.Object.wait(Native Method)
    -  waiting on org.luaj.vm2.LuaThread$State@3b27eec8
    at org.luaj.vm2.LuaThread$State.lua_yield(Unknown Source)
    at org.luaj.vm2.LuaThread.yield(Unknown Source)
    at org.luaj.vm2.lib.CoroutineLib.invoke(Unknown Source)
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

"Coroutine-106" TIMED_WAITING on org.luaj.vm2.LuaThread$State@60cf13f7
    at java.lang.Object.wait(Native Method)
    -  waiting on org.luaj.vm2.LuaThread$State@60cf13f7
    at org.luaj.vm2.LuaThread$State.lua_yield(Unknown Source)
    at org.luaj.vm2.LuaThread.yield(Unknown Source)
    at org.luaj.vm2.lib.CoroutineLib.invoke(Unknown Source)
    at org.luaj.vm2.lib.VarArgFunction.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
    at org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
    at org.luaj.vm2.LuaClosure.call(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.lib.BaseLib.pcall(Unknown Source)
    at org.luaj.vm2.lib.BaseLib$BaseLibV.invoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.execute(Unknown Source)
    at org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
    at org.luaj.vm2.LuaClosure.invoke(Unknown Source)
    at org.luaj.vm2.LuaThread$State.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by LunNova** [comment]
That is still only part of the error, full log please?

Won't be able to fix this until at the earliest Saturday, downgrade to what
was working before.

**Comment by LunNova** [comment]
Assumed fixed in latest, can't confirm as not full log but it's probably an AE network deadlock and those are now fixed.
