### ISSUE TITLE
[TT 1943]  Multiple Exception ticking TileEntity thermalexpansion and buildcraft refinery

### ISSUE THREAD

**Issue by solomon56** [MinimallyCorrect/TickThreading#816]
2013-06-26 02:10:38 [INFO] [ForgeModLoader] Loading dimension 8 (world) (ho@164314b0)
2013-06-26 02:10:38 [INFO] [TickThreading] Threading initialised for world Nexus/8
2013-06-26 02:10:41 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @192776715 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:69)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:147)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:41 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @192776715 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:89)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:172)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:41 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @192776715 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:91)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:172)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:44 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @776366735 in Overworld/0 at x, y, z: -336, 83, 91
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:94)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:172)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:46 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @192776715 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:69)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:147)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:47 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @192776715 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:89)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:147)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:48 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @1416055376 in Overworld/0 at x, y, z: -336, 83, 92
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:89)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:147)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:10:55 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @1416055376 in Overworld/0 at x, y, z: -336, 83, 92
java.lang.NullPointerException
        at net.minecraftforge.liquids.LiquidTank.fill(LiquidTank.java:94)
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:172)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
/stop
2013-06-26 02:11:03 [INFO] [Minecraft] Stopping the server
2013-06-26 02:11:03 [INFO] [TickThreading] Server shutting down - requested at
nallar.insecurity.ThisIsNotAnError: This is not an error.
        at nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:31)
        at net.minecraft.server.MinecraftServer.n(MinecraftServer.java:108)
        at hk.b(SourceFile:20)
        at x.a(CommandHandler.java:82)
        at ho.al(DedicatedServer.java:308)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:301)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
        at fy.run(SourceFile:849)
2013-06-26 02:11:03 [INFO] [TickThreading] Saving all player data.
2013-06-26 02:11:03 [INFO] [TickThreading] Done saving player data, saving worlds.
2013-06-26 02:11:03 [INFO] [TickThreading] Done saving worlds, flushing world data to disk.
2013-06-26 02:11:03 [INFO] [TickThreading] Flushed world data to disk.
2013-06-26 02:11:03 [INFO] [TickThreading] Stopping the server. serverRunning: false, serverIsRunning: true, is crash: false
2013-06-26 02:11:03 [INFO] [Minecraft] Stopping server
2013-06-26 02:11:03 [INFO] [Minecraft] Saving players
2013-06-26 02:11:03 [INFO] [Minecraft] Saving worlds
2013-06-26 02:11:03 [INFO] [Minecraft] Saving chunks for level 'world'/Overworld
2013-06-26 02:11:03 [INFO] [STDERR] java.net.SocketException: Socket closed
2013-06-26 02:11:03 [INFO] [STDERR]     at java.net.PlainSocketImpl.socketAccept(Native Method)
2013-06-26 02:11:03 [INFO] [STDERR]     at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
2013-06-26 02:11:03 [INFO] [STDERR]     at java.net.ServerSocket.implAccept(ServerSocket.java:522)
2013-06-26 02:11:03 [INFO] [STDERR]     at java.net.ServerSocket.accept(ServerSocket.java:490)
2013-06-26 02:11:03 [INFO] [STDERR]     at hu.run(ServerListenThread.java:81)
2013-06-26 02:11:03 [INFO] [STDOUT] Closing listening thread
2013-06-26 02:11:03 [INFO] [Minecraft] Saving chunks for level 'world'/Nether
2013-06-26 02:11:03 [INFO] [Minecraft] Saving chunks for level 'world'/The End
2013-06-26 02:11:03 [INFO] [Minecraft] Saving chunks for level 'world'/Nexus
2013-06-26 02:11:03 [INFO] [Minecraft] Saving chunks for level 'world'/Twilight Forest
2013-06-26 02:11:03 [INFO] [ForgeModLoader] [Thaumcraft] Removed 7 aura nodes when world 0 unloaded.
2013-06-26 02:11:03 [INFO] [Minecraft] Starting backup of world DIM 0

 on 2013-06-26 02:14:45 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @1990715111 in Overworld/0 at x, y, z: -336, 83, 91
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:142)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
reboot thing
2013-06-26 02:14:47 [INFO] [Minecraft] [Server] was testing the ssh on reboot thing
2013-06-26 02:14:52 [INFO] [Minecraft] <§dBad@$$§f><Theo> §rah
^N2013-06-26 02:15:34 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:522)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:15:49 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:523)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:16:12 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:524)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:16:29 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @836172468 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:142)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:16:32 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:523)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:16:52 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:523)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:16:54 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:524)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:17:24 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:522)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:17:37 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:523)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:17:55 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:522)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:18:22 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:522)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:18:23 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitLiquid @1735172607 in Overworld/0 at x, y, z: -337, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.getPacketPayload(TileRefinery.java:522)
        at buildcraft.core.network.PacketTileUpdate.<init>(PacketTileUpdate.java:15)
        at buildcraft.core.TileBuildCraft.getUpdatePacket(TileBuildCraft.java:98)
        at buildcraft.core.TileBuildCraft.sendNetworkUpdate(TileBuildCraft.java:82)
        at buildcraft.factory.TileRefinery.fill(TileRefinery.java:416)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.transferLiquid(TileConduitLiquid.java:577)
        at thermalexpansion.transport.GridLiquid.transferLiquid(GridLiquid.java:189)
        at thermalexpansion.transport.tileentity.TileConduitLiquid.g(TileConduitLiquid.java:389)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:18:24 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @1990715111 in Overworld/0 at x, y, z: -336, 83, 91
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:142)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:19:04 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @576499146 in Overworld/0 at x, y, z: -336, 83, 90
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:142)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:19:08 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @836172468 in Overworld/0 at x, y, z: -336, 83, 93
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:142)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-26 02:19:09 [SEVERE] [TickThreading] Exception ticking TileEntity c buildcraft.factory.TileRefinery @1990715111 in Overworld/0 at x, y, z: -336, 83, 91
java.lang.NullPointerException
        at buildcraft.factory.TileRefinery.g(TileRefinery.java:142)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Can you break and replace the refinery at the coordinates in the error
message?
