### ISSUE TITLE
Failed to load Chunk, since TT

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#821]
Im getting the following for every chunk, since the installation of TT.
on a Mindcrack Server

2013-06-30 07:10:09 [SEVERE] [ForgeModLoader] Failed to load chunk at 2064,35
java.lang.NullPointerException
    at aam.a(ThreadedChunkLoader.java:172)
    at aam.a(ThreadedChunkLoader.java:161)
    at im.f(ThreadedChunkProvider.java:708)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:519)
    at im.getChunkAt(ThreadedChunkProvider.java:493)
    at nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:895)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Which TT build are you using? That seems impossible, this is line 172:

``` java
if (chunkTagCompound == null) {
```

**Comment by Slind14** [comment]
1917 and 1943

**Comment by LunNova** [comment]
It was fixed in 1919, so that's the problem. Can you post the error with 1943? It's probably a slightly different error.

**Comment by Slind14** [comment]
k, will check tonight

**Comment by Slind14** [comment]
1959 is working
