### ISSUE TITLE
TT1959  Exception ticking TileEntity c 

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#824]
[SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @1519110360 in Overworld/0 at x, y, z: 1543, 58, 507
java.lang.NullPointerException
        at appeng.me.crafting.PushCraftRequest.Craft(PushCraftRequest.java:79)
        at appeng.me.tile.TileController.advanceCraftingCursor(TileController.java:481)
        at appeng.me.tile.TileController.g(TileController.java:968)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed in latest with the AE deadlock fixes.
