### ISSUE TITLE
1.5.2 Failed to instantiate class

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#833]
2013-07-02 01:37:19 [WARNING] [TickThreading] Failed to instantiate class nallar.tickthreading.util.contextaccess.ContextAccessReflection
java.lang.Error: Wrong class returned: class nallar.tickthreading.util.contextaccess.ContextAccessReflection, expected ContextAccessProvider
    at nallar.tickthreading.util.contextaccess.ContextAccessProvider.getContextAccess(ContextAccessProvider.java:17)
    at nallar.tickthreading.util.contextaccess.ContextAccess.<clinit>(ContextAccess.java:4)
    at net.minecraft.world.WorldServer.func_73041_k(WorldServer.java:175)
    at net.minecraftforge.common.DimensionManager.unloadWorld(DimensionManager.java:61)
    at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:31)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:434)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:302)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by LunNova** [comment]
Just a warning, shouldn't break anything. Will mean slightly worse performance for a few things, but it shouldn't break anything as it just falls back to the slow way of determining class context.

I can't fix this, as it depends on sun internal API. Maybe try updating your JRE?

**Comment by LunNova** [comment]
Can you try latest, and give the log? Might explain why it's not working, and give a possible fix. Also paste the first line of TT's `/tps` command.

**Comment by Tencao** [comment]
TickThreading v1.5.2.66 for MC1.5.2

013-07-02 02:46:25 [WARNING] [TickThreading] Unable to set up context access class class nallar.tickthreading.util.contextaccess.ContextAccessReflection
java.lang.Error: Wrong class returned: class nallar.tickthreading.util.contextaccess.ContextAccessReflection, expected ContextAccessProvider. Stack:
sun.reflect.Reflection at -2sun.reflect.Reflection at -1nallar.tickthreading.util.contextaccess.ContextAccessReflection at 0nallar.tickthreading.util.contextaccess.ContextAccessProvider at 1nallar.tickthreading.util.contextaccess.ContextAccess at 2
    at nallar.tickthreading.util.contextaccess.ContextAccessProvider.getContextAccess(ContextAccessProvider.java:25)
    at nallar.tickthreading.util.contextaccess.ContextAccess.<clinit>(ContextAccess.java:4)
    at thaumcraft.common.lib.WorldTicker.<clinit>(WorldTicker.java)
    at thaumcraft.common.CommonProxy.<init>(CommonProxy.java:78)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:58)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:471)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:504)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:85)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:94)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

This is with the latest version of JRE and tickthreading

**Comment by LunNova** [comment]
I messed that up sorry, can you try latest again?

**Comment by Tencao** [comment]
Tested again on version 67, same results.

[WARNING] [TickThreading] Unable to set up context access class class nallar.tickthreading.util.contextaccess.ContextAccessReflection
java.lang.Error: Wrong class returned: class nallar.tickthreading.util.contextaccess.ContextAccessReflection, expected ContextAccessProvider. Stack:
sun.reflect.Reflection at -2
sun.reflect.Reflection at -1
nallar.tickthreading.util.contextaccess.ContextAccessReflection at 0
nallar.tickthreading.util.contextaccess.ContextAccessProvider at 1
nallar.tickthreading.util.contextaccess.ContextAccess at 2

```
at nallar.tickthreading.util.contextaccess.ContextAccessProvider.getContextAccess(ContextAccessProvider.java:25)
at nallar.tickthreading.util.contextaccess.ContextAccess.<clinit>(ContextAccess.java:4)
at thaumcraft.common.lib.WorldTicker.<clinit>(WorldTicker.java)
at thaumcraft.common.CommonProxy.<init>(CommonProxy.java:78)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:58)
at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:471)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:504)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:85)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:94)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
```

**Comment by LunNova** [comment]
Can't replicate it, and there is no obvious reason why it's giving bad data. I'll make the log less spammy then close this.

**Comment by Tencao** [comment]
I believe I found the cause to these errors, If you use Djline.terminal\=jline.UnsupportedTerminal Or --nojline in your startup line, then these errors happen.

Hope that helps
