### ISSUE TITLE
TT - Critical server error in handling a packet

### ISSUE THREAD

**Issue by Voyevoda** [MinimallyCorrect/TickThreading#838]
2013-07-03 18:28:59 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 1
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
        at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
        at keepcalm.mods.bukkit.ToBukkit.chunkFromCoords(ToBukkit.java:69)
        at keepcalm.mods.bukkit.ToBukkit.blockFromCoords(ToBukkit.java:64)
        at keepcalm.mods.bukkit.ToBukkitEvent.PlayerInteract(ToBukkitEvent.java:102)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
        at net.minecraftforge.event.ASMEventHandler_120_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at iv.a(NetServerHandler.java:553)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:430)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:302)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
        at fy.run(SourceFile:849)
2013-07-03 18:28:59 [WARNING] [Minecraft] Failed to handle packet for Astrel/122.149.210.164: java.lang.NullPointerException
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
        at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
        at keepcalm.mods.bukkit.ToBukkit.chunkFromCoords(ToBukkit.java:69)
        at keepcalm.mods.bukkit.ToBukkit.blockFromCoords(ToBukkit.java:64)
        at keepcalm.mods.bukkit.ToBukkitEvent.PlayerInteract(ToBukkitEvent.java:102)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
        at net.minecraftforge.event.ASMEventHandler_120_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at iv.a(NetServerHandler.java:553)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:430)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:302)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
        at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Update BukkitForge, http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.4.7/4/
