### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#839]
java.lang.NullPointerException
        at org.bukkit.Bukkit.getLogger(Bukkit.java:188)
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180)
        at org.bukkit.craftbukkit.Main.loadOptions(Main.java:159)
        at net.minecraft.server.MinecraftServer.fmlReentry(MinecraftServer.java:1620)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:138)
        at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1612)
        at org.bukkit.craftbukkit.Main.main(Main.java:21)

Got a message that my server was online,
I try to reboot it and before it actually loads i suddenly get this.
Tried updating tickthreading but this shows before it loads.
Any clue ?

**Comment by LunNova** [comment]
You have a broken configuration file, probably your bukkit.yml:

`at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180)`

**Comment by ThuGie** [comment]
You where right!
Even though i haven't even touched any config in ages..
That problem solved strait onto

27 achievements
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:138)
        at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1612)
        at org.bukkit.craftbukkit.Main.main(Main.java:21)
Caused by: java.lang.NoClassDefFoundError: me/nallar/collections/ListSet
        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:204)
        at ho.<init>(DedicatedServer.java:61)
        at net.minecraft.server.MinecraftServer.fmlReentry(MinecraftServer.java:1632)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: me.nallar.collections.ListSet
        at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
Caused by: java.lang.NullPointerException
        at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:207)
        ... 13 more
Any clue what could  be wrong here ?
No log is generated. so..

**Comment by LunNova** [comment]
Delete your server jar, and use the server jar in the TickThreadingBackups folder.

**Comment by ThuGie** [comment]
Thank you so much! People been bothering me about the down time haha.
