### ISSUE TITLE
TT1970 -- Harvester still

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#848]
[SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1569933505 in Overworld/0 at x, y, z: -1105, 73, 1099
java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
        at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-04 16:53:41 [INFO] Player Gods_Daddy used the wrench to remove the ic2.core.block.wiring.ElectricMFE (608-1) at 889/113/1322

**Comment by Drehmini** [comment]
I'm still getting these as well

```
2013-07-07 16:00:09 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1453859370 in Overworld/0 at x, y, z: 9599, 9, 4099
java.lang.NullPointerException
    at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
    at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```
