### ISSUE TITLE
[TT 1981 and earlier] Energy Tesseract Array Index

### ISSUE THREAD

**Issue by SuddenTurmoil** [MinimallyCorrect/TickThreading#851]
Many of the energy tesseracts attached to Energy Converters from the Energy Converts mod in FTB throw this error every few minutes. Not every energy tesseract attached to an Energy Converter throws the error, and not every error appears to have an Energy Converter attached to it. The vast majority are the combination of the two.
Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileTeleportEnergy @1543381828 in GregTower (Age 26)/26 at x, y, z: 252, 45, -226
java.lang.ArrayIndexOutOfBoundsException

I have changed the config for tesseracts to allow them to transfer up to 10000 MJ/t and there are many energy networks on the server that have at least 8K input/output. This error has been in at least the last 900 builds of TT.

**Comment by LunNova** [comment]
Is that the full error message? Can't fix it without a stack trace :s

**Comment by SuddenTurmoil** [comment]
It was at the time, I had to add the stacktrace tag onto the server start file but there were too many people on my server to kick them off in good conscious. Early morning updating / backups have since let me add that on and get a full stack trace for you. 
2013-07-05 08:10:14 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileTeleportEnergy @2036740901 in Twilight Forest/77 at x, y, z: 1806, 11, 11
java.lang.ArrayIndexOutOfBoundsException: 6
    at cofh.core.BlockUtils.getAdjacentCoordinatesForSide(BlockUtils.java:82)
    at thermalexpansion.transport.tileentity.TileTeleportEnergy.addToAdjPowerProvider(TileTeleportEnergy.java:166)
    at thermalexpansion.transport.tileentity.TileTeleportEnergy.receiveEnergy(TileTeleportEnergy.java:142)
    at thermalexpansion.transport.tileentity.TileTeleportEnergy.sendEnergy(TileTeleportEnergy.java:120)
    at thermalexpansion.transport.tileentity.TileTeleportEnergy.g(TileTeleportEnergy.java:160)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

Thank you for your help! Has anyone told you how generally awesome of an individual you are recently?

**Comment by LunNova** [comment]
Just realised this fix might not be correct, is it still happening?

**Comment by SuddenTurmoil** [comment]
I updated to the new build this morning and have had no errors in the console since. I was going to give it a full 24 hours before confirming fixed, but it appears to be so. Thanks for the follow up and all your hard work on this mod!
