### ISSUE TITLE
Incompatible with JAKJ's Redstone in Motion mod.

### ISSUE THREAD

**Issue by TaeoG** [MinimallyCorrect/TickThreading#859]
Trying to move a Frame results in an error. Asked jakj if he was capable of making it compatible and he said 

"yeah, that's not something I'm going to be able to fix right now, unless there's some token I can synchronize against. What's happening is my mod is forcing the tile entity to write itself out to a saveable record, just like what happens when the world is being saved. The problem is, this Tick Threading mod of yours probably makes the assumption that the function I'm calling will never be called except by Minecraft itself during the saving process.  
...
You can ask the TT guys if there's a way to synchronize tile-entity access so I can query tile entities at will; Without that, I don't see any way to make my mod compatible."

This is 1.5.2 btw.
Here is the error:
2013-07-07 16:09:41 [SEVERE] [TickThreading] Exception ticking TileEntity c JAKJ.RedstoneInMotion.CarriageEngineEntity @1252852893 in Overworld/0 at x, y, z: -203, 66, -75
java.lang.IllegalAccessError
        at JAKJ.RedstoneInMotion.NbtCompound.<init>(NbtCompound.java:17)
        at JAKJ.RedstoneInMotion.TileEntity.func_70310_b(TileEntity.java:36)
        at JAKJ.RedstoneInMotion.CarriageEntity.func_70310_b(CarriageEntity.java:78)
        at JAKJ.RedstoneInMotion.CarriagePackage.AddBlock(CarriagePackage.java:100)
        at JAKJ.RedstoneInMotion.PlatformCarriageEntity.FillPackage(PlatformCarriageEntity.java:23)
        at JAKJ.RedstoneInMotion.CarriageEngineEntity.GeneratePackage(CarriageEngineEntity.java:17)
        at JAKJ.RedstoneInMotion.CarriageDriveEntity.BeginMotion(CarriageDriveEntity.java:227)
        at JAKJ.RedstoneInMotion.CarriageDriveEntity.func_70316_g(CarriageDriveEntity.java:210)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-07 16:12:04 [WARNING] [TickThreading] Unsafe entity list iteration
java.lang.Throwable
        at nallar.tickthreading.minecraft.entitylist.EntityList.iterator(EntityList.java:72)
        at mithion.arsmagica.AMCore.onPlayerLogout(AMCore.java:525)
        at cpw.mods.fml.common.registry.GameRegistry.onPlayerLogout(GameRegistry.java:14)
        at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:389)
        at net.minecraft.network.NetServerHandler.func_72515_a(NetServerHandler.java:956)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:449)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
        at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:303)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by LunNova** [comment]
Remember, never report issues with TT to mod devs. It's my job to fix it, just give errors to me.

**Comment by TaeoG** [comment]
understood, just figured jakj would be interested. When his mod was incompatible with MCPC+ he worked with them directly to fix it. Good guy.
