### ISSUE TITLE
1.5.2 ticking block grass

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#861]
2013-07-08 13:47:57 [SEVERE] [TickThreading] Exception ticking block net.minecra
ft.block.BlockGrass@5507f60 at x60y1264z90
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_5_R3.CraftWorld.getBlockAt(CraftWorld.java:
202)
        at net.minecraft.block.BlockGrass.func_71847_b(BlockGrass.java:34)
        at net.minecraft.world.WorldServer.run(WorldServer.java:598)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java
:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:
16)

If you want more information, I only just started doing a world border fill when this showed up, no one else was online, and the error only showed up at the beginning. 

TT - v94
MCPC - v598

**Comment by LunNova** [comment]
Fixed in latest by disabling immediate chunk unloading, will queue as usual in all cases, even if a plugin requests an immediate unload.
