### ISSUE TITLE
MFR DeepStorageUnit Exception ticking TileEntity

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#862]
```
2013-07-07 11:57:35 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit @973074079 in Overworld/0 at x, y, z: 457, 38, 385
java.lang.NullPointerException
    at powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit.checkInput(TileEntityDeepStorageUnit.java:160)
    at powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit.g(TileEntityDeepStorageUnit.java:139)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:100)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

The Deep Storage Units still work.

**Comment by andremiller** [comment]
Been using Tickthreading + Deep storage units on MC1.4.7 + FTB since build 1962, and today I received this error for the first time, with build 2034:

2013-07-11 20:21:03 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit @1308164694 in Overworld/0 at x, y, z: -543, 51, -86
java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit.checkInput(TileEntityDeepStorageUnit.java:160)
        at powercrystals.minefactoryreloaded.processing.TileEntityDeepStorageUnit.g(TileEntityDeepStorageUnit.java:139)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:96)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
