### ISSUE TITLE
[TT 2003] ME NPE

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#869]
```
2013-07-09 15:07:11 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @51439561 in Overworld/0 at x, y, z: -195, 92, 558
java.lang.NullPointerException
    at appeng.me.tile.TileController.g_sync0(TileController.java:1024)
    at appeng.me.tile.TileController.g(TileController.java)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:96)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

**Comment by Drehmini** [comment]
This also happens with the latest (2011), and it's currently spamming the console.

**Comment by LunNova** [comment]
Fixed with AE threading rework in latest.
