### ISSUE TITLE
1.5.2 Twilight issues

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#873]
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:00 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:01 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:01 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.util.NoSuchElementException
    at java.util.LinkedList.removeFirst(Unknown Source)
    at magicbees.world.WorldTicker.tickEnd(WorldTicker.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:527)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-07-10 14:22:01 [SEVERE] [TickThreading] Twilight Forest/7 has become unstable, stopping.
2013-07-10 14:22:01 [INFO] [TickThreading] Server shutting down - requested at 
nallar.insecurity.ThisIsNotAnError: This is not an error.
    at nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:31)
    at net.minecraft.server.MinecraftServer.func_71263_m(MinecraftServer.java:110)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:580)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:676)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by Tencao** [comment]
More details - mcpc+ version 598, TT version 106
