### ISSUE TITLE
NullpointerException ticking minefactoryreloaded.plants.TileEntityHarvester

### ISSUE THREAD

**Issue by andremiller** [MinimallyCorrect/TickThreading#874]
I'm using TickThreading-1.4.7-1.0.0.2005 with FTB Ultimate 1.1.2, Minecraft 1.4.7

I've had no problems thus far, but yesterday one of the players on my server built an oak tree farm with Minefactory Reloaded planters, fertilizers and harvesters, and I noticed the following exceptions in my server log.

I don't know if this is a problem or not, he reports that his harvesters are working fine in-game.

2013-07-10 20:29:22 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1606970099 in Overworld/0 at x, y, z: -515, 63, -140
java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
        at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:96)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

2013-07-10 20:35:27 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1606970099 in Overworld/0 at x, y, z: -515, 63, -140
java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
        at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:96)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

2013-07-10 20:36:44 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1606970099 in Overworld/0 at x, y, z: -515, 63, -140
java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
        at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:96)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

2013-07-10 20:52:17 [SEVERE] [TickThreading] Exception ticking TileEntity c powercrystals.minefactoryreloaded.plants.TileEntityHarvester @1606970099 in Overworld/0 at x, y, z: -515, 63, -140
java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.plants.TileEntityHarvester.activateMachine(TileEntityHarvester.java:131)
        at powercrystals.minefactoryreloaded.core.TileEntityFactoryPowered.g(TileEntityFactoryPowered.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:96)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by andremiller** [comment]
Hmm, I'm sure I did a search before and nothing came up for harvester, but I just found an issue already logged for the same error message, Issue #793 

So I'll close this one then.
