### ISSUE TITLE
Crash on loading Screen, Only one Mod

### ISSUE THREAD

**Issue by LiquidFires** [MinimallyCorrect/TickThreading#880]
using Minecraft 1.6.2
Forge: minecraftforge-installer-1.6.2-9.10.0.789
BC:  buildcraft-A-3.7.1

getting error 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/10/13 11:28 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lnet/minecraftforge/liquids/LiquidStack;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Unknown Source)
    at java.lang.Class.getDeclaredField(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.parseSimpleFieldAnnotation(FMLModContainer.java:422)
    at cpw.mods.fml.common.FMLModContainer.processFieldAnnotations(FMLModContainer.java:378)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:520)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:193)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:173)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:104)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:510)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:172)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:796)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.liquids.LiquidStack
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:171)

I understand current BC is for 1.5 but I have been told it works for 1.6.2.... only thing i did was install the Forge Installer, not the universal because i was told not to... started on a fresh minecraft (Deleted everything and re downloaded)... other mods work but took all others out of mod folder to test BC and doesn't work so no conflicts

**Comment by LunNova** [comment]
You made the issue in the wrong place, this isn't related to TickThreading. Probably should be in the BuildCraft repo?
