### ISSUE TITLE
1.5.2 Deadlocks

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#889]
Just to say, sorry if this turns out to be my fault and not tickthreading, but I thought I'd post here anyway for some answers.

http://pastebin.com/Hk2NUQP3

**Comment by LunNova** [comment]
`"Server thread" RUNNABLE (in native)
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(Unknown Source)
        at java.io.BufferedOutputStream.write(Unknown Source)
        -  locked java.io.BufferedOutputStream@4287189c
        at java.io.PrintStream.write(Unknown Source)
        -  locked java.io.PrintStream@3360cbe3
        at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
        at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
        at sun.nio.cs.StreamEncoder.flush(Unknown Source)
        -  locked java.io.OutputStreamWriter@17e9be6f
        at java.io.OutputStreamWriter.flush(Unknown Source)
        at java.util.logging.StreamHandler.flush(Unknown Source)
        -  locked org.bukkit.craftbukkit.v1_5_R3.util.TerminalConsoleHandler@7ff8a2e1
        at org.bukkit.craftbukkit.v1_5_R3.util.TerminalConsoleHandler.flush(TerminalConsoleHandler.java:32)
        -  locked org.bukkit.craftbukkit.v1_5_R3.util.TerminalConsoleHandler@7ff8a2e1
        at java.util.logging.ConsoleHandler.publish(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at java.util.logging.Logger.doLog(Unknown Source)
        at java.util.logging.Logger.log(Unknown Source)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:494)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189)
        at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:541)
        at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:874)
        at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
        at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
        -  locked net.minecraft.server.dedicated.DedicatedServerListenThread@72d575ac
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
        -  locked net.minecraft.server.dedicated.DedicatedServerListenThread@72d575ac
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:303)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)`

Make an MCPC+ issue saying that logging froze here, and logging should be off the main thread like with forge. No idea why bukkit's logging froze up for 40+ seconds though. Were you doing a backup at the time or something?

**Comment by Tencao** [comment]
No backups, just normal server operations.

**Comment by Tencao** [comment]
I'll close this issue as it turns out to be mainly mcpc and plugin related.
