### ISSUE TITLE
Server unstable, stopping.

### ISSUE THREAD

**Issue by joaopms** [MinimallyCorrect/TickThreading#899]
Hello! I'm TichThreading and MCPC+ and my server is stopping very frequently:
TT Log: http://pastebin.com/KnrUwcxT
Patcher Log: http://pastebin.com/vkssazi3

**Comment by LunNova** [comment]
Can you upgrade TT please? I think this issue is already fixed, you're 43 builds out of date.

`v1.5.2.84`

**Comment by joaopms** [comment]
Just updated and it happened again

**Comment by LunNova** [comment]
TT log again please? Pretty sure the issue you posted there was fixed, although it could be a slightly different issue.

**Comment by joaopms** [comment]
Hmmm... I was runninc v1.5.2.137 and it crashed, but I upgraded to v1.5.2.138 and it's okay. If it shuts down I will post the log again.

2013-07-14 20:20:24 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-07-14 20:20:42 [INFO] [TickThreading] Skipping version tick handler c com.pahimar.ee3.core.handlers.VersionCheckTickHandler com.pahimar.ee3.core.handlers.VersionCheckTickHandler@6620c832
2013-07-14 20:20:59 [INFO] [TickThreading] Skipping version tick handler c magicbees.main.utils.TickHandlerVersion magicbees.main.utils.TickHandlerVersion@4807d8d0
2013-07-14 20:21:03 [SEVERE] [TickThreading] TickThreading v1.5.2.137 for MC1.5.2 on 1.5.2 tickthreading,mcpc,spigot,craftbukkit,forge,fml - 1.7.0_10-b18 is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at https://github.com/nallar/TickThreading/issues/new

Also, you really should be making regular backups. (You should be doing that even when not using TT.)
2013-07-14 20:23:19 [WARNING] [TickThreading] Unsafe entity list iteration
    at nallar.tickthreading.minecraft.entitylist.EntityList.iterator(EntityList.java:72)
    at mithion.arsmagica.AMCore.onPlayerChangedDimension(AMCore.java:542)
    at cpw.mods.fml.common.registry.GameRegistry.onPlayerChangedDimension(GameRegistry.java:426)
    at com.xcompwiz.mystcraft.linking.LinkListenerForgeServer.onLinkEnd(LinkListenerForgeServer.java:15)
    at net.minecraftforge.event.ASMEventHandler_148_LinkListenerForgeServer_onLinkEnd_LinkEventEnd.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at com.xcompwiz.mystcraft.linking.LinkListenerManager.onLinkEnd(LinkListenerManager.java:40)
    at com.xcompwiz.mystcraft.linking.LinkController.teleportEntity(LinkController.java:135)
    at com.xcompwiz.mystcraft.linking.LinkController.travelEntity(LinkController.java:59)
    at com.xcompwiz.mystcraft.command.CommandTPX.func_71515_b(CommandTPX.java:106)
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:95)
    at org.bukkit.craftbukkit.v1_5_R3.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchVanillaCommand(CraftServer.java:580)
    at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1395)
    at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1249)
    at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1175)
    at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:60)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
    at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:303)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-07-14 20:27:26 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Bad packet id 67
    at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:165)
    at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300)
    at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
    at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
2013-07-14 20:45:18 [INFO] [TickThreading] Server shutting down - requested at 
nallar.insecurity.ThisIsNotAnError: This is not an error.
    at nallar.insecurity.InsecurityManager.checkExit(InsecurityManager.java:31)
    at net.minecraft.server.MinecraftServer.func_71263_m(MinecraftServer.java:110)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.shutdown(CraftServer.java:1096)
    at org.bukkit.Bukkit.shutdown(Bukkit.java:394)
    at org.bukkit.command.defaults.StopCommand.execute(StopCommand.java:28)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
    at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:564)
    at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1389)
    at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1249)
    at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1175)
    at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:60)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
    at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:303)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-07-14 20:45:18 [INFO] [TickThreading] Saving all player data.
2013-07-14 20:45:18 [INFO] [TickThreading] Done saving player data, now saving 3 worlds.
2013-07-14 20:45:18 [INFO] [TickThreading] World save completed, flushing world data to disk.
2013-07-14 20:45:21 [INFO] [TickThreading] Flushed world data to disk.
2013-07-14 20:45:21 [INFO] [TickThreading] Stopping the server. serverRunning: false, serverIsRunning: true, is crash: false
