### ISSUE TITLE
Ticking Entity Errors - Build #662

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#90]
2013-01-28 04:38:03 [SEVERE] [TickThreading] Exception during entity tick at rX:
 1, rZ: 10, hashCode: 655361:
java.lang.NullPointerException
        at ow.bl(SourceFile:139)
        at md.c(EntityLiving.java:1781)
        at md.j_(EntityLiving.java:843)
        at ow.j_(SourceFile:106)
        at yc.a(World.java:2295)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2257)
        at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(
EntityTickRegion.java:47)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegio
n.java:88)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.j
ava:88)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.j
ava:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(
ThreadManager.java:149)

**Comment by Puremin0rez** [comment]
Here's more:
http://pastebin.com/dDpj4MEY

**Comment by Puremin0rez** [comment]
... and more:
http://pastebin.com/iYBbXpvx

**Comment by Puremin0rez** [comment]
I should note this is happening every few seconds, so you should be able to replicate them pretty easily.

**Comment by LunNova** [comment]
Are concurrent network ticks enabled? Turn them off if so.

**Comment by LunNova** [comment]
Should be fixed in latest.
