### ISSUE TITLE
Internal server Error

### ISSUE THREAD

**Issue by tacharion** [MinimallyCorrect/TickThreading#904]
I install tick threading 

And become these failure

2013-07-16 02:07:39 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 82573
java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
    at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
    at keepcalm.mods.bukkit.ToBukkit.chunkFromCoords(ToBukkit.java:65)
    at keepcalm.mods.bukkit.ToBukkit.blockFromCoords(ToBukkit.java:60)
    at keepcalm.mods.bukkit.ToBukkitEvent.PlayerInteract(ToBukkitEvent.java:102)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
    at net.minecraftforge.event.ASMEventHandler_133_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
    at iv.a(NetServerHandler.java:553)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:430)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:302)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(SourceFile:849)
2013-07-16 02:07:39 [WARNING] [Minecraft] Failed to handle packet for steffi841/25.159.110.214: java.lang.NullPointerException
java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
    at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
    at keepcalm.mods.bukkit.ToBukkit.chunkFromCoords(ToBukkit.java:65)
    at keepcalm.mods.bukkit.ToBukkit.blockFromCoords(ToBukkit.java:60)
    at keepcalm.mods.bukkit.ToBukkitEvent.PlayerInteract(ToBukkitEvent.java:102)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
    at net.minecraftforge.event.ASMEventHandler_133_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
    at iv.a(NetServerHandler.java:553)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:430)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:302)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:195)
    at fy.run(SourceFile:849)
2013-07-16 02:07:39 [INFO] [STDOUT] Unloading Player: steffi841

This is only then, when i rightclicking on air with a block in my hands 

i will be kicked with the error: 

Internaö Server Error

i use these mods:

advancedmachines
advancedsolarpaneö
Appliedenergistics
BiblioCraft
buildcraft
Chargepads
Chickenchunks 1.3.1.2
CoFHcore
Computercraft
ee3
Enderstorage
extrabees-1.5.0.6b
ExtrabiomesXL- universal- 1.4.7-3.11.0
factorzation
flatbedrock
forestry
ForgeEssentials- All
gravigun
gravisuite
gregtech
IC2
IC2 Nuclearcontrol
immibis-core-52.4.6
ironChest
MinefactoryReloaded
modularforcefieldsystem
modularpowersuits
Mystcraft
netherores
Obsidiplates
omnitools
petrogen
Portalgun
PowerConvertes
railcraft
redpowercombat
redpowercore
redpowerdigital
redpowermechanial
scretroomsmod
soulshards
SteveCarts
Thaumraft
Thaumicbees
ThermalEspansion
TickThreading-1.4.7-1.0.0.2062
tubestuff
Twillightforest
wirelessredstoneaddons
wirelesredstonecore
wirelesredstoneredpower
Xreliquary
Xycraft

And These Coremods

BukkitForge 1.4.7-255
CodechickenCore
ForgeEssentials-core
Miscperipherals-3.1c
NEI
powercrytalscore

Plugins

World edit

The server runs on ah quadcore max 3.2GH 
4 GB RAM

**Comment by LunNova** [comment]
Update BukkitForge, use http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.4.7/4/

**Comment by tacharion** [comment]
the folowing link is not avaible ......

http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.4.7/4/
