### ISSUE TITLE
applied energistics constant crashes

### ISSUE THREAD

**Issue by seriousvern** [MinimallyCorrect/TickThreading#910]
last tick 5s ago.
Waiting ThreadManagers: Entities in Overworld/0, World Tick

Definitely deadlocked: 
"Entities in Overworld/0 - 9" Id=129 BLOCKED on appeng.me.tile.TileController@1af4f8bc owned by "Entities in Overworld/0 - 3" Id=123
    at appeng.me.tile.TileController.getCellArray(TileController.java:813)
    -  blocked on appeng.me.tile.TileController@1af4f8bc
    at appeng.me.tile.TileController.requestUpdate(TileController.java:562)
    at appeng.me.GridInterface.requestUpdate(GridInterface.java:119)
    at appeng.me.tile.TileInterfaceBase.a(TileInterfaceBase.java:272)
    at appeng.util.inv.AdaptorIInventory.addItems(AdaptorIInventory.java:78)
    at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:352)
    at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:369)
    at appeng.me.tile.TileController.g(TileController.java)
    -  locked appeng.me.tile.TileController@30d4398
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@485e6fd9
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

"Entities in Overworld/0 - 3" Id=123 BLOCKED on appeng.me.tile.TileController@30d4398 owned by "Entities in Overworld/0 - 9" Id=129
    at appeng.me.tile.TileController.getCellArray(TileController.java:813)
    -  blocked on appeng.me.tile.TileController@30d4398
    at appeng.me.tile.TileController.requestUpdate(TileController.java:562)
    at appeng.me.GridInterface.requestUpdate(GridInterface.java:119)
    at appeng.me.tile.TileInterfaceBase.a(TileInterfaceBase.java:272)
    at appeng.util.inv.AdaptorIInventory.addItems(AdaptorIInventory.java:78)
    at appeng.me.tile.TileOutputCable.OutputItems(TileOutputCable.java:352)
    at appeng.me.tile.TileOutputCable.tickNetwork(TileOutputCable.java:369)
    at appeng.me.tile.TileController.g(TileController.java)
    -  locked appeng.me.tile.TileController@1af4f8bc
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@300134ad
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

Attempting to recover without restarting.

this is what i am getting on my server
can you tell me whats causing this so i can have my players avoid it. or if you can fix this for me. thanks

**Comment by darkdeath1332** [comment]
Same problem
