### ISSUE TITLE
Opening Canvas Bag causes player to crash

### ISSUE THREAD

**Issue by droosk** [MinimallyCorrect/TickThreading#918]
Using Ultimate 1.12 Recommended
Tick Threading 2090
No other plugins or mods outside of standard Ultimate pack

When the player tries to open a canvas bag, they are kicked from the server with this:

2013-07-19 22:49:27 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 1811
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
        at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
        at keepcalm.mods.bukkit.ToBukkit.chunkFromCoords(ToBukkit.java:69)
        at keepcalm.mods.bukkit.ToBukkit.blockFromCoords(ToBukkit.java:64)
        at keepcalm.mods.bukkit.ToBukkitEvent.PlayerInteract(ToBukkitEvent.java:102)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
        at net.minecraftforge.event.ASMEventHandler_123_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at iv.a(NetServerHandler.java:553)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:430)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:306)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
        at fy.run(SourceFile:849)

**Comment by droosk** [comment]
Additional:

2013-07-19 22:49:27 [WARNING] [Minecraft] Failed to handle packet for player/ip: java.lang.NullPointerException
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftChunk.getHandle(CraftChunk.java:70)
        at org.bukkit.craftbukkit.CraftChunk.<init>(CraftChunk.java:56)
        at keepcalm.mods.bukkit.ToBukkit.chunkFromCoords(ToBukkit.java:69)
        at keepcalm.mods.bukkit.ToBukkit.blockFromCoords(ToBukkit.java:64)
        at keepcalm.mods.bukkit.ToBukkitEvent.PlayerInteract(ToBukkitEvent.java:102)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
        at net.minecraftforge.event.ASMEventHandler_123_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at iv.a(NetServerHandler.java:553)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:430)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:306)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
        at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Same problem as #908, need to update BukkitForge but afaik @alexbegt hasn't released the fixed build yet.
