### ISSUE TITLE
MC 1.4.7 TTbuild-2095-Another buildcraft error

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#925]
Updating from 2091 to 2095 on the first server start i get this error

[SEVERE] [ForgeModLoader] A TileEntity net.minecraft.src.buildcraft.transport.GenericPipe(buildcraft.transport.TileGenericPipe) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at buildcraft.transport.PipeTransportItems.readFromNBT(PipeTransportItems.java)
    at buildcraft.transport.Pipe.readFromNBT(Pipe.java:222)
    at buildcraft.transport.TileGenericPipe.a(TileGenericPipe.java:124)
    at any.c(TileEntity.java:151)
    at aam.a(ThreadedChunkLoader.java:471)
    at aam.a(ThreadedChunkLoader.java:190)
    at aam.a(ThreadedChunkLoader.java:161)
    at im.f(ThreadedChunkProvider.java:741)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:552)
    at im.getChunkAt(ThreadedChunkProvider.java:521)
    at im.c(ThreadedChunkProvider.java:462)
    at yc.getTEWithLoad(World.java:346)
    at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:370)
    at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:335)
    at codechicken.chunkloader.ChunkLoaderManager.revivePlayerLoaders(ChunkLoaderManager.java:901)
    at codechicken.chunkloader.ChunkLoaderManager.serverTick(ChunkLoaderManager.java)
    at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPostServerTick_p0(FMLCommonHandler.java:275)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:342)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
    at fy.run(SourceFile:849)

Here is the log: https://gist.github.com/Kusinagie/6051368

Trying to stop and restart gives me this:
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at -130,69,-251
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at 264,61,350
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at 264,62,350
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at 266,62,348
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at 266,63,348
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at 264,63,350
2013-07-22 00:25:02 [WARNING] [Buildcraft] Detected pipe with unknown key (-1). Did you remove a buildcraft addon?
2013-07-22 00:25:02 [WARNING] [Buildcraft] Pipe failed to load from NBT at 266,61,348

And here is the full log: https://gist.github.com/Kusinagie/6051378

**Comment by jznomoney** [comment]
I believe I had that to.   All my logistics pipes disappeared.

**Comment by DrFestus** [comment]
I'm throwing these errors on build 2096 still also
