### ISSUE TITLE
MC 1.4.7 TTbuild-2096-possible twilight forest issue?

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#932]
After updating to 2096 i noticed this in the start up log. not sure if its an issue or not figured i would report it.

2013-07-22 14:51:25 [FINE] [TickThreading] Set dimension ID for Feed The Beast 1.4.2/7
2013-07-22 14:51:25 [INFO] [STDERR] java.io.InvalidClassException: nallar.collections.ConcurrentUnsafeIterableArrayList; local class incompatible: stream classdesc serialVersionUID = -560123237591319945, local class serialVersionUID = 7513209935518840089
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectStreamClass.initNonProxy(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readClassDesc(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readClassDesc(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readObject0(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at java.io.ObjectInputStream.readObject(Unknown Source)
2013-07-22 14:51:25 [INFO] [STDERR]     at twilightforest.TFFeatureCache.load(TFFeatureCache.java:146)
2013-07-22 14:51:25 [INFO] [STDERR]     at twilightforest.world.TFWorldChunkManager.loadFeatureCache(TFWorldChunkManager.java:422)
2013-07-22 14:51:25 [INFO] [STDERR]     at twilightforest.TFEventListener.worldLoad(TFEventListener.java:448)
2013-07-22 14:51:25 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_164_TFEventListener_worldLoad_Load.invoke(.dynamic)
2013-07-22 14:51:25 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-07-22 14:51:25 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-07-22 14:51:25 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:279)
2013-07-22 14:51:25 [INFO] [STDERR]     at ho.c(DedicatedServer.java:180)
2013-07-22 14:51:25 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:172)
2013-07-22 14:51:25 [INFO] [STDERR]     at fy.run(SourceFile:849)

Here is the full log: https://gist.github.com/Kusinagie/6056691

I still had the errors about buildcraft pipes as you will see in the log but i logged in found the location. The bounding boxes were still there but no actual pipe. broke replaced them all seems fine.

**Comment by LunNova** [comment]
Delete "twilight.fc" under world/DIM7.
