### ISSUE TITLE
AE error spamming console

### ISSUE THREAD

**Issue by demon959** [MinimallyCorrect/TickThreading#940]
Using build 179 currently in 1.5.2 server, this AE error keep spamming the console. The coordinate is the position of the AE controller

2013-07-25 10:36:12 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @69498045 in 152_world/0 at x, y, z: 2643, 55, -1142
java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at appeng.me.tile.TileController.updateTileEntity(TileController.java:1033)
        at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:487)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick
(TileEntityTickRegion.java:90)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by demon959** [comment]
New one showing up on console today, still from the AE controller

2013-07-26 10:48:00 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileController @644226289 in 152_world/0 at x, y, z: 2643, 55, -1142
Stack trace unavailable for java.lang.NullPointerException-java.lang.NullPointer
Exception. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.
