### ISSUE TITLE
[1.4.7 MCPC] [TT 2099] [SEVERE] [TickThreading] Failed to handle packet from unknown

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#941]
[SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (7680 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:72)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by alicheek** [comment]
[SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (8192 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:72)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by alicheek** [comment]
[SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (6656 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:72)
    at ch.run(ReplaceTcpReaderThread.java:22)
