### ISSUE TITLE
FTB Unleashed v1.1.0 Deadlock

### ISSUE THREAD

**Issue by demon959** [MinimallyCorrect/TickThreading#969]
Using Latest v1.5.2 185 build, error log as below, removed TT and the deadlock is gone.

2013-07-31 14:53:50 [INFO] [STDERR] Exception in thread "Deadlock Detector" java.lang.OutOfMemoryError: PermGen space
2013-07-31 14:53:52 [INFO] [Minecraft-Server] /10.10.69.169:57129 lost connection
2013-07-31 14:53:52 [INFO] [Minecraft-Server] /10.10.69.169:57130 lost connection
2013-07-31 14:53:52 [INFO] [Minecraft-Server] /10.10.69.169:57131 lost connection
2013-07-31 14:53:52 [INFO] [Minecraft-Server] /10.10.69.169:57132 lost connection
2013-07-31 14:53:52 [INFO] [Minecraft-Server] /10.10.69.169:57134 lost connection
2013-07-31 14:53:52 [INFO] [Minecraft-Server] /10.10.69.169:57135 lost connection
2013-07-31 14:54:00 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoClassDefFoundError
java.lang.NoClassDefFoundError: cpw/mods/ironchest/ContainerIronChestBase
    at cpw.mods.ironchest.CommonProxy.getServerGuiElement(CommonProxy.java:42)
    at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:308)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:352)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2396)
    at cpw.mods.ironchest.BlockIronChest.func_71903_a(BlockIronChest.java:143)
    at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:412)
    at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:553)
    at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:461)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:134)
    at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:307)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: cpw.mods.ironchest.ContainerIronChestBase
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more
Caused by: java.lang.OutOfMemoryError: PermGen space

**Comment by LunNova** [comment]
Caused by: java.lang.OutOfMemoryError: PermGen space.

Set -XX:MaxPermSize=128m in your java options.
