### ISSUE TITLE
1.5.2 FTB Unleashed Error

### ISSUE THREAD

**Issue by demon959** [MinimallyCorrect/TickThreading#973]
2013-08-01 01:57:10 [SEVERE] [TickThreading] Failed to write chunk data to disk
164, -72
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
        at java.util.HashMap$ValueIterator.next(HashMap.java:868)
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:24)
        at net.minecraft.nbt.NBTBase.func_74731_a(SourceFile)
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
        at net.minecraft.nbt.NBTBase.func_74731_a(SourceFile)
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
        at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:49)
        at net.minecraft.nbt.NBTBase.func_74731_a(SourceFile)
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
        at net.minecraft.nbt.NBTBase.func_74731_a(SourceFile)
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(SourceFile:25)
        at net.minecraft.nbt.NBTBase.func_74731_a(SourceFile)
        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStream
Tools.java:140)
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(Threa
dedChunkLoader.java:271)
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(Threa
dedChunkLoader.java:257)
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFil
e:29)
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:22)
        at java.lang.Thread.run(Unknown Source)

**Comment by HaoSs07** [comment]
tt for 1.5.2 is not stable for day do day use

**Comment by demon959** [comment]
Oh well, I am just reporting what I've got from using TT. If no one uses it and report, it can't get anywhere better.
