### ISSUE TITLE
1.5.2 FTB Unleashed Wireless Redstone

### ISSUE THREAD

**Issue by demon959** [MinimallyCorrect/TickThreading#976]
Using latest build #185, this several lines of log spams the server console overnight, until I checked this morning. The console was still being spammed. It created some 50mb of logs.
And I think I got disconnected on the client side when I tried to place the Chicken Bone Wireless Redstone stuff in game. Tried restarting the server but as soon as the server finished initial loading, these message came back and spam the console again.

2013-08-01 20:36:54 [SEVERE] [TickThreading] Exception ticking TileEntity c TileMultipart_cmp$$3 @1927868024 in 152_world/0 at x, y, z: 1325, 62, 2265
java.lang.IllegalStateException: Tried to finish an operation that was not on top
    at codechicken.multipart.TileMultipart$OperationSynchroniser.finishOperation(TileMultipart.scala:466)
    at codechicken.multipart.TileMultipart$.finishOperation(TileMultipart.scala:515)
    at codechicken.multipart.TileMultipart.func_70316_g(TileMultipart.scala:86)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-08-01 20:36:54 [SEVERE] [TickThreading] Exception ticking TileEntity c TileMultipart_cmp$$5 @1213981056 in 152_world/0 at x, y, z: 1354, 66, 2295
java.lang.IllegalStateException: Inconsistant Operation stack
    at codechicken.multipart.TileMultipart$OperationSynchroniser.finishOperation(TileMultipart.scala:474)
    at codechicken.multipart.TileMultipart$.finishOperation(TileMultipart.scala:515)
    at codechicken.multipart.TileMultipart.func_70316_g(TileMultipart.scala:86)
    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by BobbyFuzzy** [comment]
I also have this issue. The chunk with the offending wireless redstone (receiver in my case) did not render and looked very much like a small(er) chunk error.
I was using TT186.

**Comment by floh22** [comment]
are people still having this issue?

**Comment by alicheek** [comment]
yes I am I just disabled the mod

**Comment by floh22** [comment]
hm ok, and do you have barrels working? cause for me they all dissapeared like mentioned in another bug report. i wanna use TT, it just doesnt seem stable enough atm though :frowning:
