### ISSUE TITLE
TT 185, MCPC152 B623 - [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.7 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#980]
This is beeing spammed in my console. Things are working as it should, but it just fills the console making ut unreadable.

Thanks.

21:09:10 [SEVERE] Could not pass event BlockFromToEvent to GriefPrevention v7.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at net.minecraft.block.BlockFlowing.func_71847_b(BlockFlowing.java:222)
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:352)
        at net.minecraft.world.WorldServer.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:411)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:531)
        at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:684)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_5_R3.CraftWorld.getUID(CraftWorld.java:539)
        at org.bukkit.craftbukkit.v1_5_R3.CraftWorld.equals(CraftWorld.java:1208)
        at java.util.ArrayList.indexOf(ArrayList.java:269)
        at java.util.ArrayList.contains(ArrayList.java:252)
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockFromTo(BlockEventHandler.java:626)
        at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)
        ... 12 more

**Comment by kittykiller** [comment]
set 
 cleanWorlds=false
in the TickThreading.cfg

**Comment by mainsheep** [comment]
Ahhh damnit! How could I miss that? :)

Thank you.
