### ISSUE TITLE
Unrecoverable chunk update crash

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#99]
2013-01-30 10:51:39 [SEVERE] [ForgeModLoader] Error handling login related packet - connection from usernameXXX [/xxx.xxx.xxx.xxx:55981] refused
java.lang.IllegalStateException: Entity is already tracked!
        at ii.a_nolock(EntityTracker.java:196)
        at ii.a(EntityTracker.java)
        at ii.a_nolock(EntityTracker.java:150)
        at ii.a(EntityTracker.java)
        at ij.a(SourceFile:24)
        at yc.a(World.java:1554)
        at in.a(WorldServer.java:865)
        at yc.a(World.java:40)
        at zz.c_nolock(Chunk.java:1084)
        at zz.c(Chunk.java)
        at im.c(ChunkProviderServer.java:223)
        at ik.a(SourceFile:53)
        at ik.a_s0(SourceFile:203)
        at ik.a(SourceFile)
        at gm.a(ServerConfigurationManager.java:163)
        at gm.c_nolock(ServerConfigurationManager.java:206)
        at gm.c(ServerConfigurationManager.java)
        at gm.a(ServerConfigurationManager.java:123)
        at it.completeConnection(NetLoginHandler.java:198)
        at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
        at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
        at it.d(NetLoginHandler.java:182)
        at it.c(NetLoginHandler.java:75)

And this one is repeated for atleast 3 threads in overworld:
2013-01-30 10:51:44 [SEVERE] [TickThreading] Unhandled exception in worker thread Chunk Updates for Overworld/0 - 5
t: Exception getting block type in world
        at yc.a(World.java:413)
        at akj.b(BlockGrass.java:114)
        at in.run(WorldServer.java:152)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:149)
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at ii.a_nolock(EntityTracker.java:196)
        at ii.a(EntityTracker.java)
        at ii.a_nolock(EntityTracker.java:150)
        at ii.a(EntityTracker.java)
        at ij.a(SourceFile:24)
        at yc.a(World.java:1554)
        at in.a(WorldServer.java:865)
        at yc.a(World.java:40)
        at zz.c_nolock(Chunk.java:1084)
        at zz.c(Chunk.java)
        at im.c(ChunkProviderServer.java:223)
        at im.d(ChunkProviderServer.java:115)
        at yc.e(World.java:524)
        at yc.a(World.java:404)
        ... 4 more

**Comment by ghost** [comment]
After the crash the server does nothing, can't even Ctrl+c close it. So i'm using >kill -7 pid to ckill it. This error seems to happen quite often.

**Comment by LunNova** [comment]
This is fixed in build 709, sorry about not updating ftb-craft last night. I was on intermittent 3G internet and didn't want to risk leaving the server half-updated or broken in some way. :(
