### ISSUE TITLE
mcpc+ 1.5.2 TT186 Bukkit TekkitCustomizer

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#998]
This error happens only when TT is set to unload world 

[SEVERE] Could not pass event PlayerInteractEvent to TekkitCustomizer v1.6

org.bukkit.event.EventException

  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:363)

  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

  at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:47)

  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)

  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)

  at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189)

  at net.minecraft.item.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:164)

  at net.minecraft.network.NetServerHandler.func_72510_a(NetServerHandler.java:752)

  at net.minecraft.network.packet.Packet14BlockDig.func_73279_a(SourceFile:46)

  at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:323)

  at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)

  at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)

Caused by: java.lang.NullPointerException

  at org.bukkit.craftbukkit.v1_5_R3.CraftWorld.getUID(CraftWorld.java:539)

  at org.bukkit.craftbukkit.v1_5_R3.CraftWorld.equals(CraftWorld.java:1208)

  at java.util.ArrayList.indexOf(ArrayList.java:269)

  at java.util.ArrayList.contains(ArrayList.java:252)

  at me.ryanhamshire.TekkitCustomizer.TekkitCustomizer.isBanned(TekkitCustomizer.java:475)

  at me.ryanhamshire.TekkitCustomizer.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:108)

  at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:606)

  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:361)

  ... 11 more

**Comment by LunNova** [comment]
TekkitCustomizer isn't handling world unload events properly (or at all), it's leaving a world which is unloaded in whichever arraylist is accessed at at me.ryanhamshire.TekkitCustomizer.TekkitCustomizer.isBanned(TekkitCustomizer.java:475).

Not a TT bug.

**Comment by HaoSs07** [comment]
thats strange. because there was no exception when mcpc was unloading worlds

**Comment by LunNova** [comment]
It was just leaking memory without throwing an error. Clean worlds fixes
the leaking but breaks if somethinf uses the world.

**Comment by HaoSs07** [comment]
well the nether got corrupted. had to rollback it. also put the world on unload false. and after 12 hours. i had this with 3 players on :)) :
&gt;12:37:17 [INFO]  [0;33;22mCurrent TPS =  [1.988 [m

&gt;12:37:17 [INFO]  [0;33;22mMaximum memory: [5,053 MB. [m

&gt;12:37:17 [INFO]  [0;33;22mAllocated memory: [5,053 MB. [m

&gt;12:37:17 [INFO]  [0;33;22mFree memory: [9 MB. [m

i have 2 GB more then what i had for 1.4.7. alos the CPU usage is duble. on ultimate had 80 - 100 cpu for a month+ old map. On unleashed i have 200 cpu for a week old map. Unfortunately TT for 1.5.2 is unusable for me.
