### ISSUE TITLE
[1.5.2][186][SEVERE] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by JohnPark234** [MinimallyCorrect/TickThreading#999]
2013-08-13 12:11:10 [SEVERE] java.util.ConcurrentModificationException
2013-08-13 12:11:10 [SEVERE]    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
2013-08-13 12:11:10 [SEVERE]    at java.util.HashMap$EntryIterator.next(HashMap.java:934)
2013-08-13 12:11:10 [SEVERE]    at java.util.HashMap$EntryIterator.next(HashMap.java:932)
2013-08-13 12:11:10 [SEVERE]    at universalelectricity.core.electricity.ElectricityNetwork.getProduced(ElectricityNetwork.java:126)
2013-08-13 12:11:10 [SEVERE]    at universalelectricity.core.electricity.ElectricityNetwork.consumeElectricity(ElectricityNetwork.java:250)
2013-08-13 12:11:10 [SEVERE]    at universalelectricity.core.electricity.ElectricityNetworkHelper.consumeFromMultipleSides(ElectricityNetworkHelper.java:153)
2013-08-13 12:11:10 [SEVERE]    at universalelectricity.prefab.tile.TileEntityElectricityRunnable.func_70316_g(TileEntityElectricityRunnable.java:41)
2013-08-13 12:11:10 [SEVERE]    at micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityElectric.func_70316_g(GCCoreTileEntityElectric.java:118)
2013-08-13 12:11:10 [SEVERE]    at micdoodle8.mods.galacticraft.core.tile.GCCoreTileEntityOxygenCollector.func_70316_g(GCCoreTileEntityOxygenCollector.java:58)
2013-08-13 12:11:10 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
2013-08-13 12:11:10 [SEVERE]    at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
2013-08-13 12:11:10 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
2013-08-13 12:11:10 [SEVERE]    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
2013-08-13 12:11:10 [SEVERE]    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by JohnPark234** [comment]
Console being spammed with this...
